version: "3.8"
services:
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd1"
      ACCEPT_EULA: "Y"

  backend:
    container_name: impera-backend-dev
    image: impera-backend:latest
    ports:
      - "8080:5000"
    secrets:
      - appsettings.local.json
    environment:
      - ASPNETCORE_ENVIRONMENT=local

    depends_on:
      - sql-server-db

    logging:
      options:
        max-size: "100m"
        max-file: "3"

    # Want to run sql server separately
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  appsettings.local.json:
    file: ./appsettings.local.json

volumes:
  mssql-server-linux-data:
