version: "3.2"

logging:
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

services:
  backend-dev:
    container_name: impera-backend-dev
    restart: always
    image: impera-backend:latest
    ports:
      - "5002:5000"
    secrets:
      - appsettings.dev.json
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    # Want to run sql server separately
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-production:
    container_name: impera-backend-production
    restart: always    
    image: impera-backend:production
    ports:
      - "5004:5000"
    secrets:
      - appsettings.production.json
    environment:
      - ASPNETCORE_ENVIRONMENT=production
    # Want to run sql server separately
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always    
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

    ports:
      - "1433:1433"

    volumes:
      - /opt/docker/mssql-latest:/var/opt/mssql/data

    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ACCEPT_EULA=Y
      - SA_PASSWORD

secrets:
  appsettings.dev.json:
    file: ./appsettings.dev.json
  appsettings.production.json:
    file: ./appsettings.production.json
