// <auto-generated />
namespace ImperaPlus.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImperaV97 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImperaV97));
        
        string IMigrationMetadata.Id
        {
            get { return "201607230458393_ImperaV9-7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
