using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Imperawins()
        {
            var mapTemplate = new MapTemplate("Imperawins") { Image = "impera4wins.png" };
            var country1 = new CountryTemplate("1", "A1") { X = 128, Y = 211 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "A2") { X = 182, Y = 211 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "A3") { X = 236, Y = 211 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "A4") { X = 288, Y = 211 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "B1") { X = 128, Y = 263 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "B2") { X = 182, Y = 263 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "B3") { X = 236, Y = 263 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "B4") { X = 288, Y = 263 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "C1") { X = 128, Y = 315 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "C2") { X = 182, Y = 315 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "C3") { X = 236, Y = 315 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "C4") { X = 288, Y = 315 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "D1") { X = 128, Y = 367 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "D2") { X = 182, Y = 367 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "D3") { X = 236, Y = 367 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "D4") { X = 288, Y = 367 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "E1") { X = 128, Y = 420 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "E2") { X = 182, Y = 420 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "E3") { X = 236, Y = 420 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "E4") { X = 288, Y = 420 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "F1") { X = 128, Y = 473 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "F2") { X = 182, Y = 473 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "F3") { X = 236, Y = 473 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "F4") { X = 288, Y = 473 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "G1") { X = 128, Y = 527 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "G2") { X = 182, Y = 527 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "G3") { X = 236, Y = 527 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "G4") { X = 288, Y = 527 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "A5") { X = 340, Y = 211 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "B5") { X = 340, Y = 263 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "C5") { X = 340, Y = 315 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "D5") { X = 340, Y = 367 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "A6") { X = 394, Y = 211 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "B6") { X = 394, Y = 263 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "C6") { X = 394, Y = 315 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "D6") { X = 394, Y = 367 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "A7") { X = 448, Y = 211 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "B7") { X = 448, Y = 263 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "C7") { X = 448, Y = 315 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "D7") { X = 448, Y = 367 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "E5") { X = 340, Y = 420 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "E6") { X = 394, Y = 420 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "E7") { X = 448, Y = 420 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "F5") { X = 340, Y = 473 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "F6") { X = 394, Y = 473 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "F7") { X = 448, Y = 473 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "G5") { X = 340, Y = 527 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "G6") { X = 394, Y = 527 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "G7") { X = 448, Y = 527 };
            mapTemplate.Countries.Add(country49);
            var continent1 = new Continent("1", 1);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 1);
            continent2.Countries.Add(country2);
            continent2.Countries.Add(country3);
            continent2.Countries.Add(country4);
            continent2.Countries.Add(country29);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 1);
            continent3.Countries.Add(country3);
            continent3.Countries.Add(country4);
            continent3.Countries.Add(country29);
            continent3.Countries.Add(country33);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 1);
            continent4.Countries.Add(country4);
            continent4.Countries.Add(country29);
            continent4.Countries.Add(country33);
            continent4.Countries.Add(country37);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 1);
            continent5.Countries.Add(country5);
            continent5.Countries.Add(country6);
            continent5.Countries.Add(country7);
            continent5.Countries.Add(country8);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 1);
            continent6.Countries.Add(country6);
            continent6.Countries.Add(country7);
            continent6.Countries.Add(country8);
            continent6.Countries.Add(country30);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 1);
            continent7.Countries.Add(country7);
            continent7.Countries.Add(country8);
            continent7.Countries.Add(country30);
            continent7.Countries.Add(country34);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 1);
            continent8.Countries.Add(country8);
            continent8.Countries.Add(country30);
            continent8.Countries.Add(country34);
            continent8.Countries.Add(country38);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 1);
            continent9.Countries.Add(country9);
            continent9.Countries.Add(country10);
            continent9.Countries.Add(country11);
            continent9.Countries.Add(country12);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 1);
            continent10.Countries.Add(country10);
            continent10.Countries.Add(country11);
            continent10.Countries.Add(country12);
            continent10.Countries.Add(country31);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 1);
            continent11.Countries.Add(country11);
            continent11.Countries.Add(country12);
            continent11.Countries.Add(country31);
            continent11.Countries.Add(country35);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 1);
            continent12.Countries.Add(country12);
            continent12.Countries.Add(country31);
            continent12.Countries.Add(country35);
            continent12.Countries.Add(country39);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 1);
            continent13.Countries.Add(country13);
            continent13.Countries.Add(country14);
            continent13.Countries.Add(country15);
            continent13.Countries.Add(country16);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 1);
            continent14.Countries.Add(country14);
            continent14.Countries.Add(country15);
            continent14.Countries.Add(country16);
            continent14.Countries.Add(country32);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 1);
            continent15.Countries.Add(country15);
            continent15.Countries.Add(country16);
            continent15.Countries.Add(country32);
            continent15.Countries.Add(country36);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 1);
            continent16.Countries.Add(country16);
            continent16.Countries.Add(country32);
            continent16.Countries.Add(country36);
            continent16.Countries.Add(country40);
            mapTemplate.Continents.Add(continent16);
            var continent17 = new Continent("17", 1);
            continent17.Countries.Add(country17);
            continent17.Countries.Add(country18);
            continent17.Countries.Add(country19);
            continent17.Countries.Add(country20);
            mapTemplate.Continents.Add(continent17);
            var continent18 = new Continent("18", 1);
            continent18.Countries.Add(country18);
            continent18.Countries.Add(country19);
            continent18.Countries.Add(country20);
            continent18.Countries.Add(country41);
            mapTemplate.Continents.Add(continent18);
            var continent19 = new Continent("19", 1);
            continent19.Countries.Add(country19);
            continent19.Countries.Add(country20);
            continent19.Countries.Add(country41);
            continent19.Countries.Add(country42);
            mapTemplate.Continents.Add(continent19);
            var continent20 = new Continent("20", 1);
            continent20.Countries.Add(country20);
            continent20.Countries.Add(country41);
            continent20.Countries.Add(country42);
            continent20.Countries.Add(country43);
            mapTemplate.Continents.Add(continent20);
            var continent21 = new Continent("21", 1);
            continent21.Countries.Add(country21);
            continent21.Countries.Add(country22);
            continent21.Countries.Add(country23);
            continent21.Countries.Add(country24);
            mapTemplate.Continents.Add(continent21);
            var continent22 = new Continent("22", 1);
            continent22.Countries.Add(country22);
            continent22.Countries.Add(country23);
            continent22.Countries.Add(country24);
            continent22.Countries.Add(country44);
            mapTemplate.Continents.Add(continent22);
            var continent23 = new Continent("23", 1);
            continent23.Countries.Add(country23);
            continent23.Countries.Add(country24);
            continent23.Countries.Add(country44);
            continent23.Countries.Add(country45);
            mapTemplate.Continents.Add(continent23);
            var continent24 = new Continent("24", 1);
            continent24.Countries.Add(country24);
            continent24.Countries.Add(country44);
            continent24.Countries.Add(country45);
            continent24.Countries.Add(country46);
            mapTemplate.Continents.Add(continent24);
            var continent25 = new Continent("25", 1);
            continent25.Countries.Add(country25);
            continent25.Countries.Add(country26);
            continent25.Countries.Add(country27);
            continent25.Countries.Add(country28);
            mapTemplate.Continents.Add(continent25);
            var continent26 = new Continent("26", 1);
            continent26.Countries.Add(country26);
            continent26.Countries.Add(country27);
            continent26.Countries.Add(country28);
            continent26.Countries.Add(country47);
            mapTemplate.Continents.Add(continent26);
            var continent27 = new Continent("27", 1);
            continent27.Countries.Add(country27);
            continent27.Countries.Add(country28);
            continent27.Countries.Add(country47);
            continent27.Countries.Add(country48);
            mapTemplate.Continents.Add(continent27);
            var continent28 = new Continent("28", 1);
            continent28.Countries.Add(country28);
            continent28.Countries.Add(country47);
            continent28.Countries.Add(country48);
            continent28.Countries.Add(country49);
            mapTemplate.Continents.Add(continent28);
            var continent29 = new Continent("29", 1);
            continent29.Countries.Add(country1);
            continent29.Countries.Add(country5);
            continent29.Countries.Add(country9);
            continent29.Countries.Add(country13);
            mapTemplate.Continents.Add(continent29);
            var continent30 = new Continent("30", 1);
            continent30.Countries.Add(country5);
            continent30.Countries.Add(country9);
            continent30.Countries.Add(country13);
            continent30.Countries.Add(country17);
            mapTemplate.Continents.Add(continent30);
            var continent31 = new Continent("31", 1);
            continent31.Countries.Add(country9);
            continent31.Countries.Add(country13);
            continent31.Countries.Add(country17);
            continent31.Countries.Add(country21);
            mapTemplate.Continents.Add(continent31);
            var continent32 = new Continent("32", 1);
            continent32.Countries.Add(country13);
            continent32.Countries.Add(country17);
            continent32.Countries.Add(country21);
            continent32.Countries.Add(country25);
            mapTemplate.Continents.Add(continent32);
            var continent33 = new Continent("33", 1);
            continent33.Countries.Add(country2);
            continent33.Countries.Add(country6);
            continent33.Countries.Add(country10);
            continent33.Countries.Add(country14);
            mapTemplate.Continents.Add(continent33);
            var continent34 = new Continent("34", 1);
            continent34.Countries.Add(country6);
            continent34.Countries.Add(country10);
            continent34.Countries.Add(country14);
            continent34.Countries.Add(country18);
            mapTemplate.Continents.Add(continent34);
            var continent35 = new Continent("35", 1);
            continent35.Countries.Add(country10);
            continent35.Countries.Add(country14);
            continent35.Countries.Add(country18);
            continent35.Countries.Add(country22);
            mapTemplate.Continents.Add(continent35);
            var continent36 = new Continent("36", 1);
            continent36.Countries.Add(country14);
            continent36.Countries.Add(country18);
            continent36.Countries.Add(country22);
            continent36.Countries.Add(country26);
            mapTemplate.Continents.Add(continent36);
            var continent37 = new Continent("37", 1);
            continent37.Countries.Add(country3);
            continent37.Countries.Add(country7);
            continent37.Countries.Add(country11);
            continent37.Countries.Add(country15);
            mapTemplate.Continents.Add(continent37);
            var continent38 = new Continent("38", 1);
            continent38.Countries.Add(country7);
            continent38.Countries.Add(country11);
            continent38.Countries.Add(country15);
            continent38.Countries.Add(country19);
            mapTemplate.Continents.Add(continent38);
            var continent39 = new Continent("39", 1);
            continent39.Countries.Add(country11);
            continent39.Countries.Add(country15);
            continent39.Countries.Add(country19);
            continent39.Countries.Add(country23);
            mapTemplate.Continents.Add(continent39);
            var continent40 = new Continent("40", 1);
            continent40.Countries.Add(country15);
            continent40.Countries.Add(country19);
            continent40.Countries.Add(country23);
            continent40.Countries.Add(country27);
            mapTemplate.Continents.Add(continent40);
            var continent41 = new Continent("41", 1);
            continent41.Countries.Add(country4);
            continent41.Countries.Add(country8);
            continent41.Countries.Add(country12);
            continent41.Countries.Add(country16);
            mapTemplate.Continents.Add(continent41);
            var continent42 = new Continent("42", 1);
            continent42.Countries.Add(country8);
            continent42.Countries.Add(country12);
            continent42.Countries.Add(country16);
            continent42.Countries.Add(country20);
            mapTemplate.Continents.Add(continent42);
            var continent43 = new Continent("43", 1);
            continent43.Countries.Add(country12);
            continent43.Countries.Add(country16);
            continent43.Countries.Add(country20);
            continent43.Countries.Add(country24);
            mapTemplate.Continents.Add(continent43);
            var continent44 = new Continent("44", 1);
            continent44.Countries.Add(country16);
            continent44.Countries.Add(country20);
            continent44.Countries.Add(country24);
            continent44.Countries.Add(country28);
            mapTemplate.Continents.Add(continent44);
            var continent45 = new Continent("45", 1);
            continent45.Countries.Add(country29);
            continent45.Countries.Add(country30);
            continent45.Countries.Add(country31);
            continent45.Countries.Add(country32);
            mapTemplate.Continents.Add(continent45);
            var continent46 = new Continent("46", 1);
            continent46.Countries.Add(country30);
            continent46.Countries.Add(country31);
            continent46.Countries.Add(country32);
            continent46.Countries.Add(country41);
            mapTemplate.Continents.Add(continent46);
            var continent47 = new Continent("47", 1);
            continent47.Countries.Add(country31);
            continent47.Countries.Add(country32);
            continent47.Countries.Add(country41);
            continent47.Countries.Add(country44);
            mapTemplate.Continents.Add(continent47);
            var continent48 = new Continent("48", 1);
            continent48.Countries.Add(country32);
            continent48.Countries.Add(country41);
            continent48.Countries.Add(country44);
            continent48.Countries.Add(country47);
            mapTemplate.Continents.Add(continent48);
            var continent49 = new Continent("49", 1);
            continent49.Countries.Add(country33);
            continent49.Countries.Add(country34);
            continent49.Countries.Add(country35);
            continent49.Countries.Add(country36);
            mapTemplate.Continents.Add(continent49);
            var continent50 = new Continent("50", 1);
            continent50.Countries.Add(country34);
            continent50.Countries.Add(country35);
            continent50.Countries.Add(country36);
            continent50.Countries.Add(country42);
            mapTemplate.Continents.Add(continent50);
            var continent51 = new Continent("51", 1);
            continent51.Countries.Add(country35);
            continent51.Countries.Add(country36);
            continent51.Countries.Add(country42);
            continent51.Countries.Add(country45);
            mapTemplate.Continents.Add(continent51);
            var continent52 = new Continent("52", 1);
            continent52.Countries.Add(country36);
            continent52.Countries.Add(country42);
            continent52.Countries.Add(country45);
            continent52.Countries.Add(country48);
            mapTemplate.Continents.Add(continent52);
            var continent53 = new Continent("53", 1);
            continent53.Countries.Add(country37);
            continent53.Countries.Add(country38);
            continent53.Countries.Add(country39);
            continent53.Countries.Add(country40);
            mapTemplate.Continents.Add(continent53);
            var continent54 = new Continent("54", 1);
            continent54.Countries.Add(country38);
            continent54.Countries.Add(country39);
            continent54.Countries.Add(country40);
            continent54.Countries.Add(country43);
            mapTemplate.Continents.Add(continent54);
            var continent55 = new Continent("55", 1);
            continent55.Countries.Add(country39);
            continent55.Countries.Add(country40);
            continent55.Countries.Add(country43);
            continent55.Countries.Add(country46);
            mapTemplate.Continents.Add(continent55);
            var continent56 = new Continent("56", 1);
            continent56.Countries.Add(country40);
            continent56.Countries.Add(country43);
            continent56.Countries.Add(country46);
            continent56.Countries.Add(country49);
            mapTemplate.Continents.Add(continent56);
            var continent57 = new Continent("57", 2);
            continent57.Countries.Add(country1);
            continent57.Countries.Add(country6);
            continent57.Countries.Add(country11);
            continent57.Countries.Add(country16);
            mapTemplate.Continents.Add(continent57);
            var continent58 = new Continent("58", 2);
            continent58.Countries.Add(country6);
            continent58.Countries.Add(country11);
            continent58.Countries.Add(country16);
            continent58.Countries.Add(country41);
            mapTemplate.Continents.Add(continent58);
            var continent59 = new Continent("59", 2);
            continent59.Countries.Add(country11);
            continent59.Countries.Add(country16);
            continent59.Countries.Add(country41);
            continent59.Countries.Add(country45);
            mapTemplate.Continents.Add(continent59);
            var continent60 = new Continent("60", 2);
            continent60.Countries.Add(country16);
            continent60.Countries.Add(country41);
            continent60.Countries.Add(country45);
            continent60.Countries.Add(country49);
            mapTemplate.Continents.Add(continent60);
            var continent61 = new Continent("61", 2);
            continent61.Countries.Add(country2);
            continent61.Countries.Add(country7);
            continent61.Countries.Add(country12);
            continent61.Countries.Add(country32);
            mapTemplate.Continents.Add(continent61);
            var continent62 = new Continent("62", 2);
            continent62.Countries.Add(country7);
            continent62.Countries.Add(country12);
            continent62.Countries.Add(country32);
            continent62.Countries.Add(country42);
            mapTemplate.Continents.Add(continent62);
            var continent63 = new Continent("63", 2);
            continent63.Countries.Add(country12);
            continent63.Countries.Add(country32);
            continent63.Countries.Add(country42);
            continent63.Countries.Add(country46);
            mapTemplate.Continents.Add(continent63);
            var continent64 = new Continent("64", 2);
            continent64.Countries.Add(country3);
            continent64.Countries.Add(country8);
            continent64.Countries.Add(country31);
            continent64.Countries.Add(country36);
            mapTemplate.Continents.Add(continent64);
            var continent65 = new Continent("65", 2);
            continent65.Countries.Add(country8);
            continent65.Countries.Add(country31);
            continent65.Countries.Add(country36);
            continent65.Countries.Add(country43);
            mapTemplate.Continents.Add(continent65);
            var continent66 = new Continent("66", 2);
            continent66.Countries.Add(country4);
            continent66.Countries.Add(country30);
            continent66.Countries.Add(country35);
            continent66.Countries.Add(country40);
            mapTemplate.Continents.Add(continent66);
            var continent67 = new Continent("67", 2);
            continent67.Countries.Add(country4);
            continent67.Countries.Add(country7);
            continent67.Countries.Add(country10);
            continent67.Countries.Add(country13);
            mapTemplate.Continents.Add(continent67);
            var continent68 = new Continent("68", 2);
            continent68.Countries.Add(country29);
            continent68.Countries.Add(country8);
            continent68.Countries.Add(country11);
            continent68.Countries.Add(country14);
            mapTemplate.Continents.Add(continent68);
            var continent69 = new Continent("69", 2);
            continent69.Countries.Add(country8);
            continent69.Countries.Add(country11);
            continent69.Countries.Add(country14);
            continent69.Countries.Add(country17);
            mapTemplate.Continents.Add(continent69);
            var continent70 = new Continent("70", 2);
            continent70.Countries.Add(country33);
            continent70.Countries.Add(country30);
            continent70.Countries.Add(country12);
            continent70.Countries.Add(country15);
            mapTemplate.Continents.Add(continent70);
            var continent71 = new Continent("71", 2);
            continent71.Countries.Add(country30);
            continent71.Countries.Add(country12);
            continent71.Countries.Add(country15);
            continent71.Countries.Add(country18);
            mapTemplate.Continents.Add(continent71);
            var continent72 = new Continent("72", 2);
            continent72.Countries.Add(country12);
            continent72.Countries.Add(country15);
            continent72.Countries.Add(country18);
            continent72.Countries.Add(country21);
            mapTemplate.Continents.Add(continent72);
            var continent73 = new Continent("73", 2);
            continent73.Countries.Add(country37);
            continent73.Countries.Add(country34);
            continent73.Countries.Add(country31);
            continent73.Countries.Add(country16);
            mapTemplate.Continents.Add(continent73);
            var continent74 = new Continent("74", 2);
            continent74.Countries.Add(country34);
            continent74.Countries.Add(country31);
            continent74.Countries.Add(country16);
            continent74.Countries.Add(country19);
            mapTemplate.Continents.Add(continent74);
            var continent75 = new Continent("75", 2);
            continent75.Countries.Add(country31);
            continent75.Countries.Add(country16);
            continent75.Countries.Add(country19);
            continent75.Countries.Add(country22);
            mapTemplate.Continents.Add(continent75);
            var continent76 = new Continent("76", 2);
            continent76.Countries.Add(country16);
            continent76.Countries.Add(country19);
            continent76.Countries.Add(country22);
            continent76.Countries.Add(country25);
            mapTemplate.Continents.Add(continent76);
            var continent77 = new Continent("77", 2);
            continent77.Countries.Add(country5);
            continent77.Countries.Add(country10);
            continent77.Countries.Add(country15);
            continent77.Countries.Add(country20);
            mapTemplate.Continents.Add(continent77);
            var continent78 = new Continent("78", 2);
            continent78.Countries.Add(country10);
            continent78.Countries.Add(country15);
            continent78.Countries.Add(country20);
            continent78.Countries.Add(country44);
            mapTemplate.Continents.Add(continent78);
            var continent79 = new Continent("79", 2);
            continent79.Countries.Add(country15);
            continent79.Countries.Add(country20);
            continent79.Countries.Add(country44);
            continent79.Countries.Add(country48);
            mapTemplate.Continents.Add(continent79);
            var continent80 = new Continent("80", 2);
            continent80.Countries.Add(country9);
            continent80.Countries.Add(country14);
            continent80.Countries.Add(country19);
            continent80.Countries.Add(country24);
            mapTemplate.Continents.Add(continent80);
            var continent81 = new Continent("81", 2);
            continent81.Countries.Add(country14);
            continent81.Countries.Add(country19);
            continent81.Countries.Add(country24);
            continent81.Countries.Add(country47);
            mapTemplate.Continents.Add(continent81);
            var continent82 = new Continent("82", 2);
            continent82.Countries.Add(country13);
            continent82.Countries.Add(country18);
            continent82.Countries.Add(country23);
            continent82.Countries.Add(country28);
            mapTemplate.Continents.Add(continent82);
            var continent83 = new Continent("83", 2);
            continent83.Countries.Add(country26);
            continent83.Countries.Add(country23);
            continent83.Countries.Add(country20);
            continent83.Countries.Add(country32);
            mapTemplate.Continents.Add(continent83);
            var continent84 = new Continent("84", 2);
            continent84.Countries.Add(country23);
            continent84.Countries.Add(country20);
            continent84.Countries.Add(country32);
            continent84.Countries.Add(country35);
            mapTemplate.Continents.Add(continent84);
            var continent85 = new Continent("85", 2);
            continent85.Countries.Add(country20);
            continent85.Countries.Add(country32);
            continent85.Countries.Add(country35);
            continent85.Countries.Add(country38);
            mapTemplate.Continents.Add(continent85);
            var continent86 = new Continent("86", 2);
            continent86.Countries.Add(country27);
            continent86.Countries.Add(country24);
            continent86.Countries.Add(country41);
            continent86.Countries.Add(country36);
            mapTemplate.Continents.Add(continent86);
            var continent87 = new Continent("87", 2);
            continent87.Countries.Add(country24);
            continent87.Countries.Add(country41);
            continent87.Countries.Add(country36);
            continent87.Countries.Add(country39);
            mapTemplate.Continents.Add(continent87);
            var continent88 = new Continent("88", 2);
            continent88.Countries.Add(country28);
            continent88.Countries.Add(country44);
            continent88.Countries.Add(country42);
            continent88.Countries.Add(country40);
            mapTemplate.Continents.Add(continent88);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "5"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "6"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "7"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "29"));
            mapTemplate.Connections.Add(new Connection("4", "8"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "9"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "10"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "11"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "30"));
            mapTemplate.Connections.Add(new Connection("8", "12"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "14"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "15"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "31"));
            mapTemplate.Connections.Add(new Connection("12", "16"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "17"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "18"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "19"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "32"));
            mapTemplate.Connections.Add(new Connection("16", "20"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "21"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "22"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "23"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "41"));
            mapTemplate.Connections.Add(new Connection("20", "24"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "25"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "26"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "27"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "44"));
            mapTemplate.Connections.Add(new Connection("24", "28"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "1"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "2"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "3"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "47"));
            mapTemplate.Connections.Add(new Connection("28", "4"));
            mapTemplate.Connections.Add(new Connection("29", "4"));
            mapTemplate.Connections.Add(new Connection("29", "33"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("30", "8"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "12"));
            mapTemplate.Connections.Add(new Connection("31", "35"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "16"));
            mapTemplate.Connections.Add(new Connection("32", "36"));
            mapTemplate.Connections.Add(new Connection("32", "41"));
            mapTemplate.Connections.Add(new Connection("33", "29"));
            mapTemplate.Connections.Add(new Connection("33", "37"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("35", "31"));
            mapTemplate.Connections.Add(new Connection("35", "39"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("36", "32"));
            mapTemplate.Connections.Add(new Connection("36", "40"));
            mapTemplate.Connections.Add(new Connection("36", "42"));
            mapTemplate.Connections.Add(new Connection("37", "33"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("39", "35"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("40", "36"));
            mapTemplate.Connections.Add(new Connection("40", "43"));
            mapTemplate.Connections.Add(new Connection("41", "20"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "44"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "45"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "46"));
            mapTemplate.Connections.Add(new Connection("44", "24"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "47"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "48"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "49"));
            mapTemplate.Connections.Add(new Connection("47", "28"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "29"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "33"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "37"));

            return mapTemplate;
        }
    }
}
