
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate ColdWar()
        {

var mapTemplate = new MapTemplate("ColdWar") { Image = "coldwar.jpg" };
var country1 = new CountryTemplate("1", "Ireland") { X = 20, Y = 121 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "United Kingdom") { X = 43, Y = 232 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Netherland") { X = 66, Y = 363 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Belgium") { X = 0, Y = 366 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "BRD") { X = 33, Y = 446 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "DDR") { X = 130, Y = 462 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Denmark") { X = 174, Y = 416 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Norway") { X = 307, Y = 327 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Sweden") { X = 301, Y = 417};
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Finland") { X = 495, Y = 515};
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Cz. Rep") { X = 67, Y = 592 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Poland") { X = 153, Y = 614 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Kalingrad") { X = 249, Y = 585};
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Slov.") { X = 72, Y = 653 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Hung.") { X = 37, Y = 694};
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Serbia") { X = 0, Y = 711};
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Romania") { X = 56, Y = 813 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Moldova") { X = 146, Y = 828 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Bulgaria") { X = 14, Y = 861};
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Ukraine") { X = 230, Y = 852 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Belarus") { X = 285, Y = 715 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Lith.") { X = 292, Y = 625 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Latavia") { X = 349, Y = 612 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Est.") { X = 403, Y = 576};
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Turkey") { X = 61, Y = 1093 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Syria") { X = 45, Y = 1285 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Iraq") { X = 85, Y = 1429 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Kuwait") { X = 121, Y = 1560 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Iran") { X = 319, Y =  1568};
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Saudi Arabia") { X = 55, Y =  1636};
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Georgien") { X = 289, Y = 1189 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Armenien") { X = 264, Y = 1228 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Azerbaijan") { X = 310, Y = 1249 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Turkmenistan") { X = 554, Y = 1468 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Uzbekistan") { X = 687, Y = 1459 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Afghanistan") { X = 657, Y = 1628 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Tajikistan") { X = 842, Y = 1576 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Kyrgyzstan") { X = 876, Y = 1518 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Pakistan") { X = 861, Y = 1670 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Wolograd") { X = 352, Y = 1075 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Kazakhstan") { X = 799, Y = 1278 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Moscow district") { X = 602, Y = 811 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Yakutia") { X = 1363, Y = 925 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Siberia") { X = 1903, Y = 697 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Japan") { X = 2420, Y = 1325 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "South Korea") { X = 2210, Y = 1465 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "North Korea") { X = 2123, Y = 1389 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "China") { X = 1502, Y = 1594 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Mongolia") { X = 1488, Y = 1372};
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Austria") { X = 13, Y = 602 };
mapTemplate.Countries.Add(country50);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country5);
continent3.Countries.Add(country6);
continent3.Countries.Add(country50);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country11);
continent4.Countries.Add(country12);
continent4.Countries.Add(country13);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 6);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
continent5.Countries.Add(country20);
continent5.Countries.Add(country21);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country25);
continent7.Countries.Add(country26);
continent7.Countries.Add(country27);
continent7.Countries.Add(country28);
continent7.Countries.Add(country29);
continent7.Countries.Add(country30);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country31);
continent8.Countries.Add(country32);
continent8.Countries.Add(country33);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 5);
continent9.Countries.Add(country34);
continent9.Countries.Add(country35);
continent9.Countries.Add(country36);
continent9.Countries.Add(country37);
continent9.Countries.Add(country38);
continent9.Countries.Add(country39);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country45);
continent10.Countries.Add(country46);
continent10.Countries.Add(country47);
continent10.Countries.Add(country48);
continent10.Countries.Add(country49);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 4);
continent11.Countries.Add(country40);
continent11.Countries.Add(country41);
continent11.Countries.Add(country42);
continent11.Countries.Add(country43);
continent11.Countries.Add(country44);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "8"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));	
mapTemplate.Connections.Add(new Connection("5", "11"));
mapTemplate.Connections.Add(new Connection("5", "50"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("6", "12"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("8", "2"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "42"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "42"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "50"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "6"));
mapTemplate.Connections.Add(new Connection("12", "21"));
mapTemplate.Connections.Add(new Connection("12", "20"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "22"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "20"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "20"));
mapTemplate.Connections.Add(new Connection("15", "50"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "25"));
mapTemplate.Connections.Add(new Connection("20", "17"));	
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "40"));
mapTemplate.Connections.Add(new Connection("20", "42"));
mapTemplate.Connections.Add(new Connection("20", "15"));
mapTemplate.Connections.Add(new Connection("20", "12"));
mapTemplate.Connections.Add(new Connection("20", "14"));
mapTemplate.Connections.Add(new Connection("21", "42"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "12"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("22", "13"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "12"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "42"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "42"));
mapTemplate.Connections.Add(new Connection("25", "32"));
mapTemplate.Connections.Add(new Connection("25", "19"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "31"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("29", "33"));
mapTemplate.Connections.Add(new Connection("29", "34"));
mapTemplate.Connections.Add(new Connection("29", "36"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("31", "40"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "25"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "25"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "29"));
mapTemplate.Connections.Add(new Connection("33", "40"));
mapTemplate.Connections.Add(new Connection("34", "29"));
mapTemplate.Connections.Add(new Connection("34", "41"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "41"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("36", "48"));
mapTemplate.Connections.Add(new Connection("36", "29"));
mapTemplate.Connections.Add(new Connection("37", "35"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "48"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "48"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("39", "48"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "20"));
mapTemplate.Connections.Add(new Connection("40", "31"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "33"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "34"));
mapTemplate.Connections.Add(new Connection("41", "48"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "35"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("42", "24"));
mapTemplate.Connections.Add(new Connection("42", "23"));
mapTemplate.Connections.Add(new Connection("42", "10"));
mapTemplate.Connections.Add(new Connection("42", "21"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "20"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "8"));
mapTemplate.Connections.Add(new Connection("43", "49"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "48"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "48"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "47"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "44"));
mapTemplate.Connections.Add(new Connection("48", "38"));
mapTemplate.Connections.Add(new Connection("48", "37"));
mapTemplate.Connections.Add(new Connection("48", "39"));
mapTemplate.Connections.Add(new Connection("48", "36"));
mapTemplate.Connections.Add(new Connection("48", "41"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "44"));
mapTemplate.Connections.Add(new Connection("48", "43"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "43"));
mapTemplate.Connections.Add(new Connection("50", "5"));
mapTemplate.Connections.Add(new Connection("50", "11"));
mapTemplate.Connections.Add(new Connection("50", "14"));
mapTemplate.Connections.Add(new Connection("50", "15"));


            return mapTemplate;
		}
    }
}

