
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Phantasia()
        {

var mapTemplate = new MapTemplate("Phantasia") { Image = "phantasia.png" };
var country1 = new CountryTemplate("1", "Nordmalck") { X = 191, Y = 53 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Tomkomonko") { X = 205, Y = 189 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Obik�sa") { X = 297, Y = 135 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Idantam") { X = 451, Y = 99 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Vordatt") { X = 392, Y = 157 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Dunnich") { X = 300, Y = 187 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Domajin") { X = 585, Y = 175 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Mindoran") { X = 788, Y = 264 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Otolen") { X = 860, Y = 273 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Bynyx") { X = 779, Y = 340 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Pok") { X = 730, Y = 465 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Hermon") { X = 787, Y = 497 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Jophyl") { X = 794, Y = 399 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Westpralanx") { X = 172, Y = 368 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Ostpralanx") { X = 234, Y = 435 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Numbin") { X = 320, Y = 379 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Westraffan") { X = 479, Y = 345 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Sopaz") { X = 541, Y = 349 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Arbadull") { X = 544, Y = 435 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Raunon") { X = 610, Y = 359 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "S�draffan") { X = 626, Y = 494 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Nontonaj") { X = 46, Y = 637 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Wingup") { X = 199, Y = 599 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Kroff") { X = 280, Y = 598 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Finoktum") { X = 335, Y = 569 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Boltosa") { X = 108, Y = 668 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Gidollon") { X = 221, Y = 689 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Ephy") { X = 121, Y = 733 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Binthof") { X = 255, Y = 788 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Kr�pti") { X = 229, Y = 840 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Lorbott") { X = 443, Y = 587 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Exolon") { X = 388, Y = 714 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Walor") { X = 514, Y = 562 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Koratur") { X = 509, Y = 663 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Quld") { X = 465, Y = 668 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Yalteph") { X = 502, Y = 713 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Agupy") { X = 547, Y = 731 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "K�ntobai") { X = 650, Y = 588 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Zuphanol") { X = 645, Y = 668 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Prankitz") { X = 706, Y = 646 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Orplasch") { X = 770, Y = 628 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Valdorr") { X = 874, Y = 512 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Tarock") { X = 896, Y = 581 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Mainto") { X = 865, Y = 549 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Flottorbuk") { X = 712, Y = 780 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "L�sson") { X = 478, Y = 807 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Marjab") { X = 586, Y = 805 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Minock") { X = 638, Y = 808 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Biock") { X = 710, Y = 865 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "HS Gorgorphina") { X = 98, Y = 122 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "HS Halundorass") { X = 231, Y = 347 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "HS Rodun") { X = 517, Y = 382 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "HS Lurasa") { X = 714, Y = 391 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "HS Ziladon") { X = 192, Y = 745 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "HS Palladus") { X = 472, Y = 626 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "HS Marity") { X = 695, Y = 717 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "HS S�padon") { X = 618, Y = 774 };
mapTemplate.Countries.Add(country57);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country17);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 5);
continent5.Countries.Add(country22);
continent5.Countries.Add(country23);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country34);
continent6.Countries.Add(country35);
continent6.Countries.Add(country36);
continent6.Countries.Add(country37);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
continent7.Countries.Add(country41);
continent7.Countries.Add(country42);
continent7.Countries.Add(country43);
continent7.Countries.Add(country44);
continent7.Countries.Add(country45);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country46);
continent8.Countries.Add(country47);
continent8.Countries.Add(country48);
continent8.Countries.Add(country49);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country50);
continent9.Countries.Add(country55);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 1);
continent10.Countries.Add(country51);
continent10.Countries.Add(country56);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 1);
continent11.Countries.Add(country53);
continent11.Countries.Add(country54);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 1);
continent12.Countries.Add(country52);
continent12.Countries.Add(country57);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "50"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "14"));
mapTemplate.Connections.Add(new Connection("2", "50"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "50"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "50"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "50"));
mapTemplate.Connections.Add(new Connection("6", "16"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "50"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "18"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "50"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "20"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("8", "53"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "53"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "53"));
mapTemplate.Connections.Add(new Connection("11", "41"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "53"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "53"));
mapTemplate.Connections.Add(new Connection("13", "42"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("13", "53"));
mapTemplate.Connections.Add(new Connection("14", "2"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "51"));
mapTemplate.Connections.Add(new Connection("14", "22"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "51"));
mapTemplate.Connections.Add(new Connection("15", "24"));
mapTemplate.Connections.Add(new Connection("15", "23"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "6"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "51"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "52"));
mapTemplate.Connections.Add(new Connection("17", "25"));
mapTemplate.Connections.Add(new Connection("18", "7"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "52"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "52"));
mapTemplate.Connections.Add(new Connection("19", "31"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "52"));
mapTemplate.Connections.Add(new Connection("20", "8"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "52"));
mapTemplate.Connections.Add(new Connection("21", "38"));
mapTemplate.Connections.Add(new Connection("22", "14"));
mapTemplate.Connections.Add(new Connection("22", "28"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "54"));
mapTemplate.Connections.Add(new Connection("23", "15"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "54"));
mapTemplate.Connections.Add(new Connection("24", "15"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "54"));
mapTemplate.Connections.Add(new Connection("25", "17"));
mapTemplate.Connections.Add(new Connection("25", "31"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "30"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "54"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "54"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "54"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "22"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "54"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "54"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "25"));
mapTemplate.Connections.Add(new Connection("30", "54"));
mapTemplate.Connections.Add(new Connection("31", "19"));
mapTemplate.Connections.Add(new Connection("31", "25"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "55"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("32", "55"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "38"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "55"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "55"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "55"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "47"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "55"));
mapTemplate.Connections.Add(new Connection("37", "47"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "55"));
mapTemplate.Connections.Add(new Connection("38", "33"));
mapTemplate.Connections.Add(new Connection("38", "21"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "56"));
mapTemplate.Connections.Add(new Connection("39", "48"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "45"));
mapTemplate.Connections.Add(new Connection("39", "56"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "45"));
mapTemplate.Connections.Add(new Connection("40", "44"));
mapTemplate.Connections.Add(new Connection("40", "56"));
mapTemplate.Connections.Add(new Connection("41", "11"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("41", "56"));
mapTemplate.Connections.Add(new Connection("42", "13"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "56"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "56"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "40"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "56"));
mapTemplate.Connections.Add(new Connection("45", "49"));
mapTemplate.Connections.Add(new Connection("45", "40"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "39"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "56"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "57"));
mapTemplate.Connections.Add(new Connection("47", "37"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "36"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "57"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "39"));
mapTemplate.Connections.Add(new Connection("48", "57"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "45"));
mapTemplate.Connections.Add(new Connection("49", "57"));
mapTemplate.Connections.Add(new Connection("50", "7"));
mapTemplate.Connections.Add(new Connection("50", "4"));
mapTemplate.Connections.Add(new Connection("50", "5"));
mapTemplate.Connections.Add(new Connection("50", "6"));
mapTemplate.Connections.Add(new Connection("50", "3"));
mapTemplate.Connections.Add(new Connection("50", "2"));
mapTemplate.Connections.Add(new Connection("50", "1"));
mapTemplate.Connections.Add(new Connection("50", "55"));
mapTemplate.Connections.Add(new Connection("51", "16"));
mapTemplate.Connections.Add(new Connection("51", "15"));
mapTemplate.Connections.Add(new Connection("51", "14"));
mapTemplate.Connections.Add(new Connection("51", "56"));
mapTemplate.Connections.Add(new Connection("52", "17"));
mapTemplate.Connections.Add(new Connection("52", "18"));
mapTemplate.Connections.Add(new Connection("52", "20"));
mapTemplate.Connections.Add(new Connection("52", "19"));
mapTemplate.Connections.Add(new Connection("52", "21"));
mapTemplate.Connections.Add(new Connection("52", "57"));
mapTemplate.Connections.Add(new Connection("53", "11"));
mapTemplate.Connections.Add(new Connection("53", "12"));
mapTemplate.Connections.Add(new Connection("53", "10"));
mapTemplate.Connections.Add(new Connection("53", "8"));
mapTemplate.Connections.Add(new Connection("53", "9"));
mapTemplate.Connections.Add(new Connection("53", "13"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("54", "30"));
mapTemplate.Connections.Add(new Connection("54", "29"));
mapTemplate.Connections.Add(new Connection("54", "27"));
mapTemplate.Connections.Add(new Connection("54", "24"));
mapTemplate.Connections.Add(new Connection("54", "25"));
mapTemplate.Connections.Add(new Connection("54", "23"));
mapTemplate.Connections.Add(new Connection("54", "28"));
mapTemplate.Connections.Add(new Connection("54", "26"));
mapTemplate.Connections.Add(new Connection("54", "22"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("55", "31"));
mapTemplate.Connections.Add(new Connection("55", "33"));
mapTemplate.Connections.Add(new Connection("55", "34"));
mapTemplate.Connections.Add(new Connection("55", "35"));
mapTemplate.Connections.Add(new Connection("55", "32"));
mapTemplate.Connections.Add(new Connection("55", "36"));
mapTemplate.Connections.Add(new Connection("55", "37"));
mapTemplate.Connections.Add(new Connection("55", "50"));
mapTemplate.Connections.Add(new Connection("56", "45"));
mapTemplate.Connections.Add(new Connection("56", "39"));
mapTemplate.Connections.Add(new Connection("56", "38"));
mapTemplate.Connections.Add(new Connection("56", "40"));
mapTemplate.Connections.Add(new Connection("56", "41"));
mapTemplate.Connections.Add(new Connection("56", "44"));
mapTemplate.Connections.Add(new Connection("56", "42"));
mapTemplate.Connections.Add(new Connection("56", "43"));
mapTemplate.Connections.Add(new Connection("56", "51"));
mapTemplate.Connections.Add(new Connection("57", "49"));
mapTemplate.Connections.Add(new Connection("57", "48"));
mapTemplate.Connections.Add(new Connection("57", "47"));
mapTemplate.Connections.Add(new Connection("57", "46"));
mapTemplate.Connections.Add(new Connection("57", "52"));

            return mapTemplate;
		}
    }
}

