using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate ThirtyYearsWar()
        {
            var mapTemplate = new MapTemplate("ThirtyYearsWar") { Image = "30years.jpg" };
            var country1 = new CountryTemplate("1", "Savoyen") { X = 221, Y = 684 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Mayland") { X = 317, Y = 681 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Piacenza") { X = 414, Y = 702 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Venedig") { X = 460, Y = 697 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Basel") { X = 228, Y = 541 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Bern") { X = 232, Y = 596 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Z&uuml;rich") { X = 296, Y = 556 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Velthin") { X = 347, Y = 613 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Tyrol") { X = 418, Y = 601 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Salzburg") { X = 512, Y = 547 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Kernthen") { X = 538, Y = 587 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Krain") { X = 570, Y = 648 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "OberSteyermark") { X = 651, Y = 612 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Steyermark") { X = 603, Y = 546 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "&Ouml;sterreich") { X = 613, Y = 485 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Metz") { X = 149, Y = 420 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Bar") { X = 164, Y = 492 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "FrancheComte") { X = 182, Y = 547 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Saarverd") { X = 208, Y = 484 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Elsass") { X = 244, Y = 497 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Saarbr&uuml;ck") { X = 257, Y = 436 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Baden") { X = 279, Y = 476 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Wirtemberg") { X = 334, Y = 445 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "F&uuml;rstenberg") { X = 309, Y = 508 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Augsburg") { X = 374, Y = 514 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "&Ouml;tting") { X = 381, Y = 463 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "OberPfalz") { X = 463, Y = 396 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Bayern") { X = 472, Y = 474 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Pilsen") { X = 507, Y = 358 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Budweis") { X = 557, Y = 413 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Prag") { X = 568, Y = 354 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Braunau") { X = 604, Y = 320 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Brod") { X = 629, Y = 363 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "M&auml;hren") { X = 680, Y = 404 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Glogau") { X = 625, Y = 245 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Schweidnitz") { X = 667, Y = 296 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Wohlau") { X = 676, Y = 244 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Oderberg") { X = 763, Y = 325 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Bernburg") { X = 426, Y = 255 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "L&uuml;tzen") { X = 476, Y = 269 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Meissen") { X = 523, Y = 286 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "NiederLausitz") { X = 560, Y = 227 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "OberLausitz") { X = 573, Y = 271 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Wied") { X = 290, Y = 327 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Hessen") { X = 347, Y = 297 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Mainz") { X = 332, Y = 358 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Th&uuml;ringen") { X = 418, Y = 312 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Franken") { X = 375, Y = 361 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Culmbach") { X = 416, Y = 372 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "J&uuml;lich") { X = 224, Y = 294 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Trier") { X = 234, Y = 354 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Pfalz") { X = 273, Y = 392 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Lens") { X = 35, Y = 309 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Flandern") { X = 58, Y = 265 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Holland") { X = 116, Y = 197 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Groningen") { X = 217, Y = 169 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Nimwegen") { X = 178, Y = 238 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Br&uuml;ssel") { X = 121, Y = 290 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Maastricht") { X = 176, Y = 284 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Luxemburg") { X = 171, Y = 357 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Wesel") { X = 214, Y = 227 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "M&uuml;nster") { X = 255, Y = 219 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Berg") { X = 253, Y = 271 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "Westfalen") { X = 294, Y = 269 };
            mapTemplate.Countries.Add(country64);
            var country65 = new CountryTemplate("65", "Ostfriesland") { X = 267, Y = 99 };
            mapTemplate.Countries.Add(country65);
            var country66 = new CountryTemplate("66", "Meppen") { X = 271, Y = 151 };
            mapTemplate.Countries.Add(country66);
            var country67 = new CountryTemplate("67", "Osnabr&uuml;ck") { X = 285, Y = 191 };
            mapTemplate.Countries.Add(country67);
            var country68 = new CountryTemplate("68", "Oldenburg") { X = 308, Y = 135 };
            mapTemplate.Countries.Add(country68);
            var country69 = new CountryTemplate("69", "Bremen") { X = 334, Y = 105 };
            mapTemplate.Countries.Add(country69);
            var country70 = new CountryTemplate("70", "L&uuml;neburg") { X = 379, Y = 170 };
            mapTemplate.Countries.Add(country70);
            var country71 = new CountryTemplate("71", "Ravensburg") { X = 323, Y = 215 };
            mapTemplate.Countries.Add(country71);
            var country72 = new CountryTemplate("72", "Hildesheim") { X = 376, Y = 226 };
            mapTemplate.Countries.Add(country72);
            var country73 = new CountryTemplate("73", "Magdeburg") { X = 436, Y = 216 };
            mapTemplate.Countries.Add(country73);
            var country74 = new CountryTemplate("74", "Altmark") { X = 434, Y = 171 };
            mapTemplate.Countries.Add(country74);
            var country75 = new CountryTemplate("75", "Prignitz") { X = 465, Y = 141 };
            mapTemplate.Countries.Add(country75);
            var country76 = new CountryTemplate("76", "Mittelmark") { X = 518, Y = 185 };
            mapTemplate.Countries.Add(country76);
            var country77 = new CountryTemplate("77", "Ukermark") { X = 532, Y = 135 };
            mapTemplate.Countries.Add(country77);
            var country78 = new CountryTemplate("78", "Neumark") { X = 585, Y = 162 };
            mapTemplate.Countries.Add(country78);
            var country79 = new CountryTemplate("79", "Holstein") { X = 351, Y = 65 };
            mapTemplate.Countries.Add(country79);
            var country80 = new CountryTemplate("80", "Kiel") { X = 402, Y = 52 };
            mapTemplate.Countries.Add(country80);
            var country81 = new CountryTemplate("81", "Lauenburg") { X = 397, Y = 104 };
            mapTemplate.Countries.Add(country81);
            var country82 = new CountryTemplate("82", "Wismar") { X = 449, Y = 74 };
            mapTemplate.Countries.Add(country82);
            var country83 = new CountryTemplate("83", "Schwerin") { X = 478, Y = 104 };
            mapTemplate.Countries.Add(country83);
            var country84 = new CountryTemplate("84", "VorPommern") { X = 530, Y = 62 };
            mapTemplate.Countries.Add(country84);
            var country85 = new CountryTemplate("85", "HinterPommern") { X = 654, Y = 56 };
            mapTemplate.Countries.Add(country85);
            var country86 = new CountryTemplate("86", "Hokerland") { X = 765, Y = 78 };
            mapTemplate.Countries.Add(country86);
            var country87 = new CountryTemplate("87", "Galindien") { X = 834, Y = 88 };
            mapTemplate.Countries.Add(country87);
            var country88 = new CountryTemplate("88", "K&ouml;nigsberg") { X = 806, Y = 25 };
            mapTemplate.Countries.Add(country88);
            var country89 = new CountryTemplate("89", "Nadrauen") { X = 877, Y = 34 };
            mapTemplate.Countries.Add(country89);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country86);
            continent1.Countries.Add(country87);
            continent1.Countries.Add(country89);
            continent1.Countries.Add(country88);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 1);
            continent2.Countries.Add(country84);
            continent2.Countries.Add(country85);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country83);
            continent3.Countries.Add(country82);
            continent3.Countries.Add(country81);
            continent3.Countries.Add(country80);
            continent3.Countries.Add(country79);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 4);
            continent4.Countries.Add(country73);
            continent4.Countries.Add(country74);
            continent4.Countries.Add(country75);
            continent4.Countries.Add(country76);
            continent4.Countries.Add(country77);
            continent4.Countries.Add(country78);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country72);
            continent5.Countries.Add(country71);
            continent5.Countries.Add(country70);
            continent5.Countries.Add(country69);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country67);
            continent6.Countries.Add(country66);
            continent6.Countries.Add(country68);
            continent6.Countries.Add(country65);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 4);
            continent7.Countries.Add(country60);
            continent7.Countries.Add(country59);
            continent7.Countries.Add(country58);
            continent7.Countries.Add(country53);
            continent7.Countries.Add(country54);
            continent7.Countries.Add(country55);
            continent7.Countries.Add(country57);
            continent7.Countries.Add(country56);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country61);
            continent8.Countries.Add(country62);
            continent8.Countries.Add(country63);
            continent8.Countries.Add(country64);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 4);
            continent9.Countries.Add(country44);
            continent9.Countries.Add(country45);
            continent9.Countries.Add(country47);
            continent9.Countries.Add(country49);
            continent9.Countries.Add(country48);
            continent9.Countries.Add(country46);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country52);
            continent10.Countries.Add(country51);
            continent10.Countries.Add(country50);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 3);
            continent11.Countries.Add(country39);
            continent11.Countries.Add(country40);
            continent11.Countries.Add(country41);
            continent11.Countries.Add(country43);
            continent11.Countries.Add(country42);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 2);
            continent12.Countries.Add(country35);
            continent12.Countries.Add(country37);
            continent12.Countries.Add(country36);
            continent12.Countries.Add(country38);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 3);
            continent13.Countries.Add(country29);
            continent13.Countries.Add(country30);
            continent13.Countries.Add(country31);
            continent13.Countries.Add(country32);
            continent13.Countries.Add(country33);
            continent13.Countries.Add(country34);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 1);
            continent14.Countries.Add(country28);
            continent14.Countries.Add(country27);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 3);
            continent15.Countries.Add(country25);
            continent15.Countries.Add(country26);
            continent15.Countries.Add(country23);
            continent15.Countries.Add(country22);
            continent15.Countries.Add(country24);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 4);
            continent16.Countries.Add(country20);
            continent16.Countries.Add(country18);
            continent16.Countries.Add(country19);
            continent16.Countries.Add(country17);
            continent16.Countries.Add(country16);
            continent16.Countries.Add(country21);
            mapTemplate.Continents.Add(continent16);
            var continent17 = new Continent("17", 3);
            continent17.Countries.Add(country5);
            continent17.Countries.Add(country6);
            continent17.Countries.Add(country7);
            continent17.Countries.Add(country8);
            mapTemplate.Continents.Add(continent17);
            var continent18 = new Continent("18", 4);
            continent18.Countries.Add(country9);
            continent18.Countries.Add(country10);
            continent18.Countries.Add(country15);
            continent18.Countries.Add(country14);
            continent18.Countries.Add(country11);
            continent18.Countries.Add(country13);
            continent18.Countries.Add(country12);
            mapTemplate.Continents.Add(continent18);
            var continent19 = new Continent("19", 2);
            continent19.Countries.Add(country4);
            continent19.Countries.Add(country3);
            continent19.Countries.Add(country2);
            continent19.Countries.Add(country1);
            mapTemplate.Continents.Add(continent19);
            mapTemplate.Connections.Add(new Connection("15", "28"));
            mapTemplate.Connections.Add(new Connection("15", "30"));
            mapTemplate.Connections.Add(new Connection("15", "34"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "10"));
            mapTemplate.Connections.Add(new Connection("62", "61"));
            mapTemplate.Connections.Add(new Connection("62", "56"));
            mapTemplate.Connections.Add(new Connection("62", "67"));
            mapTemplate.Connections.Add(new Connection("62", "71"));
            mapTemplate.Connections.Add(new Connection("62", "64"));
            mapTemplate.Connections.Add(new Connection("62", "63"));
            mapTemplate.Connections.Add(new Connection("62", "50"));
            mapTemplate.Connections.Add(new Connection("62", "59"));
            mapTemplate.Connections.Add(new Connection("79", "80"));
            mapTemplate.Connections.Add(new Connection("79", "81"));
            mapTemplate.Connections.Add(new Connection("79", "69"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("30", "15"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("43", "41"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "35"));
            mapTemplate.Connections.Add(new Connection("43", "32"));
            mapTemplate.Connections.Add(new Connection("31", "29"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("16", "60"));
            mapTemplate.Connections.Add(new Connection("16", "19"));
            mapTemplate.Connections.Add(new Connection("48", "46"));
            mapTemplate.Connections.Add(new Connection("48", "45"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "27"));
            mapTemplate.Connections.Add(new Connection("48", "26"));
            mapTemplate.Connections.Add(new Connection("80", "79"));
            mapTemplate.Connections.Add(new Connection("86", "87"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("59", "58"));
            mapTemplate.Connections.Add(new Connection("59", "57"));
            mapTemplate.Connections.Add(new Connection("59", "61"));
            mapTemplate.Connections.Add(new Connection("59", "50"));
            mapTemplate.Connections.Add(new Connection("59", "62"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "32"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "15"));
            mapTemplate.Connections.Add(new Connection("32", "41"));
            mapTemplate.Connections.Add(new Connection("32", "43"));
            mapTemplate.Connections.Add(new Connection("32", "35"));
            mapTemplate.Connections.Add(new Connection("32", "36"));
            mapTemplate.Connections.Add(new Connection("32", "34"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "29"));
            mapTemplate.Connections.Add(new Connection("73", "72"));
            mapTemplate.Connections.Add(new Connection("73", "70"));
            mapTemplate.Connections.Add(new Connection("73", "74"));
            mapTemplate.Connections.Add(new Connection("73", "75"));
            mapTemplate.Connections.Add(new Connection("73", "76"));
            mapTemplate.Connections.Add(new Connection("73", "39"));
            mapTemplate.Connections.Add(new Connection("73", "41"));
            mapTemplate.Connections.Add(new Connection("41", "47"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "76"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "43"));
            mapTemplate.Connections.Add(new Connection("41", "32"));
            mapTemplate.Connections.Add(new Connection("41", "29"));
            mapTemplate.Connections.Add(new Connection("41", "27"));
            mapTemplate.Connections.Add(new Connection("41", "73"));
            mapTemplate.Connections.Add(new Connection("70", "67"));
            mapTemplate.Connections.Add(new Connection("70", "66"));
            mapTemplate.Connections.Add(new Connection("70", "68"));
            mapTemplate.Connections.Add(new Connection("70", "69"));
            mapTemplate.Connections.Add(new Connection("70", "81"));
            mapTemplate.Connections.Add(new Connection("70", "75"));
            mapTemplate.Connections.Add(new Connection("70", "74"));
            mapTemplate.Connections.Add(new Connection("70", "73"));
            mapTemplate.Connections.Add(new Connection("70", "72"));
            mapTemplate.Connections.Add(new Connection("70", "71"));
            mapTemplate.Connections.Add(new Connection("70", "83"));
            mapTemplate.Connections.Add(new Connection("60", "58"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("60", "50"));
            mapTemplate.Connections.Add(new Connection("60", "51"));
            mapTemplate.Connections.Add(new Connection("60", "19"));
            mapTemplate.Connections.Add(new Connection("60", "16"));
            mapTemplate.Connections.Add(new Connection("85", "84"));
            mapTemplate.Connections.Add(new Connection("85", "88"));
            mapTemplate.Connections.Add(new Connection("85", "78"));
            mapTemplate.Connections.Add(new Connection("85", "77"));
            mapTemplate.Connections.Add(new Connection("1", "6"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("61", "57"));
            mapTemplate.Connections.Add(new Connection("61", "56"));
            mapTemplate.Connections.Add(new Connection("61", "62"));
            mapTemplate.Connections.Add(new Connection("61", "59"));
            mapTemplate.Connections.Add(new Connection("29", "27"));
            mapTemplate.Connections.Add(new Connection("29", "41"));
            mapTemplate.Connections.Add(new Connection("29", "32"));
            mapTemplate.Connections.Add(new Connection("29", "31"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("14", "10"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "11"));
            mapTemplate.Connections.Add(new Connection("83", "82"));
            mapTemplate.Connections.Add(new Connection("83", "84"));
            mapTemplate.Connections.Add(new Connection("83", "77"));
            mapTemplate.Connections.Add(new Connection("83", "76"));
            mapTemplate.Connections.Add(new Connection("83", "75"));
            mapTemplate.Connections.Add(new Connection("83", "81"));
            mapTemplate.Connections.Add(new Connection("83", "70"));
            mapTemplate.Connections.Add(new Connection("47", "45"));
            mapTemplate.Connections.Add(new Connection("47", "40"));
            mapTemplate.Connections.Add(new Connection("47", "41"));
            mapTemplate.Connections.Add(new Connection("47", "27"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "39"));
            mapTemplate.Connections.Add(new Connection("68", "66"));
            mapTemplate.Connections.Add(new Connection("68", "65"));
            mapTemplate.Connections.Add(new Connection("68", "69"));
            mapTemplate.Connections.Add(new Connection("68", "70"));
            mapTemplate.Connections.Add(new Connection("58", "53"));
            mapTemplate.Connections.Add(new Connection("58", "54"));
            mapTemplate.Connections.Add(new Connection("58", "55"));
            mapTemplate.Connections.Add(new Connection("58", "57"));
            mapTemplate.Connections.Add(new Connection("58", "59"));
            mapTemplate.Connections.Add(new Connection("58", "60"));
            mapTemplate.Connections.Add(new Connection("75", "83"));
            mapTemplate.Connections.Add(new Connection("75", "76"));
            mapTemplate.Connections.Add(new Connection("75", "73"));
            mapTemplate.Connections.Add(new Connection("75", "74"));
            mapTemplate.Connections.Add(new Connection("75", "70"));
            mapTemplate.Connections.Add(new Connection("75", "81"));
            mapTemplate.Connections.Add(new Connection("82", "83"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "5"));
            mapTemplate.Connections.Add(new Connection("18", "6"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("63", "62"));
            mapTemplate.Connections.Add(new Connection("63", "64"));
            mapTemplate.Connections.Add(new Connection("63", "50"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("66", "56"));
            mapTemplate.Connections.Add(new Connection("66", "65"));
            mapTemplate.Connections.Add(new Connection("66", "68"));
            mapTemplate.Connections.Add(new Connection("66", "70"));
            mapTemplate.Connections.Add(new Connection("66", "67"));
            mapTemplate.Connections.Add(new Connection("81", "79"));
            mapTemplate.Connections.Add(new Connection("81", "83"));
            mapTemplate.Connections.Add(new Connection("81", "70"));
            mapTemplate.Connections.Add(new Connection("81", "75"));
            mapTemplate.Connections.Add(new Connection("81", "69"));
            mapTemplate.Connections.Add(new Connection("12", "4"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("44", "51"));
            mapTemplate.Connections.Add(new Connection("44", "50"));
            mapTemplate.Connections.Add(new Connection("44", "64"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "46"));
            mapTemplate.Connections.Add(new Connection("44", "52"));
            mapTemplate.Connections.Add(new Connection("27", "48"));
            mapTemplate.Connections.Add(new Connection("27", "49"));
            mapTemplate.Connections.Add(new Connection("27", "47"));
            mapTemplate.Connections.Add(new Connection("27", "41"));
            mapTemplate.Connections.Add(new Connection("27", "29"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("64", "63"));
            mapTemplate.Connections.Add(new Connection("64", "62"));
            mapTemplate.Connections.Add(new Connection("64", "71"));
            mapTemplate.Connections.Add(new Connection("64", "45"));
            mapTemplate.Connections.Add(new Connection("64", "44"));
            mapTemplate.Connections.Add(new Connection("64", "50"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "6"));
            mapTemplate.Connections.Add(new Connection("2", "8"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "11"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("77", "83"));
            mapTemplate.Connections.Add(new Connection("77", "84"));
            mapTemplate.Connections.Add(new Connection("77", "78"));
            mapTemplate.Connections.Add(new Connection("77", "76"));
            mapTemplate.Connections.Add(new Connection("77", "85"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("28", "25"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "15"));
            mapTemplate.Connections.Add(new Connection("28", "10"));
            mapTemplate.Connections.Add(new Connection("28", "9"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("84", "83"));
            mapTemplate.Connections.Add(new Connection("84", "85"));
            mapTemplate.Connections.Add(new Connection("84", "77"));
            mapTemplate.Connections.Add(new Connection("84", "78"));
            mapTemplate.Connections.Add(new Connection("57", "55"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("57", "61"));
            mapTemplate.Connections.Add(new Connection("57", "59"));
            mapTemplate.Connections.Add(new Connection("57", "58"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "35"));
            mapTemplate.Connections.Add(new Connection("51", "60"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "44"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "19"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "4"));
            mapTemplate.Connections.Add(new Connection("8", "2"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "47"));
            mapTemplate.Connections.Add(new Connection("40", "45"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "52"));
            mapTemplate.Connections.Add(new Connection("23", "46"));
            mapTemplate.Connections.Add(new Connection("23", "26"));
            mapTemplate.Connections.Add(new Connection("23", "25"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("87", "86"));
            mapTemplate.Connections.Add(new Connection("87", "89"));
            mapTemplate.Connections.Add(new Connection("72", "71"));
            mapTemplate.Connections.Add(new Connection("72", "70"));
            mapTemplate.Connections.Add(new Connection("72", "73"));
            mapTemplate.Connections.Add(new Connection("72", "39"));
            mapTemplate.Connections.Add(new Connection("72", "45"));
            mapTemplate.Connections.Add(new Connection("35", "43"));
            mapTemplate.Connections.Add(new Connection("35", "42"));
            mapTemplate.Connections.Add(new Connection("35", "78"));
            mapTemplate.Connections.Add(new Connection("35", "37"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "32"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "20"));
            mapTemplate.Connections.Add(new Connection("7", "22"));
            mapTemplate.Connections.Add(new Connection("7", "24"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "25"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "27"));
            mapTemplate.Connections.Add(new Connection("54", "55"));
            mapTemplate.Connections.Add(new Connection("54", "58"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("71", "67"));
            mapTemplate.Connections.Add(new Connection("71", "70"));
            mapTemplate.Connections.Add(new Connection("71", "72"));
            mapTemplate.Connections.Add(new Connection("71", "45"));
            mapTemplate.Connections.Add(new Connection("71", "64"));
            mapTemplate.Connections.Add(new Connection("71", "62"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "52"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "7"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "25"));
            mapTemplate.Connections.Add(new Connection("9", "28"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("9", "4"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "58"));
            mapTemplate.Connections.Add(new Connection("65", "68"));
            mapTemplate.Connections.Add(new Connection("65", "66"));
            mapTemplate.Connections.Add(new Connection("65", "56"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("21", "52"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("6", "18"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("6", "2"));
            mapTemplate.Connections.Add(new Connection("6", "1"));
            mapTemplate.Connections.Add(new Connection("78", "76"));
            mapTemplate.Connections.Add(new Connection("78", "77"));
            mapTemplate.Connections.Add(new Connection("78", "85"));
            mapTemplate.Connections.Add(new Connection("78", "35"));
            mapTemplate.Connections.Add(new Connection("78", "42"));
            mapTemplate.Connections.Add(new Connection("78", "84"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "44"));
            mapTemplate.Connections.Add(new Connection("52", "46"));
            mapTemplate.Connections.Add(new Connection("52", "23"));
            mapTemplate.Connections.Add(new Connection("52", "22"));
            mapTemplate.Connections.Add(new Connection("52", "21"));
            mapTemplate.Connections.Add(new Connection("52", "19"));
            mapTemplate.Connections.Add(new Connection("42", "76"));
            mapTemplate.Connections.Add(new Connection("42", "78"));
            mapTemplate.Connections.Add(new Connection("42", "35"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "7"));
            mapTemplate.Connections.Add(new Connection("88", "85"));
            mapTemplate.Connections.Add(new Connection("88", "89"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "8"));
            mapTemplate.Connections.Add(new Connection("4", "9"));
            mapTemplate.Connections.Add(new Connection("4", "11"));
            mapTemplate.Connections.Add(new Connection("4", "12"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "32"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("19", "16"));
            mapTemplate.Connections.Add(new Connection("19", "60"));
            mapTemplate.Connections.Add(new Connection("19", "51"));
            mapTemplate.Connections.Add(new Connection("19", "52"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "5"));
            mapTemplate.Connections.Add(new Connection("26", "46"));
            mapTemplate.Connections.Add(new Connection("26", "48"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "23"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("55", "57"));
            mapTemplate.Connections.Add(new Connection("55", "58"));
            mapTemplate.Connections.Add(new Connection("55", "54"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "14"));
            mapTemplate.Connections.Add(new Connection("11", "13"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "4"));
            mapTemplate.Connections.Add(new Connection("50", "60"));
            mapTemplate.Connections.Add(new Connection("50", "59"));
            mapTemplate.Connections.Add(new Connection("50", "62"));
            mapTemplate.Connections.Add(new Connection("50", "63"));
            mapTemplate.Connections.Add(new Connection("50", "64"));
            mapTemplate.Connections.Add(new Connection("50", "44"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("67", "56"));
            mapTemplate.Connections.Add(new Connection("67", "66"));
            mapTemplate.Connections.Add(new Connection("67", "70"));
            mapTemplate.Connections.Add(new Connection("67", "71"));
            mapTemplate.Connections.Add(new Connection("67", "62"));
            mapTemplate.Connections.Add(new Connection("39", "72"));
            mapTemplate.Connections.Add(new Connection("39", "73"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "76"));
            mapTemplate.Connections.Add(new Connection("39", "47"));
            mapTemplate.Connections.Add(new Connection("39", "45"));
            mapTemplate.Connections.Add(new Connection("76", "73"));
            mapTemplate.Connections.Add(new Connection("76", "75"));
            mapTemplate.Connections.Add(new Connection("76", "77"));
            mapTemplate.Connections.Add(new Connection("76", "83"));
            mapTemplate.Connections.Add(new Connection("76", "78"));
            mapTemplate.Connections.Add(new Connection("76", "42"));
            mapTemplate.Connections.Add(new Connection("76", "41"));
            mapTemplate.Connections.Add(new Connection("76", "39"));
            mapTemplate.Connections.Add(new Connection("45", "64"));
            mapTemplate.Connections.Add(new Connection("45", "71"));
            mapTemplate.Connections.Add(new Connection("45", "72"));
            mapTemplate.Connections.Add(new Connection("45", "39"));
            mapTemplate.Connections.Add(new Connection("45", "47"));
            mapTemplate.Connections.Add(new Connection("45", "48"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "40"));
            mapTemplate.Connections.Add(new Connection("74", "70"));
            mapTemplate.Connections.Add(new Connection("74", "75"));
            mapTemplate.Connections.Add(new Connection("74", "73"));
            mapTemplate.Connections.Add(new Connection("89", "87"));
            mapTemplate.Connections.Add(new Connection("89", "88"));
            mapTemplate.Connections.Add(new Connection("46", "44"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "48"));
            mapTemplate.Connections.Add(new Connection("46", "26"));
            mapTemplate.Connections.Add(new Connection("46", "23"));
            mapTemplate.Connections.Add(new Connection("46", "52"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("20", "7"));
            mapTemplate.Connections.Add(new Connection("20", "5"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "23"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "28"));
            mapTemplate.Connections.Add(new Connection("25", "9"));
            mapTemplate.Connections.Add(new Connection("25", "7"));
            mapTemplate.Connections.Add(new Connection("10", "28"));
            mapTemplate.Connections.Add(new Connection("10", "15"));
            mapTemplate.Connections.Add(new Connection("10", "14"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("56", "65"));
            mapTemplate.Connections.Add(new Connection("56", "66"));
            mapTemplate.Connections.Add(new Connection("56", "67"));
            mapTemplate.Connections.Add(new Connection("56", "62"));
            mapTemplate.Connections.Add(new Connection("56", "61"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("5", "18"));
            mapTemplate.Connections.Add(new Connection("5", "20"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "19"));
            mapTemplate.Connections.Add(new Connection("69", "70"));
            mapTemplate.Connections.Add(new Connection("69", "68"));
            mapTemplate.Connections.Add(new Connection("69", "81"));
            mapTemplate.Connections.Add(new Connection("69", "79"));

            return mapTemplate;
        }
    }
}
