using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Utopia()
        {
            var mapTemplate = new MapTemplate("Utopia") { Image = "utopia.jpg" };
            var country1 = new CountryTemplate("1", "Timeo") { X = 412, Y = 62 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Et") { X = 534, Y = 40 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Danaos") { X = 521, Y = 106 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Ferentes") { X = 617, Y = 95 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Dona") { X = 695, Y = 36 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Jokan") { X = 746, Y = 349 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Barisha") { X = 846, Y = 377 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Ingasiel") { X = 876, Y = 475 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Qarie") { X = 778, Y = 426 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Tsagn Ul") { X = 900, Y = 579 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Srg") { X = 773, Y = 503 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Rharakuu") { X = 793, Y = 578 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Eran") { X = 720, Y = 472 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Kan Maruu") { X = 647, Y = 619 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Jado") { X = 545, Y = 529 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Knoch-Andoo") { X = 327, Y = 472 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Ria") { X = 229, Y = 467 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Caol Ila") { X = 137, Y = 547 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Talisker") { X = 275, Y = 603 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Aire") { X = 59, Y = 650 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Ilae") { X = 212, Y = 298 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Slarhyn") { X = 396, Y = 371 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Corelthyn") { X = 201, Y = 388 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Ithyn") { X = 473, Y = 335 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Is Est") { X = 688, Y = 233 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Fendal") { X = 569, Y = 187 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Neneas") { X = 575, Y = 301 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Coral") { X = 490, Y = 249 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Is Ovest") { X = 357, Y = 274 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Son Fjorden") { X = 178, Y = 53 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Drauend Kusten") { X = 190, Y = 130 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Yokul") { X = 66, Y = 67 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Isr") { X = 82, Y = 128 };
            mapTemplate.Countries.Add(country33);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            continent2.Countries.Add(country8);
            continent2.Countries.Add(country9);
            continent2.Countries.Add(country10);
            continent2.Countries.Add(country11);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 2);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country15);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country16);
            continent4.Countries.Add(country17);
            continent4.Countries.Add(country18);
            continent4.Countries.Add(country19);
            continent4.Countries.Add(country20);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country21);
            continent5.Countries.Add(country22);
            continent5.Countries.Add(country23);
            continent5.Countries.Add(country24);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 4);
            continent6.Countries.Add(country25);
            continent6.Countries.Add(country26);
            continent6.Countries.Add(country27);
            continent6.Countries.Add(country28);
            continent6.Countries.Add(country29);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country30);
            continent7.Countries.Add(country31);
            continent7.Countries.Add(country32);
            continent7.Countries.Add(country33);
            mapTemplate.Continents.Add(continent7);
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "31"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "28"));
            mapTemplate.Connections.Add(new Connection("3", "26"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("4", "26"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("5", "25"));
            mapTemplate.Connections.Add(new Connection("6", "9"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "13"));
            mapTemplate.Connections.Add(new Connection("6", "27"));
            mapTemplate.Connections.Add(new Connection("6", "25"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "23"));
            mapTemplate.Connections.Add(new Connection("8", "11"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("8", "12"));
            mapTemplate.Connections.Add(new Connection("9", "6"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("10", "20"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "8"));
            mapTemplate.Connections.Add(new Connection("11", "13"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "8"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "6"));
            mapTemplate.Connections.Add(new Connection("13", "9"));
            mapTemplate.Connections.Add(new Connection("13", "11"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "19"));
            mapTemplate.Connections.Add(new Connection("16", "23"));
            mapTemplate.Connections.Add(new Connection("16", "22"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "23"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "23"));
            mapTemplate.Connections.Add(new Connection("19", "16"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "10"));
            mapTemplate.Connections.Add(new Connection("21", "23"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "31"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "16"));
            mapTemplate.Connections.Add(new Connection("22", "29"));
            mapTemplate.Connections.Add(new Connection("23", "21"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "7"));
            mapTemplate.Connections.Add(new Connection("23", "18"));
            mapTemplate.Connections.Add(new Connection("23", "17"));
            mapTemplate.Connections.Add(new Connection("23", "16"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "28"));
            mapTemplate.Connections.Add(new Connection("24", "27"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "6"));
            mapTemplate.Connections.Add(new Connection("25", "5"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "3"));
            mapTemplate.Connections.Add(new Connection("26", "4"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "6"));
            mapTemplate.Connections.Add(new Connection("27", "24"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "3"));
            mapTemplate.Connections.Add(new Connection("28", "24"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "31"));
            mapTemplate.Connections.Add(new Connection("29", "22"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "21"));
            mapTemplate.Connections.Add(new Connection("31", "1"));
            mapTemplate.Connections.Add(new Connection("31", "29"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "31"));

            return mapTemplate;
        }
    }
}
