using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate BRD()
        {
            var mapTemplate = new MapTemplate("BRD") { Image = "brd.jpg" };
            var country1 = new CountryTemplate("1", "Flensburg") { X = 359, Y = 90 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Heide") { X = 357, Y = 179 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Kiel") { X = 441, Y = 181 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Lübeck") { X = 490, Y = 200 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Pinneberg") { X = 405, Y = 233 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Mölln") { X = 481, Y = 265 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Hamburg") { X = 426, Y = 259 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Schwerin") { X = 542, Y = 241 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Rostock") { X = 605, Y = 192 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Ludwigslust") { X = 637, Y = 277 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Stralsund") { X = 674, Y = 163 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Greifswald") { X = 736, Y = 212 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Neubrandenburg") { X = 720, Y = 292 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Pasewalk") { X = 827, Y = 256 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Bremerhaven") { X = 298, Y = 247 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Bremen") { X = 307, Y = 333 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Cuxhaven") { X = 345, Y = 245 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Soltau") { X = 396, Y = 319 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Uelzen") { X = 505, Y = 350 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Oldenburg") { X = 253, Y = 318 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Emden") { X = 190, Y = 268 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Papenburg") { X = 186, Y = 358 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Osnabrück") { X = 246, Y = 468 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Diepholz") { X = 282, Y = 415 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Hannover") { X = 366, Y = 439 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Braunschweig") { X = 473, Y = 457 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Göttingen") { X = 426, Y = 577 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Neuruppin") { X = 706, Y = 363 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Prenzlau") { X = 806, Y = 347 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Eberswalde") { X = 816, Y = 397 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Frankfurt (Oder)") { X = 850, Y = 482 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Cottbus") { X = 817, Y = 590 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Herzberg") { X = 774, Y = 545 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Potsdam") { X = 726, Y = 458 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Berlin") { X = 767, Y = 423 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Salzwedel") { X = 554, Y = 413 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Halberstadt") { X = 539, Y = 549 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Magdeburg") { X = 625, Y = 481 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Dessau") { X = 673, Y = 561 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Halle") { X = 606, Y = 633 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Leipzig") { X = 709, Y = 666 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Meißen") { X = 815, Y = 638 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Görlitz") { X = 894, Y = 622 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Dresden") { X = 808, Y = 706 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Zwickau") { X = 678, Y = 766 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Gera") { X = 624, Y = 727 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Erfurt") { X = 547, Y = 671 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Eisenach") { X = 476, Y = 659 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Suhl") { X = 482, Y = 762 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Kassel") { X = 305, Y = 682 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Bad Hersfeld") { X = 386, Y = 712 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Fulda") { X = 363, Y = 795 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Frankfurt (Main)") { X = 288, Y = 861 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Gießen") { X = 302, Y = 761 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Wiesbaden") { X = 239, Y = 773 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Düsseldorf") { X = 155, Y = 672 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Dortmund") { X = 193, Y = 621 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Bielefeld") { X = 290, Y = 545 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Münster") { X = 160, Y = 526 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Duisburg") { X = 61, Y = 573 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Köln") { X = 72, Y = 724 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "Koblenz") { X = 181, Y = 767 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Kerpen") { X = 166, Y = 819 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "Trier") { X = 89, Y = 873 };
            mapTemplate.Countries.Add(country64);
            var country65 = new CountryTemplate("65", "Mainz") { X = 222, Y = 887 };
            mapTemplate.Countries.Add(country65);
            var country66 = new CountryTemplate("66", "Kaiserslautern") { X = 195, Y = 967 };
            mapTemplate.Countries.Add(country66);
            var country67 = new CountryTemplate("67", "Merzig") { X = 66, Y = 939 };
            mapTemplate.Countries.Add(country67);
            var country68 = new CountryTemplate("68", "Saarbrücken") { X = 121, Y = 954 };
            mapTemplate.Countries.Add(country68);
            var country69 = new CountryTemplate("69", "Karlsruhe") { X = 283, Y = 985 };
            mapTemplate.Countries.Add(country69);
            var country70 = new CountryTemplate("70", "Heilbronn") { X = 358, Y = 986 };
            mapTemplate.Countries.Add(country70);
            var country71 = new CountryTemplate("71", "Stuttgart") { X = 298, Y = 1160 };
            mapTemplate.Countries.Add(country71);
            var country72 = new CountryTemplate("72", "Offenburg") { X = 214, Y = 1107 };
            mapTemplate.Countries.Add(country72);
            var country73 = new CountryTemplate("73", "Ulm") { X = 420, Y = 1072 };
            mapTemplate.Countries.Add(country73);
            var country74 = new CountryTemplate("74", "Freiburg") { X = 182, Y = 1208 };
            mapTemplate.Countries.Add(country74);
            var country75 = new CountryTemplate("75", "Ravensburg") { X = 373, Y = 1181 };
            mapTemplate.Countries.Add(country75);
            var country76 = new CountryTemplate("76", "Würzburg") { X = 416, Y = 840 };
            mapTemplate.Countries.Add(country76);
            var country77 = new CountryTemplate("77", "Nürnberg") { X = 500, Y = 905 };
            mapTemplate.Countries.Add(country77);
            var country78 = new CountryTemplate("78", "Bayreuth") { X = 609, Y = 867 };
            mapTemplate.Countries.Add(country78);
            var country79 = new CountryTemplate("79", "Regensburg") { X = 619, Y = 968 };
            mapTemplate.Countries.Add(country79);
            var country80 = new CountryTemplate("80", "Passau") { X = 777, Y = 1060 };
            mapTemplate.Countries.Add(country80);
            var country81 = new CountryTemplate("81", "Landshut") { X = 660, Y = 1099 };
            mapTemplate.Countries.Add(country81);
            var country82 = new CountryTemplate("82", "Augsburg") { X = 517, Y = 1069 };
            mapTemplate.Countries.Add(country82);
            var country83 = new CountryTemplate("83", "Kempten") { X = 481, Y = 1208 };
            mapTemplate.Countries.Add(country83);
            var country84 = new CountryTemplate("84", "München") { X = 606, Y = 1211 };
            mapTemplate.Countries.Add(country84);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            continent1.Countries.Add(country6);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 1);
            continent2.Countries.Add(country7);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country8);
            continent3.Countries.Add(country9);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 1);
            continent4.Countries.Add(country15);
            continent4.Countries.Add(country16);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 5);
            continent5.Countries.Add(country17);
            continent5.Countries.Add(country18);
            continent5.Countries.Add(country19);
            continent5.Countries.Add(country20);
            continent5.Countries.Add(country21);
            continent5.Countries.Add(country22);
            continent5.Countries.Add(country23);
            continent5.Countries.Add(country24);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country28);
            continent6.Countries.Add(country29);
            continent6.Countries.Add(country30);
            continent6.Countries.Add(country31);
            continent6.Countries.Add(country32);
            continent6.Countries.Add(country33);
            continent6.Countries.Add(country34);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 1);
            continent7.Countries.Add(country35);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country36);
            continent8.Countries.Add(country37);
            continent8.Countries.Add(country38);
            continent8.Countries.Add(country39);
            continent8.Countries.Add(country40);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 2);
            continent9.Countries.Add(country41);
            continent9.Countries.Add(country42);
            continent9.Countries.Add(country43);
            continent9.Countries.Add(country44);
            continent9.Countries.Add(country45);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country46);
            continent10.Countries.Add(country47);
            continent10.Countries.Add(country48);
            continent10.Countries.Add(country49);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 4);
            continent11.Countries.Add(country50);
            continent11.Countries.Add(country51);
            continent11.Countries.Add(country52);
            continent11.Countries.Add(country53);
            continent11.Countries.Add(country54);
            continent11.Countries.Add(country55);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 3);
            continent12.Countries.Add(country56);
            continent12.Countries.Add(country57);
            continent12.Countries.Add(country58);
            continent12.Countries.Add(country59);
            continent12.Countries.Add(country60);
            continent12.Countries.Add(country61);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 2);
            continent13.Countries.Add(country62);
            continent13.Countries.Add(country63);
            continent13.Countries.Add(country64);
            continent13.Countries.Add(country65);
            continent13.Countries.Add(country66);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 1);
            continent14.Countries.Add(country67);
            continent14.Countries.Add(country68);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 3);
            continent15.Countries.Add(country69);
            continent15.Countries.Add(country70);
            continent15.Countries.Add(country71);
            continent15.Countries.Add(country72);
            continent15.Countries.Add(country73);
            continent15.Countries.Add(country74);
            continent15.Countries.Add(country75);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 4);
            continent16.Countries.Add(country76);
            continent16.Countries.Add(country77);
            continent16.Countries.Add(country78);
            continent16.Countries.Add(country79);
            continent16.Countries.Add(country80);
            continent16.Countries.Add(country81);
            continent16.Countries.Add(country82);
            continent16.Countries.Add(country83);
            continent16.Countries.Add(country84);
            mapTemplate.Continents.Add(continent16);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "6"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "6"));
            mapTemplate.Connections.Add(new Connection("4", "8"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("6", "3"));
            mapTemplate.Connections.Add(new Connection("6", "4"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("6", "19"));
            mapTemplate.Connections.Add(new Connection("6", "18"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "10"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "18"));
            mapTemplate.Connections.Add(new Connection("8", "4"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("9", "12"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "13"));
            mapTemplate.Connections.Add(new Connection("10", "28"));
            mapTemplate.Connections.Add(new Connection("10", "19"));
            mapTemplate.Connections.Add(new Connection("10", "6"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("12", "9"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "10"));
            mapTemplate.Connections.Add(new Connection("13", "29"));
            mapTemplate.Connections.Add(new Connection("13", "28"));
            mapTemplate.Connections.Add(new Connection("13", "9"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "29"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("16", "20"));
            mapTemplate.Connections.Add(new Connection("16", "24"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "20"));
            mapTemplate.Connections.Add(new Connection("18", "7"));
            mapTemplate.Connections.Add(new Connection("18", "6"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "26"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "24"));
            mapTemplate.Connections.Add(new Connection("18", "25"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("19", "10"));
            mapTemplate.Connections.Add(new Connection("19", "6"));
            mapTemplate.Connections.Add(new Connection("19", "28"));
            mapTemplate.Connections.Add(new Connection("19", "36"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "26"));
            mapTemplate.Connections.Add(new Connection("20", "17"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "16"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("20", "24"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "58"));
            mapTemplate.Connections.Add(new Connection("23", "59"));
            mapTemplate.Connections.Add(new Connection("24", "16"));
            mapTemplate.Connections.Add(new Connection("24", "18"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "20"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "58"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "18"));
            mapTemplate.Connections.Add(new Connection("25", "27"));
            mapTemplate.Connections.Add(new Connection("25", "58"));
            mapTemplate.Connections.Add(new Connection("26", "37"));
            mapTemplate.Connections.Add(new Connection("26", "36"));
            mapTemplate.Connections.Add(new Connection("26", "19"));
            mapTemplate.Connections.Add(new Connection("26", "18"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("27", "37"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "25"));
            mapTemplate.Connections.Add(new Connection("27", "58"));
            mapTemplate.Connections.Add(new Connection("27", "48"));
            mapTemplate.Connections.Add(new Connection("27", "50"));
            mapTemplate.Connections.Add(new Connection("27", "51"));
            mapTemplate.Connections.Add(new Connection("28", "13"));
            mapTemplate.Connections.Add(new Connection("28", "10"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "34"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "36"));
            mapTemplate.Connections.Add(new Connection("28", "19"));
            mapTemplate.Connections.Add(new Connection("28", "35"));
            mapTemplate.Connections.Add(new Connection("29", "14"));
            mapTemplate.Connections.Add(new Connection("29", "13"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "35"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "35"));
            mapTemplate.Connections.Add(new Connection("31", "34"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "42"));
            mapTemplate.Connections.Add(new Connection("32", "43"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "39"));
            mapTemplate.Connections.Add(new Connection("33", "42"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "28"));
            mapTemplate.Connections.Add(new Connection("34", "31"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "39"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("35", "30"));
            mapTemplate.Connections.Add(new Connection("35", "31"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "28"));
            mapTemplate.Connections.Add(new Connection("36", "28"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "19"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "26"));
            mapTemplate.Connections.Add(new Connection("37", "40"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "26"));
            mapTemplate.Connections.Add(new Connection("37", "27"));
            mapTemplate.Connections.Add(new Connection("37", "48"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("39", "34"));
            mapTemplate.Connections.Add(new Connection("39", "33"));
            mapTemplate.Connections.Add(new Connection("39", "42"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("40", "46"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("40", "47"));
            mapTemplate.Connections.Add(new Connection("40", "37"));
            mapTemplate.Connections.Add(new Connection("40", "48"));
            mapTemplate.Connections.Add(new Connection("41", "44"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "45"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "46"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("42", "33"));
            mapTemplate.Connections.Add(new Connection("42", "32"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "44"));
            mapTemplate.Connections.Add(new Connection("42", "39"));
            mapTemplate.Connections.Add(new Connection("43", "32"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "41"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "42"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "41"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "78"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "41"));
            mapTemplate.Connections.Add(new Connection("46", "40"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "49"));
            mapTemplate.Connections.Add(new Connection("46", "78"));
            mapTemplate.Connections.Add(new Connection("46", "77"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "40"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("48", "27"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "40"));
            mapTemplate.Connections.Add(new Connection("48", "37"));
            mapTemplate.Connections.Add(new Connection("48", "51"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("49", "51"));
            mapTemplate.Connections.Add(new Connection("49", "46"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "52"));
            mapTemplate.Connections.Add(new Connection("49", "77"));
            mapTemplate.Connections.Add(new Connection("49", "76"));
            mapTemplate.Connections.Add(new Connection("50", "56"));
            mapTemplate.Connections.Add(new Connection("50", "27"));
            mapTemplate.Connections.Add(new Connection("50", "58"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("50", "54"));
            mapTemplate.Connections.Add(new Connection("50", "55"));
            mapTemplate.Connections.Add(new Connection("51", "27"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "48"));
            mapTemplate.Connections.Add(new Connection("51", "49"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "54"));
            mapTemplate.Connections.Add(new Connection("52", "49"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "55"));
            mapTemplate.Connections.Add(new Connection("52", "54"));
            mapTemplate.Connections.Add(new Connection("52", "76"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("53", "55"));
            mapTemplate.Connections.Add(new Connection("53", "65"));
            mapTemplate.Connections.Add(new Connection("53", "69"));
            mapTemplate.Connections.Add(new Connection("53", "76"));
            mapTemplate.Connections.Add(new Connection("53", "70"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("54", "52"));
            mapTemplate.Connections.Add(new Connection("54", "51"));
            mapTemplate.Connections.Add(new Connection("54", "55"));
            mapTemplate.Connections.Add(new Connection("54", "50"));
            mapTemplate.Connections.Add(new Connection("55", "53"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("55", "62"));
            mapTemplate.Connections.Add(new Connection("55", "65"));
            mapTemplate.Connections.Add(new Connection("55", "52"));
            mapTemplate.Connections.Add(new Connection("55", "54"));
            mapTemplate.Connections.Add(new Connection("55", "63"));
            mapTemplate.Connections.Add(new Connection("55", "50"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "60"));
            mapTemplate.Connections.Add(new Connection("56", "61"));
            mapTemplate.Connections.Add(new Connection("56", "58"));
            mapTemplate.Connections.Add(new Connection("56", "50"));
            mapTemplate.Connections.Add(new Connection("56", "63"));
            mapTemplate.Connections.Add(new Connection("56", "62"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("57", "58"));
            mapTemplate.Connections.Add(new Connection("57", "59"));
            mapTemplate.Connections.Add(new Connection("57", "60"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("58", "27"));
            mapTemplate.Connections.Add(new Connection("58", "23"));
            mapTemplate.Connections.Add(new Connection("58", "25"));
            mapTemplate.Connections.Add(new Connection("58", "24"));
            mapTemplate.Connections.Add(new Connection("58", "59"));
            mapTemplate.Connections.Add(new Connection("58", "57"));
            mapTemplate.Connections.Add(new Connection("58", "56"));
            mapTemplate.Connections.Add(new Connection("58", "50"));
            mapTemplate.Connections.Add(new Connection("59", "23"));
            mapTemplate.Connections.Add(new Connection("59", "58"));
            mapTemplate.Connections.Add(new Connection("59", "57"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("60", "57"));
            mapTemplate.Connections.Add(new Connection("60", "61"));
            mapTemplate.Connections.Add(new Connection("60", "56"));
            mapTemplate.Connections.Add(new Connection("61", "60"));
            mapTemplate.Connections.Add(new Connection("61", "56"));
            mapTemplate.Connections.Add(new Connection("61", "63"));
            mapTemplate.Connections.Add(new Connection("62", "56"));
            mapTemplate.Connections.Add(new Connection("62", "63"));
            mapTemplate.Connections.Add(new Connection("62", "55"));
            mapTemplate.Connections.Add(new Connection("63", "61"));
            mapTemplate.Connections.Add(new Connection("63", "56"));
            mapTemplate.Connections.Add(new Connection("63", "64"));
            mapTemplate.Connections.Add(new Connection("63", "62"));
            mapTemplate.Connections.Add(new Connection("63", "65"));
            mapTemplate.Connections.Add(new Connection("63", "55"));
            mapTemplate.Connections.Add(new Connection("64", "63"));
            mapTemplate.Connections.Add(new Connection("64", "67"));
            mapTemplate.Connections.Add(new Connection("64", "65"));
            mapTemplate.Connections.Add(new Connection("65", "63"));
            mapTemplate.Connections.Add(new Connection("65", "55"));
            mapTemplate.Connections.Add(new Connection("65", "53"));
            mapTemplate.Connections.Add(new Connection("65", "64"));
            mapTemplate.Connections.Add(new Connection("65", "67"));
            mapTemplate.Connections.Add(new Connection("65", "66"));
            mapTemplate.Connections.Add(new Connection("65", "69"));
            mapTemplate.Connections.Add(new Connection("66", "67"));
            mapTemplate.Connections.Add(new Connection("66", "68"));
            mapTemplate.Connections.Add(new Connection("66", "65"));
            mapTemplate.Connections.Add(new Connection("66", "69"));
            mapTemplate.Connections.Add(new Connection("67", "64"));
            mapTemplate.Connections.Add(new Connection("67", "65"));
            mapTemplate.Connections.Add(new Connection("67", "66"));
            mapTemplate.Connections.Add(new Connection("67", "68"));
            mapTemplate.Connections.Add(new Connection("68", "66"));
            mapTemplate.Connections.Add(new Connection("68", "67"));
            mapTemplate.Connections.Add(new Connection("69", "66"));
            mapTemplate.Connections.Add(new Connection("69", "65"));
            mapTemplate.Connections.Add(new Connection("69", "53"));
            mapTemplate.Connections.Add(new Connection("69", "70"));
            mapTemplate.Connections.Add(new Connection("69", "72"));
            mapTemplate.Connections.Add(new Connection("69", "71"));
            mapTemplate.Connections.Add(new Connection("70", "76"));
            mapTemplate.Connections.Add(new Connection("70", "69"));
            mapTemplate.Connections.Add(new Connection("70", "53"));
            mapTemplate.Connections.Add(new Connection("70", "77"));
            mapTemplate.Connections.Add(new Connection("70", "71"));
            mapTemplate.Connections.Add(new Connection("70", "73"));
            mapTemplate.Connections.Add(new Connection("71", "74"));
            mapTemplate.Connections.Add(new Connection("71", "72"));
            mapTemplate.Connections.Add(new Connection("71", "69"));
            mapTemplate.Connections.Add(new Connection("71", "70"));
            mapTemplate.Connections.Add(new Connection("71", "73"));
            mapTemplate.Connections.Add(new Connection("71", "75"));
            mapTemplate.Connections.Add(new Connection("72", "69"));
            mapTemplate.Connections.Add(new Connection("72", "74"));
            mapTemplate.Connections.Add(new Connection("72", "71"));
            mapTemplate.Connections.Add(new Connection("73", "70"));
            mapTemplate.Connections.Add(new Connection("73", "71"));
            mapTemplate.Connections.Add(new Connection("73", "75"));
            mapTemplate.Connections.Add(new Connection("73", "77"));
            mapTemplate.Connections.Add(new Connection("73", "82"));
            mapTemplate.Connections.Add(new Connection("73", "83"));
            mapTemplate.Connections.Add(new Connection("74", "72"));
            mapTemplate.Connections.Add(new Connection("74", "75"));
            mapTemplate.Connections.Add(new Connection("74", "71"));
            mapTemplate.Connections.Add(new Connection("75", "74"));
            mapTemplate.Connections.Add(new Connection("75", "71"));
            mapTemplate.Connections.Add(new Connection("75", "73"));
            mapTemplate.Connections.Add(new Connection("75", "83"));
            mapTemplate.Connections.Add(new Connection("76", "49"));
            mapTemplate.Connections.Add(new Connection("76", "53"));
            mapTemplate.Connections.Add(new Connection("76", "70"));
            mapTemplate.Connections.Add(new Connection("76", "77"));
            mapTemplate.Connections.Add(new Connection("76", "52"));
            mapTemplate.Connections.Add(new Connection("77", "46"));
            mapTemplate.Connections.Add(new Connection("77", "49"));
            mapTemplate.Connections.Add(new Connection("77", "70"));
            mapTemplate.Connections.Add(new Connection("77", "76"));
            mapTemplate.Connections.Add(new Connection("77", "78"));
            mapTemplate.Connections.Add(new Connection("77", "73"));
            mapTemplate.Connections.Add(new Connection("77", "82"));
            mapTemplate.Connections.Add(new Connection("77", "79"));
            mapTemplate.Connections.Add(new Connection("78", "45"));
            mapTemplate.Connections.Add(new Connection("78", "46"));
            mapTemplate.Connections.Add(new Connection("78", "77"));
            mapTemplate.Connections.Add(new Connection("78", "79"));
            mapTemplate.Connections.Add(new Connection("79", "78"));
            mapTemplate.Connections.Add(new Connection("79", "77"));
            mapTemplate.Connections.Add(new Connection("79", "82"));
            mapTemplate.Connections.Add(new Connection("79", "80"));
            mapTemplate.Connections.Add(new Connection("79", "81"));
            mapTemplate.Connections.Add(new Connection("80", "79"));
            mapTemplate.Connections.Add(new Connection("80", "81"));
            mapTemplate.Connections.Add(new Connection("81", "79"));
            mapTemplate.Connections.Add(new Connection("81", "80"));
            mapTemplate.Connections.Add(new Connection("81", "82"));
            mapTemplate.Connections.Add(new Connection("81", "84"));
            mapTemplate.Connections.Add(new Connection("82", "73"));
            mapTemplate.Connections.Add(new Connection("82", "77"));
            mapTemplate.Connections.Add(new Connection("82", "83"));
            mapTemplate.Connections.Add(new Connection("82", "79"));
            mapTemplate.Connections.Add(new Connection("82", "81"));
            mapTemplate.Connections.Add(new Connection("82", "84"));
            mapTemplate.Connections.Add(new Connection("83", "73"));
            mapTemplate.Connections.Add(new Connection("83", "75"));
            mapTemplate.Connections.Add(new Connection("83", "82"));
            mapTemplate.Connections.Add(new Connection("83", "84"));
            mapTemplate.Connections.Add(new Connection("84", "82"));
            mapTemplate.Connections.Add(new Connection("84", "83"));
            mapTemplate.Connections.Add(new Connection("84", "81"));

            return mapTemplate;
        }
    }
}
