using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Whitehouse()
        {
            var mapTemplate = new MapTemplate("Whitehouse") { Image = "whitehouse.png" };
            var country1 = new CountryTemplate("1", "Kitchen") { X = 59, Y = 101 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Ki 3") { X = 123, Y = 182 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Presidents Dining") { X = 173, Y = 107 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Cosmotology") { X = 299, Y = 79 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "West Room") { X = 410, Y = 107 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "We 3") { X = 373, Y = 179 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "We 4") { X = 439, Y = 178 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "North Hall") { X = 497, Y = 181 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "No 2") { X = 488, Y = 73 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Small Stair") { X = 283, Y = 175 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Sm 2") { X = 327, Y = 175 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "East Room") { X = 571, Y = 108 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Ea 2") { X = 539, Y = 178 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Ea 3") { X = 601, Y = 178 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Grand Stair") { X = 694, Y = 181 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Gr 2") { X = 693, Y = 80 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Queens Room") { X = 815, Y = 101 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "QR 2") { X = 759, Y = 64 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "QR 3") { X = 742, Y = 157 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "QR 4") { X = 860, Y = 182 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Room") { X = 742, Y = 187 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Ro 2") { X = 786, Y = 220 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Queens Sitting") { X = 898, Y = 87 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "QS 2") { X = 943, Y = 133 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "QS 3") { X = 894, Y = 181 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "QS 4") { X = 936, Y = 182 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "West Sitting Hall") { X = 189, Y = 258 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Center Hall") { X = 492, Y = 259 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "East Sitting Hall") { X = 899, Y = 273 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Dressing Room") { X = 70, Y = 419 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Presidents Room") { X = 171, Y = 425 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Dr 3") { X = 37, Y = 352 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Dr 4") { X = 123, Y = 338 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Private Sitting") { X = 326, Y = 427 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Pr 2") { X = 254, Y = 337 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Pr 3") { X = 330, Y = 368 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Pr 4") { X = 378, Y = 343 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Yellow Oval") { X = 490, Y = 440 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Truman Balcony") { X = 570, Y = 569 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Treaty Room") { X = 653, Y = 416 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Tr 2") { X = 565, Y = 337 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Lincoln Bedroom") { X = 810, Y = 440 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "LB 2") { X = 753, Y = 319 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "LB 3") { X = 804, Y = 319 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Lincoln Sitting") { X = 894, Y = 424 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "LS 2") { X = 894, Y = 378 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "LS 3") { X = 938, Y = 353 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "LS 4") { X = 936, Y = 398 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Stair Standing") { X = 670, Y = 266 };
            mapTemplate.Countries.Add(country49);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 2);
            continent2.Countries.Add(country4);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 1);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 1);
            continent4.Countries.Add(country8);
            continent4.Countries.Add(country9);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 2);
            continent5.Countries.Add(country12);
            continent5.Countries.Add(country13);
            continent5.Countries.Add(country14);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 1);
            continent6.Countries.Add(country15);
            continent6.Countries.Add(country16);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country17);
            continent7.Countries.Add(country18);
            continent7.Countries.Add(country19);
            continent7.Countries.Add(country20);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 2);
            continent8.Countries.Add(country23);
            continent8.Countries.Add(country24);
            continent8.Countries.Add(country25);
            continent8.Countries.Add(country26);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 1);
            continent9.Countries.Add(country21);
            continent9.Countries.Add(country22);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country27);
            continent10.Countries.Add(country28);
            continent10.Countries.Add(country29);
            continent10.Countries.Add(country49);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 2);
            continent11.Countries.Add(country30);
            continent11.Countries.Add(country31);
            continent11.Countries.Add(country32);
            continent11.Countries.Add(country33);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 2);
            continent12.Countries.Add(country34);
            continent12.Countries.Add(country35);
            continent12.Countries.Add(country36);
            continent12.Countries.Add(country37);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 1);
            continent13.Countries.Add(country38);
            continent13.Countries.Add(country39);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 1);
            continent14.Countries.Add(country40);
            continent14.Countries.Add(country41);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 2);
            continent15.Countries.Add(country42);
            continent15.Countries.Add(country43);
            continent15.Countries.Add(country44);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 2);
            continent16.Countries.Add(country45);
            continent16.Countries.Add(country46);
            continent16.Countries.Add(country47);
            continent16.Countries.Add(country48);
            mapTemplate.Continents.Add(continent16);
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "27"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "27"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "10"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "28"));
            mapTemplate.Connections.Add(new Connection("8", "12"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("10", "4"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("12", "8"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "49"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("17", "29"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "20"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "23"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("20", "17"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("22", "29"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("23", "17"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "25"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("25", "29"));
            mapTemplate.Connections.Add(new Connection("25", "23"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("27", "1"));
            mapTemplate.Connections.Add(new Connection("27", "3"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "31"));
            mapTemplate.Connections.Add(new Connection("27", "33"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "8"));
            mapTemplate.Connections.Add(new Connection("28", "49"));
            mapTemplate.Connections.Add(new Connection("28", "38"));
            mapTemplate.Connections.Add(new Connection("28", "34"));
            mapTemplate.Connections.Add(new Connection("29", "49"));
            mapTemplate.Connections.Add(new Connection("29", "22"));
            mapTemplate.Connections.Add(new Connection("29", "25"));
            mapTemplate.Connections.Add(new Connection("29", "17"));
            mapTemplate.Connections.Add(new Connection("29", "46"));
            mapTemplate.Connections.Add(new Connection("29", "42"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("31", "34"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "27"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "27"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "37"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "31"));
            mapTemplate.Connections.Add(new Connection("34", "28"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("37", "34"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("38", "28"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("40", "49"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("42", "46"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "29"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "48"));
            mapTemplate.Connections.Add(new Connection("46", "29"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "42"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("48", "45"));
            mapTemplate.Connections.Add(new Connection("49", "15"));
            mapTemplate.Connections.Add(new Connection("49", "28"));
            mapTemplate.Connections.Add(new Connection("49", "29"));
            mapTemplate.Connections.Add(new Connection("49", "40"));

            return mapTemplate;
        }
    }
}
