using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate LotRisk()
        {
            var mapTemplate = new MapTemplate("LotRisk") { Image = "lotrisk.jpg" };
            var country1 = new CountryTemplate("1", "Forlindon") { X = 35, Y = 247 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Mithlond") { X = 110, Y = 280 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Tal des Lhun") { X = 131, Y = 207 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Turmberge") { X = 167, Y = 296 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Evendim-Berge") { X = 228, Y = 210 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Auenland") { X = 208, Y = 334 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Harlindon") { X = 81, Y = 351 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Forodwaith") { X = 444, Y = 43 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Ost-Angmar") { X = 466, Y = 96 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Angmar") { X = 366, Y = 125 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Grenzlande") { X = 362, Y = 203 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Noerdliche Hoehen") { X = 297, Y = 190 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Rhudaur") { X = 424, Y = 276 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Wetterberge") { X = 350, Y = 283 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Alter Wald") { X = 299, Y = 326 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Bockland") { X = 251, Y = 311 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Suedhoehen") { X = 302, Y = 388 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Carrock") { X = 502, Y = 166 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Noerdlicher Duesterwald") { X = 574, Y = 230 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Suedlicher Duesterwald") { X = 602, Y = 424 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Nord-Rhun") { X = 724, Y = 51 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Duerre Heide") { X = 656, Y = 82 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Esgaroth") { X = 635, Y = 217 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Sued-Rhun") { X = 716, Y = 255 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Moria") { X = 429, Y = 395 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Schwertefelder") { X = 496, Y = 380 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Lorien") { X = 461, Y = 483 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Oedland") { X = 495, Y = 606 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Emyn Muil") { X = 572, Y = 542 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Rhun-Berge") { X = 717, Y = 580 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Braune Lande") { X = 658, Y = 658 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Eregion") { X = 382, Y = 372 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Dunland") { X = 330, Y = 495 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Enedwaith") { X = 299, Y = 590 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Fangorn") { X = 411, Y = 640 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Pforte von Rohan") { X = 414, Y = 734 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Westrohan") { X = 328, Y = 696 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Udun-Tal") { X = 575, Y = 787 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Schicksalsberg") { X = 622, Y = 848 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Gorgoroth") { X = 690, Y = 858 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Minas Morgul") { X = 576, Y = 897 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Nurn") { X = 622, Y = 952 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Umbar") { X = 424, Y = 1055 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Harad") { X = 547, Y = 1089 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Weit-Harad") { X = 443, Y = 1118 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Nah-Harad") { X = 632, Y = 1075 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Druwaith Iaur") { X = 200, Y = 796 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Andrast") { X = 191, Y = 905 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Anfalas") { X = 235, Y = 874 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Erech-Tal") { X = 303, Y = 842 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Lamedon") { X = 362, Y = 835 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Lebennin") { X = 437, Y = 903 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Belfalas") { X = 378, Y = 917 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Tolfalas") { X = 380, Y = 989 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Minas Tirith") { X = 434, Y = 824 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Ithilien") { X = 511, Y = 872 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Sued-Ithilien") { X = 509, Y = 926 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Fornost") { X = 272, Y = 255 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Minhiriath") { X = 237, Y = 440 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Tal des Anduin") { X = 538, Y = 395 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Duesterwald") { X = 591, Y = 316 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "Harondor") { X = 504, Y = 1005 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Khand") { X = 713, Y = 1032 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "Totensuempfe") { X = 537, Y = 713 };
            mapTemplate.Countries.Add(country64);
            var continent1 = new Continent("1", 7);
            continent1.Countries.Add(country8);
            continent1.Countries.Add(country9);
            continent1.Countries.Add(country10);
            continent1.Countries.Add(country11);
            continent1.Countries.Add(country12);
            continent1.Countries.Add(country13);
            continent1.Countries.Add(country14);
            continent1.Countries.Add(country15);
            continent1.Countries.Add(country16);
            continent1.Countries.Add(country17);
            continent1.Countries.Add(country58);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 5);
            continent2.Countries.Add(country25);
            continent2.Countries.Add(country26);
            continent2.Countries.Add(country27);
            continent2.Countries.Add(country28);
            continent2.Countries.Add(country29);
            continent2.Countries.Add(country30);
            continent2.Countries.Add(country31);
            continent2.Countries.Add(country64);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 4);
            continent3.Countries.Add(country32);
            continent3.Countries.Add(country33);
            continent3.Countries.Add(country34);
            continent3.Countries.Add(country35);
            continent3.Countries.Add(country36);
            continent3.Countries.Add(country37);
            continent3.Countries.Add(country59);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 4);
            continent4.Countries.Add(country18);
            continent4.Countries.Add(country19);
            continent4.Countries.Add(country20);
            continent4.Countries.Add(country60);
            continent4.Countries.Add(country61);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country1);
            continent5.Countries.Add(country2);
            continent5.Countries.Add(country3);
            continent5.Countries.Add(country4);
            continent5.Countries.Add(country5);
            continent5.Countries.Add(country6);
            continent5.Countries.Add(country7);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 2);
            continent6.Countries.Add(country21);
            continent6.Countries.Add(country22);
            continent6.Countries.Add(country23);
            continent6.Countries.Add(country24);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country38);
            continent7.Countries.Add(country39);
            continent7.Countries.Add(country40);
            continent7.Countries.Add(country41);
            continent7.Countries.Add(country42);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 7);
            continent8.Countries.Add(country47);
            continent8.Countries.Add(country48);
            continent8.Countries.Add(country49);
            continent8.Countries.Add(country50);
            continent8.Countries.Add(country51);
            continent8.Countries.Add(country52);
            continent8.Countries.Add(country53);
            continent8.Countries.Add(country54);
            continent8.Countries.Add(country55);
            continent8.Countries.Add(country56);
            continent8.Countries.Add(country57);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 2);
            continent9.Countries.Add(country43);
            continent9.Countries.Add(country44);
            continent9.Countries.Add(country45);
            continent9.Countries.Add(country46);
            continent9.Countries.Add(country62);
            continent9.Countries.Add(country63);
            mapTemplate.Continents.Add(continent9);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "7"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "8"));
            mapTemplate.Connections.Add(new Connection("2", "59"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "11"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("4", "6"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("5", "12"));
            mapTemplate.Connections.Add(new Connection("5", "11"));
            mapTemplate.Connections.Add(new Connection("6", "4"));
            mapTemplate.Connections.Add(new Connection("6", "16"));
            mapTemplate.Connections.Add(new Connection("7", "2"));
            mapTemplate.Connections.Add(new Connection("8", "11"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "22"));
            mapTemplate.Connections.Add(new Connection("8", "21"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("8", "2"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "18"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("11", "3"));
            mapTemplate.Connections.Add(new Connection("11", "5"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "14"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "8"));
            mapTemplate.Connections.Add(new Connection("11", "58"));
            mapTemplate.Connections.Add(new Connection("12", "5"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "58"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "18"));
            mapTemplate.Connections.Add(new Connection("13", "32"));
            mapTemplate.Connections.Add(new Connection("14", "11"));
            mapTemplate.Connections.Add(new Connection("14", "58"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "17"));
            mapTemplate.Connections.Add(new Connection("15", "58"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("16", "6"));
            mapTemplate.Connections.Add(new Connection("16", "58"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "59"));
            mapTemplate.Connections.Add(new Connection("17", "14"));
            mapTemplate.Connections.Add(new Connection("18", "9"));
            mapTemplate.Connections.Add(new Connection("18", "13"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "60"));
            mapTemplate.Connections.Add(new Connection("19", "23"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "61"));
            mapTemplate.Connections.Add(new Connection("20", "61"));
            mapTemplate.Connections.Add(new Connection("20", "60"));
            mapTemplate.Connections.Add(new Connection("20", "29"));
            mapTemplate.Connections.Add(new Connection("20", "31"));
            mapTemplate.Connections.Add(new Connection("21", "8"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "24"));
            mapTemplate.Connections.Add(new Connection("22", "8"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "19"));
            mapTemplate.Connections.Add(new Connection("24", "21"));
            mapTemplate.Connections.Add(new Connection("24", "31"));
            mapTemplate.Connections.Add(new Connection("25", "32"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("26", "60"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("27", "35"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("28", "36"));
            mapTemplate.Connections.Add(new Connection("28", "35"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "60"));
            mapTemplate.Connections.Add(new Connection("29", "20"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "31"));
            mapTemplate.Connections.Add(new Connection("29", "64"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "24"));
            mapTemplate.Connections.Add(new Connection("31", "61"));
            mapTemplate.Connections.Add(new Connection("31", "29"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "64"));
            mapTemplate.Connections.Add(new Connection("31", "20"));
            mapTemplate.Connections.Add(new Connection("32", "13"));
            mapTemplate.Connections.Add(new Connection("32", "25"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("33", "59"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("34", "59"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "28"));
            mapTemplate.Connections.Add(new Connection("35", "27"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "28"));
            mapTemplate.Connections.Add(new Connection("36", "55"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "47"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "64"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("41", "56"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("43", "45"));
            mapTemplate.Connections.Add(new Connection("43", "53"));
            mapTemplate.Connections.Add(new Connection("44", "46"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "62"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "43"));
            mapTemplate.Connections.Add(new Connection("46", "63"));
            mapTemplate.Connections.Add(new Connection("46", "44"));
            mapTemplate.Connections.Add(new Connection("47", "37"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "50"));
            mapTemplate.Connections.Add(new Connection("50", "49"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "55"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "59"));
            mapTemplate.Connections.Add(new Connection("53", "43"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("55", "36"));
            mapTemplate.Connections.Add(new Connection("55", "52"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "41"));
            mapTemplate.Connections.Add(new Connection("56", "64"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("57", "62"));
            mapTemplate.Connections.Add(new Connection("58", "12"));
            mapTemplate.Connections.Add(new Connection("58", "16"));
            mapTemplate.Connections.Add(new Connection("58", "14"));
            mapTemplate.Connections.Add(new Connection("58", "11"));
            mapTemplate.Connections.Add(new Connection("58", "15"));
            mapTemplate.Connections.Add(new Connection("59", "17"));
            mapTemplate.Connections.Add(new Connection("59", "33"));
            mapTemplate.Connections.Add(new Connection("59", "34"));
            mapTemplate.Connections.Add(new Connection("59", "2"));
            mapTemplate.Connections.Add(new Connection("59", "53"));
            mapTemplate.Connections.Add(new Connection("60", "18"));
            mapTemplate.Connections.Add(new Connection("60", "61"));
            mapTemplate.Connections.Add(new Connection("60", "20"));
            mapTemplate.Connections.Add(new Connection("60", "26"));
            mapTemplate.Connections.Add(new Connection("60", "29"));
            mapTemplate.Connections.Add(new Connection("61", "60"));
            mapTemplate.Connections.Add(new Connection("61", "19"));
            mapTemplate.Connections.Add(new Connection("61", "31"));
            mapTemplate.Connections.Add(new Connection("61", "20"));
            mapTemplate.Connections.Add(new Connection("62", "44"));
            mapTemplate.Connections.Add(new Connection("62", "57"));
            mapTemplate.Connections.Add(new Connection("63", "46"));
            mapTemplate.Connections.Add(new Connection("64", "56"));
            mapTemplate.Connections.Add(new Connection("64", "38"));
            mapTemplate.Connections.Add(new Connection("64", "29"));
            mapTemplate.Connections.Add(new Connection("64", "31"));

            return mapTemplate;
        }
    }
}
