
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Sezessionskrieg_1861()
        {

var mapTemplate = new MapTemplate("Sezessionskrieg_1861") { Image = "sezession.jpg" };
var country1 = new CountryTemplate("1", "Oregon") { X = 78, Y = 146 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "California") { X = 58, Y = 292 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Washington Territory") { X = 190, Y = 154 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Utah Territory") { X = 178, Y = 296 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "New Mexico Territory") { X = 250, Y = 420 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Colorado Territory") { X = 322, Y = 302 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Nebraska Territory") { X = 328, Y = 160 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Unorganized Territory") { X = 424, Y = 134 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Minnesota") { X = 528, Y = 122 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Iowa") { X = 532, Y = 236 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Wisconsin") { X = 608, Y = 172 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Illinois") { X = 616, Y = 278 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Indiana") { X = 676, Y = 272 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Michigan") { X = 668, Y = 192 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Ohio") { X = 730, Y = 268 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Pennsylvania") { X = 822, Y = 238 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "New York") { X = 844, Y = 174 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Massachusets") { X = 896, Y = 146 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Maine") { X = 930, Y = 102 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Maryland") { X = 886, Y = 252 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Kansas") { X = 456, Y = 308 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Indian Reservat") { X = 478, Y = 410 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Missouri") { X = 562, Y = 342 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Kentucky") { X = 694, Y = 336 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Texas") { X = 452, Y = 490 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Arkansas") { X = 568, Y = 412 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Tennessee") { X = 678, Y = 388 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "North Carolina") { X = 828, Y = 376 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Virginia") { X = 803, Y = 320 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "South Carolina") { X = 798, Y = 406 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Alabama") { X = 684, Y = 452 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Mississippi") { X = 622, Y = 460 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Louisiana") { X = 570, Y = 474 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Florida") { X = 778, Y = 522 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Georgia") { X = 748, Y = 444 };
mapTemplate.Countries.Add(country35);
var continent1 = new Continent("1", 7);
continent1.Countries.Add(country9);
continent1.Countries.Add(country10);
continent1.Countries.Add(country11);
continent1.Countries.Add(country12);
continent1.Countries.Add(country13);
continent1.Countries.Add(country14);
continent1.Countries.Add(country15);
continent1.Countries.Add(country16);
continent1.Countries.Add(country17);
continent1.Countries.Add(country18);
continent1.Countries.Add(country19);
continent1.Countries.Add(country20);
continent1.Countries.Add(country21);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country25);
continent2.Countries.Add(country26);
continent2.Countries.Add(country27);
continent2.Countries.Add(country28);
continent2.Countries.Add(country29);
continent2.Countries.Add(country30);
continent2.Countries.Add(country31);
continent2.Countries.Add(country32);
continent2.Countries.Add(country33);
continent2.Countries.Add(country34);
continent2.Countries.Add(country35);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country3);
continent3.Countries.Add(country4);
continent3.Countries.Add(country5);
continent3.Countries.Add(country6);
continent3.Countries.Add(country7);
continent3.Countries.Add(country8);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country1);
continent5.Countries.Add(country2);
mapTemplate.Continents.Add(continent5);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "22"));
mapTemplate.Connections.Add(new Connection("5", "25"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "21"));
mapTemplate.Connections.Add(new Connection("6", "22"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "21"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "21"));
mapTemplate.Connections.Add(new Connection("10", "23"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "23"));
mapTemplate.Connections.Add(new Connection("12", "24"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "24"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "24"));
mapTemplate.Connections.Add(new Connection("15", "29"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("16", "29"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "29"));
mapTemplate.Connections.Add(new Connection("21", "6"));
mapTemplate.Connections.Add(new Connection("21", "7"));
mapTemplate.Connections.Add(new Connection("21", "10"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("22", "5"));
mapTemplate.Connections.Add(new Connection("22", "6"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("23", "10"));
mapTemplate.Connections.Add(new Connection("23", "12"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("24", "12"));
mapTemplate.Connections.Add(new Connection("24", "13"));
mapTemplate.Connections.Add(new Connection("24", "15"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "29"));
mapTemplate.Connections.Add(new Connection("25", "5"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "33"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "32"));
mapTemplate.Connections.Add(new Connection("26", "33"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "31"));
mapTemplate.Connections.Add(new Connection("27", "32"));
mapTemplate.Connections.Add(new Connection("27", "35"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "35"));
mapTemplate.Connections.Add(new Connection("29", "15"));
mapTemplate.Connections.Add(new Connection("29", "16"));
mapTemplate.Connections.Add(new Connection("29", "20"));
mapTemplate.Connections.Add(new Connection("29", "24"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "35"));
mapTemplate.Connections.Add(new Connection("31", "27"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "35"));
mapTemplate.Connections.Add(new Connection("32", "26"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "25"));
mapTemplate.Connections.Add(new Connection("33", "26"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "31"));
mapTemplate.Connections.Add(new Connection("35", "27"));
mapTemplate.Connections.Add(new Connection("35", "30"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "28"));

            return mapTemplate;
		}
    }
}

