
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Scherbenwelten()
        {

var mapTemplate = new MapTemplate("Scherbenwelten") { Image = "scherbenwelten.jpg" };
var country1 = new CountryTemplate("1", "Lager_Sued") { X = 162, Y = 553 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Winternacht") { X = 241, Y = 554 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Druidenforst") { X = 250, Y = 472 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Fendrakan") { X = 157, Y = 475 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Lothia") { X = 13, Y = 308 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Feste_Loh") { X = 89, Y = 329 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Burg_Tacheless") { X = 133, Y = 286 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Magesh") { X = 168, Y = 238 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Camp_Hoffnung") { X = 214, Y = 218 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Narvalon") { X = 236, Y = 164 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Goldburg") { X = 234, Y = 99 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Minuial") { X = 437, Y = 28 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Paladins_Lager") { X = 397, Y = 74 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Lukanien") { X = 345, Y = 97 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Gray_Monor") { X = 293, Y = 137 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Kuslik") { X = 316, Y = 179 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Nottinghamshire") { X = 262, Y = 243 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Sala_Mandra") { X = 202, Y = 297 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Lupinia") { X = 264, Y = 317 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "New_Hope") { X = 332, Y = 253 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Asgards_Heaven") { X = 324, Y = 316 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Menegroth") { X = 378, Y = 334 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Ostfels") { X = 437, Y = 318 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Orkenfried") { X = 489, Y = 349 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Aerlinn") { X = 551, Y = 389 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Kstenbrise") { X = 494, Y = 410 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Eremits_Ruh") { X = 520, Y = 486 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Miluiverien") { X = 562, Y = 433 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Zwillingsfels") { X = 638, Y = 424 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Wespennest") { X = 647, Y = 508 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Baslilea") { X = 593, Y = 565 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Albionatar") { X = 469, Y = 554 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Darkwood") { X = 524, Y = 643 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Arx_ars_Arcana") { X = 481, Y = 712 };
mapTemplate.Countries.Add(country34);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 6);
continent2.Countries.Add(country18);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country15);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
continent2.Countries.Add(country20);
continent2.Countries.Add(country19);
continent2.Countries.Add(country21);
continent2.Countries.Add(country22);
continent2.Countries.Add(country22);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country29);
continent4.Countries.Add(country28);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country30);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
continent5.Countries.Add(country34);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country4);
continent6.Countries.Add(country1);
continent6.Countries.Add(country2);
continent6.Countries.Add(country3);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("15", "10"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "23"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "15"));
mapTemplate.Connections.Add(new Connection("31", "27"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "10"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("7", "18"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "32"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("32", "2"));
mapTemplate.Connections.Add(new Connection("32", "22"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("9", "17"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "7"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("27", "31"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "9"));
mapTemplate.Connections.Add(new Connection("17", "10"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("2", "32"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "15"));
mapTemplate.Connections.Add(new Connection("10", "16"));
mapTemplate.Connections.Add(new Connection("10", "17"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));

            return mapTemplate;
		}
    }
}

