
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate USA()
        {

var mapTemplate = new MapTemplate("USA") { Image = "usa.png" };
var country1 = new CountryTemplate("1", "Alaska") { X = 110, Y = 563 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Hawaii") { X = 303, Y = 628 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Washington") { X = 128, Y = 47 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Oregon") { X = 96, Y = 136 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "California") { X = 38, Y = 290 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Montana") { X = 293, Y = 86 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Idaho") { X = 196, Y = 158 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Nevada") { X = 122, Y = 252 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Wyoming") { X = 324, Y = 195 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Utah") { X = 223, Y = 273 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Arizona") { X = 221, Y = 400 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Colorado") { X = 343, Y = 302 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "New Mexico") { X = 327, Y = 413 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "North Dakota") { X = 452, Y = 94 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "South Dakota") { X = 456, Y = 170 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Nebraska") { X = 473, Y = 251 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Kansas") { X = 495, Y = 327 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Oklahoma") { X = 519, Y = 412 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Texas") { X = 466, Y = 493 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Minnesota") { X = 560, Y = 108 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Iowa") { X = 590, Y = 235 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Missouri") { X = 602, Y = 331 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Arkansas") { X = 605, Y = 425 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Lousina") { X = 617, Y = 504 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Wisconsin") { X = 659, Y = 169 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Michigan") { X = 754, Y = 189 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Illinois") { X = 679, Y = 255 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Indiana") { X = 737, Y = 263 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Ohio") { X = 802, Y = 257 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Kentucky") { X = 774, Y = 326 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "West Virginia") { X = 842, Y = 307 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Virginia") { X = 906, Y = 305 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "North Carolina") { X = 882, Y = 361 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Tennesse") { X = 771, Y = 377 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Mississippi") { X = 686, Y = 459 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Alabama") { X = 738, Y = 453 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Georgia") { X = 825, Y = 458 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "South Carolina") { X = 866, Y = 414 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Florida") { X = 872, Y = 565 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Massachusetts") { X = 950, Y = 470 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Connecticut") { X = 951, Y = 502 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Rhode Island") { X = 951, Y = 537 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Delaware") { X = 951, Y = 567 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Maryland") { X = 929, Y = 273 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Pennsylvania") { X = 882, Y = 225 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "New York") { X = 945, Y = 156 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "New Jersey") { X = 983, Y = 239 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Vermont") { X = 968, Y = 104 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "New Hampshire") { X = 998, Y = 127 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Maine") { X = 1028, Y = 63 };
mapTemplate.Countries.Add(country50);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 1);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country20);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
continent6.Countries.Add(country27);
continent6.Countries.Add(country28);
continent6.Countries.Add(country29);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country23);
continent7.Countries.Add(country24);
continent7.Countries.Add(country35);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country36);
continent8.Countries.Add(country37);
continent8.Countries.Add(country38);
continent8.Countries.Add(country39);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country30);
continent9.Countries.Add(country31);
continent9.Countries.Add(country32);
continent9.Countries.Add(country33);
continent9.Countries.Add(country34);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 2);
continent10.Countries.Add(country44);
continent10.Countries.Add(country45);
continent10.Countries.Add(country46);
continent10.Countries.Add(country47);
continent10.Countries.Add(country48);
continent10.Countries.Add(country49);
continent10.Countries.Add(country50);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 1);
continent11.Countries.Add(country40);
continent11.Countries.Add(country41);
continent11.Countries.Add(country42);
continent11.Countries.Add(country43);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("2", "11"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "11"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "14"));
mapTemplate.Connections.Add(new Connection("6", "15"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "15"));
mapTemplate.Connections.Add(new Connection("9", "16"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("11", "2"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "18"));
mapTemplate.Connections.Add(new Connection("13", "19"));
mapTemplate.Connections.Add(new Connection("14", "6"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "20"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "20"));
mapTemplate.Connections.Add(new Connection("15", "9"));
mapTemplate.Connections.Add(new Connection("15", "6"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "21"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "9"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "22"));
mapTemplate.Connections.Add(new Connection("16", "21"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "13"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("18", "23"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "13"));
mapTemplate.Connections.Add(new Connection("19", "24"));
mapTemplate.Connections.Add(new Connection("19", "23"));
mapTemplate.Connections.Add(new Connection("20", "14"));
mapTemplate.Connections.Add(new Connection("20", "15"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "25"));
mapTemplate.Connections.Add(new Connection("21", "15"));
mapTemplate.Connections.Add(new Connection("21", "16"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "25"));
mapTemplate.Connections.Add(new Connection("21", "27"));
mapTemplate.Connections.Add(new Connection("22", "16"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "34"));
mapTemplate.Connections.Add(new Connection("22", "30"));
mapTemplate.Connections.Add(new Connection("22", "27"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("23", "18"));
mapTemplate.Connections.Add(new Connection("23", "19"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "35"));
mapTemplate.Connections.Add(new Connection("23", "34"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("24", "19"));
mapTemplate.Connections.Add(new Connection("24", "35"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "21"));
mapTemplate.Connections.Add(new Connection("25", "20"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "22"));
mapTemplate.Connections.Add(new Connection("27", "21"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "45"));
mapTemplate.Connections.Add(new Connection("30", "22"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "44"));
mapTemplate.Connections.Add(new Connection("31", "45"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "44"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "37"));
mapTemplate.Connections.Add(new Connection("33", "38"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "23"));
mapTemplate.Connections.Add(new Connection("34", "22"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "24"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "23"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "33"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "33"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("40", "46"));
mapTemplate.Connections.Add(new Connection("40", "48"));
mapTemplate.Connections.Add(new Connection("40", "49"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("41", "46"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("44", "31"));
mapTemplate.Connections.Add(new Connection("44", "32"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "29"));
mapTemplate.Connections.Add(new Connection("45", "31"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("46", "40"));
mapTemplate.Connections.Add(new Connection("46", "41"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("48", "40"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "40"));
mapTemplate.Connections.Add(new Connection("50", "49"));

            return mapTemplate;
		}
    }
}

