using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Hessen()
        {
            var mapTemplate = new MapTemplate("Hessen") { Image = "hessen.png" };
            var country1 = new CountryTemplate("1", "Hochsauerland") { X = 275, Y = 149 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Olpe") { X = 216, Y = 201 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Siegen-Wittgenstein") { X = 267, Y = 251 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Maerkischer Kreis") { X = 137, Y = 115 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Waldeck-Frankenberg") { X = 415, Y = 135 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Kassel") { X = 523, Y = 124 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Schwalm-Eder-Kreis") { X = 510, Y = 261 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Werra-Meissner-Kreis") { X = 673, Y = 207 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Hersfeld-Rotenburg") { X = 615, Y = 249 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Fulda") { X = 611, Y = 387 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Wiesbaden") { X = 259, Y = 600 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Rheingau-Taunus") { X = 232, Y = 531 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Hoch-Taunus") { X = 308, Y = 489 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Wetterau") { X = 403, Y = 492 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Main-Kinzig-Kreis") { X = 500, Y = 520 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Main-Taunus") { X = 289, Y = 555 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Frankfurt") { X = 350, Y = 551 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Offenbach") { X = 383, Y = 593 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Gross-Gerau") { X = 295, Y = 675 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Darmstadt-Dieburg") { X = 362, Y = 687 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Bergstrasse") { X = 372, Y = 758 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Odenwald") { X = 418, Y = 708 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Limburg-Weilburg") { X = 239, Y = 472 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Lahn-Dill-Kreis") { X = 297, Y = 401 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Marburg-Biedenkopf") { X = 367, Y = 315 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Giessen") { X = 396, Y = 414 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Vogelsberg") { X = 492, Y = 397 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Altenkirchen") { X = 143, Y = 303 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Westerwald") { X = 154, Y = 418 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Neuwied") { X = 44, Y = 380 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Mayen-Koblenz") { X = 74, Y = 475 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Rhein-Lahn-Kreis") { X = 130, Y = 517 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Rhein-Hunsrück") { X = 80, Y = 568 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Bad Kreuznach") { X = 117, Y = 654 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Mainz-Bingen") { X = 248, Y = 650 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Alzey-Worms") { X = 206, Y = 675 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Bad Kissingen") { X = 654, Y = 521 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Main-Spessart") { X = 586, Y = 602 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Aschaffenburg") { X = 472, Y = 600 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Schweinfurt") { X = 652, Y = 722 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Miltenberg") { X = 486, Y = 725 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Tauber-Bischoffsheim") { X = 599, Y = 759 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Neckar-Odenwald") { X = 492, Y = 800 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Heidelberg") { X = 344, Y = 825 };
            mapTemplate.Countries.Add(country44);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country28);
            continent2.Countries.Add(country29);
            continent2.Countries.Add(country30);
            continent2.Countries.Add(country31);
            continent2.Countries.Add(country32);
            continent2.Countries.Add(country33);
            continent2.Countries.Add(country34);
            continent2.Countries.Add(country35);
            continent2.Countries.Add(country36);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 4);
            continent3.Countries.Add(country37);
            continent3.Countries.Add(country38);
            continent3.Countries.Add(country39);
            continent3.Countries.Add(country40);
            continent3.Countries.Add(country41);
            continent3.Countries.Add(country42);
            continent3.Countries.Add(country43);
            continent3.Countries.Add(country44);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country5);
            continent4.Countries.Add(country6);
            continent4.Countries.Add(country7);
            continent4.Countries.Add(country8);
            continent4.Countries.Add(country9);
            continent4.Countries.Add(country10);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country23);
            continent5.Countries.Add(country24);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 6);
            continent6.Countries.Add(country11);
            continent6.Countries.Add(country12);
            continent6.Countries.Add(country13);
            continent6.Countries.Add(country14);
            continent6.Countries.Add(country15);
            continent6.Countries.Add(country16);
            continent6.Countries.Add(country17);
            continent6.Countries.Add(country18);
            continent6.Countries.Add(country19);
            continent6.Countries.Add(country20);
            continent6.Countries.Add(country21);
            continent6.Countries.Add(country22);
            mapTemplate.Continents.Add(continent6);
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "5"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "28"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("5", "1"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "27"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "27"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "37"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "19"));
            mapTemplate.Connections.Add(new Connection("11", "16"));
            mapTemplate.Connections.Add(new Connection("12", "32"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "16"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "17"));
            mapTemplate.Connections.Add(new Connection("13", "16"));
            mapTemplate.Connections.Add(new Connection("14", "27"));
            mapTemplate.Connections.Add(new Connection("14", "26"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "17"));
            mapTemplate.Connections.Add(new Connection("15", "37"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "39"));
            mapTemplate.Connections.Add(new Connection("15", "18"));
            mapTemplate.Connections.Add(new Connection("16", "12"));
            mapTemplate.Connections.Add(new Connection("16", "13"));
            mapTemplate.Connections.Add(new Connection("16", "11"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "19"));
            mapTemplate.Connections.Add(new Connection("17", "13"));
            mapTemplate.Connections.Add(new Connection("17", "14"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "15"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("19", "11"));
            mapTemplate.Connections.Add(new Connection("19", "16"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "41"));
            mapTemplate.Connections.Add(new Connection("23", "29"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("24", "29"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "27"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "14"));
            mapTemplate.Connections.Add(new Connection("27", "25"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "7"));
            mapTemplate.Connections.Add(new Connection("27", "9"));
            mapTemplate.Connections.Add(new Connection("27", "14"));
            mapTemplate.Connections.Add(new Connection("28", "3"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "31"));
            mapTemplate.Connections.Add(new Connection("29", "32"));
            mapTemplate.Connections.Add(new Connection("29", "23"));
            mapTemplate.Connections.Add(new Connection("29", "24"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "29"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("32", "29"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "12"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("33", "35"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "33"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("37", "10"));
            mapTemplate.Connections.Add(new Connection("37", "15"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "41"));
            mapTemplate.Connections.Add(new Connection("38", "42"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("39", "15"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "43"));
            mapTemplate.Connections.Add(new Connection("41", "38"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "22"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("42", "38"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("43", "41"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("44", "43"));

            return mapTemplate;
        }
    }
}
