
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate NovaAtlantis()
        {

var mapTemplate = new MapTemplate("NovaAtlantis") { Image = "novatlan.jpg" };
var country1 = new CountryTemplate("1", "Thule") { X = 314, Y = 81 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Varangia") { X = 536, Y = 18 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Galicia") { X = 492, Y = 126 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Alemania") { X = 348, Y = 261 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Gaul") { X = 256, Y = 378 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Iberia") { X = 208, Y = 513 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Anglia") { X = 188, Y = 259 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Caledonia") { X = 166, Y = 183 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Hibernia") { X = 96, Y = 242 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Hesperide") { X = 40, Y = 391 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Tritonis") { X = 21, Y = 464 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Poseidonis") { X = 33, Y = 560 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Oricalcos") { X = 59, Y = 626 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Atlas") { X = 260, Y = 631 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Carthago") { X = 420, Y = 571 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Gaitulia") { X = 404, Y = 643 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Cyrenaica") { X = 615, Y = 610 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Nubia") { X = 667, Y = 648 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Egypt") { X = 765, Y = 553 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Kush") { X = 864, Y = 622 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Sheba") { X = 950, Y = 536 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Babylon") { X = 956, Y = 453 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Sumer") { X = 985, Y = 365 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Assyria") { X = 911, Y = 354 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Parthia") { X = 955, Y = 250 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Phoenicia") { X = 826, Y = 396 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Sarmatia") { X = 936, Y = 57 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Rus") { X = 713, Y = 43 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Scythia") { X = 641, Y = 158 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Cimmeria") { X = 765, Y = 162 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Anatolia") { X = 828, Y = 282 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Ionia") { X = 698, Y = 360 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Dacia") { X = 526, Y = 260 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Thracia") { X = 578, Y = 324 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Graecia") { X = 587, Y = 412 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Minoa") { X = 659, Y = 478 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Sicilia") { X = 517, Y = 516 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Apulia") { X = 501, Y = 444 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Roma") { X = 435, Y = 417 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Corsica") { X = 383, Y = 472 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Liguria") { X = 389, Y = 365 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Dalmatia") { X = 470, Y = 339 };
mapTemplate.Countries.Add(country42);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country27);
continent2.Countries.Add(country28);
continent2.Countries.Add(country29);
continent2.Countries.Add(country30);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 6);
continent3.Countries.Add(country31);
continent3.Countries.Add(country32);
continent3.Countries.Add(country33);
continent3.Countries.Add(country34);
continent3.Countries.Add(country35);
continent3.Countries.Add(country36);
continent3.Countries.Add(country37);
continent3.Countries.Add(country38);
continent3.Countries.Add(country39);
continent3.Countries.Add(country40);
continent3.Countries.Add(country41);
continent3.Countries.Add(country42);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country10);
continent5.Countries.Add(country11);
continent5.Countries.Add(country12);
continent5.Countries.Add(country13);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country14);
continent6.Countries.Add(country15);
continent6.Countries.Add(country16);
continent6.Countries.Add(country17);
continent6.Countries.Add(country18);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "8"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "28"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "41"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "13"));
mapTemplate.Connections.Add(new Connection("6", "14"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("8", "1"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "6"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "6"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "37"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "26"));
mapTemplate.Connections.Add(new Connection("19", "36"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "26"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("26", "19"));
mapTemplate.Connections.Add(new Connection("26", "21"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "31"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "2"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "33"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "26"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("33", "29"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "42"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "42"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "19"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("37", "15"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "42"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "5"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "33"));
mapTemplate.Connections.Add(new Connection("42", "34"));
mapTemplate.Connections.Add(new Connection("42", "35"));
mapTemplate.Connections.Add(new Connection("42", "38"));
mapTemplate.Connections.Add(new Connection("42", "41"));

            return mapTemplate;
		}
    }
}

