
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Pirateninseln()
        {

var mapTemplate = new MapTemplate("Pirateninseln") { Image = "pirateninseln.png" };
var country1 = new CountryTemplate("1", "Nai") { X = 122, Y = 198 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Relec") { X = 188, Y = 222 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Naxur") { X = 222, Y = 131 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Ban") { X = 231, Y = 281 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Uskrr") { X = 397, Y = 172 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Nowik") { X = 546, Y = 178 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Wisolur") { X = 631, Y = 243 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Iero") { X = 539, Y = 250 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Serl") { X = 460, Y = 281 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Therv") { X = 761, Y = 139 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Aughn") { X = 890, Y = 188 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Baem") { X = 806, Y = 240 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Esyna") { X = 980, Y = 93 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Kelth") { X = 966, Y = 203 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Icero") { X = 1072, Y = 240 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Lybede") { X = 951, Y = 393 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Tryz") { X = 923, Y = 505 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Ooldu") { X = 995, Y = 461 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Hot") { X = 1010, Y = 578 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Ens") { X = 936, Y = 618 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Met") { X = 1077, Y = 605 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Ely") { X = 747, Y = 636 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Zhes") { X = 678, Y = 601 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Rynnd") { X = 591, Y = 646 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Ede") { X = 500, Y = 552 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Rucida") { X = 488, Y = 655 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Punan") { X = 208, Y = 638 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Kedutoya") { X = 246, Y = 543 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Zonin") { X = 122, Y = 588 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Banif") { X = 107, Y = 498 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Hin") { X = 203, Y = 433 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Tedyre") { X = 358, Y = 428 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Ket") { X = 576, Y = 463 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Cida") { X = 732, Y = 442 };
mapTemplate.Countries.Add(country34);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country16);
continent4.Countries.Add(country17);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country22);
continent5.Countries.Add(country23);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country27);
continent6.Countries.Add(country28);
continent6.Countries.Add(country29);
continent6.Countries.Add(country30);
continent6.Countries.Add(country31);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country32);
continent7.Countries.Add(country33);
continent7.Countries.Add(country34);
mapTemplate.Continents.Add(continent7);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "30"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "32"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "34"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "19"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "34"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "13"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "29"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("25", "32"));
mapTemplate.Connections.Add(new Connection("25", "33"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "24"));
mapTemplate.Connections.Add(new Connection("30", "1"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("32", "5"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "25"));
mapTemplate.Connections.Add(new Connection("33", "25"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "7"));
mapTemplate.Connections.Add(new Connection("34", "14"));

            return mapTemplate;
		}
    }
}

