using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Bayern()
        {
            var mapTemplate = new MapTemplate("Bayern") { Image = "bayern.jpg" };
            var country1 = new CountryTemplate("1", "Wuerzburg") { X = 139, Y = 198 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Miltenberg") { X = 30, Y = 189 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Aschaffenburg") { X = 30, Y = 119 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Main-Spessart") { X = 98, Y = 118 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Bad Kissingen") { X = 138, Y = 71 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Rhoen Grabfeld") { X = 178, Y = 29 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Schweinfurt") { X = 183, Y = 118 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Hasseberge") { X = 238, Y = 100 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Kitzingen") { X = 184, Y = 177 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Coburg") { X = 294, Y = 55 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Lichtenfels") { X = 318, Y = 94 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Bamberg") { X = 287, Y = 148 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Kronach") { X = 358, Y = 44 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Kulmbach") { X = 370, Y = 98 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Bayreuth") { X = 375, Y = 153 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Hof") { X = 421, Y = 59 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Wunsiedel") { X = 455, Y = 100 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Tischenreuth") { X = 475, Y = 193 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Neustadt_a_d_W.") { X = 486, Y = 137 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Amberg-Sulzbach") { X = 422, Y = 253 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Schwandorf") { X = 488, Y = 271 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Regen") { X = 562, Y = 292 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Neumarkt_i_d_Opf") { X = 386, Y = 304 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Nuernberger Land") { X = 359, Y = 239 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Erlangen") { X = 312, Y = 224 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Nuernberg") { X = 314, Y = 262 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Fuerth") { X = 281, Y = 248 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Erlangen-Hochstadt") { X = 277, Y = 204 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Neustadt_a_d_Aisch") { X = 222, Y = 226 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Ansbach") { X = 218, Y = 301 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Weissenburg-Gunzenhausen") { X = 287, Y = 348 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Roth") { X = 323, Y = 315 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Forchheim") { X = 329, Y = 187 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Regensburg") { X = 472, Y = 355 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Kelheim") { X = 433, Y = 395 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Landshut") { X = 487, Y = 455 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Straubing-Bogen") { X = 548, Y = 374 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Straubing") { X = 634, Y = 346 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Deggendorf") { X = 611, Y = 401 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Dingolfing-Landau") { X = 549, Y = 436 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Rottal-Inn") { X = 594, Y = 488 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Passau") { X = 659, Y = 451 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Freyung-Gravenau") { X = 695, Y = 382 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Eichstaett") { X = 362, Y = 371 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Ingolstadt") { X = 361, Y = 413 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Neuburg-Schrobenhausen") { X = 327, Y = 431 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Pfaffenhofen_a_d_Ilm") { X = 376, Y = 465 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Dachau") { X = 362, Y = 513 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Fuerstenfeldbruck") { X = 333, Y = 546 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Freising") { X = 418, Y = 489 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Muenchen") { X = 396, Y = 566 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Erding") { X = 458, Y = 519 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Ebersberg") { X = 448, Y = 572 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Muehldorf_a_Inn") { X = 519, Y = 530 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Altoetting") { X = 571, Y = 548 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Traunstein") { X = 561, Y = 622 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Berchtesgardener_Land") { X = 608, Y = 662 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Rosenheim") { X = 490, Y = 619 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Miesbach") { X = 436, Y = 650 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Wolfratshausen") { X = 385, Y = 653 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Starnberg") { X = 346, Y = 586 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "Weilheim-Schongau") { X = 316, Y = 637 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Landsberg_a_Lech") { X = 296, Y = 581 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "Garmisch-Partenkirchen") { X = 323, Y = 691 };
            mapTemplate.Countries.Add(country64);
            var country65 = new CountryTemplate("65", "Augsburg") { X = 264, Y = 519 };
            mapTemplate.Countries.Add(country65);
            var country66 = new CountryTemplate("66", "Donau-Ries") { X = 255, Y = 400 };
            mapTemplate.Countries.Add(country66);
            var country67 = new CountryTemplate("67", "Dillingen_a_d_Donau") { X = 228, Y = 452 };
            mapTemplate.Countries.Add(country67);
            var country68 = new CountryTemplate("68", "Guenzburg") { X = 209, Y = 519 };
            mapTemplate.Countries.Add(country68);
            var country69 = new CountryTemplate("69", "Neu-Ulm") { X = 173, Y = 526 };
            mapTemplate.Countries.Add(country69);
            var country70 = new CountryTemplate("70", "Unterallgaeu") { X = 205, Y = 577 };
            mapTemplate.Countries.Add(country70);
            var country71 = new CountryTemplate("71", "Lindau") { X = 135, Y = 674 };
            mapTemplate.Countries.Add(country71);
            var country72 = new CountryTemplate("72", "Oberallgaeu") { X = 187, Y = 687 };
            mapTemplate.Countries.Add(country72);
            var country73 = new CountryTemplate("73", "Ostallgaeu") { X = 241, Y = 658 };
            mapTemplate.Countries.Add(country73);
            var country74 = new CountryTemplate("74", "Aichach-Friedberg") { X = 313, Y = 486 };
            mapTemplate.Countries.Add(country74);
            var continent1 = new Continent("1", 4);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            continent1.Countries.Add(country6);
            continent1.Countries.Add(country7);
            continent1.Countries.Add(country8);
            continent1.Countries.Add(country9);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 1);
            continent2.Countries.Add(country1);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 5);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country15);
            continent3.Countries.Add(country16);
            continent3.Countries.Add(country17);
            continent3.Countries.Add(country33);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 6);
            continent4.Countries.Add(country24);
            continent4.Countries.Add(country28);
            continent4.Countries.Add(country29);
            continent4.Countries.Add(country30);
            continent4.Countries.Add(country31);
            continent4.Countries.Add(country32);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 2);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 5);
            continent6.Countries.Add(country18);
            continent6.Countries.Add(country19);
            continent6.Countries.Add(country20);
            continent6.Countries.Add(country21);
            continent6.Countries.Add(country22);
            continent6.Countries.Add(country23);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 1);
            continent7.Countries.Add(country34);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 6);
            continent8.Countries.Add(country66);
            continent8.Countries.Add(country67);
            continent8.Countries.Add(country68);
            continent8.Countries.Add(country69);
            continent8.Countries.Add(country70);
            continent8.Countries.Add(country71);
            continent8.Countries.Add(country72);
            continent8.Countries.Add(country73);
            continent8.Countries.Add(country74);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 1);
            continent9.Countries.Add(country65);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 5);
            continent10.Countries.Add(country44);
            continent10.Countries.Add(country46);
            continent10.Countries.Add(country47);
            continent10.Countries.Add(country48);
            continent10.Countries.Add(country49);
            continent10.Countries.Add(country50);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 1);
            continent11.Countries.Add(country45);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 6);
            continent12.Countries.Add(country35);
            continent12.Countries.Add(country36);
            continent12.Countries.Add(country37);
            continent12.Countries.Add(country38);
            continent12.Countries.Add(country39);
            continent12.Countries.Add(country40);
            continent12.Countries.Add(country41);
            continent12.Countries.Add(country42);
            continent12.Countries.Add(country43);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 8);
            continent13.Countries.Add(country52);
            continent13.Countries.Add(country53);
            continent13.Countries.Add(country54);
            continent13.Countries.Add(country55);
            continent13.Countries.Add(country56);
            continent13.Countries.Add(country57);
            continent13.Countries.Add(country58);
            continent13.Countries.Add(country59);
            continent13.Countries.Add(country60);
            continent13.Countries.Add(country61);
            continent13.Countries.Add(country62);
            continent13.Countries.Add(country63);
            continent13.Countries.Add(country64);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 1);
            continent14.Countries.Add(country51);
            mapTemplate.Continents.Add(continent14);
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("1", "7"));
            mapTemplate.Connections.Add(new Connection("1", "9"));
            mapTemplate.Connections.Add(new Connection("1", "29"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("4", "7"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "1"));
            mapTemplate.Connections.Add(new Connection("7", "4"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "12"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("8", "12"));
            mapTemplate.Connections.Add(new Connection("9", "1"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "12"));
            mapTemplate.Connections.Add(new Connection("9", "29"));
            mapTemplate.Connections.Add(new Connection("10", "13"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "13"));
            mapTemplate.Connections.Add(new Connection("11", "14"));
            mapTemplate.Connections.Add(new Connection("11", "15"));
            mapTemplate.Connections.Add(new Connection("12", "28"));
            mapTemplate.Connections.Add(new Connection("12", "29"));
            mapTemplate.Connections.Add(new Connection("12", "9"));
            mapTemplate.Connections.Add(new Connection("12", "7"));
            mapTemplate.Connections.Add(new Connection("12", "8"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "15"));
            mapTemplate.Connections.Add(new Connection("12", "33"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("13", "16"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "11"));
            mapTemplate.Connections.Add(new Connection("13", "10"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "11"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "16"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "18"));
            mapTemplate.Connections.Add(new Connection("15", "19"));
            mapTemplate.Connections.Add(new Connection("15", "20"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "12"));
            mapTemplate.Connections.Add(new Connection("15", "24"));
            mapTemplate.Connections.Add(new Connection("15", "33"));
            mapTemplate.Connections.Add(new Connection("15", "11"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "14"));
            mapTemplate.Connections.Add(new Connection("16", "13"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("18", "21"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "15"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "15"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("20", "24"));
            mapTemplate.Connections.Add(new Connection("20", "15"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("21", "34"));
            mapTemplate.Connections.Add(new Connection("21", "23"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "18"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("22", "38"));
            mapTemplate.Connections.Add(new Connection("22", "37"));
            mapTemplate.Connections.Add(new Connection("22", "34"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("23", "44"));
            mapTemplate.Connections.Add(new Connection("23", "32"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("23", "34"));
            mapTemplate.Connections.Add(new Connection("23", "35"));
            mapTemplate.Connections.Add(new Connection("23", "21"));
            mapTemplate.Connections.Add(new Connection("24", "32"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "33"));
            mapTemplate.Connections.Add(new Connection("24", "15"));
            mapTemplate.Connections.Add(new Connection("24", "20"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "27"));
            mapTemplate.Connections.Add(new Connection("25", "28"));
            mapTemplate.Connections.Add(new Connection("25", "33"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "32"));
            mapTemplate.Connections.Add(new Connection("27", "32"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("27", "29"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "25"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "12"));
            mapTemplate.Connections.Add(new Connection("28", "33"));
            mapTemplate.Connections.Add(new Connection("28", "25"));
            mapTemplate.Connections.Add(new Connection("29", "9"));
            mapTemplate.Connections.Add(new Connection("29", "1"));
            mapTemplate.Connections.Add(new Connection("29", "12"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "27"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("30", "66"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("31", "66"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "44"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "44"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "27"));
            mapTemplate.Connections.Add(new Connection("32", "26"));
            mapTemplate.Connections.Add(new Connection("32", "24"));
            mapTemplate.Connections.Add(new Connection("32", "23"));
            mapTemplate.Connections.Add(new Connection("33", "25"));
            mapTemplate.Connections.Add(new Connection("33", "28"));
            mapTemplate.Connections.Add(new Connection("33", "12"));
            mapTemplate.Connections.Add(new Connection("33", "15"));
            mapTemplate.Connections.Add(new Connection("33", "24"));
            mapTemplate.Connections.Add(new Connection("34", "37"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "23"));
            mapTemplate.Connections.Add(new Connection("34", "21"));
            mapTemplate.Connections.Add(new Connection("34", "22"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "50"));
            mapTemplate.Connections.Add(new Connection("35", "47"));
            mapTemplate.Connections.Add(new Connection("35", "44"));
            mapTemplate.Connections.Add(new Connection("35", "23"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("36", "52"));
            mapTemplate.Connections.Add(new Connection("36", "50"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "40"));
            mapTemplate.Connections.Add(new Connection("36", "41"));
            mapTemplate.Connections.Add(new Connection("36", "54"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("37", "40"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "34"));
            mapTemplate.Connections.Add(new Connection("37", "22"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "39"));
            mapTemplate.Connections.Add(new Connection("38", "43"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "22"));
            mapTemplate.Connections.Add(new Connection("39", "42"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "37"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "43"));
            mapTemplate.Connections.Add(new Connection("40", "37"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "36"));
            mapTemplate.Connections.Add(new Connection("41", "55"));
            mapTemplate.Connections.Add(new Connection("41", "54"));
            mapTemplate.Connections.Add(new Connection("41", "36"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "39"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "39"));
            mapTemplate.Connections.Add(new Connection("43", "38"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "46"));
            mapTemplate.Connections.Add(new Connection("44", "66"));
            mapTemplate.Connections.Add(new Connection("44", "31"));
            mapTemplate.Connections.Add(new Connection("44", "32"));
            mapTemplate.Connections.Add(new Connection("44", "23"));
            mapTemplate.Connections.Add(new Connection("44", "35"));
            mapTemplate.Connections.Add(new Connection("44", "47"));
            mapTemplate.Connections.Add(new Connection("45", "47"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("46", "74"));
            mapTemplate.Connections.Add(new Connection("46", "66"));
            mapTemplate.Connections.Add(new Connection("46", "44"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "45"));
            mapTemplate.Connections.Add(new Connection("47", "44"));
            mapTemplate.Connections.Add(new Connection("47", "35"));
            mapTemplate.Connections.Add(new Connection("47", "50"));
            mapTemplate.Connections.Add(new Connection("47", "74"));
            mapTemplate.Connections.Add(new Connection("48", "51"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "74"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "50"));
            mapTemplate.Connections.Add(new Connection("49", "61"));
            mapTemplate.Connections.Add(new Connection("49", "63"));
            mapTemplate.Connections.Add(new Connection("49", "74"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "51"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("50", "48"));
            mapTemplate.Connections.Add(new Connection("50", "47"));
            mapTemplate.Connections.Add(new Connection("50", "35"));
            mapTemplate.Connections.Add(new Connection("50", "36"));
            mapTemplate.Connections.Add(new Connection("50", "52"));
            mapTemplate.Connections.Add(new Connection("51", "59"));
            mapTemplate.Connections.Add(new Connection("51", "60"));
            mapTemplate.Connections.Add(new Connection("51", "61"));
            mapTemplate.Connections.Add(new Connection("51", "49"));
            mapTemplate.Connections.Add(new Connection("51", "48"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "58"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "50"));
            mapTemplate.Connections.Add(new Connection("52", "36"));
            mapTemplate.Connections.Add(new Connection("52", "54"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "58"));
            mapTemplate.Connections.Add(new Connection("54", "56"));
            mapTemplate.Connections.Add(new Connection("54", "58"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "52"));
            mapTemplate.Connections.Add(new Connection("54", "36"));
            mapTemplate.Connections.Add(new Connection("54", "41"));
            mapTemplate.Connections.Add(new Connection("54", "55"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("55", "54"));
            mapTemplate.Connections.Add(new Connection("55", "41"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "58"));
            mapTemplate.Connections.Add(new Connection("56", "54"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("58", "56"));
            mapTemplate.Connections.Add(new Connection("58", "54"));
            mapTemplate.Connections.Add(new Connection("58", "53"));
            mapTemplate.Connections.Add(new Connection("58", "59"));
            mapTemplate.Connections.Add(new Connection("58", "51"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("59", "51"));
            mapTemplate.Connections.Add(new Connection("59", "58"));
            mapTemplate.Connections.Add(new Connection("60", "64"));
            mapTemplate.Connections.Add(new Connection("60", "62"));
            mapTemplate.Connections.Add(new Connection("60", "61"));
            mapTemplate.Connections.Add(new Connection("60", "51"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("61", "60"));
            mapTemplate.Connections.Add(new Connection("61", "62"));
            mapTemplate.Connections.Add(new Connection("61", "63"));
            mapTemplate.Connections.Add(new Connection("61", "49"));
            mapTemplate.Connections.Add(new Connection("61", "51"));
            mapTemplate.Connections.Add(new Connection("62", "64"));
            mapTemplate.Connections.Add(new Connection("62", "73"));
            mapTemplate.Connections.Add(new Connection("62", "63"));
            mapTemplate.Connections.Add(new Connection("62", "61"));
            mapTemplate.Connections.Add(new Connection("62", "60"));
            mapTemplate.Connections.Add(new Connection("63", "62"));
            mapTemplate.Connections.Add(new Connection("63", "73"));
            mapTemplate.Connections.Add(new Connection("63", "65"));
            mapTemplate.Connections.Add(new Connection("63", "74"));
            mapTemplate.Connections.Add(new Connection("63", "49"));
            mapTemplate.Connections.Add(new Connection("63", "61"));
            mapTemplate.Connections.Add(new Connection("64", "73"));
            mapTemplate.Connections.Add(new Connection("64", "62"));
            mapTemplate.Connections.Add(new Connection("64", "60"));
            mapTemplate.Connections.Add(new Connection("65", "73"));
            mapTemplate.Connections.Add(new Connection("65", "70"));
            mapTemplate.Connections.Add(new Connection("65", "68"));
            mapTemplate.Connections.Add(new Connection("65", "67"));
            mapTemplate.Connections.Add(new Connection("65", "66"));
            mapTemplate.Connections.Add(new Connection("65", "63"));
            mapTemplate.Connections.Add(new Connection("65", "74"));
            mapTemplate.Connections.Add(new Connection("66", "67"));
            mapTemplate.Connections.Add(new Connection("66", "65"));
            mapTemplate.Connections.Add(new Connection("66", "74"));
            mapTemplate.Connections.Add(new Connection("66", "46"));
            mapTemplate.Connections.Add(new Connection("66", "44"));
            mapTemplate.Connections.Add(new Connection("66", "31"));
            mapTemplate.Connections.Add(new Connection("66", "30"));
            mapTemplate.Connections.Add(new Connection("67", "66"));
            mapTemplate.Connections.Add(new Connection("67", "65"));
            mapTemplate.Connections.Add(new Connection("67", "68"));
            mapTemplate.Connections.Add(new Connection("68", "70"));
            mapTemplate.Connections.Add(new Connection("68", "69"));
            mapTemplate.Connections.Add(new Connection("68", "67"));
            mapTemplate.Connections.Add(new Connection("68", "65"));
            mapTemplate.Connections.Add(new Connection("69", "68"));
            mapTemplate.Connections.Add(new Connection("69", "70"));
            mapTemplate.Connections.Add(new Connection("70", "72"));
            mapTemplate.Connections.Add(new Connection("70", "69"));
            mapTemplate.Connections.Add(new Connection("70", "68"));
            mapTemplate.Connections.Add(new Connection("70", "65"));
            mapTemplate.Connections.Add(new Connection("70", "73"));
            mapTemplate.Connections.Add(new Connection("71", "72"));
            mapTemplate.Connections.Add(new Connection("72", "71"));
            mapTemplate.Connections.Add(new Connection("72", "70"));
            mapTemplate.Connections.Add(new Connection("72", "73"));
            mapTemplate.Connections.Add(new Connection("73", "72"));
            mapTemplate.Connections.Add(new Connection("73", "70"));
            mapTemplate.Connections.Add(new Connection("73", "65"));
            mapTemplate.Connections.Add(new Connection("73", "63"));
            mapTemplate.Connections.Add(new Connection("73", "62"));
            mapTemplate.Connections.Add(new Connection("73", "64"));
            mapTemplate.Connections.Add(new Connection("74", "46"));
            mapTemplate.Connections.Add(new Connection("74", "48"));
            mapTemplate.Connections.Add(new Connection("74", "49"));
            mapTemplate.Connections.Add(new Connection("74", "63"));
            mapTemplate.Connections.Add(new Connection("74", "65"));
            mapTemplate.Connections.Add(new Connection("74", "66"));
            mapTemplate.Connections.Add(new Connection("74", "47"));

            return mapTemplate;
        }
    }
}
