
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate oesterreich_ungarn()
        {

var mapTemplate = new MapTemplate("oesterreich_ungarn") { Image = "oesterreich_ungarn.jpg" };
var country1 = new CountryTemplate("1", "Vorarlberg") { X = 22, Y = 366 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Tirol") { X = 131, Y = 437 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Salzburg") { X = 248, Y = 368 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Kaernten") { X = 332, Y = 431 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Oberoesterreich") { X = 296, Y = 322 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Niederoesterreich") { X = 415, Y = 281 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Steiermark") { X = 400, Y = 375 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Istrien") { X = 294, Y = 610 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Krain") { X = 352, Y = 544 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Kroatien") { X = 402, Y = 620 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Dalmatien") { X = 448, Y = 756 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Slavonien") { X = 528, Y = 572 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Bosnien") { X = 561, Y = 700 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Herzegowina") { X = 588, Y = 804 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Boehmen") { X = 365, Y = 140 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Maehren") { X = 478, Y = 190 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Schlesien") { X = 612, Y = 143 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Westgalizien") { X = 794, Y = 136 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Ostgalizien") { X = 1001, Y = 172 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Bukowina") { X = 1088, Y = 279 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Slowakei") { X = 713, Y = 257 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Pannonien") { X = 576, Y = 467 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Magyar") { X = 769, Y = 404 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Banat") { X = 834, Y = 574 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Siebenb�rgen") { X = 1008, Y = 455 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Transkarpatien") { X = 910, Y = 234 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Wien") { X = 469, Y = 294 };
mapTemplate.Countries.Add(country27);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country27);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country8);
continent5.Countries.Add(country9);
continent5.Countries.Add(country10);
continent5.Countries.Add(country11);
continent5.Countries.Add(country12);
continent5.Countries.Add(country13);
continent5.Countries.Add(country14);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country18);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "9"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "15"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "15"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "16"));
mapTemplate.Connections.Add(new Connection("6", "21"));
mapTemplate.Connections.Add(new Connection("6", "22"));
mapTemplate.Connections.Add(new Connection("6", "27"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "22"));
mapTemplate.Connections.Add(new Connection("7", "12"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "4"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "23"));
mapTemplate.Connections.Add(new Connection("12", "24"));
mapTemplate.Connections.Add(new Connection("12", "22"));
mapTemplate.Connections.Add(new Connection("12", "7"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("15", "5"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "6"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "6"));
mapTemplate.Connections.Add(new Connection("16", "21"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "26"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "26"));
mapTemplate.Connections.Add(new Connection("19", "23"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "25"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("21", "6"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "16"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "26"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("22", "6"));
mapTemplate.Connections.Add(new Connection("22", "7"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "12"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "12"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "19"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "12"));
mapTemplate.Connections.Add(new Connection("25", "20"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "19"));
mapTemplate.Connections.Add(new Connection("26", "18"));
mapTemplate.Connections.Add(new Connection("26", "21"));
mapTemplate.Connections.Add(new Connection("27", "6"));

            return mapTemplate;
		}
    }
}

