
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Frankreich()
        {
            var mapTemplate = new MapTemplate("Frankreich") { Image = "frankreich.png" };
            var country1 = new CountryTemplate("1", "Corse du Sud") { X = 1443, Y = 1109 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Haute Corse") { X = 1431, Y = 1041 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "La Couronne") { X = 1200, Y = 1132 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "La Richelieu") { X = 1410, Y = 908 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Alps de Haute") { X = 989, Y = 879 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Provence") { X = 1101, Y = 910 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Maritimes") { X = 1168, Y = 849 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Vaucluse") { X = 1070, Y = 797 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Var") { X = 1145, Y = 783 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Herault") { X = 740, Y = 1007 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Lozere") { X = 689, Y = 969 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Audesi") { X = 778, Y = 914 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Orientales") { X = 892, Y = 871 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Gard") { X = 825, Y = 814 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Gers") { X = 458, Y = 961 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Pyrenees") { X = 609, Y = 991 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Ariege") { X = 462, Y = 892 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Haute-Garonne") { X = 543, Y = 905 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Cahors") { X = 634, Y = 894 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Albi") { X = 583, Y = 825 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Montauban") { X = 723, Y = 877 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Zaruone") { X = 727, Y = 801 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Tarn") { X = 632, Y = 787 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Gironde") { X = 316, Y = 927 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Dordogne") { X = 387, Y = 936 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Pau") { X = 384, Y = 871 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Lot") { X = 342, Y = 818 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Bordeaux") { X = 459, Y = 815 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Agen") { X = 353, Y = 736 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Marsan") { X = 444, Y = 768 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Garonne") { X = 544, Y = 758 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Auch") { X = 516, Y = 700 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Niort") { X = 373, Y = 631 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Vienne") { X = 431, Y = 692 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Deux") { X = 489, Y = 641 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Poitiers") { X = 427, Y = 598 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Sevres") { X = 513, Y = 557 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Charente") { X = 443, Y = 539 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Tulle") { X = 622, Y = 712 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Gueret") { X = 663, Y = 668 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Creuse") { X = 572, Y = 657 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Limo") { X = 585, Y = 602 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Aube") { X = 685, Y = 612 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Moulins") { X = 697, Y = 752 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Chantal") { X = 780, Y = 728 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Le Puy") { X = 868, Y = 718 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Ferrand") { X = 809, Y = 663 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Aurilac") { X = 742, Y = 666 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Clermont") { X = 744, Y = 601 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Ardeche") { X = 901, Y = 789 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Ain") { X = 1006, Y = 780 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Drome") { X = 1023, Y = 736 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Annecy") { X = 929, Y = 696 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Savoie") { X = 926, Y = 624 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Rhone") { X = 985, Y = 642 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Isere") { X = 1052, Y = 670 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Privas") { X = 1149, Y = 680 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Bourge") { X = 1120, Y = 608 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Jura") { X = 1035, Y = 550 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Larinie") { X = 1036, Y = 467 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Doubs") { X = 1082, Y = 496 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "Belfort") { X = 1124, Y = 461 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Macon") { X = 881, Y = 568 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "Loire") { X = 796, Y = 510 };
            mapTemplate.Countries.Add(country64);
            var country65 = new CountryTemplate("65", "Auxerre") { X = 941, Y = 530 };
            mapTemplate.Countries.Add(country65);
            var country66 = new CountryTemplate("66", "Saone") { X = 974, Y = 483 };
            mapTemplate.Countries.Add(country66);
            var country67 = new CountryTemplate("67", "Dijon") { X = 859, Y = 479 };
            mapTemplate.Countries.Add(country67);
            var country68 = new CountryTemplate("68", "Nevers") { X = 782, Y = 469 };
            mapTemplate.Countries.Add(country68);
            var country69 = new CountryTemplate("69", "Yonne") { X = 907, Y = 414 };
            mapTemplate.Countries.Add(country69);
            var country70 = new CountryTemplate("70", "Nievre") { X = 801, Y = 390 };
            mapTemplate.Countries.Add(country70);
            var country71 = new CountryTemplate("71", "Tourette") { X = 694, Y = 522 };
            mapTemplate.Countries.Add(country71);
            var country72 = new CountryTemplate("72", "Eurc") { X = 612, Y = 548 };
            mapTemplate.Countries.Add(country72);
            var country73 = new CountryTemplate("73", "Indre") { X = 510, Y = 464 };
            mapTemplate.Countries.Add(country73);
            var country74 = new CountryTemplate("74", "Blois") { X = 608, Y = 491 };
            mapTemplate.Countries.Add(country74);
            var country75 = new CountryTemplate("75", "Cher") { X = 712, Y = 470 };
            mapTemplate.Countries.Add(country75);
            var country76 = new CountryTemplate("76", "Cheverny") { X = 584, Y = 443 };
            mapTemplate.Countries.Add(country76);
            var country77 = new CountryTemplate("77", "Orleans") { X = 670, Y = 391 };
            mapTemplate.Countries.Add(country77);
            var country78 = new CountryTemplate("78", "Paris") { X = 598, Y = 355 };
            mapTemplate.Countries.Add(country78);
            var country79 = new CountryTemplate("79", "Sarthe") { X = 345, Y = 562 };
            mapTemplate.Countries.Add(country79);
            var country80 = new CountryTemplate("80", "Laval") { X = 272, Y = 521 };
            mapTemplate.Countries.Add(country80);
            var country81 = new CountryTemplate("81", "Vendee") { X = 344, Y = 499 };
            mapTemplate.Countries.Add(country81);
            var country82 = new CountryTemplate("82", "Yon") { X = 287, Y = 446 };
            mapTemplate.Countries.Add(country82);
            var country83 = new CountryTemplate("83", "Mainet") { X = 376, Y = 407 };
            mapTemplate.Countries.Add(country83);
            var country84 = new CountryTemplate("84", "Atlantique") { X = 450, Y = 430 };
            mapTemplate.Countries.Add(country84);
            var country85 = new CountryTemplate("85", "Nantes") { X = 499, Y = 399 };
            mapTemplate.Countries.Add(country85);
            var country86 = new CountryTemplate("86", "Brest") { X = 65, Y = 343 };
            mapTemplate.Countries.Add(country86);
            var country87 = new CountryTemplate("87", "Morbihan") { X = 146, Y = 298 };
            mapTemplate.Countries.Add(country87);
            var country88 = new CountryTemplate("88", "Finistere") { X = 124, Y = 361 };
            mapTemplate.Countries.Add(country88);
            var country89 = new CountryTemplate("89", "Redon") { X = 217, Y = 359 };
            mapTemplate.Countries.Add(country89);
            var country90 = new CountryTemplate("90", "Quimpere") { X = 220, Y = 417 };
            mapTemplate.Countries.Add(country90);
            var country91 = new CountryTemplate("91", "Ille") { X = 287, Y = 334 };
            mapTemplate.Countries.Add(country91);
            var country92 = new CountryTemplate("92", "Armor") { X = 327, Y = 368 };
            mapTemplate.Countries.Add(country92);
            var country93 = new CountryTemplate("93", "Caen") { X = 321, Y = 218 };
            mapTemplate.Countries.Add(country93);
            var country94 = new CountryTemplate("94", "Calvados") { X = 396, Y = 261 };
            mapTemplate.Countries.Add(country94);
            var country95 = new CountryTemplate("95", "Orne") { X = 352, Y = 303 };
            mapTemplate.Countries.Add(country95);
            var country96 = new CountryTemplate("96", "Alencon") { X = 410, Y = 297 };
            mapTemplate.Countries.Add(country96);
            var country97 = new CountryTemplate("97", "Alleji") { X = 467, Y = 250 };
            mapTemplate.Countries.Add(country97);
            var country98 = new CountryTemplate("98", "Bayeux") { X = 521, Y = 328 };
            mapTemplate.Countries.Add(country98);
            var country99 = new CountryTemplate("99", "Euree") { X = 532, Y = 213 };
            mapTemplate.Countries.Add(country99);
            var country100 = new CountryTemplate("100", "Rouen") { X = 576, Y = 258 };
            mapTemplate.Countries.Add(country100);
            var country101 = new CountryTemplate("101", "Seine") { X = 596, Y = 208 };
            mapTemplate.Countries.Add(country101);
            var country102 = new CountryTemplate("102", "Evry") { X = 670, Y = 277 };
            mapTemplate.Countries.Add(country102);
            var country103 = new CountryTemplate("103", "Creteil") { X = 725, Y = 347 };
            mapTemplate.Countries.Add(country103);
            var country104 = new CountryTemplate("104", "Melun") { X = 748, Y = 289 };
            mapTemplate.Countries.Add(country104);
            var country105 = new CountryTemplate("105", "Chaumont") { X = 888, Y = 214 };
            mapTemplate.Countries.Add(country105);
            var country106 = new CountryTemplate("106", "Ardene") { X = 911, Y = 276 };
            mapTemplate.Countries.Add(country106);
            var country107 = new CountryTemplate("107", "Arobe") { X = 836, Y = 298 };
            mapTemplate.Countries.Add(country107);
            var country108 = new CountryTemplate("108", "Marne") { X = 856, Y = 364 };
            mapTemplate.Countries.Add(country108);
            var country109 = new CountryTemplate("109", "Champagne") { X = 933, Y = 366 };
            mapTemplate.Countries.Add(country109);
            var country110 = new CountryTemplate("110", "Reims") { X = 991, Y = 386 };
            mapTemplate.Countries.Add(country110);
            var country111 = new CountryTemplate("111", "Metz") { X = 981, Y = 268 };
            mapTemplate.Countries.Add(country111);
            var country112 = new CountryTemplate("112", "Moselle") { X = 1054, Y = 238 };
            mapTemplate.Countries.Add(country112);
            var country113 = new CountryTemplate("113", "Epinal") { X = 1035, Y = 321 };
            mapTemplate.Countries.Add(country113);
            var country114 = new CountryTemplate("114", "Vosges") { X = 1114, Y = 292 };
            mapTemplate.Countries.Add(country114);
            var country115 = new CountryTemplate("115", "Nancy") { X = 1121, Y = 352 };
            mapTemplate.Countries.Add(country115);
            var country116 = new CountryTemplate("116", "Comar") { X = 1181, Y = 414 };
            mapTemplate.Countries.Add(country116);
            var country117 = new CountryTemplate("117", "Rhin") { X = 1198, Y = 325 };
            mapTemplate.Countries.Add(country117);
            var country118 = new CountryTemplate("118", "Bas") { X = 1232, Y = 275 };
            mapTemplate.Countries.Add(country118);
            var country119 = new CountryTemplate("119", "Gouy") { X = 800, Y = 235 };
            mapTemplate.Countries.Add(country119);
            var country120 = new CountryTemplate("120", "Somme") { X = 696, Y = 236 };
            mapTemplate.Countries.Add(country120);
            var country121 = new CountryTemplate("121", "Oise") { X = 832, Y = 200 };
            mapTemplate.Countries.Add(country121);
            var country122 = new CountryTemplate("122", "Aisne") { X = 760, Y = 180 };
            mapTemplate.Countries.Add(country122);
            var country123 = new CountryTemplate("123", "Amiens") { X = 651, Y = 152 };
            mapTemplate.Countries.Add(country123);
            var country124 = new CountryTemplate("124", "Lilleq") { X = 644, Y = 92 };
            mapTemplate.Countries.Add(country124);
            var country125 = new CountryTemplate("125", "Nord") { X = 693, Y = 71 };
            mapTemplate.Countries.Add(country125);
            var country126 = new CountryTemplate("126", "Calais") { X = 736, Y = 122 };
            mapTemplate.Countries.Add(country126);
            var country127 = new CountryTemplate("127", "ca4") { X = 790, Y = 121 };
            mapTemplate.Countries.Add(country127);
            var continent1 = new Continent("1", 1);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 3);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            continent2.Countries.Add(country8);
            continent2.Countries.Add(country9);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 6);
            continent4.Countries.Add(country15);
            continent4.Countries.Add(country16);
            continent4.Countries.Add(country17);
            continent4.Countries.Add(country18);
            continent4.Countries.Add(country19);
            continent4.Countries.Add(country20);
            continent4.Countries.Add(country21);
            continent4.Countries.Add(country22);
            continent4.Countries.Add(country23);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 5);
            continent5.Countries.Add(country24);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            continent5.Countries.Add(country28);
            continent5.Countries.Add(country29);
            continent5.Countries.Add(country30);
            continent5.Countries.Add(country31);
            continent5.Countries.Add(country32);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 4);
            continent6.Countries.Add(country33);
            continent6.Countries.Add(country34);
            continent6.Countries.Add(country35);
            continent6.Countries.Add(country36);
            continent6.Countries.Add(country37);
            continent6.Countries.Add(country38);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 3);
            continent7.Countries.Add(country39);
            continent7.Countries.Add(country40);
            continent7.Countries.Add(country41);
            continent7.Countries.Add(country42);
            continent7.Countries.Add(country43);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 4);
            continent8.Countries.Add(country44);
            continent8.Countries.Add(country45);
            continent8.Countries.Add(country46);
            continent8.Countries.Add(country47);
            continent8.Countries.Add(country48);
            continent8.Countries.Add(country49);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 6);
            continent9.Countries.Add(country50);
            continent9.Countries.Add(country51);
            continent9.Countries.Add(country52);
            continent9.Countries.Add(country53);
            continent9.Countries.Add(country54);
            continent9.Countries.Add(country55);
            continent9.Countries.Add(country56);
            continent9.Countries.Add(country57);
            continent9.Countries.Add(country58);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country59);
            continent10.Countries.Add(country60);
            continent10.Countries.Add(country61);
            continent10.Countries.Add(country62);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 5);
            continent11.Countries.Add(country63);
            continent11.Countries.Add(country64);
            continent11.Countries.Add(country65);
            continent11.Countries.Add(country66);
            continent11.Countries.Add(country67);
            continent11.Countries.Add(country68);
            continent11.Countries.Add(country69);
            continent11.Countries.Add(country70);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 5);
            continent12.Countries.Add(country71);
            continent12.Countries.Add(country72);
            continent12.Countries.Add(country73);
            continent12.Countries.Add(country74);
            continent12.Countries.Add(country75);
            continent12.Countries.Add(country76);
            continent12.Countries.Add(country77);
            continent12.Countries.Add(country78);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 4);
            continent13.Countries.Add(country79);
            continent13.Countries.Add(country80);
            continent13.Countries.Add(country81);
            continent13.Countries.Add(country82);
            continent13.Countries.Add(country83);
            continent13.Countries.Add(country84);
            continent13.Countries.Add(country85);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 3);
            continent14.Countries.Add(country86);
            continent14.Countries.Add(country87);
            continent14.Countries.Add(country88);
            continent14.Countries.Add(country89);
            continent14.Countries.Add(country90);
            continent14.Countries.Add(country91);
            continent14.Countries.Add(country92);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 3);
            continent15.Countries.Add(country93);
            continent15.Countries.Add(country94);
            continent15.Countries.Add(country95);
            continent15.Countries.Add(country96);
            continent15.Countries.Add(country97);
            continent15.Countries.Add(country98);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 2);
            continent16.Countries.Add(country99);
            continent16.Countries.Add(country100);
            continent16.Countries.Add(country101);
            mapTemplate.Continents.Add(continent16);
            var continent17 = new Continent("17", 2);
            continent17.Countries.Add(country102);
            continent17.Countries.Add(country103);
            continent17.Countries.Add(country104);
            mapTemplate.Continents.Add(continent17);
            var continent18 = new Continent("18", 4);
            continent18.Countries.Add(country105);
            continent18.Countries.Add(country106);
            continent18.Countries.Add(country107);
            continent18.Countries.Add(country108);
            continent18.Countries.Add(country109);
            continent18.Countries.Add(country110);
            mapTemplate.Continents.Add(continent18);
            var continent19 = new Continent("19", 3);
            continent19.Countries.Add(country111);
            continent19.Countries.Add(country112);
            continent19.Countries.Add(country113);
            continent19.Countries.Add(country114);
            continent19.Countries.Add(country115);
            mapTemplate.Continents.Add(continent19);
            var continent20 = new Continent("20", 2);
            continent20.Countries.Add(country116);
            continent20.Countries.Add(country117);
            continent20.Countries.Add(country118);
            mapTemplate.Continents.Add(continent20);
            var continent21 = new Continent("21", 3);
            continent21.Countries.Add(country119);
            continent21.Countries.Add(country120);
            continent21.Countries.Add(country121);
            continent21.Countries.Add(country122);
            continent21.Countries.Add(country123);
            mapTemplate.Continents.Add(continent21);
            var continent22 = new Continent("22", 2);
            continent22.Countries.Add(country124);
            continent22.Countries.Add(country125);
            continent22.Countries.Add(country126);
            continent22.Countries.Add(country127);
            mapTemplate.Continents.Add(continent22);
            var continent23 = new Continent("23", 1);
            continent23.Countries.Add(country3);
            continent23.Countries.Add(country4);
            mapTemplate.Continents.Add(continent23);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "6"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "58"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "51"));
            mapTemplate.Connections.Add(new Connection("5", "13"));
            mapTemplate.Connections.Add(new Connection("6", "3"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("6", "51"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "51"));
            mapTemplate.Connections.Add(new Connection("8", "52"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "52"));
            mapTemplate.Connections.Add(new Connection("9", "57"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "16"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "16"));
            mapTemplate.Connections.Add(new Connection("11", "19"));
            mapTemplate.Connections.Add(new Connection("11", "18"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "21"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("13", "5"));
            mapTemplate.Connections.Add(new Connection("13", "50"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "21"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("14", "50"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "22"));
            mapTemplate.Connections.Add(new Connection("14", "21"));
            mapTemplate.Connections.Add(new Connection("14", "46"));
            mapTemplate.Connections.Add(new Connection("14", "45"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "25"));
            mapTemplate.Connections.Add(new Connection("16", "10"));
            mapTemplate.Connections.Add(new Connection("16", "11"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "25"));
            mapTemplate.Connections.Add(new Connection("17", "26"));
            mapTemplate.Connections.Add(new Connection("17", "28"));
            mapTemplate.Connections.Add(new Connection("18", "11"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "28"));
            mapTemplate.Connections.Add(new Connection("19", "11"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("20", "28"));
            mapTemplate.Connections.Add(new Connection("20", "31"));
            mapTemplate.Connections.Add(new Connection("21", "13"));
            mapTemplate.Connections.Add(new Connection("21", "12"));
            mapTemplate.Connections.Add(new Connection("21", "14"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "23"));
            mapTemplate.Connections.Add(new Connection("22", "14"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "44"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("23", "21"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "31"));
            mapTemplate.Connections.Add(new Connection("23", "44"));
            mapTemplate.Connections.Add(new Connection("23", "39"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "27"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "15"));
            mapTemplate.Connections.Add(new Connection("25", "17"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "17"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("27", "24"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "29"));
            mapTemplate.Connections.Add(new Connection("28", "17"));
            mapTemplate.Connections.Add(new Connection("28", "18"));
            mapTemplate.Connections.Add(new Connection("28", "20"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "31"));
            mapTemplate.Connections.Add(new Connection("29", "27"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("31", "20"));
            mapTemplate.Connections.Add(new Connection("31", "23"));
            mapTemplate.Connections.Add(new Connection("31", "28"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "39"));
            mapTemplate.Connections.Add(new Connection("32", "41"));
            mapTemplate.Connections.Add(new Connection("32", "35"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "36"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("35", "41"));
            mapTemplate.Connections.Add(new Connection("35", "32"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "37"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "33"));
            mapTemplate.Connections.Add(new Connection("36", "79"));
            mapTemplate.Connections.Add(new Connection("37", "42"));
            mapTemplate.Connections.Add(new Connection("37", "35"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "72"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "81"));
            mapTemplate.Connections.Add(new Connection("38", "73"));
            mapTemplate.Connections.Add(new Connection("39", "23"));
            mapTemplate.Connections.Add(new Connection("39", "44"));
            mapTemplate.Connections.Add(new Connection("39", "32"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("40", "48"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "43"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("40", "44"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "32"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "35"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "72"));
            mapTemplate.Connections.Add(new Connection("42", "37"));
            mapTemplate.Connections.Add(new Connection("43", "49"));
            mapTemplate.Connections.Add(new Connection("43", "48"));
            mapTemplate.Connections.Add(new Connection("43", "40"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "71"));
            mapTemplate.Connections.Add(new Connection("44", "22"));
            mapTemplate.Connections.Add(new Connection("44", "23"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "48"));
            mapTemplate.Connections.Add(new Connection("44", "39"));
            mapTemplate.Connections.Add(new Connection("44", "40"));
            mapTemplate.Connections.Add(new Connection("45", "14"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "47"));
            mapTemplate.Connections.Add(new Connection("45", "48"));
            mapTemplate.Connections.Add(new Connection("46", "14"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "53"));
            mapTemplate.Connections.Add(new Connection("46", "50"));
            mapTemplate.Connections.Add(new Connection("47", "53"));
            mapTemplate.Connections.Add(new Connection("47", "54"));
            mapTemplate.Connections.Add(new Connection("47", "45"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("47", "63"));
            mapTemplate.Connections.Add(new Connection("48", "45"));
            mapTemplate.Connections.Add(new Connection("48", "44"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "43"));
            mapTemplate.Connections.Add(new Connection("48", "40"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "63"));
            mapTemplate.Connections.Add(new Connection("49", "64"));
            mapTemplate.Connections.Add(new Connection("49", "71"));
            mapTemplate.Connections.Add(new Connection("49", "43"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("50", "52"));
            mapTemplate.Connections.Add(new Connection("50", "55"));
            mapTemplate.Connections.Add(new Connection("50", "53"));
            mapTemplate.Connections.Add(new Connection("50", "13"));
            mapTemplate.Connections.Add(new Connection("50", "14"));
            mapTemplate.Connections.Add(new Connection("50", "46"));
            mapTemplate.Connections.Add(new Connection("51", "6"));
            mapTemplate.Connections.Add(new Connection("51", "5"));
            mapTemplate.Connections.Add(new Connection("51", "8"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("52", "8"));
            mapTemplate.Connections.Add(new Connection("52", "9"));
            mapTemplate.Connections.Add(new Connection("52", "56"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "50"));
            mapTemplate.Connections.Add(new Connection("52", "55"));
            mapTemplate.Connections.Add(new Connection("53", "55"));
            mapTemplate.Connections.Add(new Connection("53", "50"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "46"));
            mapTemplate.Connections.Add(new Connection("53", "47"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "55"));
            mapTemplate.Connections.Add(new Connection("54", "47"));
            mapTemplate.Connections.Add(new Connection("54", "63"));
            mapTemplate.Connections.Add(new Connection("54", "65"));
            mapTemplate.Connections.Add(new Connection("55", "52"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("55", "59"));
            mapTemplate.Connections.Add(new Connection("55", "53"));
            mapTemplate.Connections.Add(new Connection("55", "50"));
            mapTemplate.Connections.Add(new Connection("55", "54"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "58"));
            mapTemplate.Connections.Add(new Connection("56", "52"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("56", "59"));
            mapTemplate.Connections.Add(new Connection("57", "58"));
            mapTemplate.Connections.Add(new Connection("57", "9"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("58", "4"));
            mapTemplate.Connections.Add(new Connection("58", "57"));
            mapTemplate.Connections.Add(new Connection("58", "56"));
            mapTemplate.Connections.Add(new Connection("59", "56"));
            mapTemplate.Connections.Add(new Connection("59", "55"));
            mapTemplate.Connections.Add(new Connection("59", "65"));
            mapTemplate.Connections.Add(new Connection("59", "61"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("60", "66"));
            mapTemplate.Connections.Add(new Connection("60", "61"));
            mapTemplate.Connections.Add(new Connection("60", "62"));
            mapTemplate.Connections.Add(new Connection("60", "110"));
            mapTemplate.Connections.Add(new Connection("61", "59"));
            mapTemplate.Connections.Add(new Connection("61", "62"));
            mapTemplate.Connections.Add(new Connection("61", "60"));
            mapTemplate.Connections.Add(new Connection("62", "61"));
            mapTemplate.Connections.Add(new Connection("62", "60"));
            mapTemplate.Connections.Add(new Connection("62", "116"));
            mapTemplate.Connections.Add(new Connection("62", "115"));
            mapTemplate.Connections.Add(new Connection("63", "47"));
            mapTemplate.Connections.Add(new Connection("63", "54"));
            mapTemplate.Connections.Add(new Connection("63", "49"));
            mapTemplate.Connections.Add(new Connection("63", "67"));
            mapTemplate.Connections.Add(new Connection("63", "65"));
            mapTemplate.Connections.Add(new Connection("63", "64"));
            mapTemplate.Connections.Add(new Connection("64", "49"));
            mapTemplate.Connections.Add(new Connection("64", "68"));
            mapTemplate.Connections.Add(new Connection("64", "67"));
            mapTemplate.Connections.Add(new Connection("64", "71"));
            mapTemplate.Connections.Add(new Connection("64", "63"));
            mapTemplate.Connections.Add(new Connection("65", "54"));
            mapTemplate.Connections.Add(new Connection("65", "67"));
            mapTemplate.Connections.Add(new Connection("65", "69"));
            mapTemplate.Connections.Add(new Connection("65", "59"));
            mapTemplate.Connections.Add(new Connection("65", "66"));
            mapTemplate.Connections.Add(new Connection("65", "63"));
            mapTemplate.Connections.Add(new Connection("66", "65"));
            mapTemplate.Connections.Add(new Connection("66", "69"));
            mapTemplate.Connections.Add(new Connection("66", "60"));
            mapTemplate.Connections.Add(new Connection("67", "64"));
            mapTemplate.Connections.Add(new Connection("67", "68"));
            mapTemplate.Connections.Add(new Connection("67", "70"));
            mapTemplate.Connections.Add(new Connection("67", "69"));
            mapTemplate.Connections.Add(new Connection("67", "63"));
            mapTemplate.Connections.Add(new Connection("67", "65"));
            mapTemplate.Connections.Add(new Connection("68", "70"));
            mapTemplate.Connections.Add(new Connection("68", "75"));
            mapTemplate.Connections.Add(new Connection("68", "64"));
            mapTemplate.Connections.Add(new Connection("68", "67"));
            mapTemplate.Connections.Add(new Connection("68", "77"));
            mapTemplate.Connections.Add(new Connection("69", "108"));
            mapTemplate.Connections.Add(new Connection("69", "109"));
            mapTemplate.Connections.Add(new Connection("69", "110"));
            mapTemplate.Connections.Add(new Connection("69", "67"));
            mapTemplate.Connections.Add(new Connection("69", "65"));
            mapTemplate.Connections.Add(new Connection("69", "66"));
            mapTemplate.Connections.Add(new Connection("69", "70"));
            mapTemplate.Connections.Add(new Connection("70", "104"));
            mapTemplate.Connections.Add(new Connection("70", "103"));
            mapTemplate.Connections.Add(new Connection("70", "77"));
            mapTemplate.Connections.Add(new Connection("70", "68"));
            mapTemplate.Connections.Add(new Connection("70", "108"));
            mapTemplate.Connections.Add(new Connection("70", "67"));
            mapTemplate.Connections.Add(new Connection("70", "69"));
            mapTemplate.Connections.Add(new Connection("71", "49"));
            mapTemplate.Connections.Add(new Connection("71", "43"));
            mapTemplate.Connections.Add(new Connection("71", "72"));
            mapTemplate.Connections.Add(new Connection("71", "74"));
            mapTemplate.Connections.Add(new Connection("71", "75"));
            mapTemplate.Connections.Add(new Connection("71", "64"));
            mapTemplate.Connections.Add(new Connection("72", "42"));
            mapTemplate.Connections.Add(new Connection("72", "37"));
            mapTemplate.Connections.Add(new Connection("72", "71"));
            mapTemplate.Connections.Add(new Connection("72", "73"));
            mapTemplate.Connections.Add(new Connection("72", "74"));
            mapTemplate.Connections.Add(new Connection("73", "38"));
            mapTemplate.Connections.Add(new Connection("73", "84"));
            mapTemplate.Connections.Add(new Connection("73", "72"));
            mapTemplate.Connections.Add(new Connection("73", "76"));
            mapTemplate.Connections.Add(new Connection("73", "74"));
            mapTemplate.Connections.Add(new Connection("74", "73"));
            mapTemplate.Connections.Add(new Connection("74", "76"));
            mapTemplate.Connections.Add(new Connection("74", "72"));
            mapTemplate.Connections.Add(new Connection("74", "71"));
            mapTemplate.Connections.Add(new Connection("74", "75"));
            mapTemplate.Connections.Add(new Connection("74", "77"));
            mapTemplate.Connections.Add(new Connection("75", "71"));
            mapTemplate.Connections.Add(new Connection("75", "74"));
            mapTemplate.Connections.Add(new Connection("75", "77"));
            mapTemplate.Connections.Add(new Connection("75", "68"));
            mapTemplate.Connections.Add(new Connection("76", "78"));
            mapTemplate.Connections.Add(new Connection("76", "85"));
            mapTemplate.Connections.Add(new Connection("76", "73"));
            mapTemplate.Connections.Add(new Connection("76", "74"));
            mapTemplate.Connections.Add(new Connection("76", "77"));
            mapTemplate.Connections.Add(new Connection("77", "76"));
            mapTemplate.Connections.Add(new Connection("77", "74"));
            mapTemplate.Connections.Add(new Connection("77", "75"));
            mapTemplate.Connections.Add(new Connection("77", "78"));
            mapTemplate.Connections.Add(new Connection("77", "103"));
            mapTemplate.Connections.Add(new Connection("77", "70"));
            mapTemplate.Connections.Add(new Connection("77", "68"));
            mapTemplate.Connections.Add(new Connection("78", "76"));
            mapTemplate.Connections.Add(new Connection("78", "98"));
            mapTemplate.Connections.Add(new Connection("78", "77"));
            mapTemplate.Connections.Add(new Connection("78", "100"));
            mapTemplate.Connections.Add(new Connection("78", "102"));
            mapTemplate.Connections.Add(new Connection("78", "103"));
            mapTemplate.Connections.Add(new Connection("79", "36"));
            mapTemplate.Connections.Add(new Connection("79", "80"));
            mapTemplate.Connections.Add(new Connection("79", "81"));
            mapTemplate.Connections.Add(new Connection("80", "79"));
            mapTemplate.Connections.Add(new Connection("80", "82"));
            mapTemplate.Connections.Add(new Connection("80", "81"));
            mapTemplate.Connections.Add(new Connection("81", "79"));
            mapTemplate.Connections.Add(new Connection("81", "80"));
            mapTemplate.Connections.Add(new Connection("81", "38"));
            mapTemplate.Connections.Add(new Connection("81", "82"));
            mapTemplate.Connections.Add(new Connection("81", "84"));
            mapTemplate.Connections.Add(new Connection("81", "83"));
            mapTemplate.Connections.Add(new Connection("82", "80"));
            mapTemplate.Connections.Add(new Connection("82", "81"));
            mapTemplate.Connections.Add(new Connection("82", "83"));
            mapTemplate.Connections.Add(new Connection("82", "90"));
            mapTemplate.Connections.Add(new Connection("82", "92"));
            mapTemplate.Connections.Add(new Connection("83", "81"));
            mapTemplate.Connections.Add(new Connection("83", "82"));
            mapTemplate.Connections.Add(new Connection("83", "84"));
            mapTemplate.Connections.Add(new Connection("83", "92"));
            mapTemplate.Connections.Add(new Connection("84", "81"));
            mapTemplate.Connections.Add(new Connection("84", "83"));
            mapTemplate.Connections.Add(new Connection("84", "85"));
            mapTemplate.Connections.Add(new Connection("84", "73"));
            mapTemplate.Connections.Add(new Connection("84", "96"));
            mapTemplate.Connections.Add(new Connection("85", "84"));
            mapTemplate.Connections.Add(new Connection("85", "98"));
            mapTemplate.Connections.Add(new Connection("85", "76"));
            mapTemplate.Connections.Add(new Connection("86", "87"));
            mapTemplate.Connections.Add(new Connection("86", "88"));
            mapTemplate.Connections.Add(new Connection("87", "86"));
            mapTemplate.Connections.Add(new Connection("87", "88"));
            mapTemplate.Connections.Add(new Connection("87", "89"));
            mapTemplate.Connections.Add(new Connection("88", "86"));
            mapTemplate.Connections.Add(new Connection("88", "87"));
            mapTemplate.Connections.Add(new Connection("88", "89"));
            mapTemplate.Connections.Add(new Connection("88", "90"));
            mapTemplate.Connections.Add(new Connection("89", "87"));
            mapTemplate.Connections.Add(new Connection("89", "88"));
            mapTemplate.Connections.Add(new Connection("89", "90"));
            mapTemplate.Connections.Add(new Connection("89", "91"));
            mapTemplate.Connections.Add(new Connection("90", "88"));
            mapTemplate.Connections.Add(new Connection("90", "89"));
            mapTemplate.Connections.Add(new Connection("90", "91"));
            mapTemplate.Connections.Add(new Connection("90", "92"));
            mapTemplate.Connections.Add(new Connection("90", "82"));
            mapTemplate.Connections.Add(new Connection("91", "89"));
            mapTemplate.Connections.Add(new Connection("91", "90"));
            mapTemplate.Connections.Add(new Connection("91", "92"));
            mapTemplate.Connections.Add(new Connection("91", "95"));
            mapTemplate.Connections.Add(new Connection("92", "90"));
            mapTemplate.Connections.Add(new Connection("92", "91"));
            mapTemplate.Connections.Add(new Connection("92", "82"));
            mapTemplate.Connections.Add(new Connection("92", "83"));
            mapTemplate.Connections.Add(new Connection("92", "95"));
            mapTemplate.Connections.Add(new Connection("93", "94"));
            mapTemplate.Connections.Add(new Connection("94", "93"));
            mapTemplate.Connections.Add(new Connection("94", "95"));
            mapTemplate.Connections.Add(new Connection("94", "97"));
            mapTemplate.Connections.Add(new Connection("94", "96"));
            mapTemplate.Connections.Add(new Connection("95", "92"));
            mapTemplate.Connections.Add(new Connection("95", "94"));
            mapTemplate.Connections.Add(new Connection("95", "91"));
            mapTemplate.Connections.Add(new Connection("95", "96"));
            mapTemplate.Connections.Add(new Connection("96", "94"));
            mapTemplate.Connections.Add(new Connection("96", "98"));
            mapTemplate.Connections.Add(new Connection("96", "97"));
            mapTemplate.Connections.Add(new Connection("96", "84"));
            mapTemplate.Connections.Add(new Connection("96", "95"));
            mapTemplate.Connections.Add(new Connection("97", "94"));
            mapTemplate.Connections.Add(new Connection("97", "99"));
            mapTemplate.Connections.Add(new Connection("97", "98"));
            mapTemplate.Connections.Add(new Connection("97", "96"));
            mapTemplate.Connections.Add(new Connection("98", "97"));
            mapTemplate.Connections.Add(new Connection("98", "96"));
            mapTemplate.Connections.Add(new Connection("98", "85"));
            mapTemplate.Connections.Add(new Connection("98", "78"));
            mapTemplate.Connections.Add(new Connection("98", "100"));
            mapTemplate.Connections.Add(new Connection("99", "97"));
            mapTemplate.Connections.Add(new Connection("99", "101"));
            mapTemplate.Connections.Add(new Connection("99", "100"));
            mapTemplate.Connections.Add(new Connection("100", "98"));
            mapTemplate.Connections.Add(new Connection("100", "99"));
            mapTemplate.Connections.Add(new Connection("100", "101"));
            mapTemplate.Connections.Add(new Connection("100", "78"));
            mapTemplate.Connections.Add(new Connection("100", "102"));
            mapTemplate.Connections.Add(new Connection("101", "99"));
            mapTemplate.Connections.Add(new Connection("101", "100"));
            mapTemplate.Connections.Add(new Connection("101", "123"));
            mapTemplate.Connections.Add(new Connection("101", "120"));
            mapTemplate.Connections.Add(new Connection("102", "100"));
            mapTemplate.Connections.Add(new Connection("102", "78"));
            mapTemplate.Connections.Add(new Connection("102", "120"));
            mapTemplate.Connections.Add(new Connection("102", "103"));
            mapTemplate.Connections.Add(new Connection("102", "104"));
            mapTemplate.Connections.Add(new Connection("103", "78"));
            mapTemplate.Connections.Add(new Connection("103", "77"));
            mapTemplate.Connections.Add(new Connection("103", "102"));
            mapTemplate.Connections.Add(new Connection("103", "104"));
            mapTemplate.Connections.Add(new Connection("103", "70"));
            mapTemplate.Connections.Add(new Connection("104", "102"));
            mapTemplate.Connections.Add(new Connection("104", "120"));
            mapTemplate.Connections.Add(new Connection("104", "103"));
            mapTemplate.Connections.Add(new Connection("104", "119"));
            mapTemplate.Connections.Add(new Connection("104", "107"));
            mapTemplate.Connections.Add(new Connection("104", "70"));
            mapTemplate.Connections.Add(new Connection("105", "121"));
            mapTemplate.Connections.Add(new Connection("105", "107"));
            mapTemplate.Connections.Add(new Connection("105", "106"));
            mapTemplate.Connections.Add(new Connection("105", "111"));
            mapTemplate.Connections.Add(new Connection("106", "105"));
            mapTemplate.Connections.Add(new Connection("106", "107"));
            mapTemplate.Connections.Add(new Connection("106", "108"));
            mapTemplate.Connections.Add(new Connection("106", "109"));
            mapTemplate.Connections.Add(new Connection("106", "111"));
            mapTemplate.Connections.Add(new Connection("107", "119"));
            mapTemplate.Connections.Add(new Connection("107", "104"));
            mapTemplate.Connections.Add(new Connection("107", "105"));
            mapTemplate.Connections.Add(new Connection("107", "106"));
            mapTemplate.Connections.Add(new Connection("107", "108"));
            mapTemplate.Connections.Add(new Connection("108", "107"));
            mapTemplate.Connections.Add(new Connection("108", "70"));
            mapTemplate.Connections.Add(new Connection("108", "106"));
            mapTemplate.Connections.Add(new Connection("108", "109"));
            mapTemplate.Connections.Add(new Connection("108", "69"));
            mapTemplate.Connections.Add(new Connection("109", "108"));
            mapTemplate.Connections.Add(new Connection("109", "106"));
            mapTemplate.Connections.Add(new Connection("109", "110"));
            mapTemplate.Connections.Add(new Connection("109", "69"));
            mapTemplate.Connections.Add(new Connection("109", "111"));
            mapTemplate.Connections.Add(new Connection("110", "109"));
            mapTemplate.Connections.Add(new Connection("110", "69"));
            mapTemplate.Connections.Add(new Connection("110", "60"));
            mapTemplate.Connections.Add(new Connection("110", "113"));
            mapTemplate.Connections.Add(new Connection("111", "109"));
            mapTemplate.Connections.Add(new Connection("111", "106"));
            mapTemplate.Connections.Add(new Connection("111", "105"));
            mapTemplate.Connections.Add(new Connection("111", "112"));
            mapTemplate.Connections.Add(new Connection("111", "113"));
            mapTemplate.Connections.Add(new Connection("112", "114"));
            mapTemplate.Connections.Add(new Connection("112", "113"));
            mapTemplate.Connections.Add(new Connection("112", "111"));
            mapTemplate.Connections.Add(new Connection("113", "114"));
            mapTemplate.Connections.Add(new Connection("113", "115"));
            mapTemplate.Connections.Add(new Connection("113", "112"));
            mapTemplate.Connections.Add(new Connection("113", "110"));
            mapTemplate.Connections.Add(new Connection("113", "111"));
            mapTemplate.Connections.Add(new Connection("114", "118"));
            mapTemplate.Connections.Add(new Connection("114", "117"));
            mapTemplate.Connections.Add(new Connection("114", "115"));
            mapTemplate.Connections.Add(new Connection("114", "112"));
            mapTemplate.Connections.Add(new Connection("114", "113"));
            mapTemplate.Connections.Add(new Connection("115", "116"));
            mapTemplate.Connections.Add(new Connection("115", "62"));
            mapTemplate.Connections.Add(new Connection("115", "114"));
            mapTemplate.Connections.Add(new Connection("115", "113"));
            mapTemplate.Connections.Add(new Connection("116", "117"));
            mapTemplate.Connections.Add(new Connection("116", "62"));
            mapTemplate.Connections.Add(new Connection("116", "115"));
            mapTemplate.Connections.Add(new Connection("117", "118"));
            mapTemplate.Connections.Add(new Connection("117", "116"));
            mapTemplate.Connections.Add(new Connection("117", "114"));
            mapTemplate.Connections.Add(new Connection("118", "117"));
            mapTemplate.Connections.Add(new Connection("118", "114"));
            mapTemplate.Connections.Add(new Connection("119", "120"));
            mapTemplate.Connections.Add(new Connection("119", "104"));
            mapTemplate.Connections.Add(new Connection("119", "122"));
            mapTemplate.Connections.Add(new Connection("119", "121"));
            mapTemplate.Connections.Add(new Connection("119", "107"));
            mapTemplate.Connections.Add(new Connection("120", "101"));
            mapTemplate.Connections.Add(new Connection("120", "123"));
            mapTemplate.Connections.Add(new Connection("120", "102"));
            mapTemplate.Connections.Add(new Connection("120", "104"));
            mapTemplate.Connections.Add(new Connection("120", "122"));
            mapTemplate.Connections.Add(new Connection("120", "119"));
            mapTemplate.Connections.Add(new Connection("121", "127"));
            mapTemplate.Connections.Add(new Connection("121", "119"));
            mapTemplate.Connections.Add(new Connection("121", "122"));
            mapTemplate.Connections.Add(new Connection("121", "105"));
            mapTemplate.Connections.Add(new Connection("122", "127"));
            mapTemplate.Connections.Add(new Connection("122", "120"));
            mapTemplate.Connections.Add(new Connection("122", "119"));
            mapTemplate.Connections.Add(new Connection("122", "121"));
            mapTemplate.Connections.Add(new Connection("122", "123"));
            mapTemplate.Connections.Add(new Connection("123", "126"));
            mapTemplate.Connections.Add(new Connection("123", "124"));
            mapTemplate.Connections.Add(new Connection("123", "101"));
            mapTemplate.Connections.Add(new Connection("123", "120"));
            mapTemplate.Connections.Add(new Connection("123", "122"));
            mapTemplate.Connections.Add(new Connection("124", "125"));
            mapTemplate.Connections.Add(new Connection("124", "126"));
            mapTemplate.Connections.Add(new Connection("124", "123"));
            mapTemplate.Connections.Add(new Connection("125", "124"));
            mapTemplate.Connections.Add(new Connection("125", "126"));
            mapTemplate.Connections.Add(new Connection("126", "125"));
            mapTemplate.Connections.Add(new Connection("126", "127"));
            mapTemplate.Connections.Add(new Connection("126", "124"));
            mapTemplate.Connections.Add(new Connection("126", "123"));
            mapTemplate.Connections.Add(new Connection("127", "126"));
            mapTemplate.Connections.Add(new Connection("127", "121"));
            mapTemplate.Connections.Add(new Connection("127", "122"));

            return mapTemplate;
        }
    }
}

