
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Inselreiche()
        {

var mapTemplate = new MapTemplate("Inselreiche") { Image = "inselreiche.gif" };
var country1 = new CountryTemplate("1", "Revo") { X = 265, Y = 58 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "ArkHan") { X = 137, Y = 56 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Quanor") { X = 227, Y = 154 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Syladria") { X = 143, Y = 138 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Sanclavia") { X = 183, Y = 220 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Iratuob") { X = 109, Y = 238 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Gom") { X = 79, Y = 358 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Alcantar") { X = 171, Y = 466 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Soltierra") { X = 313, Y = 418 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Carandor") { X = 359, Y = 666 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Aureus") { X = 319, Y = 636 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Moriandris") { X = 267, Y = 714 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Pionas") { X = 199, Y = 688 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Kemet Schetait") { X = 595, Y = 448 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Groenfelden") { X = 635, Y = 360 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Fortia") { X = 765, Y = 389 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Luteria") { X = 919, Y = 373 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Nordmarken") { X = 669, Y = 279 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Solwerus") { X = 545, Y = 239 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Ankhalshaan") { X = 691, Y = 223 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Grothans Rhash") { X = 873, Y = 263 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Nargelas") { X = 831, Y = 199 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Khasradir") { X = 761, Y = 149 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Adiulleth") { X = 633, Y = 145 };
mapTemplate.Countries.Add(country24);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country13);
continent1.Countries.Add(country12);
continent1.Countries.Add(country11);
continent1.Countries.Add(country10);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country18);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
continent3.Countries.Add(country21);
continent3.Countries.Add(country22);
continent3.Countries.Add(country23);
continent3.Countries.Add(country24);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 7);
continent4.Countries.Add(country9);
continent4.Countries.Add(country8);
continent4.Countries.Add(country7);
continent4.Countries.Add(country6);
continent4.Countries.Add(country5);
continent4.Countries.Add(country3);
continent4.Countries.Add(country4);
continent4.Countries.Add(country1);
continent4.Countries.Add(country2);
mapTemplate.Continents.Add(continent4);
mapTemplate.Connections.Add(new Connection("24", "19"));
mapTemplate.Connections.Add(new Connection("24", "20"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "16"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "4"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "24"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("19", "3"));
mapTemplate.Connections.Add(new Connection("19", "24"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "7"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "21"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("15", "9"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "5"));
mapTemplate.Connections.Add(new Connection("9", "15"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "17"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "21"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "19"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "3"));

            return mapTemplate;
		}
    }
}

