
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate China()
        {

var mapTemplate = new MapTemplate("China") { Image = "china.jpg" };
var country1 = new CountryTemplate("1", "West- Kasachstan") { X = 120, Y = 25 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Nord- Kasachstan") { X = 448, Y = 125 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Qaraghandy") { X = 341, Y = 151 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Sued- Kasachstan") { X = 239, Y = 251 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Alma Ata") { X = 497, Y = 271 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Ost- Kasachstan") { X = 545, Y = 190 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Omsk") { X = 464, Y = 49 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Tomsk") { X = 650, Y = 23 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Novosibirsk") { X = 589, Y = 90 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Altai") { X = 566, Y = 132 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Gorno Altai") { X = 627, Y = 197 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Kemerovo") { X = 673, Y = 103 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Chakassien") { X = 684, Y = 146 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Krasnojarsk") { X = 775, Y = 56 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Tuwa") { X = 777, Y = 179 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Irkutsk") { X = 873, Y = 134 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Burjatien") { X = 947, Y = 182 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Sabaikalski Krai") { X = 1079, Y = 177 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Amur") { X = 1234, Y = 100 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Birobidshan") { X = 1340, Y = 175 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Chabrowsk") { X = 1437, Y = 74 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Sakhalien") { X = 1592, Y = 160 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Primorje") { X = 1426, Y = 256 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Nord- Korea") { X = 1289, Y = 420 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Sued- Korea") { X = 1322, Y = 489 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Hokkaido") { X = 1596, Y = 260 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Honshu") { X = 1522, Y = 504 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Shikoku") { X = 1436, Y = 563 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Kyushu") { X = 1385, Y = 582 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Phillippinen") { X = 1291, Y = 922 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Vietnam") { X = 920, Y = 869 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Laos") { X = 866, Y = 916 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Thailand") { X = 813, Y = 970 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Burma") { X = 734, Y = 811 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Bangladesh") { X = 613, Y = 849 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Ost- Indien") { X = 539, Y = 792 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Bhutan") { X = 619, Y = 730 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Nepal") { X = 474, Y = 669 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Kashmir") { X = 400, Y = 546 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Nord- Indien") { X = 343, Y = 705 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "West- Indien") { X = 315, Y = 867 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Sued- Indien") { X = 364, Y = 933 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Pakistan") { X = 211, Y = 597 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Suedost- Afghanistan") { X = 93, Y = 562 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Nordwest- Afghanistan") { X = 84, Y = 476 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Iran") { X = 24, Y = 661 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Usbekistan") { X = 84, Y = 267 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Turkmenistan") { X = 52, Y = 361 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Tadschikistan") { X = 321, Y = 425 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Kirgisistan") { X = 384, Y = 331 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Mongolischer Altai") { X = 697, Y = 269 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Altai - Gobi") { X = 770, Y = 362 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Zentral- Mongolei") { X = 864, Y = 320 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Nord- Mongolei") { X = 820, Y = 228 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "West- Mongolei") { X = 1041, Y = 261 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Nei Mongol") { X = 1002, Y = 439 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Bejing") { X = 1103, Y = 432 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Hebai") { X = 1093, Y = 482 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Shanxi") { X = 1041, Y = 489 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Tjanjin") { X = 1134, Y = 450 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Shenyang") { X = 1301, Y = 263 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Jilin") { X = 1258, Y = 330 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Liaoning") { X = 1220, Y = 374 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Xinjiang") { X = 589, Y = 445 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Gansu") { X = 757, Y = 431 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Ningxia") { X = 935, Y = 510 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Shaanxi") { X = 966, Y = 581 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Qinghai") { X = 753, Y = 542 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Ngari") { X = 506, Y = 597 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Xizang") { X = 612, Y = 625 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Sichuan") { X = 855, Y = 654 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Yunnan") { X = 821, Y = 776 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Guizhou") { X = 944, Y = 768 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Shandong") { X = 1145, Y = 532 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Jiangsu") { X = 1180, Y = 564 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Shanghei") { X = 1230, Y = 631 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Anhui") { X = 1150, Y = 611 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Jiangxi") { X = 1123, Y = 718 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Zhejiang") { X = 1207, Y = 662 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Fujian") { X = 1179, Y = 758 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Taiwan") { X = 1253, Y = 792 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Henan") { X = 1075, Y = 597 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Hubei") { X = 1045, Y = 649 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Hunan") { X = 1042, Y = 705 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Guangxi") { X = 1025, Y = 809 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Guangdong") { X = 1139, Y = 804 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Hong Kong und Macau") { X = 1112, Y = 840 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Hainan") { X = 1022, Y = 927 };
mapTemplate.Countries.Add(country88);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 4);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country30);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country34);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country35);
continent7.Countries.Add(country36);
continent7.Countries.Add(country37);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
continent7.Countries.Add(country41);
continent7.Countries.Add(country42);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country43);
continent8.Countries.Add(country44);
continent8.Countries.Add(country45);
continent8.Countries.Add(country46);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country47);
continent9.Countries.Add(country48);
continent9.Countries.Add(country49);
continent9.Countries.Add(country50);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 4);
continent10.Countries.Add(country51);
continent10.Countries.Add(country52);
continent10.Countries.Add(country53);
continent10.Countries.Add(country54);
continent10.Countries.Add(country55);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 4);
continent11.Countries.Add(country56);
continent11.Countries.Add(country57);
continent11.Countries.Add(country58);
continent11.Countries.Add(country59);
continent11.Countries.Add(country60);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 2);
continent12.Countries.Add(country61);
continent12.Countries.Add(country62);
continent12.Countries.Add(country63);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 4);
continent13.Countries.Add(country64);
continent13.Countries.Add(country65);
continent13.Countries.Add(country66);
continent13.Countries.Add(country67);
continent13.Countries.Add(country68);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 4);
continent14.Countries.Add(country69);
continent14.Countries.Add(country70);
continent14.Countries.Add(country71);
continent14.Countries.Add(country72);
continent14.Countries.Add(country73);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 5);
continent15.Countries.Add(country74);
continent15.Countries.Add(country75);
continent15.Countries.Add(country76);
continent15.Countries.Add(country77);
continent15.Countries.Add(country78);
continent15.Countries.Add(country79);
continent15.Countries.Add(country80);
continent15.Countries.Add(country81);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 5);
continent16.Countries.Add(country82);
continent16.Countries.Add(country83);
continent16.Countries.Add(country84);
continent16.Countries.Add(country85);
continent16.Countries.Add(country86);
continent16.Countries.Add(country87);
continent16.Countries.Add(country88);
mapTemplate.Continents.Add(continent16);
mapTemplate.Connections.Add(new Connection("1", "47"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "7"));
mapTemplate.Connections.Add(new Connection("2", "9"));
mapTemplate.Connections.Add(new Connection("2", "10"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("4", "50"));
mapTemplate.Connections.Add(new Connection("4", "47"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "64"));
mapTemplate.Connections.Add(new Connection("5", "50"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("6", "64"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "2"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("7", "2"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "14"));
mapTemplate.Connections.Add(new Connection("8", "12"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "2"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "2"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("11", "64"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "51"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("12", "8"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "8"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "51"));
mapTemplate.Connections.Add(new Connection("15", "54"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "54"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "54"));
mapTemplate.Connections.Add(new Connection("18", "55"));
mapTemplate.Connections.Add(new Connection("18", "56"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "61"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "61"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("20", "61"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "61"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "61"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "61"));
mapTemplate.Connections.Add(new Connection("24", "62"));
mapTemplate.Connections.Add(new Connection("24", "63"));
mapTemplate.Connections.Add(new Connection("24", "74"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "76"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "76"));
mapTemplate.Connections.Add(new Connection("29", "81"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "87"));
mapTemplate.Connections.Add(new Connection("30", "81"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "72"));
mapTemplate.Connections.Add(new Connection("31", "85"));
mapTemplate.Connections.Add(new Connection("31", "88"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "72"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "70"));
mapTemplate.Connections.Add(new Connection("34", "72"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("36", "42"));
mapTemplate.Connections.Add(new Connection("36", "43"));
mapTemplate.Connections.Add(new Connection("36", "40"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "70"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "41"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "70"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "69"));
mapTemplate.Connections.Add(new Connection("38", "70"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("39", "64"));
mapTemplate.Connections.Add(new Connection("39", "43"));
mapTemplate.Connections.Add(new Connection("39", "69"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "43"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "69"));
mapTemplate.Connections.Add(new Connection("40", "36"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "36"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "36"));
mapTemplate.Connections.Add(new Connection("43", "64"));
mapTemplate.Connections.Add(new Connection("43", "39"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "40"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "36"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "64"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "48"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "49"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "4"));
mapTemplate.Connections.Add(new Connection("47", "1"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("48", "45"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("49", "64"));
mapTemplate.Connections.Add(new Connection("49", "45"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("50", "64"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "5"));
mapTemplate.Connections.Add(new Connection("50", "4"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("51", "64"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "11"));
mapTemplate.Connections.Add(new Connection("51", "15"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("52", "64"));
mapTemplate.Connections.Add(new Connection("52", "65"));
mapTemplate.Connections.Add(new Connection("52", "56"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "55"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "55"));
mapTemplate.Connections.Add(new Connection("54", "15"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "17"));
mapTemplate.Connections.Add(new Connection("54", "18"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "53"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "18"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "52"));
mapTemplate.Connections.Add(new Connection("56", "67"));
mapTemplate.Connections.Add(new Connection("56", "66"));
mapTemplate.Connections.Add(new Connection("56", "65"));
mapTemplate.Connections.Add(new Connection("56", "59"));
mapTemplate.Connections.Add(new Connection("56", "52"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "58"));
mapTemplate.Connections.Add(new Connection("56", "18"));
mapTemplate.Connections.Add(new Connection("56", "61"));
mapTemplate.Connections.Add(new Connection("56", "62"));
mapTemplate.Connections.Add(new Connection("56", "63"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("58", "56"));
mapTemplate.Connections.Add(new Connection("58", "60"));
mapTemplate.Connections.Add(new Connection("58", "63"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "82"));
mapTemplate.Connections.Add(new Connection("58", "74"));
mapTemplate.Connections.Add(new Connection("59", "67"));
mapTemplate.Connections.Add(new Connection("59", "82"));
mapTemplate.Connections.Add(new Connection("59", "56"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("60", "74"));
mapTemplate.Connections.Add(new Connection("60", "58"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("60", "63"));
mapTemplate.Connections.Add(new Connection("61", "56"));
mapTemplate.Connections.Add(new Connection("61", "19"));
mapTemplate.Connections.Add(new Connection("61", "20"));
mapTemplate.Connections.Add(new Connection("61", "18"));
mapTemplate.Connections.Add(new Connection("61", "23"));
mapTemplate.Connections.Add(new Connection("61", "24"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "21"));
mapTemplate.Connections.Add(new Connection("62", "56"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "24"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "56"));
mapTemplate.Connections.Add(new Connection("63", "58"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "24"));
mapTemplate.Connections.Add(new Connection("63", "74"));
mapTemplate.Connections.Add(new Connection("63", "60"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "68"));
mapTemplate.Connections.Add(new Connection("64", "70"));
mapTemplate.Connections.Add(new Connection("64", "69"));
mapTemplate.Connections.Add(new Connection("64", "49"));
mapTemplate.Connections.Add(new Connection("64", "39"));
mapTemplate.Connections.Add(new Connection("64", "50"));
mapTemplate.Connections.Add(new Connection("64", "5"));
mapTemplate.Connections.Add(new Connection("64", "6"));
mapTemplate.Connections.Add(new Connection("64", "11"));
mapTemplate.Connections.Add(new Connection("64", "51"));
mapTemplate.Connections.Add(new Connection("64", "52"));
mapTemplate.Connections.Add(new Connection("64", "43"));
mapTemplate.Connections.Add(new Connection("64", "45"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "68"));
mapTemplate.Connections.Add(new Connection("65", "67"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "52"));
mapTemplate.Connections.Add(new Connection("65", "56"));
mapTemplate.Connections.Add(new Connection("65", "71"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "56"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("67", "71"));
mapTemplate.Connections.Add(new Connection("67", "65"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "83"));
mapTemplate.Connections.Add(new Connection("67", "82"));
mapTemplate.Connections.Add(new Connection("67", "59"));
mapTemplate.Connections.Add(new Connection("67", "56"));
mapTemplate.Connections.Add(new Connection("68", "64"));
mapTemplate.Connections.Add(new Connection("68", "70"));
mapTemplate.Connections.Add(new Connection("68", "71"));
mapTemplate.Connections.Add(new Connection("68", "65"));
mapTemplate.Connections.Add(new Connection("69", "64"));
mapTemplate.Connections.Add(new Connection("69", "39"));
mapTemplate.Connections.Add(new Connection("69", "40"));
mapTemplate.Connections.Add(new Connection("69", "38"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("70", "64"));
mapTemplate.Connections.Add(new Connection("70", "38"));
mapTemplate.Connections.Add(new Connection("70", "36"));
mapTemplate.Connections.Add(new Connection("70", "37"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "34"));
mapTemplate.Connections.Add(new Connection("70", "68"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "73"));
mapTemplate.Connections.Add(new Connection("71", "68"));
mapTemplate.Connections.Add(new Connection("71", "67"));
mapTemplate.Connections.Add(new Connection("71", "84"));
mapTemplate.Connections.Add(new Connection("71", "83"));
mapTemplate.Connections.Add(new Connection("71", "65"));
mapTemplate.Connections.Add(new Connection("72", "34"));
mapTemplate.Connections.Add(new Connection("72", "32"));
mapTemplate.Connections.Add(new Connection("72", "31"));
mapTemplate.Connections.Add(new Connection("72", "85"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("73", "85"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "71"));
mapTemplate.Connections.Add(new Connection("73", "84"));
mapTemplate.Connections.Add(new Connection("74", "63"));
mapTemplate.Connections.Add(new Connection("74", "60"));
mapTemplate.Connections.Add(new Connection("74", "58"));
mapTemplate.Connections.Add(new Connection("74", "24"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("74", "82"));
mapTemplate.Connections.Add(new Connection("74", "77"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "79"));
mapTemplate.Connections.Add(new Connection("75", "77"));
mapTemplate.Connections.Add(new Connection("76", "29"));
mapTemplate.Connections.Add(new Connection("76", "25"));
mapTemplate.Connections.Add(new Connection("76", "81"));
mapTemplate.Connections.Add(new Connection("76", "79"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("77", "75"));
mapTemplate.Connections.Add(new Connection("77", "82"));
mapTemplate.Connections.Add(new Connection("77", "74"));
mapTemplate.Connections.Add(new Connection("77", "79"));
mapTemplate.Connections.Add(new Connection("77", "83"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("78", "84"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "83"));
mapTemplate.Connections.Add(new Connection("78", "86"));
mapTemplate.Connections.Add(new Connection("78", "80"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("79", "76"));
mapTemplate.Connections.Add(new Connection("79", "75"));
mapTemplate.Connections.Add(new Connection("79", "77"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("80", "86"));
mapTemplate.Connections.Add(new Connection("80", "78"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("81", "30"));
mapTemplate.Connections.Add(new Connection("81", "29"));
mapTemplate.Connections.Add(new Connection("81", "76"));
mapTemplate.Connections.Add(new Connection("81", "87"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("82", "67"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "59"));
mapTemplate.Connections.Add(new Connection("82", "58"));
mapTemplate.Connections.Add(new Connection("82", "74"));
mapTemplate.Connections.Add(new Connection("82", "77"));
mapTemplate.Connections.Add(new Connection("83", "71"));
mapTemplate.Connections.Add(new Connection("83", "67"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "77"));
mapTemplate.Connections.Add(new Connection("83", "78"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("84", "73"));
mapTemplate.Connections.Add(new Connection("84", "71"));
mapTemplate.Connections.Add(new Connection("84", "86"));
mapTemplate.Connections.Add(new Connection("84", "78"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("85", "31"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "73"));
mapTemplate.Connections.Add(new Connection("85", "72"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("86", "84"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "80"));
mapTemplate.Connections.Add(new Connection("86", "78"));
mapTemplate.Connections.Add(new Connection("87", "30"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "81"));
mapTemplate.Connections.Add(new Connection("88", "31"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "86"));

            return mapTemplate;
		}
    }
}

