
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Galaxy_Far_Away()
        {

var mapTemplate = new MapTemplate("Galaxy_Far_Away") { Image = "galaxy_far_away.jpg" };
var country1 = new CountryTemplate("1", "Empress Teta") { X = 292, Y = 694 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Vulpter") { X = 346, Y = 703 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Coruscant") { X = 271, Y = 655 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Alsakan") { X = 301, Y = 621 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Anaxes") { X = 343, Y = 605 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Corulag") { X = 376, Y = 589 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Ralltiir") { X = 439, Y = 556 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Caamas") { X = 458, Y = 585 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Alderaan") { X = 453, Y = 620 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Kuat") { X = 485, Y = 646 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Humbarine") { X = 501, Y = 679 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Rendili") { X = 465, Y = 702 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Aargau") { X = 373, Y = 649 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Nubia") { X = 490, Y = 780 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Borleias") { X = 278, Y = 533 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Arkania") { X = 425, Y = 497 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Carida") { X = 507, Y = 523 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Balmorra") { X = 542, Y = 637 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Neimoidian Worlds") { X = 546, Y = 702 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Commenor") { X = 577, Y = 740 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Tapani Sector") { X = 389, Y = 915 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Fondor") { X = 325, Y = 917 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Hapes Consortium") { X = 712, Y = 589 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Bilbringi") { X = 271, Y = 474 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Carratos") { X = 274, Y = 499 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Colla IV") { X = 588, Y = 496 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Zeltros") { X = 687, Y = 772 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Manaan") { X = 691, Y = 851 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Antar") { X = 638, Y = 898 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Atzerri") { X = 506, Y = 941 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Kinyen") { X = 339, Y = 1071 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Osarian") { X = 615, Y = 989 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Gyndine") { X = 745, Y = 921 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Contruum") { X = 694, Y = 399 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Iridonia") { X = 304, Y = 316 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Ord Mantell") { X = 320, Y = 348 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Ithor") { X = 634, Y = 201 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Velmor") { X = 845, Y = 309 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Metalorn") { X = 1001, Y = 403 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Anzat") { X = 1075, Y = 392 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Bimmisaari") { X = 1104, Y = 508 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Kashyyyk") { X = 963, Y = 588 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Lannik") { X = 1065, Y = 853 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Bothawui") { X = 1043, Y = 1102 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Rodia") { X = 855, Y = 1195 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Falleen") { X = 818, Y = 1168 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Naboo") { X = 674, Y = 1300 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Malastare") { X = 539, Y = 1275 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Yaga Minor") { X = 394, Y = 115 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Muunilinst") { X = 474, Y = 63 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Bastion") { X = 524, Y = 25 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Mandalore Sector") { X = 780, Y = 154 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Phindar") { X = 880, Y = 162 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Yavin 4") { X = 978, Y = 132 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Ancient Sith Worlds") { X = 1100, Y = 117 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Tion Cluster") { X = 1305, Y = 255 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Mon Calamari") { X = 1409, Y = 288 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Jabiim") { X = 1174, Y = 400 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Kessel") { X = 1368, Y = 642 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Toydaria") { X = 1127, Y = 809 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Nal Hutta") { X = 1210, Y = 838 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Ylesia") { X = 1323, Y = 833 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Nar Kreeta") { X = 1217, Y = 714 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "SiKlaata Cluster") { X = 1234, Y = 640 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Aduba III") { X = 1421, Y = 777 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Gamorr") { X = 1286, Y = 1058 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Kamino") { X = 1149, Y = 1148 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Rothana") { X = 1276, Y = 1231 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Hypori") { X = 1136, Y = 1343 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Ryloth") { X = 1075, Y = 1409 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Geonosis") { X = 1036, Y = 1363 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Vergesso Asteroids") { X = 751, Y = 1471 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "KalShebbol") { X = 520, Y = 1597 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Sullust") { X = 457, Y = 1368 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Moddell Sector") { X = 38, Y = 1127 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Twin Nebulae Sectors") { X = 186, Y = 1257 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Corellia") { X = 432, Y = 735 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Duro") { X = 451, Y = 814 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Moorja") { X = 365, Y = 997 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "YagDhul") { X = 411, Y = 978 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Thyferra") { X = 363, Y = 961 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Vandelhelm") { X = 443, Y = 1087 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Sluis Van") { X = 521, Y = 1482 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Subterrel Sector") { X = 422, Y = 1647 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Eriadu") { X = 469, Y = 1406 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Denon") { X = 572, Y = 896 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Arkanis Sector") { X = 1009, Y = 1335 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Christophsis") { X = 944, Y = 1305 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Druckenwell") { X = 742, Y = 1134 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Brentaal") { X = 401, Y = 568 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Taanab") { X = 628, Y = 456 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Roche Asteroids") { X = 849, Y = 400 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Centares") { X = 1030, Y = 331 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Belderone") { X = 1090, Y = 276 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Bogden") { X = 429, Y = 409 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Bandomeer") { X = 726, Y = 123 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Toprawa") { X = 788, Y = 74 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Telos") { X = 910, Y = 43 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Corporate Sector") { X = 1072, Y = 42 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Minos Cluster") { X = 501, Y = 1534 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "Ciutric Hegemony") { X = 595, Y = 108 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "Vorzyd V") { X = 1008, Y = 237 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "Metellos") { X = 207, Y = 679 };
mapTemplate.Countries.Add(country103);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 7);
continent2.Countries.Add(country3);
continent2.Countries.Add(country4);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
continent2.Countries.Add(country103);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 6);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
continent3.Countries.Add(country21);
continent3.Countries.Add(country22);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 5);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
continent4.Countries.Add(country28);
continent4.Countries.Add(country29);
continent4.Countries.Add(country30);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
continent5.Countries.Add(country34);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 8);
continent6.Countries.Add(country35);
continent6.Countries.Add(country36);
continent6.Countries.Add(country37);
continent6.Countries.Add(country38);
continent6.Countries.Add(country39);
continent6.Countries.Add(country40);
continent6.Countries.Add(country41);
continent6.Countries.Add(country42);
continent6.Countries.Add(country43);
continent6.Countries.Add(country44);
continent6.Countries.Add(country45);
continent6.Countries.Add(country46);
continent6.Countries.Add(country47);
continent6.Countries.Add(country48);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 7);
continent7.Countries.Add(country49);
continent7.Countries.Add(country50);
continent7.Countries.Add(country51);
continent7.Countries.Add(country52);
continent7.Countries.Add(country53);
continent7.Countries.Add(country54);
continent7.Countries.Add(country55);
continent7.Countries.Add(country56);
continent7.Countries.Add(country57);
continent7.Countries.Add(country58);
continent7.Countries.Add(country59);
continent7.Countries.Add(country101);
continent7.Countries.Add(country102);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country60);
continent8.Countries.Add(country61);
continent8.Countries.Add(country62);
continent8.Countries.Add(country63);
continent8.Countries.Add(country64);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country81);
continent9.Countries.Add(country82);
continent9.Countries.Add(country83);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 5);
continent10.Countries.Add(country76);
continent10.Countries.Add(country77);
continent10.Countries.Add(country78);
continent10.Countries.Add(country79);
continent10.Countries.Add(country80);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country84);
continent11.Countries.Add(country85);
continent11.Countries.Add(country86);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 3);
continent12.Countries.Add(country87);
continent12.Countries.Add(country88);
continent12.Countries.Add(country89);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 6);
continent13.Countries.Add(country90);
continent13.Countries.Add(country91);
continent13.Countries.Add(country92);
continent13.Countries.Add(country93);
continent13.Countries.Add(country94);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 4);
continent14.Countries.Add(country95);
continent14.Countries.Add(country96);
continent14.Countries.Add(country97);
continent14.Countries.Add(country98);
continent14.Countries.Add(country99);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 7);
continent15.Countries.Add(country65);
continent15.Countries.Add(country66);
continent15.Countries.Add(country67);
continent15.Countries.Add(country68);
continent15.Countries.Add(country69);
continent15.Countries.Add(country70);
continent15.Countries.Add(country71);
continent15.Countries.Add(country72);
continent15.Countries.Add(country73);
continent15.Countries.Add(country74);
continent15.Countries.Add(country75);
continent15.Countries.Add(country100);
mapTemplate.Continents.Add(continent15);
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "13"));
mapTemplate.Connections.Add(new Connection("3", "103"));
mapTemplate.Connections.Add(new Connection("3", "15"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "13"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "90"));
mapTemplate.Connections.Add(new Connection("7", "90"));
mapTemplate.Connections.Add(new Connection("7", "17"));
mapTemplate.Connections.Add(new Connection("8", "90"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "18"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("11", "19"));
mapTemplate.Connections.Add(new Connection("11", "86"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "77"));
mapTemplate.Connections.Add(new Connection("13", "2"));
mapTemplate.Connections.Add(new Connection("13", "3"));
mapTemplate.Connections.Add(new Connection("13", "77"));
mapTemplate.Connections.Add(new Connection("14", "77"));
mapTemplate.Connections.Add(new Connection("14", "86"));
mapTemplate.Connections.Add(new Connection("15", "25"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "3"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "7"));
mapTemplate.Connections.Add(new Connection("17", "91"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("18", "10"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "23"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "11"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "27"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "81"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "18"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("24", "36"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "15"));
mapTemplate.Connections.Add(new Connection("25", "95"));
mapTemplate.Connections.Add(new Connection("26", "91"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("27", "20"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "86"));
mapTemplate.Connections.Add(new Connection("30", "80"));
mapTemplate.Connections.Add(new Connection("30", "86"));
mapTemplate.Connections.Add(new Connection("31", "79"));
mapTemplate.Connections.Add(new Connection("31", "82"));
mapTemplate.Connections.Add(new Connection("31", "76"));
mapTemplate.Connections.Add(new Connection("32", "86"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "82"));
mapTemplate.Connections.Add(new Connection("32", "89"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "91"));
mapTemplate.Connections.Add(new Connection("34", "92"));
mapTemplate.Connections.Add(new Connection("35", "49"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "24"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "92"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "92"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "93"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("42", "64"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "60"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "69"));
mapTemplate.Connections.Add(new Connection("44", "66"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("45", "88"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "89"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "89"));
mapTemplate.Connections.Add(new Connection("48", "85"));
mapTemplate.Connections.Add(new Connection("48", "86"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "35"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "101"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("52", "96"));
mapTemplate.Connections.Add(new Connection("52", "97"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "102"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "97"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "94"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("56", "94"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("58", "94"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("59", "65"));
mapTemplate.Connections.Add(new Connection("59", "64"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("60", "43"));
mapTemplate.Connections.Add(new Connection("60", "63"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("62", "65"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("63", "60"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "59"));
mapTemplate.Connections.Add(new Connection("64", "42"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "59"));
mapTemplate.Connections.Add(new Connection("65", "62"));
mapTemplate.Connections.Add(new Connection("66", "44"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("69", "44"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("71", "87"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("72", "83"));
mapTemplate.Connections.Add(new Connection("72", "87"));
mapTemplate.Connections.Add(new Connection("73", "100"));
mapTemplate.Connections.Add(new Connection("74", "76"));
mapTemplate.Connections.Add(new Connection("74", "82"));
mapTemplate.Connections.Add(new Connection("74", "85"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("76", "31"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "74"));
mapTemplate.Connections.Add(new Connection("77", "12"));
mapTemplate.Connections.Add(new Connection("77", "13"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("77", "14"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "80"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("79", "31"));
mapTemplate.Connections.Add(new Connection("80", "78"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("80", "30"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("80", "82"));
mapTemplate.Connections.Add(new Connection("81", "21"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("82", "31"));
mapTemplate.Connections.Add(new Connection("82", "80"));
mapTemplate.Connections.Add(new Connection("82", "32"));
mapTemplate.Connections.Add(new Connection("82", "74"));
mapTemplate.Connections.Add(new Connection("83", "85"));
mapTemplate.Connections.Add(new Connection("83", "72"));
mapTemplate.Connections.Add(new Connection("83", "100"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("85", "74"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "83"));
mapTemplate.Connections.Add(new Connection("85", "48"));
mapTemplate.Connections.Add(new Connection("86", "11"));
mapTemplate.Connections.Add(new Connection("86", "29"));
mapTemplate.Connections.Add(new Connection("86", "14"));
mapTemplate.Connections.Add(new Connection("86", "30"));
mapTemplate.Connections.Add(new Connection("86", "32"));
mapTemplate.Connections.Add(new Connection("86", "48"));
mapTemplate.Connections.Add(new Connection("87", "72"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "71"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "45"));
mapTemplate.Connections.Add(new Connection("89", "32"));
mapTemplate.Connections.Add(new Connection("89", "47"));
mapTemplate.Connections.Add(new Connection("89", "46"));
mapTemplate.Connections.Add(new Connection("90", "95"));
mapTemplate.Connections.Add(new Connection("90", "6"));
mapTemplate.Connections.Add(new Connection("90", "7"));
mapTemplate.Connections.Add(new Connection("90", "8"));
mapTemplate.Connections.Add(new Connection("91", "95"));
mapTemplate.Connections.Add(new Connection("91", "17"));
mapTemplate.Connections.Add(new Connection("91", "26"));
mapTemplate.Connections.Add(new Connection("91", "34"));
mapTemplate.Connections.Add(new Connection("92", "38"));
mapTemplate.Connections.Add(new Connection("92", "93"));
mapTemplate.Connections.Add(new Connection("92", "34"));
mapTemplate.Connections.Add(new Connection("92", "39"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "92"));
mapTemplate.Connections.Add(new Connection("93", "40"));
mapTemplate.Connections.Add(new Connection("93", "102"));
mapTemplate.Connections.Add(new Connection("94", "54"));
mapTemplate.Connections.Add(new Connection("94", "56"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("94", "58"));
mapTemplate.Connections.Add(new Connection("95", "25"));
mapTemplate.Connections.Add(new Connection("95", "96"));
mapTemplate.Connections.Add(new Connection("95", "91"));
mapTemplate.Connections.Add(new Connection("95", "90"));
mapTemplate.Connections.Add(new Connection("96", "97"));
mapTemplate.Connections.Add(new Connection("96", "52"));
mapTemplate.Connections.Add(new Connection("96", "95"));
mapTemplate.Connections.Add(new Connection("96", "101"));
mapTemplate.Connections.Add(new Connection("97", "96"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "52"));
mapTemplate.Connections.Add(new Connection("97", "54"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("100", "73"));
mapTemplate.Connections.Add(new Connection("100", "83"));
mapTemplate.Connections.Add(new Connection("101", "50"));
mapTemplate.Connections.Add(new Connection("101", "96"));
mapTemplate.Connections.Add(new Connection("102", "53"));
mapTemplate.Connections.Add(new Connection("102", "93"));
mapTemplate.Connections.Add(new Connection("103", "3"));

            return mapTemplate;
		}
    }
}

