using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Venezia()
        {
            var mapTemplate = new MapTemplate("Venezia") { Image = "Venezia.jpg" };
            var country1 = new CountryTemplate("1", "Isola di Sant Elena") { X = 1249, Y = 666 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "San Isepo") { X = 1110, Y = 530 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Isola San Pietro") { X = 1190, Y = 481 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Arsenale") { X = 1186, Y = 365 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "San Giovanni") { X = 928, Y = 433 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "San Martin") { X = 992, Y = 438 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "San Francesco") { X = 1012, Y = 353 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "San Giovanni e Paolo") { X = 891, Y = 310 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "San Maria Formosa") { X = 817, Y = 398 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "San Moise") { X = 825, Y = 461 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "San Stefano") { X = 644, Y = 501 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "San Luca") { X = 719, Y = 452 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "San Salvador") { X = 762, Y = 382 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "San Giorgio Maggiore") { X = 873, Y = 626 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Santa Maria") { X = 583, Y = 388 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "San Silvestro") { X = 708, Y = 372 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "San Cassan") { X = 664, Y = 320 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Isola Michelle") { X = 951, Y = 128 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Sant Alvise") { X = 812, Y = 330 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "San Canciano") { X = 830, Y = 259 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Santi Apostoli") { X = 756, Y = 236 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "San Felice") { X = 685, Y = 218 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Madonna dell Orto") { X = 677, Y = 159 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "San Girolamo") { X = 570, Y = 88 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "San Marcuola") { X = 581, Y = 204 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "San Giobbe") { X = 477, Y = 210 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Santa Lucia") { X = 422, Y = 278 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Isola del Tronchetto") { X = 181, Y = 220 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Bacino della Stazione Marittima") { X = 291, Y = 302 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "San Nicolo da Tolenti") { X = 452, Y = 360 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "San Simeone Grande") { X = 543, Y = 305 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "San Giovanni dall Orio") { X = 593, Y = 299 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "San Puntalon") { X = 469, Y = 411 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "San Nicolo") { X = 286, Y = 505 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Santa Maria dei Carmini") { X = 395, Y = 469 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "San Trovaso") { X = 491, Y = 500 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Santa Maria dei Gesuati") { X = 659, Y = 591 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "San Biagio") { X = 180, Y = 658 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Sacca Fisola") { X = 277, Y = 671 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "La Giudecca") { X = 499, Y = 720 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Redentore") { X = 655, Y = 745 };
            mapTemplate.Countries.Add(country41);
            var continent1 = new Continent("1", 5);
            continent1.Countries.Add(country19);
            continent1.Countries.Add(country20);
            continent1.Countries.Add(country21);
            continent1.Countries.Add(country22);
            continent1.Countries.Add(country23);
            continent1.Countries.Add(country24);
            continent1.Countries.Add(country25);
            continent1.Countries.Add(country26);
            continent1.Countries.Add(country27);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country28);
            continent2.Countries.Add(country29);
            continent2.Countries.Add(country30);
            continent2.Countries.Add(country31);
            continent2.Countries.Add(country32);
            continent2.Countries.Add(country33);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 4);
            continent3.Countries.Add(country34);
            continent3.Countries.Add(country35);
            continent3.Countries.Add(country36);
            continent3.Countries.Add(country37);
            continent3.Countries.Add(country38);
            continent3.Countries.Add(country39);
            continent3.Countries.Add(country40);
            continent3.Countries.Add(country41);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country15);
            continent4.Countries.Add(country16);
            continent4.Countries.Add(country17);
            continent4.Countries.Add(country18);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country10);
            continent5.Countries.Add(country11);
            continent5.Countries.Add(country12);
            continent5.Countries.Add(country13);
            continent5.Countries.Add(country14);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 5);
            continent6.Countries.Add(country1);
            continent6.Countries.Add(country2);
            continent6.Countries.Add(country3);
            continent6.Countries.Add(country4);
            continent6.Countries.Add(country5);
            continent6.Countries.Add(country6);
            continent6.Countries.Add(country7);
            continent6.Countries.Add(country8);
            continent6.Countries.Add(country9);
            mapTemplate.Continents.Add(continent6);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "14"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "6"));
            mapTemplate.Connections.Add(new Connection("4", "18"));
            mapTemplate.Connections.Add(new Connection("5", "10"));
            mapTemplate.Connections.Add(new Connection("5", "9"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "4"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "20"));
            mapTemplate.Connections.Add(new Connection("8", "19"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "19"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "5"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "5"));
            mapTemplate.Connections.Add(new Connection("10", "13"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "37"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("13", "9"));
            mapTemplate.Connections.Add(new Connection("13", "10"));
            mapTemplate.Connections.Add(new Connection("13", "16"));
            mapTemplate.Connections.Add(new Connection("13", "19"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("14", "2"));
            mapTemplate.Connections.Add(new Connection("14", "41"));
            mapTemplate.Connections.Add(new Connection("15", "30"));
            mapTemplate.Connections.Add(new Connection("15", "33"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "32"));
            mapTemplate.Connections.Add(new Connection("15", "31"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("16", "13"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("17", "32"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("18", "4"));
            mapTemplate.Connections.Add(new Connection("18", "21"));
            mapTemplate.Connections.Add(new Connection("19", "9"));
            mapTemplate.Connections.Add(new Connection("19", "13"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "8"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "8"));
            mapTemplate.Connections.Add(new Connection("21", "18"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "25"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "25"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "23"));
            mapTemplate.Connections.Add(new Connection("25", "22"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "30"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("27", "29"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "34"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "27"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("30", "35"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "15"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "26"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "15"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "17"));
            mapTemplate.Connections.Add(new Connection("32", "15"));
            mapTemplate.Connections.Add(new Connection("33", "36"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "15"));
            mapTemplate.Connections.Add(new Connection("33", "35"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "29"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "30"));
            mapTemplate.Connections.Add(new Connection("35", "33"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "33"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "39"));
            mapTemplate.Connections.Add(new Connection("37", "41"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "11"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "36"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("41", "37"));
            mapTemplate.Connections.Add(new Connection("41", "14"));
            mapTemplate.Connections.Add(new Connection("41", "40"));

            return mapTemplate;
        }
    }
}
