
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate RomeTotalWar()
        {

var mapTemplate = new MapTemplate("RomeTotalWar") { Image = "rometotalwar.jpg" };
var country1 = new CountryTemplate("1", "Hibernia") { X = 148, Y = 123 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Britannia Inferior") { X = 242, Y = 127 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Britannia Superior") { X = 256, Y = 221 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Tribus Silurii") { X = 219, Y = 164 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Mauretania") { X = 73, Y = 657 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Gaetulia") { X = 298, Y = 754 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Sahara") { X = 257, Y = 830 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Numidia") { X = 290, Y = 656 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Africa") { X = 371, Y = 630 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Byzacium") { X = 384, Y = 693 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Tripolitania") { X = 466, Y = 781 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Baliares") { X = 244, Y = 532 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Sardinia") { X = 387, Y = 510 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Lilybaeum") { X = 470, Y = 625 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Syracuse") { X = 504, Y = 641 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Messana") { X = 503, Y = 588 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Crete") { X = 730, Y = 673 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Rhodos") { X = 777, Y = 630 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Cyprus") { X = 929, Y = 646 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Cyrenaica") { X = 673, Y = 754 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Libya") { X = 757, Y = 798 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Nile Delta") { X = 898, Y = 756 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Mittel Aegypten") { X = 925, Y = 809 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Thebais") { X = 974, Y = 846 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Sinai") { X = 996, Y = 762 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Judaea") { X = 992, Y = 730 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Nabataea") { X = 1054, Y = 717 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Arabia") { X = 1159, Y = 689 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Phoenicia") { X = 971, Y = 650 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Damascus") { X = 1028, Y = 652 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Palmyra") { X = 1084, Y = 655 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Babylonia") { X = 1190, Y = 616 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Elymais") { X = 1245, Y = 656 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Syria") { X = 1011, Y = 597 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Assyria") { X = 1085, Y = 557 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Media") { X = 1215, Y = 511 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Atropatene") { X = 1193, Y = 423 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Armenia") { X = 1088, Y = 469 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Colchis") { X = 1069, Y = 377 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Pontus") { X = 923, Y = 471 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Cappadocia") { X = 955, Y = 515 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Cillicia") { X = 934, Y = 564 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Bithynia") { X = 832, Y = 489 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Galatia") { X = 895, Y = 509 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Phrygia") { X = 787, Y = 551 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Ionia") { X = 799, Y = 577 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Lycia") { X = 842, Y = 606 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Tribus Alanni") { X = 1082, Y = 255 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Tribus Sakae") { X = 1238, Y = 242 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Hyperboria") { X = 904, Y = 87 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Tribus Sarmatae") { X = 888, Y = 197 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Maeotis") { X = 971, Y = 285 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Bosphorus") { X = 869, Y = 359 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Locus Gepidae") { X = 686, Y = 132 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Pripet") { X = 689, Y = 236 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Scythia") { X = 794, Y = 302 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Tribus Getae") { X = 743, Y = 374 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Thrace") { X = 728, Y = 461 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Propontis") { X = 755, Y = 496 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Macedonia") { X = 676, Y = 519 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Epirus") { X = 620, Y = 545 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Thessalia") { X = 670, Y = 545 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Paionia") { X = 670, Y = 472 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Aetolia") { X = 645, Y = 577 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Attica") { X = 708, Y = 589 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Corinth") { X = 668, Y = 603 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Laconia") { X = 694, Y = 630 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Dacia") { X = 694, Y = 340 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Tribus Iazyges") { X = 617, Y = 358 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Pannonia") { X = 536, Y = 346 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Illyria") { X = 599, Y = 449 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Dalmatia") { X = 574, Y = 485 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Venetia") { X = 445, Y = 391 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Mediolanium") { X = 384, Y = 399 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Liguria") { X = 386, Y = 428 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Etruria") { X = 437, Y = 453 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Umbria") { X = 488, Y = 466 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Roma") { X = 463, Y = 492 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Apullia") { X = 552, Y = 533 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Capua") { X = 500, Y = 524 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Bruttium") { X = 550, Y = 577 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Massilia") { X = 331, Y = 436 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Narbonensis") { X = 262, Y = 439 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Aquitania") { X = 227, Y = 390 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Gallaecia") { X = 87, Y = 432 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Celtiberia") { X = 138, Y = 487 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Taraconenis") { X = 208, Y = 479 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Lusitania") { X = 52, Y = 480 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Baetica") { X = 81, Y = 568 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Hispania") { X = 171, Y = 550 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Armorica") { X = 223, Y = 309 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Alesia") { X = 297, Y = 324 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Lugdinensis") { X = 321, Y = 381 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Noricum") { X = 453, Y = 349 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Belgica") { X = 318, Y = 248 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Germania Inferior") { X = 392, Y = 214 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Germania Superior") { X = 364, Y = 298 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Tribus Saxones") { X = 431, Y = 170 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Tribus Chattii") { X = 466, Y = 243 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Agre Decumates") { X = 426, Y = 270 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "Locus Gothi") { X = 554, Y = 167 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "Regnum Marcomannii") { X = 598, Y = 225 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "Boihaemum") { X = 537, Y = 286 };
mapTemplate.Countries.Add(country103);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country78);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country61);
continent2.Countries.Add(country79);
continent2.Countries.Add(country81);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country75);
continent3.Countries.Add(country76);
continent3.Countries.Add(country77);
continent3.Countries.Add(country82);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country15);
continent4.Countries.Add(country80);
continent4.Countries.Add(country16);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country89);
continent5.Countries.Add(country13);
continent5.Countries.Add(country12);
continent5.Countries.Add(country9);
continent5.Countries.Add(country10);
continent5.Countries.Add(country14);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country88);
continent6.Countries.Add(country90);
continent6.Countries.Add(country85);
continent6.Countries.Add(country87);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country74);
continent7.Countries.Add(country73);
continent7.Countries.Add(country86);
continent7.Countries.Add(country83);
continent7.Countries.Add(country84);
continent7.Countries.Add(country93);
continent7.Countries.Add(country92);
continent7.Countries.Add(country91);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country1);
continent8.Countries.Add(country2);
continent8.Countries.Add(country3);
continent8.Countries.Add(country4);
continent8.Countries.Add(country95);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 5);
continent9.Countries.Add(country94);
continent9.Countries.Add(country96);
continent9.Countries.Add(country97);
continent9.Countries.Add(country98);
continent9.Countries.Add(country99);
continent9.Countries.Add(country100);
continent9.Countries.Add(country101);
continent9.Countries.Add(country102);
continent9.Countries.Add(country103);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 1);
continent10.Countries.Add(country68);
continent10.Countries.Add(country69);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country60);
continent11.Countries.Add(country63);
continent11.Countries.Add(country62);
continent11.Countries.Add(country66);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 4);
continent12.Countries.Add(country17);
continent12.Countries.Add(country18);
continent12.Countries.Add(country20);
continent12.Countries.Add(country67);
continent12.Countries.Add(country45);
continent12.Countries.Add(country65);
continent12.Countries.Add(country64);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 2);
continent13.Countries.Add(country58);
continent13.Countries.Add(country57);
continent13.Countries.Add(country59);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 4);
continent14.Countries.Add(country56);
continent14.Countries.Add(country51);
continent14.Countries.Add(country52);
continent14.Countries.Add(country48);
continent14.Countries.Add(country50);
continent14.Countries.Add(country53);
continent14.Countries.Add(country54);
continent14.Countries.Add(country55);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 3);
continent15.Countries.Add(country40);
continent15.Countries.Add(country41);
continent15.Countries.Add(country43);
continent15.Countries.Add(country44);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 5);
continent16.Countries.Add(country22);
continent16.Countries.Add(country23);
continent16.Countries.Add(country24);
continent16.Countries.Add(country19);
continent16.Countries.Add(country25);
continent16.Countries.Add(country26);
continent16.Countries.Add(country29);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 5);
continent17.Countries.Add(country47);
continent17.Countries.Add(country46);
continent17.Countries.Add(country42);
continent17.Countries.Add(country34);
continent17.Countries.Add(country35);
continent17.Countries.Add(country30);
continent17.Countries.Add(country32);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 1);
continent18.Countries.Add(country38);
continent18.Countries.Add(country39);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 3);
continent19.Countries.Add(country33);
continent19.Countries.Add(country36);
continent19.Countries.Add(country37);
continent19.Countries.Add(country49);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 3);
continent20.Countries.Add(country5);
continent20.Countries.Add(country7);
continent20.Countries.Add(country8);
continent20.Countries.Add(country6);
continent20.Countries.Add(country11);
continent20.Countries.Add(country21);
mapTemplate.Continents.Add(continent20);
var continent21 = new Continent("21", 2);
continent21.Countries.Add(country27);
continent21.Countries.Add(country28);
continent21.Countries.Add(country31);
mapTemplate.Continents.Add(continent21);
var continent22 = new Continent("22", 2);
continent22.Countries.Add(country70);
continent22.Countries.Add(country71);
continent22.Countries.Add(country72);
mapTemplate.Continents.Add(continent22);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "91"));
mapTemplate.Connections.Add(new Connection("3", "95"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "89"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("9", "14"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "21"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "90"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "76"));
mapTemplate.Connections.Add(new Connection("14", "9"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "81"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "67"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "47"));
mapTemplate.Connections.Add(new Connection("19", "29"));
mapTemplate.Connections.Add(new Connection("19", "47"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "11"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "30"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "31"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "32"));
mapTemplate.Connections.Add(new Connection("28", "33"));
mapTemplate.Connections.Add(new Connection("29", "19"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "34"));
mapTemplate.Connections.Add(new Connection("30", "26"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("31", "27"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "35"));
mapTemplate.Connections.Add(new Connection("32", "28"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("33", "28"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "36"));
mapTemplate.Connections.Add(new Connection("34", "29"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "41"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("35", "31"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "41"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "33"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "48"));
mapTemplate.Connections.Add(new Connection("37", "49"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "48"));
mapTemplate.Connections.Add(new Connection("39", "52"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "43"));
mapTemplate.Connections.Add(new Connection("40", "44"));
mapTemplate.Connections.Add(new Connection("41", "34"));
mapTemplate.Connections.Add(new Connection("41", "35"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("42", "34"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "46"));
mapTemplate.Connections.Add(new Connection("42", "47"));
mapTemplate.Connections.Add(new Connection("43", "40"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "59"));
mapTemplate.Connections.Add(new Connection("44", "40"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "59"));
mapTemplate.Connections.Add(new Connection("46", "42"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "42"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "18"));
mapTemplate.Connections.Add(new Connection("47", "19"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("48", "51"));
mapTemplate.Connections.Add(new Connection("48", "52"));
mapTemplate.Connections.Add(new Connection("48", "37"));
mapTemplate.Connections.Add(new Connection("48", "39"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "37"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("51", "48"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("51", "55"));
mapTemplate.Connections.Add(new Connection("51", "56"));
mapTemplate.Connections.Add(new Connection("52", "39"));
mapTemplate.Connections.Add(new Connection("52", "48"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "56"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("54", "50"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "101"));
mapTemplate.Connections.Add(new Connection("55", "51"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "69"));
mapTemplate.Connections.Add(new Connection("55", "101"));
mapTemplate.Connections.Add(new Connection("55", "102"));
mapTemplate.Connections.Add(new Connection("56", "52"));
mapTemplate.Connections.Add(new Connection("56", "51"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "68"));
mapTemplate.Connections.Add(new Connection("56", "69"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "68"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "60"));
mapTemplate.Connections.Add(new Connection("58", "63"));
mapTemplate.Connections.Add(new Connection("58", "68"));
mapTemplate.Connections.Add(new Connection("59", "43"));
mapTemplate.Connections.Add(new Connection("59", "45"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "58"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("60", "62"));
mapTemplate.Connections.Add(new Connection("60", "63"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("61", "64"));
mapTemplate.Connections.Add(new Connection("61", "71"));
mapTemplate.Connections.Add(new Connection("61", "72"));
mapTemplate.Connections.Add(new Connection("61", "79"));
mapTemplate.Connections.Add(new Connection("62", "60"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "64"));
mapTemplate.Connections.Add(new Connection("62", "65"));
mapTemplate.Connections.Add(new Connection("63", "58"));
mapTemplate.Connections.Add(new Connection("63", "60"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "68"));
mapTemplate.Connections.Add(new Connection("63", "71"));
mapTemplate.Connections.Add(new Connection("64", "61"));
mapTemplate.Connections.Add(new Connection("64", "62"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("65", "62"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("67", "17"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("68", "56"));
mapTemplate.Connections.Add(new Connection("68", "57"));
mapTemplate.Connections.Add(new Connection("68", "58"));
mapTemplate.Connections.Add(new Connection("68", "63"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("68", "71"));
mapTemplate.Connections.Add(new Connection("69", "55"));
mapTemplate.Connections.Add(new Connection("69", "56"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "71"));
mapTemplate.Connections.Add(new Connection("69", "102"));
mapTemplate.Connections.Add(new Connection("69", "103"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "73"));
mapTemplate.Connections.Add(new Connection("70", "94"));
mapTemplate.Connections.Add(new Connection("70", "103"));
mapTemplate.Connections.Add(new Connection("71", "61"));
mapTemplate.Connections.Add(new Connection("71", "63"));
mapTemplate.Connections.Add(new Connection("71", "68"));
mapTemplate.Connections.Add(new Connection("71", "69"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "73"));
mapTemplate.Connections.Add(new Connection("72", "61"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("73", "70"));
mapTemplate.Connections.Add(new Connection("73", "71"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("73", "76"));
mapTemplate.Connections.Add(new Connection("73", "77"));
mapTemplate.Connections.Add(new Connection("73", "94"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("74", "82"));
mapTemplate.Connections.Add(new Connection("74", "93"));
mapTemplate.Connections.Add(new Connection("74", "94"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("75", "82"));
mapTemplate.Connections.Add(new Connection("76", "13"));
mapTemplate.Connections.Add(new Connection("76", "73"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "78"));
mapTemplate.Connections.Add(new Connection("77", "73"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("77", "79"));
mapTemplate.Connections.Add(new Connection("77", "80"));
mapTemplate.Connections.Add(new Connection("78", "76"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "80"));
mapTemplate.Connections.Add(new Connection("79", "61"));
mapTemplate.Connections.Add(new Connection("79", "77"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("79", "81"));
mapTemplate.Connections.Add(new Connection("80", "77"));
mapTemplate.Connections.Add(new Connection("80", "78"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("81", "79"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("81", "16"));
mapTemplate.Connections.Add(new Connection("82", "74"));
mapTemplate.Connections.Add(new Connection("82", "75"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "93"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "87"));
mapTemplate.Connections.Add(new Connection("83", "93"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("84", "86"));
mapTemplate.Connections.Add(new Connection("84", "87"));
mapTemplate.Connections.Add(new Connection("84", "91"));
mapTemplate.Connections.Add(new Connection("84", "92"));
mapTemplate.Connections.Add(new Connection("84", "93"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("85", "88"));
mapTemplate.Connections.Add(new Connection("86", "84"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("86", "89"));
mapTemplate.Connections.Add(new Connection("86", "90"));
mapTemplate.Connections.Add(new Connection("87", "83"));
mapTemplate.Connections.Add(new Connection("87", "84"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "90"));
mapTemplate.Connections.Add(new Connection("88", "85"));
mapTemplate.Connections.Add(new Connection("88", "86"));
mapTemplate.Connections.Add(new Connection("88", "89"));
mapTemplate.Connections.Add(new Connection("89", "86"));
mapTemplate.Connections.Add(new Connection("89", "88"));
mapTemplate.Connections.Add(new Connection("89", "90"));
mapTemplate.Connections.Add(new Connection("89", "5"));
mapTemplate.Connections.Add(new Connection("90", "86"));
mapTemplate.Connections.Add(new Connection("90", "87"));
mapTemplate.Connections.Add(new Connection("90", "89"));
mapTemplate.Connections.Add(new Connection("90", "12"));
mapTemplate.Connections.Add(new Connection("91", "3"));
mapTemplate.Connections.Add(new Connection("91", "84"));
mapTemplate.Connections.Add(new Connection("91", "92"));
mapTemplate.Connections.Add(new Connection("91", "95"));
mapTemplate.Connections.Add(new Connection("92", "84"));
mapTemplate.Connections.Add(new Connection("92", "91"));
mapTemplate.Connections.Add(new Connection("92", "93"));
mapTemplate.Connections.Add(new Connection("92", "95"));
mapTemplate.Connections.Add(new Connection("92", "97"));
mapTemplate.Connections.Add(new Connection("93", "74"));
mapTemplate.Connections.Add(new Connection("93", "82"));
mapTemplate.Connections.Add(new Connection("93", "83"));
mapTemplate.Connections.Add(new Connection("93", "84"));
mapTemplate.Connections.Add(new Connection("93", "92"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "97"));
mapTemplate.Connections.Add(new Connection("94", "70"));
mapTemplate.Connections.Add(new Connection("94", "73"));
mapTemplate.Connections.Add(new Connection("94", "74"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("94", "97"));
mapTemplate.Connections.Add(new Connection("94", "100"));
mapTemplate.Connections.Add(new Connection("94", "103"));
mapTemplate.Connections.Add(new Connection("95", "3"));
mapTemplate.Connections.Add(new Connection("95", "91"));
mapTemplate.Connections.Add(new Connection("95", "92"));
mapTemplate.Connections.Add(new Connection("95", "96"));
mapTemplate.Connections.Add(new Connection("95", "97"));
mapTemplate.Connections.Add(new Connection("96", "95"));
mapTemplate.Connections.Add(new Connection("96", "97"));
mapTemplate.Connections.Add(new Connection("96", "98"));
mapTemplate.Connections.Add(new Connection("96", "99"));
mapTemplate.Connections.Add(new Connection("96", "100"));
mapTemplate.Connections.Add(new Connection("97", "92"));
mapTemplate.Connections.Add(new Connection("97", "93"));
mapTemplate.Connections.Add(new Connection("97", "94"));
mapTemplate.Connections.Add(new Connection("97", "95"));
mapTemplate.Connections.Add(new Connection("97", "96"));
mapTemplate.Connections.Add(new Connection("97", "100"));
mapTemplate.Connections.Add(new Connection("98", "96"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("98", "101"));
mapTemplate.Connections.Add(new Connection("99", "96"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("99", "100"));
mapTemplate.Connections.Add(new Connection("99", "101"));
mapTemplate.Connections.Add(new Connection("99", "102"));
mapTemplate.Connections.Add(new Connection("99", "103"));
mapTemplate.Connections.Add(new Connection("100", "94"));
mapTemplate.Connections.Add(new Connection("100", "96"));
mapTemplate.Connections.Add(new Connection("100", "97"));
mapTemplate.Connections.Add(new Connection("100", "99"));
mapTemplate.Connections.Add(new Connection("100", "102"));
mapTemplate.Connections.Add(new Connection("100", "103"));
mapTemplate.Connections.Add(new Connection("101", "54"));
mapTemplate.Connections.Add(new Connection("101", "55"));
mapTemplate.Connections.Add(new Connection("101", "98"));
mapTemplate.Connections.Add(new Connection("101", "99"));
mapTemplate.Connections.Add(new Connection("101", "102"));
mapTemplate.Connections.Add(new Connection("102", "55"));
mapTemplate.Connections.Add(new Connection("102", "69"));
mapTemplate.Connections.Add(new Connection("102", "99"));
mapTemplate.Connections.Add(new Connection("102", "100"));
mapTemplate.Connections.Add(new Connection("102", "101"));
mapTemplate.Connections.Add(new Connection("102", "103"));
mapTemplate.Connections.Add(new Connection("103", "69"));
mapTemplate.Connections.Add(new Connection("103", "70"));
mapTemplate.Connections.Add(new Connection("103", "94"));
mapTemplate.Connections.Add(new Connection("103", "99"));
mapTemplate.Connections.Add(new Connection("103", "100"));
mapTemplate.Connections.Add(new Connection("103", "102"));

            return mapTemplate;
		}
    }
}

