
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Hamburg()
        {

var mapTemplate = new MapTemplate("Hamburg") { Image = "hamburg.jpg" };
var country1 = new CountryTemplate("1", "Ohlstedt") { X = 464, Y = 82 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Poppenbuettel") { X = 406, Y = 144 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Volksdorf") { X = 503, Y = 124 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Rahlstedt") { X = 532, Y = 205 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Farmsen") { X = 475, Y = 193 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Fuhlsbuettel") { X = 374, Y = 220 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Niendorf") { X = 311, Y = 187 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Lokstedt") { X = 306, Y = 278 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "StPauli") { X = 338, Y = 293 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Eppendorf") { X = 365, Y = 280 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Winterhude") { X = 414, Y = 263 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Uhlenhorst") { X = 403, Y = 309 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Hamm") { X = 447, Y = 297 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "StGeorg") { X = 369, Y = 348 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Wandsbek") { X = 484, Y = 294 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Billstedt") { X = 501, Y = 344 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Moorfleet") { X = 438, Y = 404 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Bergedorf") { X = 577, Y = 464 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Neuengamme") { X = 528, Y = 520 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Ochsenwerder") { X = 432, Y = 461 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Veddel") { X = 332, Y = 379 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Wilhelmsburg") { X = 337, Y = 432 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Roenneburg") { X = 388, Y = 519 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Harburg") { X = 310, Y = 512 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Altenwerder") { X = 280, Y = 390 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Neugraben") { X = 233, Y = 489 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Finkenwerder") { X = 201, Y = 409 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Suelldorf") { X = 166, Y = 230 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Rissen") { X = 130, Y = 284 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Blankenese") { X = 221, Y = 284 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Lurup") { X = 263, Y = 270 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Ottensen") { X = 303, Y = 332 };
mapTemplate.Countries.Add(country32);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country3);
continent1.Countries.Add(country2);
continent1.Countries.Add(country6);
continent1.Countries.Add(country5);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country28);
continent2.Countries.Add(country29);
continent2.Countries.Add(country30);
continent2.Countries.Add(country31);
continent2.Countries.Add(country32);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 4);
continent3.Countries.Add(country11);
continent3.Countries.Add(country13);
continent3.Countries.Add(country12);
continent3.Countries.Add(country14);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country9);
continent4.Countries.Add(country10);
continent4.Countries.Add(country8);
continent4.Countries.Add(country7);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 5);
continent5.Countries.Add(country15);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country20);
continent5.Countries.Add(country19);
continent5.Countries.Add(country18);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 3);
continent7.Countries.Add(country27);
continent7.Countries.Add(country25);
continent7.Countries.Add(country26);
continent7.Countries.Add(country24);
continent7.Countries.Add(country23);
mapTemplate.Continents.Add(continent7);
mapTemplate.Connections.Add(new Connection("15", "5"));
mapTemplate.Connections.Add(new Connection("15", "4"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "32"));
mapTemplate.Connections.Add(new Connection("8", "31"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "8"));
mapTemplate.Connections.Add(new Connection("31", "7"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "31"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("32", "25"));
mapTemplate.Connections.Add(new Connection("32", "21"));
mapTemplate.Connections.Add(new Connection("32", "14"));
mapTemplate.Connections.Add(new Connection("32", "9"));
mapTemplate.Connections.Add(new Connection("32", "8"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "32"));
mapTemplate.Connections.Add(new Connection("9", "14"));
mapTemplate.Connections.Add(new Connection("21", "32"));
mapTemplate.Connections.Add(new Connection("21", "14"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "25"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "2"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("14", "21"));
mapTemplate.Connections.Add(new Connection("14", "32"));
mapTemplate.Connections.Add(new Connection("14", "9"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "15"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "21"));
mapTemplate.Connections.Add(new Connection("25", "32"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("5", "11"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "15"));

            return mapTemplate;
		}
    }
}

