
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate FreistaatSachsen()
        {

var mapTemplate = new MapTemplate("FreistaatSachsen") { Image = "Sachsen.gif" };
var country1 = new CountryTemplate("1", "Niesky") { X = 643, Y = 120 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Zittau") { X = 624, Y = 222 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Bautzen") { X = 547, Y = 162 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Kamenz") { X = 473, Y = 122 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Görlitz") { X = 683, Y = 184 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Hoyerswerda") { X = 517, Y = 82 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Pirna") { X = 476, Y = 246 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Dippoldiswalde") { X = 386, Y = 264 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Freiberg") { X = 311, Y = 266 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Dresden") { X = 409, Y = 212 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Meissen") { X = 336, Y = 175 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Grossenhain") { X = 350, Y = 116 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Torgau") { X = 256, Y = 80 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Delitzsch") { X = 142, Y = 61 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Grimma") { X = 187, Y = 127 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Döbeln") { X = 259, Y = 178 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Borna") { X = 116, Y = 170 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Mittweida") { X = 216, Y = 226 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Leipzig") { X = 109, Y = 116 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Marienberg") { X = 279, Y = 328 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Annaberg-Buchholz") { X = 235, Y = 372 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Aue") { X = 179, Y = 386 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Stollberg") { X = 201, Y = 337 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Plauen") { X = 81, Y = 423 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Stadt Plauen") { X = 50, Y = 398 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Zwickau") { X = 131, Y = 326 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Werdau") { X = 92, Y = 323 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Glauchau") { X = 167, Y = 297 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Chemnitz") { X = 219, Y = 288 };
mapTemplate.Countries.Add(country29);
var continent1 = new Continent("1", 5);
continent1.Countries.Add(country20);
continent1.Countries.Add(country21);
continent1.Countries.Add(country22);
continent1.Countries.Add(country23);
continent1.Countries.Add(country24);
continent1.Countries.Add(country27);
continent1.Countries.Add(country28);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
continent2.Countries.Add(country18);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country1);
continent3.Countries.Add(country2);
continent3.Countries.Add(country3);
continent3.Countries.Add(country4);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country7);
continent4.Countries.Add(country8);
continent4.Countries.Add(country9);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country5);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 1);
continent6.Countries.Add(country6);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 1);
continent7.Countries.Add(country10);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country19);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country29);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 1);
continent10.Countries.Add(country26);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 1);
continent11.Countries.Add(country25);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "5"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "11"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "11"));
mapTemplate.Connections.Add(new Connection("4", "12"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("5", "1"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("9", "20"));
mapTemplate.Connections.Add(new Connection("9", "29"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "4"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("11", "3"));
mapTemplate.Connections.Add(new Connection("12", "4"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "29"));
mapTemplate.Connections.Add(new Connection("18", "28"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("20", "9"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "27"));
mapTemplate.Connections.Add(new Connection("23", "29"));
mapTemplate.Connections.Add(new Connection("23", "28"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "22"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("28", "18"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "23"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("29", "9"));
mapTemplate.Connections.Add(new Connection("29", "18"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "23"));

            return mapTemplate;
		}
    }
}

