
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate gta()
        {

var mapTemplate = new MapTemplate("gta") { Image = "gta.jpg" };
var country1 = new CountryTemplate("1", "Westdyke") { X = 489, Y = 245 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Leftwood") { X = 480, Y = 396 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Alderney City") { X = 479, Y = 553 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Berchem") { X = 282, Y = 640 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Acter") { X = 276, Y = 766 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Normandy") { X = 463, Y = 718 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Tudor") { X = 236, Y = 909 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Port Tudor") { X = 453, Y = 976 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Acter Industrial Park") { X = 265, Y = 1123 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Alderney State Correctional Facility") { X = 531, Y = 1069 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Boulevard") { X = 1221, Y = 116 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Fortside") { X = 1168, Y = 235 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Industrial") { X = 1393, Y = 209 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "South Bohan") { X = 1184, Y = 363 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Chase Point") { X = 1287, Y = 356 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Northern Gardens") { X = 1429, Y = 138 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Little Bay") { X = 1547, Y = 196 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Northwood") { X = 846, Y = 263 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "North Holland") { X = 779, Y = 380 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "East Holland") { X = 928, Y = 380 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Middle Park") { X = 881, Y = 566 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Varsity Heights") { X = 758, Y = 499 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Lancaster") { X = 997, Y = 490 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Middle Park West") { X = 759, Y = 624 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Middle Park East") { X = 999, Y = 626 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Purgatory") { X = 758, Y = 748 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Star Junction") { X = 882, Y = 811 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Hatton Gardens") { X = 1007, Y = 770 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Westminster") { X = 760, Y = 867 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Easton") { X = 985, Y = 926 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Suffolk") { X = 889, Y = 983 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "The Meat Quarter") { X = 795, Y = 929 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "The Triangle") { X = 919, Y = 915 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Lower Easton") { X = 1008, Y = 1019 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Little Italy") { X = 893, Y = 1023 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "City Hall") { X = 890, Y = 1115 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Castle Garden City") { X = 811, Y = 1074 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "The Exchange") { X = 941, Y = 1201 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Castle Gardens") { X = 1042, Y = 1227 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Chinatown") { X = 993, Y = 1092 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Fishmarket North") { X = 1101, Y = 1007 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Fishmarket South") { X = 1139, Y = 1120 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Happiness Island") { X = 714, Y = 1225 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Colony Island") { X = 1172, Y = 785 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Presidents City") { X = 1054, Y = 895 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Lancet") { X = 1047, Y = 823 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Charge Island") { X = 1212, Y = 593 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Steinway") { X = 1435, Y = 577 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "East Island City") { X = 1490, Y = 667 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Meadows Park") { X = 1670, Y = 561 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Francis International Airport") { X = 1937, Y = 774 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Meadow Hills") { X = 1658, Y = 639 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Willis") { X = 1707, Y = 639 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Cerveza Heights") { X = 1564, Y = 771 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "BOABO") { X = 1376, Y = 782 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Rotterdam Hill") { X = 1394, Y = 877 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Downtown") { X = 1467, Y = 876 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Schottler") { X = 1535, Y = 878 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Beechwood City") { X = 1616, Y = 873 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "East Hook") { X = 1376, Y = 977 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Outlook") { X = 1443, Y = 1015 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "South Slopes") { X = 1525, Y = 998 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Firefly Projects") { X = 1546, Y = 1120 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Hove Beach") { X = 1442, Y = 1118 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Firefly Island") { X = 1313, Y = 1228 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Beachgate") { X = 1526, Y = 1185 };
mapTemplate.Countries.Add(country66);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
continent1.Countries.Add(country10);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 6);
continent3.Countries.Add(country26);
continent3.Countries.Add(country27);
continent3.Countries.Add(country28);
continent3.Countries.Add(country29);
continent3.Countries.Add(country30);
continent3.Countries.Add(country32);
continent3.Countries.Add(country33);
continent3.Countries.Add(country44);
continent3.Countries.Add(country45);
continent3.Countries.Add(country46);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 5);
continent4.Countries.Add(country47);
continent4.Countries.Add(country48);
continent4.Countries.Add(country49);
continent4.Countries.Add(country50);
continent4.Countries.Add(country51);
continent4.Countries.Add(country52);
continent4.Countries.Add(country53);
continent4.Countries.Add(country54);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 6);
continent5.Countries.Add(country55);
continent5.Countries.Add(country56);
continent5.Countries.Add(country57);
continent5.Countries.Add(country58);
continent5.Countries.Add(country59);
continent5.Countries.Add(country60);
continent5.Countries.Add(country61);
continent5.Countries.Add(country62);
continent5.Countries.Add(country63);
continent5.Countries.Add(country64);
continent5.Countries.Add(country65);
continent5.Countries.Add(country66);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 5);
continent6.Countries.Add(country18);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
continent6.Countries.Add(country25);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country31);
continent7.Countries.Add(country34);
continent7.Countries.Add(country35);
continent7.Countries.Add(country36);
continent7.Countries.Add(country37);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
continent7.Countries.Add(country41);
continent7.Countries.Add(country42);
continent7.Countries.Add(country43);
mapTemplate.Continents.Add(continent7);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "19"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "26"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "17"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "48"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "23"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("17", "13"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "2"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "27"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("21", "25"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "14"));
mapTemplate.Connections.Add(new Connection("23", "47"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("25", "21"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "3"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("27", "33"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "46"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "21"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "46"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "45"));
mapTemplate.Connections.Add(new Connection("30", "46"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("31", "37"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "35"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("32", "37"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "29"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "27"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("34", "40"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "45"));
mapTemplate.Connections.Add(new Connection("34", "41"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "31"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "40"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("37", "43"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "31"));
mapTemplate.Connections.Add(new Connection("37", "32"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "42"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "34"));
mapTemplate.Connections.Add(new Connection("40", "36"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "34"));
mapTemplate.Connections.Add(new Connection("41", "45"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("42", "38"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "34"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "64"));
mapTemplate.Connections.Add(new Connection("43", "37"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "34"));
mapTemplate.Connections.Add(new Connection("45", "41"));
mapTemplate.Connections.Add(new Connection("45", "30"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "30"));
mapTemplate.Connections.Add(new Connection("46", "27"));
mapTemplate.Connections.Add(new Connection("46", "28"));
mapTemplate.Connections.Add(new Connection("46", "55"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("47", "23"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("48", "13"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "54"));
mapTemplate.Connections.Add(new Connection("49", "55"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "52"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "59"));
mapTemplate.Connections.Add(new Connection("52", "50"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "59"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "59"));
mapTemplate.Connections.Add(new Connection("54", "49"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "50"));
mapTemplate.Connections.Add(new Connection("54", "57"));
mapTemplate.Connections.Add(new Connection("54", "58"));
mapTemplate.Connections.Add(new Connection("54", "59"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "46"));
mapTemplate.Connections.Add(new Connection("55", "49"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "60"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "60"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "61"));
mapTemplate.Connections.Add(new Connection("57", "54"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "61"));
mapTemplate.Connections.Add(new Connection("58", "54"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "62"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("59", "54"));
mapTemplate.Connections.Add(new Connection("59", "52"));
mapTemplate.Connections.Add(new Connection("59", "53"));
mapTemplate.Connections.Add(new Connection("59", "51"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("60", "56"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("60", "64"));
mapTemplate.Connections.Add(new Connection("60", "55"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "57"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "56"));
mapTemplate.Connections.Add(new Connection("61", "64"));
mapTemplate.Connections.Add(new Connection("62", "58"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("62", "64"));
mapTemplate.Connections.Add(new Connection("63", "66"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("64", "42"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "61"));
mapTemplate.Connections.Add(new Connection("64", "60"));
mapTemplate.Connections.Add(new Connection("64", "62"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "63"));

            return mapTemplate;
		}
    }
}

