
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate braveNewWorld()
        {

var mapTemplate = new MapTemplate("braveNewWorld") { Image = "bravenewworld.jpg" };
var country1 = new CountryTemplate("1", "Alaska") { X = 35, Y = 150 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Nordwest-Territorium") { X = 116, Y = 152 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Groenland") { X = 324, Y = 103 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Quebec") { X = 241, Y = 224 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Ontario") { X = 178, Y = 220 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Alberta") { X = 118, Y = 208 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Weststaaten") { X = 125, Y = 274 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Oststaaten") { X = 185, Y = 283 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Mittel-Amerika") { X = 148, Y = 347 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Venezuela") { X = 224, Y = 374 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Brasilien") { X = 296, Y = 445 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Peru") { X = 228, Y = 452 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Argentinien") { X = 221, Y = 522 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Nordwest-Afrika") { X = 420, Y = 406 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Aegypten") { X = 495, Y = 372 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Ost-Afrika") { X = 534, Y = 436 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Kongo") { X = 487, Y = 472 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Sued-Afrika") { X = 493, Y = 530 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Madagaskar") { X = 581, Y = 545 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "West-Europa") { X = 406, Y = 315 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Sued-Europa") { X = 482, Y = 306 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Mittel-Europa") { X = 464, Y = 264 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Gross-Britannien") { X = 395, Y = 253 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Island") { X = 361, Y = 205 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Skandinavien") { X = 473, Y = 192 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Ukraine") { X = 548, Y = 233 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Mittlerer-Osten") { X = 548, Y = 364 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Afghanistan") { X = 622, Y = 301 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Ural") { X = 642, Y = 213 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Sibirien") { X = 708, Y = 165 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Jakutien") { X = 796, Y = 156 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Kamtschatka") { X = 876, Y = 195 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Irkutsk") { X = 756, Y = 242 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Mongolei") { X = 791, Y = 300 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Japan") { X = 869, Y = 334 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "China") { X = 743, Y = 358 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Indien") { X = 664, Y = 386 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Siam") { X = 735, Y = 411 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Indonesien") { X = 753, Y = 495 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Neu-Guinea") { X = 884, Y = 499 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Ost-Australien") { X = 873, Y = 580 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "West-Australien") { X = 793, Y = 565 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Hawaii") { X = 49, Y = 306 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Nunavut") { X = 177, Y = 36 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Svalbard") { X = 497, Y = 90 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Falkland-Inseln") { X = 309, Y = 612 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Philippinen") { X = 857, Y = 425 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Neuseeland") { X = 946, Y = 621 };
mapTemplate.Countries.Add(country48);
var continent1 = new Continent("1", 6);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
continent1.Countries.Add(country43);
continent1.Countries.Add(country44);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country46);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
continent3.Countries.Add(country19);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 5);
continent4.Countries.Add(country24);
continent4.Countries.Add(country23);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country26);
continent4.Countries.Add(country25);
continent4.Countries.Add(country45);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 7);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
continent5.Countries.Add(country34);
continent5.Countries.Add(country36);
continent5.Countries.Add(country37);
continent5.Countries.Add(country38);
continent5.Countries.Add(country35);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country39);
continent6.Countries.Add(country40);
continent6.Countries.Add(country41);
continent6.Countries.Add(country42);
continent6.Countries.Add(country47);
continent6.Countries.Add(country48);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "6"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "32"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "44"));
mapTemplate.Connections.Add(new Connection("3", "24"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "44"));
mapTemplate.Connections.Add(new Connection("3", "45"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("4", "44"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "44"));
mapTemplate.Connections.Add(new Connection("6", "1"));
mapTemplate.Connections.Add(new Connection("6", "2"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "43"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "46"));
mapTemplate.Connections.Add(new Connection("13", "48"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "21"));
mapTemplate.Connections.Add(new Connection("14", "20"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "21"));
mapTemplate.Connections.Add(new Connection("15", "27"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "27"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "46"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "14"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "26"));
mapTemplate.Connections.Add(new Connection("21", "27"));
mapTemplate.Connections.Add(new Connection("21", "15"));
mapTemplate.Connections.Add(new Connection("21", "14"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("24", "3"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "45"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "21"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("27", "37"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "21"));
mapTemplate.Connections.Add(new Connection("27", "15"));
mapTemplate.Connections.Add(new Connection("27", "16"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "36"));
mapTemplate.Connections.Add(new Connection("28", "37"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "36"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "36"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "1"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "47"));
mapTemplate.Connections.Add(new Connection("35", "43"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "28"));
mapTemplate.Connections.Add(new Connection("36", "29"));
mapTemplate.Connections.Add(new Connection("36", "30"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "28"));
mapTemplate.Connections.Add(new Connection("37", "27"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "47"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "48"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("43", "7"));
mapTemplate.Connections.Add(new Connection("43", "35"));
mapTemplate.Connections.Add(new Connection("44", "2"));
mapTemplate.Connections.Add(new Connection("44", "5"));
mapTemplate.Connections.Add(new Connection("44", "4"));
mapTemplate.Connections.Add(new Connection("44", "3"));
mapTemplate.Connections.Add(new Connection("45", "3"));
mapTemplate.Connections.Add(new Connection("45", "25"));
mapTemplate.Connections.Add(new Connection("46", "13"));
mapTemplate.Connections.Add(new Connection("46", "18"));
mapTemplate.Connections.Add(new Connection("47", "35"));
mapTemplate.Connections.Add(new Connection("47", "39"));
mapTemplate.Connections.Add(new Connection("48", "41"));
mapTemplate.Connections.Add(new Connection("48", "13"));

            return mapTemplate;
		}
    }
}

