using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Asien()
        {
            var mapTemplate = new MapTemplate("Asien") { Image = "asien.jpg" };
            var country1 = new CountryTemplate("1", "Russland") { X = 335, Y = 113 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Georgien") { X = 141, Y = 278 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Armenien") { X = 141, Y = 312 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Aserbaidschan") { X = 180, Y = 312 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Tuerkei") { X = 78, Y = 308 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Syrien") { X = 114, Y = 348 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Jordanien") { X = 110, Y = 386 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Israel") { X = 82, Y = 363 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Irak") { X = 149, Y = 356 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Iran") { X = 235, Y = 365 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Afghanistan") { X = 306, Y = 350 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Pakistan") { X = 325, Y = 396 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Kuwait") { X = 170, Y = 393 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Saudi Arabien") { X = 157, Y = 431 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "VAE") { X = 229, Y = 430 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Oman") { X = 263, Y = 477 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Jemen") { X = 194, Y = 517 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Indien") { X = 409, Y = 452 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Malediven") { X = 391, Y = 602 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Sri Lanka") { X = 441, Y = 561 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Bangladesch") { X = 491, Y = 458 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Nepal") { X = 423, Y = 409 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Bhutan") { X = 486, Y = 400 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Turkmenistan") { X = 239, Y = 303 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Usbekistan") { X = 282, Y = 295 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Kasachstan") { X = 303, Y = 233 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Kirgistan") { X = 352, Y = 297 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Tadschikistan") { X = 333, Y = 326 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Mongolei") { X = 516, Y = 245 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "China") { X = 531, Y = 345 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Hong Kong") { X = 661, Y = 438 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Taiwan") { X = 715, Y = 447 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Nord-Korea") { X = 715, Y = 303 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Sued-Korea") { X = 727, Y = 338 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Japan") { X = 803, Y = 341 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Philippinen") { X = 720, Y = 537 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Malaysia") { X = 592, Y = 594 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Indonesien") { X = 667, Y = 655 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Neu Guinea") { X = 849, Y = 675 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Papua Neu Guinea") { X = 880, Y = 683 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Burma") { X = 531, Y = 441 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Thailand") { X = 572, Y = 507 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Kambodscha") { X = 599, Y = 538 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Laos") { X = 578, Y = 460 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Vietnam") { X = 638, Y = 517 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Weissrussland") { X = 49, Y = 179 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Ukraine") { X = 53, Y = 230 };
            mapTemplate.Countries.Add(country47);
            var continent1 = new Continent("1", 1);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country46);
            continent1.Countries.Add(country47);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 2);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country8);
            continent2.Countries.Add(country7);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 2);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country15);
            continent3.Countries.Add(country16);
            continent3.Countries.Add(country17);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country9);
            continent4.Countries.Add(country10);
            continent4.Countries.Add(country11);
            continent4.Countries.Add(country12);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 5);
            continent5.Countries.Add(country3);
            continent5.Countries.Add(country2);
            continent5.Countries.Add(country4);
            continent5.Countries.Add(country24);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            continent5.Countries.Add(country28);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country29);
            continent6.Countries.Add(country30);
            continent6.Countries.Add(country31);
            continent6.Countries.Add(country32);
            continent6.Countries.Add(country33);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 1);
            continent7.Countries.Add(country34);
            continent7.Countries.Add(country35);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country19);
            continent8.Countries.Add(country20);
            continent8.Countries.Add(country18);
            continent8.Countries.Add(country22);
            continent8.Countries.Add(country23);
            continent8.Countries.Add(country21);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 3);
            continent9.Countries.Add(country41);
            continent9.Countries.Add(country44);
            continent9.Countries.Add(country42);
            continent9.Countries.Add(country43);
            continent9.Countries.Add(country45);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country40);
            continent10.Countries.Add(country39);
            continent10.Countries.Add(country36);
            continent10.Countries.Add(country38);
            continent10.Countries.Add(country37);
            mapTemplate.Continents.Add(continent10);
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("30", "12"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("30", "26"));
            mapTemplate.Connections.Add(new Connection("30", "1"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "45"));
            mapTemplate.Connections.Add(new Connection("30", "44"));
            mapTemplate.Connections.Add(new Connection("30", "41"));
            mapTemplate.Connections.Add(new Connection("30", "18"));
            mapTemplate.Connections.Add(new Connection("30", "23"));
            mapTemplate.Connections.Add(new Connection("30", "22"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("23", "18"));
            mapTemplate.Connections.Add(new Connection("23", "30"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "45"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "14"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("35", "1"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "14"));
            mapTemplate.Connections.Add(new Connection("22", "18"));
            mapTemplate.Connections.Add(new Connection("22", "30"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "36"));
            mapTemplate.Connections.Add(new Connection("41", "21"));
            mapTemplate.Connections.Add(new Connection("41", "18"));
            mapTemplate.Connections.Add(new Connection("41", "30"));
            mapTemplate.Connections.Add(new Connection("41", "44"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("9", "14"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "6"));
            mapTemplate.Connections.Add(new Connection("9", "5"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "1"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("21", "18"));
            mapTemplate.Connections.Add(new Connection("21", "41"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "9"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("1", "46"));
            mapTemplate.Connections.Add(new Connection("1", "47"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("1", "26"));
            mapTemplate.Connections.Add(new Connection("1", "30"));
            mapTemplate.Connections.Add(new Connection("1", "29"));
            mapTemplate.Connections.Add(new Connection("1", "33"));
            mapTemplate.Connections.Add(new Connection("1", "35"));
            mapTemplate.Connections.Add(new Connection("29", "1"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("14", "7"));
            mapTemplate.Connections.Add(new Connection("14", "9"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "16"));
            mapTemplate.Connections.Add(new Connection("14", "17"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "44"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "37"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "11"));
            mapTemplate.Connections.Add(new Connection("24", "10"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "1"));
            mapTemplate.Connections.Add(new Connection("4", "10"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("36", "32"));
            mapTemplate.Connections.Add(new Connection("36", "39"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("26", "1"));
            mapTemplate.Connections.Add(new Connection("26", "30"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "24"));
            mapTemplate.Connections.Add(new Connection("11", "25"));
            mapTemplate.Connections.Add(new Connection("11", "28"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "12"));
            mapTemplate.Connections.Add(new Connection("18", "30"));
            mapTemplate.Connections.Add(new Connection("18", "22"));
            mapTemplate.Connections.Add(new Connection("18", "23"));
            mapTemplate.Connections.Add(new Connection("18", "21"));
            mapTemplate.Connections.Add(new Connection("18", "41"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "10"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "36"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "28"));
            mapTemplate.Connections.Add(new Connection("12", "30"));
            mapTemplate.Connections.Add(new Connection("12", "18"));
            mapTemplate.Connections.Add(new Connection("44", "30"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "42"));
            mapTemplate.Connections.Add(new Connection("44", "41"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "25"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("45", "30"));
            mapTemplate.Connections.Add(new Connection("45", "43"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "14"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("13", "9"));
            mapTemplate.Connections.Add(new Connection("13", "10"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "12"));
            mapTemplate.Connections.Add(new Connection("28", "11"));
            mapTemplate.Connections.Add(new Connection("28", "25"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "1"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("37", "42"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("25", "11"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "27"));
            mapTemplate.Connections.Add(new Connection("25", "28"));
            mapTemplate.Connections.Add(new Connection("10", "3"));
            mapTemplate.Connections.Add(new Connection("10", "4"));
            mapTemplate.Connections.Add(new Connection("10", "24"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("10", "13"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "5"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "10"));
            mapTemplate.Connections.Add(new Connection("5", "9"));
            mapTemplate.Connections.Add(new Connection("5", "6"));

            return mapTemplate;
        }
    }
}
