
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Maedin()
        {

var mapTemplate = new MapTemplate("Maedin") { Image = "maedin.png" };
var country1 = new CountryTemplate("1", "A1") { X = 77, Y = 535 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "A2") { X = 126, Y = 585 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "A3") { X = 77, Y = 634 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "A4") { X = 27, Y = 585 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "B1") { X = 77, Y = 32 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "B2") { X = 125, Y = 81 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "B3") { X = 76, Y = 130 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "B4") { X = 27, Y = 81 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "C1") { X = 581, Y = 31 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "C2") { X = 630, Y = 80 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "C3") { X = 582, Y = 131 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "C4") { X = 532, Y = 80 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "D1") { X = 582, Y = 536 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "D2") { X = 631, Y = 585 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "D3") { X = 581, Y = 635 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "D4") { X = 532, Y = 585 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "S1") { X = 273, Y = 614 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "S2") { X = 216, Y = 389 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "S3") { X = 48, Y = 277 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "S4") { X = 272, Y = 222 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "S5") { X = 385, Y = 54 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "S6") { X = 440, Y = 276 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "S7") { X = 608, Y = 389 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "S8") { X = 385, Y = 445 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Z") { X = 329, Y = 333 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "1") { X = 273, Y = 557 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "2") { X = 273, Y = 501 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "3") { X = 272, Y = 444 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "4") { X = 272, Y = 389 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "5") { X = 161, Y = 389 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "6") { X = 104, Y = 389 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "7") { X = 48, Y = 390 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "8") { X = 48, Y = 333 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "9") { X = 104, Y = 276 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "10") { X = 160, Y = 275 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "11") { X = 216, Y = 276 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "12") { X = 272, Y = 277 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "13") { X = 272, Y = 165 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "14") { X = 272, Y = 110 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "15") { X = 272, Y = 53 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "16") { X = 328, Y = 52 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "17") { X = 386, Y = 108 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "18") { X = 385, Y = 164 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "19") { X = 385, Y = 220 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "20") { X = 385, Y = 276 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "21") { X = 496, Y = 276 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "22") { X = 552, Y = 276 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "23") { X = 609, Y = 276 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "24") { X = 608, Y = 332 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "25") { X = 552, Y = 388 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "26") { X = 497, Y = 388 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "27") { X = 440, Y = 387 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "28") { X = 384, Y = 388 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "29") { X = 385, Y = 500 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "30") { X = 384, Y = 556 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "31") { X = 384, Y = 613 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "32") { X = 328, Y = 613 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "gelb1") { X = 329, Y = 557 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "gelb2") { X = 329, Y = 501 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "gelb3") { X = 329, Y = 445 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "gelb4") { X = 329, Y = 389 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "rot1") { X = 104, Y = 333 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "rot2") { X = 160, Y = 333 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "rot3") { X = 216, Y = 333 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "rot4") { X = 273, Y = 333 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "gruen1") { X = 328, Y = 109 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "gruen2") { X = 328, Y = 164 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "gruen3") { X = 329, Y = 220 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "gruen4") { X = 328, Y = 277 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "blau1") { X = 553, Y = 332 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "blau2") { X = 497, Y = 332 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "blau3") { X = 440, Y = 332 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "blau4") { X = 385, Y = 332 };
mapTemplate.Countries.Add(country73);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country58);
continent1.Countries.Add(country59);
continent1.Countries.Add(country60);
continent1.Countries.Add(country61);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 1);
continent2.Countries.Add(country62);
continent2.Countries.Add(country63);
continent2.Countries.Add(country64);
continent2.Countries.Add(country65);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 1);
continent3.Countries.Add(country66);
continent3.Countries.Add(country67);
continent3.Countries.Add(country68);
continent3.Countries.Add(country69);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 1);
continent4.Countries.Add(country70);
continent4.Countries.Add(country71);
continent4.Countries.Add(country72);
continent4.Countries.Add(country73);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country58);
continent5.Countries.Add(country59);
continent5.Countries.Add(country60);
continent5.Countries.Add(country61);
continent5.Countries.Add(country2);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 1);
continent6.Countries.Add(country58);
continent6.Countries.Add(country59);
continent6.Countries.Add(country60);
continent6.Countries.Add(country61);
continent6.Countries.Add(country6);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 1);
continent7.Countries.Add(country58);
continent7.Countries.Add(country59);
continent7.Countries.Add(country60);
continent7.Countries.Add(country61);
continent7.Countries.Add(country10);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country58);
continent8.Countries.Add(country59);
continent8.Countries.Add(country60);
continent8.Countries.Add(country61);
continent8.Countries.Add(country14);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country62);
continent9.Countries.Add(country63);
continent9.Countries.Add(country64);
continent9.Countries.Add(country65);
continent9.Countries.Add(country3);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 1);
continent10.Countries.Add(country62);
continent10.Countries.Add(country63);
continent10.Countries.Add(country64);
continent10.Countries.Add(country65);
continent10.Countries.Add(country7);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 1);
continent11.Countries.Add(country62);
continent11.Countries.Add(country63);
continent11.Countries.Add(country64);
continent11.Countries.Add(country65);
continent11.Countries.Add(country11);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 1);
continent12.Countries.Add(country62);
continent12.Countries.Add(country63);
continent12.Countries.Add(country64);
continent12.Countries.Add(country65);
continent12.Countries.Add(country15);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 1);
continent13.Countries.Add(country66);
continent13.Countries.Add(country67);
continent13.Countries.Add(country68);
continent13.Countries.Add(country69);
continent13.Countries.Add(country4);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 1);
continent14.Countries.Add(country66);
continent14.Countries.Add(country67);
continent14.Countries.Add(country68);
continent14.Countries.Add(country69);
continent14.Countries.Add(country8);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 1);
continent15.Countries.Add(country66);
continent15.Countries.Add(country67);
continent15.Countries.Add(country68);
continent15.Countries.Add(country69);
continent15.Countries.Add(country12);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 1);
continent16.Countries.Add(country66);
continent16.Countries.Add(country67);
continent16.Countries.Add(country68);
continent16.Countries.Add(country69);
continent16.Countries.Add(country16);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 1);
continent17.Countries.Add(country70);
continent17.Countries.Add(country71);
continent17.Countries.Add(country72);
continent17.Countries.Add(country73);
continent17.Countries.Add(country1);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 1);
continent18.Countries.Add(country70);
continent18.Countries.Add(country71);
continent18.Countries.Add(country72);
continent18.Countries.Add(country73);
continent18.Countries.Add(country5);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 1);
continent19.Countries.Add(country70);
continent19.Countries.Add(country71);
continent19.Countries.Add(country72);
continent19.Countries.Add(country73);
continent19.Countries.Add(country9);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 1);
continent20.Countries.Add(country70);
continent20.Countries.Add(country71);
continent20.Countries.Add(country72);
continent20.Countries.Add(country73);
continent20.Countries.Add(country13);
mapTemplate.Continents.Add(continent20);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "5"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "17"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "19"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "12"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "21"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "23"));
mapTemplate.Connections.Add(new Connection("13", "1"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "2"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "3"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "4"));
mapTemplate.Connections.Add(new Connection("17", "2"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "26"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "30"));
mapTemplate.Connections.Add(new Connection("19", "7"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "34"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "38"));
mapTemplate.Connections.Add(new Connection("21", "12"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "42"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "46"));
mapTemplate.Connections.Add(new Connection("23", "13"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "50"));
mapTemplate.Connections.Add(new Connection("24", "17"));
mapTemplate.Connections.Add(new Connection("24", "54"));
mapTemplate.Connections.Add(new Connection("25", "18"));
mapTemplate.Connections.Add(new Connection("25", "20"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "18"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "19"));
mapTemplate.Connections.Add(new Connection("33", "62"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("37", "20"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("41", "21"));
mapTemplate.Connections.Add(new Connection("41", "66"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "22"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("49", "23"));
mapTemplate.Connections.Add(new Connection("49", "70"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "24"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("57", "17"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "25"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("65", "25"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("69", "25"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("73", "25"));

            return mapTemplate;
		}
    }
}

