using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Shogun()
        {
            var mapTemplate = new MapTemplate("Shogun") { Image = "shogun.jpg" };
            var country1 = new CountryTemplate("1", "Osumi") { X = 139, Y = 543 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Hyuga") { X = 195, Y = 533 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Higo") { X = 177, Y = 448 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Satsuma") { X = 97, Y = 493 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Hizen") { X = 167, Y = 319 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Chikuzen") { X = 228, Y = 321 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Buzen") { X = 279, Y = 382 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Chikugo") { X = 204, Y = 403 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Bungo") { X = 267, Y = 427 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Nagato") { X = 316, Y = 300 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Suo") { X = 359, Y = 348 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Iwami") { X = 463, Y = 294 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Izumo") { X = 509, Y = 307 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Bingo") { X = 491, Y = 341 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Aki") { X = 451, Y = 360 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Iyo") { X = 406, Y = 454 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Tosa") { X = 458, Y = 510 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Awa") { X = 522, Y = 526 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Awaji") { X = 583, Y = 512 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Sanuki") { X = 505, Y = 477 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Hoki") { X = 591, Y = 322 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Mima") { X = 581, Y = 376 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Bitchu") { X = 525, Y = 405 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Bizen") { X = 568, Y = 426 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Inaba") { X = 635, Y = 356 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Harima") { X = 608, Y = 422 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Tamba") { X = 687, Y = 439 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Tajima") { X = 677, Y = 360 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Kawachi") { X = 634, Y = 486 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Wakasa") { X = 744, Y = 430 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Mino") { X = 808, Y = 470 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Owari") { X = 797, Y = 508 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Omi") { X = 730, Y = 481 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Yama") { X = 690, Y = 501 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Iga") { X = 716, Y = 545 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Kii") { X = 600, Y = 593 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Ise") { X = 739, Y = 584 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Yamato") { X = 669, Y = 556 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Shinano") { X = 968, Y = 432 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Etchu") { X = 923, Y = 378 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Noto") { X = 883, Y = 347 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Kaga") { X = 845, Y = 387 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Echizen") { X = 796, Y = 408 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Hida") { X = 861, Y = 458 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Mikawa") { X = 804, Y = 584 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Totomi") { X = 843, Y = 616 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Suruga") { X = 887, Y = 594 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Kai") { X = 923, Y = 575 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Izu") { X = 921, Y = 660 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Sagami") { X = 982, Y = 634 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Musashi") { X = 1005, Y = 571 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Kozuke") { X = 1034, Y = 485 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Shimotsuke") { X = 1095, Y = 503 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Hitachi") { X = 1102, Y = 585 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Kazusa") { X = 1043, Y = 673 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "Shimosa") { X = 1055, Y = 602 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Sado") { X = 1091, Y = 299 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Dewa") { X = 1198, Y = 353 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Echigo") { X = 1050, Y = 389 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Mutsu") { X = 1178, Y = 466 };
            mapTemplate.Countries.Add(country60);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 3);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            continent2.Countries.Add(country8);
            continent2.Countries.Add(country9);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country15);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country16);
            continent4.Countries.Add(country17);
            continent4.Countries.Add(country18);
            continent4.Countries.Add(country19);
            continent4.Countries.Add(country20);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country21);
            continent5.Countries.Add(country22);
            continent5.Countries.Add(country23);
            continent5.Countries.Add(country24);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country25);
            continent6.Countries.Add(country26);
            continent6.Countries.Add(country27);
            continent6.Countries.Add(country28);
            continent6.Countries.Add(country29);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 3);
            continent7.Countries.Add(country30);
            continent7.Countries.Add(country31);
            continent7.Countries.Add(country32);
            continent7.Countries.Add(country33);
            continent7.Countries.Add(country34);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country35);
            continent8.Countries.Add(country36);
            continent8.Countries.Add(country37);
            continent8.Countries.Add(country38);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 4);
            continent9.Countries.Add(country39);
            continent9.Countries.Add(country40);
            continent9.Countries.Add(country41);
            continent9.Countries.Add(country42);
            continent9.Countries.Add(country43);
            continent9.Countries.Add(country44);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country45);
            continent10.Countries.Add(country46);
            continent10.Countries.Add(country47);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 2);
            continent11.Countries.Add(country48);
            continent11.Countries.Add(country49);
            continent11.Countries.Add(country50);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 4);
            continent12.Countries.Add(country51);
            continent12.Countries.Add(country52);
            continent12.Countries.Add(country53);
            continent12.Countries.Add(country54);
            continent12.Countries.Add(country55);
            continent12.Countries.Add(country56);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 3);
            continent13.Countries.Add(country57);
            continent13.Countries.Add(country58);
            continent13.Countries.Add(country59);
            continent13.Countries.Add(country60);
            mapTemplate.Continents.Add(continent13);
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "5"));
            mapTemplate.Connections.Add(new Connection("1", "36"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "9"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "9"));
            mapTemplate.Connections.Add(new Connection("3", "8"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("5", "1"));
            mapTemplate.Connections.Add(new Connection("5", "13"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("6", "9"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "10"));
            mapTemplate.Connections.Add(new Connection("7", "11"));
            mapTemplate.Connections.Add(new Connection("8", "3"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("9", "2"));
            mapTemplate.Connections.Add(new Connection("9", "3"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "16"));
            mapTemplate.Connections.Add(new Connection("9", "6"));
            mapTemplate.Connections.Add(new Connection("10", "7"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("11", "7"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "15"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "15"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "21"));
            mapTemplate.Connections.Add(new Connection("13", "5"));
            mapTemplate.Connections.Add(new Connection("13", "30"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "21"));
            mapTemplate.Connections.Add(new Connection("14", "23"));
            mapTemplate.Connections.Add(new Connection("15", "11"));
            mapTemplate.Connections.Add(new Connection("15", "12"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("16", "9"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("16", "20"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "26"));
            mapTemplate.Connections.Add(new Connection("19", "29"));
            mapTemplate.Connections.Add(new Connection("20", "16"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "24"));
            mapTemplate.Connections.Add(new Connection("21", "13"));
            mapTemplate.Connections.Add(new Connection("21", "14"));
            mapTemplate.Connections.Add(new Connection("21", "23"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "25"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "25"));
            mapTemplate.Connections.Add(new Connection("22", "26"));
            mapTemplate.Connections.Add(new Connection("23", "14"));
            mapTemplate.Connections.Add(new Connection("23", "21"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("24", "20"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("25", "21"));
            mapTemplate.Connections.Add(new Connection("25", "22"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "28"));
            mapTemplate.Connections.Add(new Connection("26", "19"));
            mapTemplate.Connections.Add(new Connection("26", "22"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "29"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "29"));
            mapTemplate.Connections.Add(new Connection("27", "34"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("28", "25"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("29", "19"));
            mapTemplate.Connections.Add(new Connection("29", "26"));
            mapTemplate.Connections.Add(new Connection("29", "27"));
            mapTemplate.Connections.Add(new Connection("29", "36"));
            mapTemplate.Connections.Add(new Connection("29", "38"));
            mapTemplate.Connections.Add(new Connection("29", "34"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("30", "13"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "43"));
            mapTemplate.Connections.Add(new Connection("30", "58"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "45"));
            mapTemplate.Connections.Add(new Connection("31", "43"));
            mapTemplate.Connections.Add(new Connection("31", "44"));
            mapTemplate.Connections.Add(new Connection("31", "39"));
            mapTemplate.Connections.Add(new Connection("32", "37"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "45"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "35"));
            mapTemplate.Connections.Add(new Connection("33", "37"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "29"));
            mapTemplate.Connections.Add(new Connection("34", "27"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("35", "38"));
            mapTemplate.Connections.Add(new Connection("35", "37"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "33"));
            mapTemplate.Connections.Add(new Connection("36", "1"));
            mapTemplate.Connections.Add(new Connection("36", "29"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "45"));
            mapTemplate.Connections.Add(new Connection("37", "35"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "33"));
            mapTemplate.Connections.Add(new Connection("37", "32"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("38", "35"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "29"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("39", "31"));
            mapTemplate.Connections.Add(new Connection("39", "45"));
            mapTemplate.Connections.Add(new Connection("39", "46"));
            mapTemplate.Connections.Add(new Connection("39", "47"));
            mapTemplate.Connections.Add(new Connection("39", "44"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "48"));
            mapTemplate.Connections.Add(new Connection("39", "59"));
            mapTemplate.Connections.Add(new Connection("39", "52"));
            mapTemplate.Connections.Add(new Connection("39", "51"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("40", "44"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "59"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "57"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "44"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("43", "30"));
            mapTemplate.Connections.Add(new Connection("43", "31"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("44", "31"));
            mapTemplate.Connections.Add(new Connection("44", "39"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "42"));
            mapTemplate.Connections.Add(new Connection("44", "40"));
            mapTemplate.Connections.Add(new Connection("45", "32"));
            mapTemplate.Connections.Add(new Connection("45", "31"));
            mapTemplate.Connections.Add(new Connection("45", "36"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "39"));
            mapTemplate.Connections.Add(new Connection("45", "56"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "39"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "39"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("48", "39"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "50"));
            mapTemplate.Connections.Add(new Connection("48", "51"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "50"));
            mapTemplate.Connections.Add(new Connection("50", "48"));
            mapTemplate.Connections.Add(new Connection("50", "49"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("51", "39"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "56"));
            mapTemplate.Connections.Add(new Connection("51", "48"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("52", "39"));
            mapTemplate.Connections.Add(new Connection("52", "59"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "60"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "60"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "56"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "60"));
            mapTemplate.Connections.Add(new Connection("54", "56"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("56", "51"));
            mapTemplate.Connections.Add(new Connection("56", "54"));
            mapTemplate.Connections.Add(new Connection("56", "53"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("56", "45"));
            mapTemplate.Connections.Add(new Connection("57", "41"));
            mapTemplate.Connections.Add(new Connection("57", "58"));
            mapTemplate.Connections.Add(new Connection("58", "57"));
            mapTemplate.Connections.Add(new Connection("58", "30"));
            mapTemplate.Connections.Add(new Connection("58", "59"));
            mapTemplate.Connections.Add(new Connection("58", "60"));
            mapTemplate.Connections.Add(new Connection("59", "39"));
            mapTemplate.Connections.Add(new Connection("59", "58"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("59", "52"));
            mapTemplate.Connections.Add(new Connection("59", "40"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("60", "58"));
            mapTemplate.Connections.Add(new Connection("60", "53"));
            mapTemplate.Connections.Add(new Connection("60", "52"));
            mapTemplate.Connections.Add(new Connection("60", "54"));

            return mapTemplate;
        }
    }
}
