using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Suedamerika()
        {
            var mapTemplate = new MapTemplate("Suedamerika") { Image = "suedamerika.png" };
            var country1 = new CountryTemplate("1", "Caribe") { X = 167, Y = 105 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Pacifica") { X = 156, Y = 182 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Orinoquia") { X = 225, Y = 170 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Amazonica") { X = 214, Y = 222 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Maracaibo") { X = 239, Y = 99 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Guarico") { X = 293, Y = 91 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Bolivar") { X = 344, Y = 150 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Orinoco") { X = 299, Y = 169 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Guyana") { X = 407, Y = 141 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Suriname") { X = 454, Y = 167 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Fr. Guayana") { X = 498, Y = 168 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Oriente") { X = 130, Y = 263 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Costa") { X = 85, Y = 260 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Loreto") { X = 177, Y = 290 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Piura") { X = 133, Y = 340 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Lima") { X = 169, Y = 413 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Cusco") { X = 235, Y = 447 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Beni") { X = 316, Y = 426 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "La Paz") { X = 305, Y = 513 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Santa Cruz") { X = 388, Y = 491 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Roraima") { X = 368, Y = 219 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Acre") { X = 225, Y = 354 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Rondonia") { X = 338, Y = 380 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Amazonas") { X = 269, Y = 314 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Amapa") { X = 505, Y = 224 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Para") { X = 445, Y = 316 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Tocantins") { X = 547, Y = 341 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Maranhao") { X = 603, Y = 325 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Nordeste") { X = 731, Y = 356 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Bahia") { X = 653, Y = 421 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Mato Grosso") { X = 428, Y = 398 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Pantanal") { X = 445, Y = 494 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Goias") { X = 539, Y = 451 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Mato Grosso do Sul") { X = 486, Y = 509 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Espirito Santo") { X = 655, Y = 527 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Minas Gerais") { X = 592, Y = 489 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Sao Paolo") { X = 502, Y = 573 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Rio Grande do Sul") { X = 498, Y = 663 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Salto") { X = 436, Y = 690 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Montevideo") { X = 450, Y = 722 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Chaco") { X = 386, Y = 538 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Asuncion") { X = 439, Y = 614 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Norte Grande Argentino") { X = 390, Y = 614 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Nuevo Cuyo") { X = 299, Y = 722 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Centro") { X = 382, Y = 684 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Buenos Aires") { X = 388, Y = 741 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Rio Negro") { X = 288, Y = 802 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Chubut") { X = 295, Y = 887 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Sur de Argentina") { X = 291, Y = 956 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Atacama") { X = 273, Y = 573 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Santiago de Chile") { X = 249, Y = 742 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Los Lagos") { X = 242, Y = 846 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Aisen") { X = 254, Y = 907 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Magallanes") { X = 294, Y = 1005 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Falkland") { X = 412, Y = 965 };
            mapTemplate.Countries.Add(country55);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 2);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            continent2.Countries.Add(country8);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 1);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 2);
            continent4.Countries.Add(country14);
            continent4.Countries.Add(country15);
            continent4.Countries.Add(country16);
            continent4.Countries.Add(country17);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country21);
            continent5.Countries.Add(country22);
            continent5.Countries.Add(country23);
            continent5.Countries.Add(country24);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 2);
            continent6.Countries.Add(country9);
            continent6.Countries.Add(country10);
            continent6.Countries.Add(country11);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country25);
            continent7.Countries.Add(country26);
            continent7.Countries.Add(country27);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 2);
            continent8.Countries.Add(country28);
            continent8.Countries.Add(country29);
            continent8.Countries.Add(country30);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 3);
            continent9.Countries.Add(country31);
            continent9.Countries.Add(country32);
            continent9.Countries.Add(country33);
            continent9.Countries.Add(country34);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country35);
            continent10.Countries.Add(country36);
            continent10.Countries.Add(country37);
            continent10.Countries.Add(country38);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 2);
            continent11.Countries.Add(country18);
            continent11.Countries.Add(country19);
            continent11.Countries.Add(country20);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 1);
            continent12.Countries.Add(country41);
            continent12.Countries.Add(country42);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 3);
            continent13.Countries.Add(country50);
            continent13.Countries.Add(country51);
            continent13.Countries.Add(country52);
            continent13.Countries.Add(country53);
            continent13.Countries.Add(country54);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 2);
            continent14.Countries.Add(country43);
            continent14.Countries.Add(country44);
            continent14.Countries.Add(country45);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 2);
            continent15.Countries.Add(country46);
            continent15.Countries.Add(country47);
            continent15.Countries.Add(country48);
            continent15.Countries.Add(country49);
            mapTemplate.Continents.Add(continent15);
            var continent16 = new Continent("16", 1);
            continent16.Countries.Add(country39);
            continent16.Countries.Add(country40);
            mapTemplate.Continents.Add(continent16);
            var continent17 = new Continent("17", 1);
            continent17.Countries.Add(country55);
            mapTemplate.Continents.Add(continent17);
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "5"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "13"));
            mapTemplate.Connections.Add(new Connection("2", "12"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "8"));
            mapTemplate.Connections.Add(new Connection("3", "7"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("3", "24"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "24"));
            mapTemplate.Connections.Add(new Connection("4", "14"));
            mapTemplate.Connections.Add(new Connection("4", "12"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "1"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "3"));
            mapTemplate.Connections.Add(new Connection("7", "21"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "21"));
            mapTemplate.Connections.Add(new Connection("8", "24"));
            mapTemplate.Connections.Add(new Connection("8", "3"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "26"));
            mapTemplate.Connections.Add(new Connection("9", "21"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "25"));
            mapTemplate.Connections.Add(new Connection("10", "26"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "25"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "4"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "15"));
            mapTemplate.Connections.Add(new Connection("12", "2"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "15"));
            mapTemplate.Connections.Add(new Connection("13", "2"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "16"));
            mapTemplate.Connections.Add(new Connection("14", "22"));
            mapTemplate.Connections.Add(new Connection("14", "24"));
            mapTemplate.Connections.Add(new Connection("14", "4"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "13"));
            mapTemplate.Connections.Add(new Connection("15", "12"));
            mapTemplate.Connections.Add(new Connection("16", "14"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "22"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "50"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "22"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "20"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "23"));
            mapTemplate.Connections.Add(new Connection("18", "22"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "50"));
            mapTemplate.Connections.Add(new Connection("19", "41"));
            mapTemplate.Connections.Add(new Connection("19", "43"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "18"));
            mapTemplate.Connections.Add(new Connection("20", "41"));
            mapTemplate.Connections.Add(new Connection("20", "31"));
            mapTemplate.Connections.Add(new Connection("20", "32"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("21", "24"));
            mapTemplate.Connections.Add(new Connection("21", "9"));
            mapTemplate.Connections.Add(new Connection("21", "8"));
            mapTemplate.Connections.Add(new Connection("21", "26"));
            mapTemplate.Connections.Add(new Connection("21", "7"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "18"));
            mapTemplate.Connections.Add(new Connection("22", "17"));
            mapTemplate.Connections.Add(new Connection("22", "16"));
            mapTemplate.Connections.Add(new Connection("22", "14"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "31"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("23", "18"));
            mapTemplate.Connections.Add(new Connection("24", "21"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "31"));
            mapTemplate.Connections.Add(new Connection("24", "8"));
            mapTemplate.Connections.Add(new Connection("24", "3"));
            mapTemplate.Connections.Add(new Connection("24", "4"));
            mapTemplate.Connections.Add(new Connection("24", "14"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "11"));
            mapTemplate.Connections.Add(new Connection("25", "10"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "31"));
            mapTemplate.Connections.Add(new Connection("26", "9"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "10"));
            mapTemplate.Connections.Add(new Connection("26", "21"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("27", "33"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "31"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "35"));
            mapTemplate.Connections.Add(new Connection("30", "36"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "26"));
            mapTemplate.Connections.Add(new Connection("31", "20"));
            mapTemplate.Connections.Add(new Connection("31", "23"));
            mapTemplate.Connections.Add(new Connection("31", "24"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "34"));
            mapTemplate.Connections.Add(new Connection("31", "27"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "34"));
            mapTemplate.Connections.Add(new Connection("32", "20"));
            mapTemplate.Connections.Add(new Connection("32", "41"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "36"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "27"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "32"));
            mapTemplate.Connections.Add(new Connection("34", "42"));
            mapTemplate.Connections.Add(new Connection("34", "37"));
            mapTemplate.Connections.Add(new Connection("34", "41"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("34", "31"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "30"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "30"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("36", "33"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "43"));
            mapTemplate.Connections.Add(new Connection("37", "42"));
            mapTemplate.Connections.Add(new Connection("37", "34"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "43"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "45"));
            mapTemplate.Connections.Add(new Connection("39", "43"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "46"));
            mapTemplate.Connections.Add(new Connection("40", "45"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "34"));
            mapTemplate.Connections.Add(new Connection("41", "43"));
            mapTemplate.Connections.Add(new Connection("41", "19"));
            mapTemplate.Connections.Add(new Connection("41", "20"));
            mapTemplate.Connections.Add(new Connection("41", "32"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "37"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "34"));
            mapTemplate.Connections.Add(new Connection("43", "45"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "50"));
            mapTemplate.Connections.Add(new Connection("43", "39"));
            mapTemplate.Connections.Add(new Connection("43", "38"));
            mapTemplate.Connections.Add(new Connection("43", "37"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "41"));
            mapTemplate.Connections.Add(new Connection("43", "19"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "46"));
            mapTemplate.Connections.Add(new Connection("44", "51"));
            mapTemplate.Connections.Add(new Connection("44", "47"));
            mapTemplate.Connections.Add(new Connection("44", "50"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "43"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "40"));
            mapTemplate.Connections.Add(new Connection("45", "39"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "44"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "40"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "52"));
            mapTemplate.Connections.Add(new Connection("47", "51"));
            mapTemplate.Connections.Add(new Connection("47", "44"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "53"));
            mapTemplate.Connections.Add(new Connection("48", "52"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "55"));
            mapTemplate.Connections.Add(new Connection("49", "54"));
            mapTemplate.Connections.Add(new Connection("49", "53"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("50", "44"));
            mapTemplate.Connections.Add(new Connection("50", "43"));
            mapTemplate.Connections.Add(new Connection("50", "19"));
            mapTemplate.Connections.Add(new Connection("50", "17"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "47"));
            mapTemplate.Connections.Add(new Connection("51", "44"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "48"));
            mapTemplate.Connections.Add(new Connection("52", "47"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "49"));
            mapTemplate.Connections.Add(new Connection("53", "48"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "49"));
            mapTemplate.Connections.Add(new Connection("55", "49"));

            return mapTemplate;
        }
    }
}
