using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate SonnenSys()
        {
            var mapTemplate = new MapTemplate("SonnenSys") { Image = "sonnensys.jpg" };
            var country1 = new CountryTemplate("1", "Sonne") { X = 417, Y = 400 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Pluto") { X = 800, Y = 378 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Charon") { X = 804, Y = 340 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Nyx") { X = 739, Y = 374 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Hydra") { X = 822, Y = 439 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Neptun") { X = 672, Y = 204 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Naiad") { X = 626, Y = 155 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Thalassa") { X = 675, Y = 150 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Despina") { X = 723, Y = 169 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Galatea") { X = 739, Y = 210 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Proteus") { X = 734, Y = 254 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Larissa") { X = 689, Y = 262 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Triton") { X = 637, Y = 262 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Nereid") { X = 618, Y = 218 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Uranus") { X = 376, Y = 139 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Sycorax") { X = 376, Y = 49 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Titania") { X = 444, Y = 88 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Ariel") { X = 451, Y = 120 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Puck") { X = 455, Y = 160 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Belinda") { X = 448, Y = 205 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Rosalind") { X = 390, Y = 226 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Oberon") { X = 325, Y = 202 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Cordelia") { X = 305, Y = 167 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Ophelia") { X = 299, Y = 124 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Desdemona") { X = 312, Y = 82 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Saturn") { X = 169, Y = 360 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Prometheus") { X = 169, Y = 269 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Calypso") { X = 262, Y = 265 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Hyperion") { X = 270, Y = 333 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Atlas") { X = 258, Y = 384 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Mimas") { X = 227, Y = 433 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Pandora") { X = 173, Y = 470 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Epimetheus") { X = 97, Y = 475 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Titan") { X = 64, Y = 414 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Phoebe") { X = 83, Y = 351 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Thetys") { X = 115, Y = 300 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Jupiter") { X = 373, Y = 559 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "IO") { X = 407, Y = 480 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Lysithea") { X = 460, Y = 512 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Adrastea") { X = 471, Y = 559 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Europa") { X = 460, Y = 602 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Sinope") { X = 417, Y = 639 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Ganymed") { X = 357, Y = 660 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Himalia") { X = 305, Y = 625 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Callisto") { X = 287, Y = 570 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Thebe") { X = 311, Y = 505 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "S/1999 J 1") { X = 352, Y = 482 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Mars") { X = 588, Y = 428 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Phobos") { X = 535, Y = 400 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Deimos") { X = 529, Y = 455 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Erde") { X = 478, Y = 353 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Mond") { X = 507, Y = 288 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Venus") { X = 379, Y = 320 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Merkur") { X = 333, Y = 379 };
            mapTemplate.Countries.Add(country54);
            var continent1 = new Continent("1", 5);
            continent1.Countries.Add(country26);
            continent1.Countries.Add(country27);
            continent1.Countries.Add(country28);
            continent1.Countries.Add(country29);
            continent1.Countries.Add(country30);
            continent1.Countries.Add(country31);
            continent1.Countries.Add(country32);
            continent1.Countries.Add(country33);
            continent1.Countries.Add(country34);
            continent1.Countries.Add(country35);
            continent1.Countries.Add(country36);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 5);
            continent2.Countries.Add(country15);
            continent2.Countries.Add(country16);
            continent2.Countries.Add(country17);
            continent2.Countries.Add(country18);
            continent2.Countries.Add(country19);
            continent2.Countries.Add(country20);
            continent2.Countries.Add(country21);
            continent2.Countries.Add(country22);
            continent2.Countries.Add(country23);
            continent2.Countries.Add(country24);
            continent2.Countries.Add(country25);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 4);
            continent3.Countries.Add(country6);
            continent3.Countries.Add(country7);
            continent3.Countries.Add(country8);
            continent3.Countries.Add(country9);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country48);
            continent4.Countries.Add(country49);
            continent4.Countries.Add(country50);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country2);
            continent5.Countries.Add(country3);
            continent5.Countries.Add(country4);
            continent5.Countries.Add(country5);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 2);
            continent6.Countries.Add(country51);
            continent6.Countries.Add(country52);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 1);
            continent7.Countries.Add(country54);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 1);
            continent8.Countries.Add(country53);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 1);
            continent9.Countries.Add(country1);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 5);
            continent10.Countries.Add(country37);
            continent10.Countries.Add(country38);
            continent10.Countries.Add(country39);
            continent10.Countries.Add(country40);
            continent10.Countries.Add(country41);
            continent10.Countries.Add(country42);
            continent10.Countries.Add(country43);
            continent10.Countries.Add(country44);
            continent10.Countries.Add(country45);
            continent10.Countries.Add(country46);
            continent10.Countries.Add(country47);
            mapTemplate.Continents.Add(continent10);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "6"));
            mapTemplate.Connections.Add(new Connection("1", "15"));
            mapTemplate.Connections.Add(new Connection("1", "26"));
            mapTemplate.Connections.Add(new Connection("1", "37"));
            mapTemplate.Connections.Add(new Connection("1", "48"));
            mapTemplate.Connections.Add(new Connection("1", "51"));
            mapTemplate.Connections.Add(new Connection("1", "53"));
            mapTemplate.Connections.Add(new Connection("1", "54"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("2", "6"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("6", "1"));
            mapTemplate.Connections.Add(new Connection("6", "2"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("6", "9"));
            mapTemplate.Connections.Add(new Connection("6", "10"));
            mapTemplate.Connections.Add(new Connection("6", "11"));
            mapTemplate.Connections.Add(new Connection("6", "12"));
            mapTemplate.Connections.Add(new Connection("6", "13"));
            mapTemplate.Connections.Add(new Connection("6", "14"));
            mapTemplate.Connections.Add(new Connection("6", "15"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "14"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("9", "6"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("10", "6"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("11", "6"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("12", "6"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("13", "6"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("14", "6"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "7"));
            mapTemplate.Connections.Add(new Connection("15", "1"));
            mapTemplate.Connections.Add(new Connection("15", "6"));
            mapTemplate.Connections.Add(new Connection("15", "26"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "18"));
            mapTemplate.Connections.Add(new Connection("15", "19"));
            mapTemplate.Connections.Add(new Connection("15", "20"));
            mapTemplate.Connections.Add(new Connection("15", "21"));
            mapTemplate.Connections.Add(new Connection("15", "22"));
            mapTemplate.Connections.Add(new Connection("15", "23"));
            mapTemplate.Connections.Add(new Connection("15", "24"));
            mapTemplate.Connections.Add(new Connection("15", "25"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "25"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("18", "15"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("19", "15"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("20", "15"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("21", "15"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("22", "15"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("23", "15"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("24", "15"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("25", "15"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "16"));
            mapTemplate.Connections.Add(new Connection("26", "1"));
            mapTemplate.Connections.Add(new Connection("26", "15"));
            mapTemplate.Connections.Add(new Connection("26", "37"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "29"));
            mapTemplate.Connections.Add(new Connection("26", "30"));
            mapTemplate.Connections.Add(new Connection("26", "31"));
            mapTemplate.Connections.Add(new Connection("26", "32"));
            mapTemplate.Connections.Add(new Connection("26", "33"));
            mapTemplate.Connections.Add(new Connection("26", "34"));
            mapTemplate.Connections.Add(new Connection("26", "35"));
            mapTemplate.Connections.Add(new Connection("26", "36"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "36"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "26"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("30", "26"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("31", "26"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "26"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("33", "26"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("34", "26"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("35", "26"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("36", "26"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "27"));
            mapTemplate.Connections.Add(new Connection("37", "1"));
            mapTemplate.Connections.Add(new Connection("37", "26"));
            mapTemplate.Connections.Add(new Connection("37", "48"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "39"));
            mapTemplate.Connections.Add(new Connection("37", "40"));
            mapTemplate.Connections.Add(new Connection("37", "41"));
            mapTemplate.Connections.Add(new Connection("37", "42"));
            mapTemplate.Connections.Add(new Connection("37", "43"));
            mapTemplate.Connections.Add(new Connection("37", "44"));
            mapTemplate.Connections.Add(new Connection("37", "45"));
            mapTemplate.Connections.Add(new Connection("37", "46"));
            mapTemplate.Connections.Add(new Connection("37", "47"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "47"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("39", "37"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("40", "37"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("41", "37"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("42", "37"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("43", "37"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("44", "37"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("45", "37"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("46", "37"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("47", "37"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "38"));
            mapTemplate.Connections.Add(new Connection("48", "1"));
            mapTemplate.Connections.Add(new Connection("48", "37"));
            mapTemplate.Connections.Add(new Connection("48", "51"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "50"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "50"));
            mapTemplate.Connections.Add(new Connection("50", "48"));
            mapTemplate.Connections.Add(new Connection("50", "49"));
            mapTemplate.Connections.Add(new Connection("51", "1"));
            mapTemplate.Connections.Add(new Connection("51", "48"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("53", "1"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("54", "1"));
            mapTemplate.Connections.Add(new Connection("54", "53"));

            return mapTemplate;
        }
    }
}
