
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate PirateWars()
        {

var mapTemplate = new MapTemplate("PirateWars") { Image = "piratewars.jpg" };
var country1 = new CountryTemplate("1", "Lafitte") { X = 189, Y = 209 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Condon") { X = 187, Y = 270 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Apu") { X = 155, Y = 324 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Hilt") { X = 115, Y = 456 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Guybrush") { X = 168, Y = 635 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Herman") { X = 195, Y = 615 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Elaine") { X = 255, Y = 636 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Pete") { X = 153, Y = 690 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Stan") { X = 187, Y = 689 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "LeChuck") { X = 238, Y = 680 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Culliford") { X = 430, Y = 642 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Low") { X = 561, Y = 651 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "deFlor") { X = 433, Y = 719 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Pechlin") { X = 559, Y = 727 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "leGrand") { X = 859, Y = 676 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Bart") { X = 785, Y = 641 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Feng") { X = 835, Y = 626 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Hornigold") { X = 936, Y = 618 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Sievers") { X = 877, Y = 611 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Thurot") { X = 771, Y = 577 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Belleville") { X = 794, Y = 498 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Rogers") { X = 896, Y = 466 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Read") { X = 868, Y = 506 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "deGranmont") { X = 866, Y = 543 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Heinason") { X = 950, Y = 531 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "OMalley") { X = 666, Y = 241 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Yi-Sao") { X = 746, Y = 253 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Bellamy") { X = 677, Y = 174 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Tarkondimotos") { X = 621, Y = 119 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Cassard") { X = 539, Y = 134 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Aury") { X = 608, Y = 196 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Bonny") { X = 522, Y = 189 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "duCasse") { X = 424, Y = 172 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Head") { X = 431, Y = 314 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Nose") { X = 344, Y = 458 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Morgan") { X = 338, Y = 520 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Jaw") { X = 414, Y = 499 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Sparrow") { X = 507, Y = 512 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Kidd") { X = 427, Y = 405 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Rackham") { X = 528, Y = 328 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Drake") { X = 592, Y = 392 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Blackbeard") { X = 516, Y = 420 };
mapTemplate.Countries.Add(country42);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 5);
continent4.Countries.Add(country15);
continent4.Countries.Add(country16);
continent4.Countries.Add(country17);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 5);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 7);
continent6.Countries.Add(country34);
continent6.Countries.Add(country35);
continent6.Countries.Add(country36);
continent6.Countries.Add(country37);
continent6.Countries.Add(country38);
continent6.Countries.Add(country39);
continent6.Countries.Add(country40);
continent6.Countries.Add(country41);
continent6.Countries.Add(country42);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "36"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("5", "10"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "37"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "5"));
mapTemplate.Connections.Add(new Connection("9", "27"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "5"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "19"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "24"));
mapTemplate.Connections.Add(new Connection("18", "25"));
mapTemplate.Connections.Add(new Connection("19", "15"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "24"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "38"));
mapTemplate.Connections.Add(new Connection("20", "24"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "42"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("24", "18"));
mapTemplate.Connections.Add(new Connection("24", "19"));
mapTemplate.Connections.Add(new Connection("24", "20"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "18"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "31"));
mapTemplate.Connections.Add(new Connection("27", "9"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("31", "26"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "41"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "29"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "39"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("34", "40"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "39"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("36", "1"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("37", "6"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "42"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("38", "20"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "42"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "34"));
mapTemplate.Connections.Add(new Connection("39", "35"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "34"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "31"));
mapTemplate.Connections.Add(new Connection("42", "21"));
mapTemplate.Connections.Add(new Connection("42", "38"));
mapTemplate.Connections.Add(new Connection("42", "37"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "34"));

            return mapTemplate;
		}
    }
}

