
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate dkr()
        {

var mapTemplate = new MapTemplate("dkr") { Image = "dkr.png" };
var country1 = new CountryTemplate("1", "Flensburg") { X = 283, Y = 129 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Schleswig") { X = 317, Y = 218 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Itzehoe") { X = 354, Y = 292 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "HH") { X = 355, Y = 329 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "HL") { X = 394, Y = 295 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "HB") { X = 260, Y = 344 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Aurich") { X = 149, Y = 348 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "LIngen") { X = 137, Y = 424 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "OS") { X = 200, Y = 447 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Hameln") { X = 286, Y = 428 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Hannover") { X = 318, Y = 371 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Stade") { X = 278, Y = 311 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Celle") { X = 388, Y = 376 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "OB") { X = 204, Y = 345 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Vechta") { X = 203, Y = 376 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Rostock") { X = 509, Y = 259 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Schwerin") { X = 448, Y = 308 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Waren") { X = 527, Y = 303 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "NBG") { X = 596, Y = 329 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Strelitz") { X = 564, Y = 362 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Stralsund") { X = 595, Y = 276 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Stettin") { X = 722, Y = 326 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Stargard") { X = 777, Y = 293 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Colberg") { X = 816, Y = 263 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Stolp") { X = 868, Y = 202 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "BS") { X = 366, Y = 423 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "WB") { X = 412, Y = 440 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "HM") { X = 304, Y = 487 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Seesen") { X = 360, Y = 502 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Danzig") { X = 945, Y = 228 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Graudenz") { X = 924, Y = 274 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Elbing") { X = 1007, Y = 243 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Thorn") { X = 988, Y = 334 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Königsberg") { X = 1133, Y = 164 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Allenstein") { X = 1145, Y = 273 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Tilsit") { X = 1210, Y = 106 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Bromberg") { X = 929, Y = 356 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Posen") { X = 852, Y = 418 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Gnesen") { X = 933, Y = 403 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Lissa") { X = 808, Y = 464 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Ostrowo") { X = 900, Y = 495 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Gleiwitz") { X = 976, Y = 722 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Königshütte") { X = 1007, Y = 673 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Beuthen") { X = 977, Y = 625 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Oppeln") { X = 886, Y = 605 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Breslau") { X = 826, Y = 617 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Glogau") { X = 832, Y = 551 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Liegnitz") { X = 753, Y = 571 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Küstrin") { X = 725, Y = 409 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Frankfurt a. O.") { X = 715, Y = 495 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Templin") { X = 642, Y = 373 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Berlin") { X = 639, Y = 444 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Potsdam") { X = 641, Y = 529 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Neuruppin") { X = 512, Y = 389 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Stendal") { X = 493, Y = 439 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Magdeburg") { X = 458, Y = 466 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Eisleben") { X = 399, Y = 591 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Halle") { X = 450, Y = 578 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Torgau") { X = 527, Y = 559 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "WF") { X = 484, Y = 615 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Ballenstedt") { X = 399, Y = 497 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Cöthen") { X = 529, Y = 521 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Dessau") { X = 552, Y = 489 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Detmold") { X = 226, Y = 513 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Lemgo") { X = 265, Y = 514 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Höxter") { X = 333, Y = 538 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Hamm") { X = 193, Y = 544 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Dortmund") { X = 184, Y = 604 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Münster") { X = 131, Y = 515 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Essen") { X = 70, Y = 552 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Düsseldorf") { X = 58, Y = 620 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Köln") { X = 118, Y = 666 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Bonn") { X = 48, Y = 698 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Koblenz") { X = 106, Y = 746 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Trier") { X = 65, Y = 777 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Kassel") { X = 273, Y = 607 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Wiesbaden") { X = 168, Y = 688 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Marburg") { X = 309, Y = 672 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Frankfurt a M") { X = 209, Y = 714 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "ESA") { X = 354, Y = 652 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Weimar") { X = 438, Y = 639 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Gotha") { X = 397, Y = 649 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Coburg") { X = 446, Y = 753 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Roda") { X = 436, Y = 682 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "ABG") { X = 513, Y = 653 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Leipzig") { X = 547, Y = 602 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Dresden") { X = 634, Y = 625 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Chemnitz") { X = 545, Y = 683 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Giessen") { X = 249, Y = 667 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Mainz") { X = 158, Y = 754 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Darmstadt") { X = 236, Y = 772 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Metz") { X = 43, Y = 859 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Strassburg") { X = 123, Y = 912 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Colma") { X = 90, Y = 981 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Karlsruhe") { X = 214, Y = 859 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Freiburg") { X = 152, Y = 965 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Heilbronn") { X = 301, Y = 851 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Stuttgard") { X = 216, Y = 925 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Aalen") { X = 298, Y = 930 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Ulm") { X = 301, Y = 980 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "KL") { X = 115, Y = 820 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "Pirmasens") { X = 170, Y = 830 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "Würzburg") { X = 324, Y = 758 };
mapTemplate.Countries.Add(country103);
var country104 = new CountryTemplate("104", "Nürnberg") { X = 466, Y = 807 };
mapTemplate.Countries.Add(country104);
var country105 = new CountryTemplate("105", "Augsburg") { X = 397, Y = 899 };
mapTemplate.Countries.Add(country105);
var country106 = new CountryTemplate("106", "Regensburg") { X = 523, Y = 851 };
mapTemplate.Countries.Add(country106);
var country107 = new CountryTemplate("107", "Passau") { X = 562, Y = 927 };
mapTemplate.Countries.Add(country107);
var country108 = new CountryTemplate("108", "München") { X = 435, Y = 995 };
mapTemplate.Countries.Add(country108);
var country109 = new CountryTemplate("109", "Meiningen") { X = 372, Y = 708 };
mapTemplate.Countries.Add(country109);
var country110 = new CountryTemplate("110", "Sonneberg") { X = 439, Y = 722 };
mapTemplate.Countries.Add(country110);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country4);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country7);
continent3.Countries.Add(country8);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 1);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 1);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 3);
continent7.Countries.Add(country21);
continent7.Countries.Add(country22);
continent7.Countries.Add(country23);
continent7.Countries.Add(country24);
continent7.Countries.Add(country25);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country26);
continent8.Countries.Add(country27);
continent8.Countries.Add(country28);
continent8.Countries.Add(country29);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country30);
continent9.Countries.Add(country31);
continent9.Countries.Add(country32);
continent9.Countries.Add(country33);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 2);
continent10.Countries.Add(country34);
continent10.Countries.Add(country35);
continent10.Countries.Add(country36);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country37);
continent11.Countries.Add(country38);
continent11.Countries.Add(country39);
continent11.Countries.Add(country40);
continent11.Countries.Add(country41);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 4);
continent12.Countries.Add(country42);
continent12.Countries.Add(country43);
continent12.Countries.Add(country44);
continent12.Countries.Add(country45);
continent12.Countries.Add(country46);
continent12.Countries.Add(country47);
continent12.Countries.Add(country48);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 4);
continent13.Countries.Add(country49);
continent13.Countries.Add(country50);
continent13.Countries.Add(country51);
continent13.Countries.Add(country52);
continent13.Countries.Add(country53);
continent13.Countries.Add(country54);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 4);
continent14.Countries.Add(country55);
continent14.Countries.Add(country56);
continent14.Countries.Add(country57);
continent14.Countries.Add(country58);
continent14.Countries.Add(country59);
continent14.Countries.Add(country60);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 2);
continent15.Countries.Add(country61);
continent15.Countries.Add(country62);
continent15.Countries.Add(country63);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 1);
continent16.Countries.Add(country64);
continent16.Countries.Add(country65);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 3);
continent17.Countries.Add(country66);
continent17.Countries.Add(country67);
continent17.Countries.Add(country68);
continent17.Countries.Add(country69);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 4);
continent18.Countries.Add(country70);
continent18.Countries.Add(country71);
continent18.Countries.Add(country72);
continent18.Countries.Add(country73);
continent18.Countries.Add(country74);
continent18.Countries.Add(country75);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 3);
continent19.Countries.Add(country76);
continent19.Countries.Add(country77);
continent19.Countries.Add(country78);
continent19.Countries.Add(country79);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 1);
continent20.Countries.Add(country80);
continent20.Countries.Add(country81);
mapTemplate.Continents.Add(continent20);
var continent21 = new Continent("21", 1);
continent21.Countries.Add(country82);
continent21.Countries.Add(country83);
mapTemplate.Continents.Add(continent21);
var continent22 = new Continent("22", 1);
continent22.Countries.Add(country84);
continent22.Countries.Add(country85);
mapTemplate.Continents.Add(continent22);
var continent23 = new Continent("23", 2);
continent23.Countries.Add(country86);
continent23.Countries.Add(country87);
continent23.Countries.Add(country88);
mapTemplate.Continents.Add(continent23);
var continent24 = new Continent("24", 2);
continent24.Countries.Add(country89);
continent24.Countries.Add(country90);
continent24.Countries.Add(country91);
mapTemplate.Continents.Add(continent24);
var continent25 = new Continent("25", 2);
continent25.Countries.Add(country92);
continent25.Countries.Add(country93);
continent25.Countries.Add(country94);
mapTemplate.Continents.Add(continent25);
var continent26 = new Continent("26", 1);
continent26.Countries.Add(country95);
continent26.Countries.Add(country96);
mapTemplate.Continents.Add(continent26);
var continent27 = new Continent("27", 3);
continent27.Countries.Add(country97);
continent27.Countries.Add(country98);
continent27.Countries.Add(country99);
continent27.Countries.Add(country100);
mapTemplate.Continents.Add(continent27);
var continent28 = new Continent("28", 5);
continent28.Countries.Add(country101);
continent28.Countries.Add(country102);
continent28.Countries.Add(country103);
continent28.Countries.Add(country104);
continent28.Countries.Add(country105);
continent28.Countries.Add(country106);
continent28.Countries.Add(country107);
continent28.Countries.Add(country108);
mapTemplate.Continents.Add(continent28);
var continent29 = new Continent("29", 1);
continent29.Countries.Add(country109);
continent29.Countries.Add(country110);
mapTemplate.Continents.Add(continent29);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "13"));
mapTemplate.Connections.Add(new Connection("3", "17"));
mapTemplate.Connections.Add(new Connection("4", "12"));
mapTemplate.Connections.Add(new Connection("4", "13"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "17"));
mapTemplate.Connections.Add(new Connection("6", "14"));
mapTemplate.Connections.Add(new Connection("6", "12"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "14"));
mapTemplate.Connections.Add(new Connection("8", "69"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "15"));
mapTemplate.Connections.Add(new Connection("8", "14"));
mapTemplate.Connections.Add(new Connection("9", "69"));
mapTemplate.Connections.Add(new Connection("9", "67"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "15"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "67"));
mapTemplate.Connections.Add(new Connection("10", "29"));
mapTemplate.Connections.Add(new Connection("10", "28"));
mapTemplate.Connections.Add(new Connection("10", "26"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "15"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "56"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "26"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "6"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "4"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "4"));
mapTemplate.Connections.Add(new Connection("13", "3"));
mapTemplate.Connections.Add(new Connection("13", "17"));
mapTemplate.Connections.Add(new Connection("13", "54"));
mapTemplate.Connections.Add(new Connection("13", "55"));
mapTemplate.Connections.Add(new Connection("13", "26"));
mapTemplate.Connections.Add(new Connection("13", "27"));
mapTemplate.Connections.Add(new Connection("14", "7"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "6"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "8"));
mapTemplate.Connections.Add(new Connection("15", "9"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "8"));
mapTemplate.Connections.Add(new Connection("15", "10"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "21"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "5"));
mapTemplate.Connections.Add(new Connection("17", "3"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "54"));
mapTemplate.Connections.Add(new Connection("17", "13"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "54"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "51"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "54"));
mapTemplate.Connections.Add(new Connection("20", "51"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "16"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "49"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "51"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("23", "31"));
mapTemplate.Connections.Add(new Connection("23", "49"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "31"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "30"));
mapTemplate.Connections.Add(new Connection("25", "30"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("26", "10"));
mapTemplate.Connections.Add(new Connection("26", "56"));
mapTemplate.Connections.Add(new Connection("26", "11"));
mapTemplate.Connections.Add(new Connection("26", "13"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "56"));
mapTemplate.Connections.Add(new Connection("27", "55"));
mapTemplate.Connections.Add(new Connection("27", "13"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("28", "64"));
mapTemplate.Connections.Add(new Connection("28", "65"));
mapTemplate.Connections.Add(new Connection("28", "66"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "10"));
mapTemplate.Connections.Add(new Connection("28", "67"));
mapTemplate.Connections.Add(new Connection("29", "66"));
mapTemplate.Connections.Add(new Connection("29", "61"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "10"));
mapTemplate.Connections.Add(new Connection("29", "56"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "25"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "24"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "24"));
mapTemplate.Connections.Add(new Connection("31", "23"));
mapTemplate.Connections.Add(new Connection("31", "38"));
mapTemplate.Connections.Add(new Connection("31", "37"));
mapTemplate.Connections.Add(new Connection("31", "49"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "37"));
mapTemplate.Connections.Add(new Connection("33", "39"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("37", "33"));
mapTemplate.Connections.Add(new Connection("37", "31"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("38", "31"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "49"));
mapTemplate.Connections.Add(new Connection("39", "33"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "47"));
mapTemplate.Connections.Add(new Connection("40", "50"));
mapTemplate.Connections.Add(new Connection("40", "49"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("41", "45"));
mapTemplate.Connections.Add(new Connection("41", "47"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "41"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("47", "41"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "40"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("48", "53"));
mapTemplate.Connections.Add(new Connection("48", "87"));
mapTemplate.Connections.Add(new Connection("48", "59"));
mapTemplate.Connections.Add(new Connection("49", "40"));
mapTemplate.Connections.Add(new Connection("49", "38"));
mapTemplate.Connections.Add(new Connection("49", "52"));
mapTemplate.Connections.Add(new Connection("49", "22"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "23"));
mapTemplate.Connections.Add(new Connection("49", "31"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "40"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "52"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "22"));
mapTemplate.Connections.Add(new Connection("51", "20"));
mapTemplate.Connections.Add(new Connection("51", "19"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "49"));
mapTemplate.Connections.Add(new Connection("52", "50"));
mapTemplate.Connections.Add(new Connection("53", "48"));
mapTemplate.Connections.Add(new Connection("53", "59"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "63"));
mapTemplate.Connections.Add(new Connection("54", "17"));
mapTemplate.Connections.Add(new Connection("54", "18"));
mapTemplate.Connections.Add(new Connection("54", "13"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "63"));
mapTemplate.Connections.Add(new Connection("54", "20"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "13"));
mapTemplate.Connections.Add(new Connection("55", "63"));
mapTemplate.Connections.Add(new Connection("55", "27"));
mapTemplate.Connections.Add(new Connection("56", "58"));
mapTemplate.Connections.Add(new Connection("56", "61"));
mapTemplate.Connections.Add(new Connection("56", "27"));
mapTemplate.Connections.Add(new Connection("56", "26"));
mapTemplate.Connections.Add(new Connection("56", "62"));
mapTemplate.Connections.Add(new Connection("56", "63"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "29"));
mapTemplate.Connections.Add(new Connection("56", "10"));
mapTemplate.Connections.Add(new Connection("57", "76"));
mapTemplate.Connections.Add(new Connection("57", "66"));
mapTemplate.Connections.Add(new Connection("57", "80"));
mapTemplate.Connections.Add(new Connection("57", "82"));
mapTemplate.Connections.Add(new Connection("57", "81"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("58", "66"));
mapTemplate.Connections.Add(new Connection("58", "81"));
mapTemplate.Connections.Add(new Connection("58", "60"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "61"));
mapTemplate.Connections.Add(new Connection("58", "56"));
mapTemplate.Connections.Add(new Connection("58", "62"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "86"));
mapTemplate.Connections.Add(new Connection("59", "48"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "86"));
mapTemplate.Connections.Add(new Connection("59", "87"));
mapTemplate.Connections.Add(new Connection("59", "53"));
mapTemplate.Connections.Add(new Connection("59", "63"));
mapTemplate.Connections.Add(new Connection("59", "62"));
mapTemplate.Connections.Add(new Connection("60", "81"));
mapTemplate.Connections.Add(new Connection("60", "84"));
mapTemplate.Connections.Add(new Connection("60", "85"));
mapTemplate.Connections.Add(new Connection("60", "88"));
mapTemplate.Connections.Add(new Connection("60", "86"));
mapTemplate.Connections.Add(new Connection("60", "58"));
mapTemplate.Connections.Add(new Connection("61", "66"));
mapTemplate.Connections.Add(new Connection("61", "58"));
mapTemplate.Connections.Add(new Connection("61", "29"));
mapTemplate.Connections.Add(new Connection("61", "56"));
mapTemplate.Connections.Add(new Connection("62", "58"));
mapTemplate.Connections.Add(new Connection("62", "56"));
mapTemplate.Connections.Add(new Connection("62", "59"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "56"));
mapTemplate.Connections.Add(new Connection("63", "59"));
mapTemplate.Connections.Add(new Connection("63", "54"));
mapTemplate.Connections.Add(new Connection("63", "55"));
mapTemplate.Connections.Add(new Connection("63", "53"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("64", "67"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "28"));
mapTemplate.Connections.Add(new Connection("65", "67"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "28"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "76"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "57"));
mapTemplate.Connections.Add(new Connection("66", "28"));
mapTemplate.Connections.Add(new Connection("66", "29"));
mapTemplate.Connections.Add(new Connection("66", "61"));
mapTemplate.Connections.Add(new Connection("66", "58"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "69"));
mapTemplate.Connections.Add(new Connection("67", "9"));
mapTemplate.Connections.Add(new Connection("67", "10"));
mapTemplate.Connections.Add(new Connection("67", "64"));
mapTemplate.Connections.Add(new Connection("67", "65"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "76"));
mapTemplate.Connections.Add(new Connection("67", "28"));
mapTemplate.Connections.Add(new Connection("68", "71"));
mapTemplate.Connections.Add(new Connection("68", "70"));
mapTemplate.Connections.Add(new Connection("68", "72"));
mapTemplate.Connections.Add(new Connection("68", "77"));
mapTemplate.Connections.Add(new Connection("68", "76"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("69", "67"));
mapTemplate.Connections.Add(new Connection("69", "9"));
mapTemplate.Connections.Add(new Connection("69", "8"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "68"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("71", "73"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "68"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("72", "74"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "68"));
mapTemplate.Connections.Add(new Connection("72", "77"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "71"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("74", "101"));
mapTemplate.Connections.Add(new Connection("74", "90"));
mapTemplate.Connections.Add(new Connection("74", "77"));
mapTemplate.Connections.Add(new Connection("74", "72"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("75", "92"));
mapTemplate.Connections.Add(new Connection("75", "101"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "89"));
mapTemplate.Connections.Add(new Connection("76", "78"));
mapTemplate.Connections.Add(new Connection("76", "68"));
mapTemplate.Connections.Add(new Connection("76", "67"));
mapTemplate.Connections.Add(new Connection("76", "57"));
mapTemplate.Connections.Add(new Connection("76", "80"));
mapTemplate.Connections.Add(new Connection("76", "66"));
mapTemplate.Connections.Add(new Connection("77", "74"));
mapTemplate.Connections.Add(new Connection("77", "72"));
mapTemplate.Connections.Add(new Connection("77", "90"));
mapTemplate.Connections.Add(new Connection("77", "68"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "89"));
mapTemplate.Connections.Add(new Connection("77", "79"));
mapTemplate.Connections.Add(new Connection("77", "91"));
mapTemplate.Connections.Add(new Connection("78", "103"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("78", "109"));
mapTemplate.Connections.Add(new Connection("78", "89"));
mapTemplate.Connections.Add(new Connection("78", "76"));
mapTemplate.Connections.Add(new Connection("78", "80"));
mapTemplate.Connections.Add(new Connection("79", "103"));
mapTemplate.Connections.Add(new Connection("79", "91"));
mapTemplate.Connections.Add(new Connection("79", "77"));
mapTemplate.Connections.Add(new Connection("79", "89"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("80", "109"));
mapTemplate.Connections.Add(new Connection("80", "78"));
mapTemplate.Connections.Add(new Connection("80", "76"));
mapTemplate.Connections.Add(new Connection("80", "57"));
mapTemplate.Connections.Add(new Connection("80", "82"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("81", "57"));
mapTemplate.Connections.Add(new Connection("81", "58"));
mapTemplate.Connections.Add(new Connection("81", "60"));
mapTemplate.Connections.Add(new Connection("81", "84"));
mapTemplate.Connections.Add(new Connection("82", "110"));
mapTemplate.Connections.Add(new Connection("82", "109"));
mapTemplate.Connections.Add(new Connection("82", "80"));
mapTemplate.Connections.Add(new Connection("82", "57"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("82", "84"));
mapTemplate.Connections.Add(new Connection("83", "103"));
mapTemplate.Connections.Add(new Connection("83", "104"));
mapTemplate.Connections.Add(new Connection("83", "110"));
mapTemplate.Connections.Add(new Connection("83", "109"));
mapTemplate.Connections.Add(new Connection("84", "110"));
mapTemplate.Connections.Add(new Connection("84", "82"));
mapTemplate.Connections.Add(new Connection("84", "81"));
mapTemplate.Connections.Add(new Connection("84", "60"));
mapTemplate.Connections.Add(new Connection("84", "88"));
mapTemplate.Connections.Add(new Connection("85", "60"));
mapTemplate.Connections.Add(new Connection("85", "88"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("86", "60"));
mapTemplate.Connections.Add(new Connection("86", "59"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "58"));
mapTemplate.Connections.Add(new Connection("87", "48"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "59"));
mapTemplate.Connections.Add(new Connection("88", "104"));
mapTemplate.Connections.Add(new Connection("88", "110"));
mapTemplate.Connections.Add(new Connection("88", "84"));
mapTemplate.Connections.Add(new Connection("88", "85"));
mapTemplate.Connections.Add(new Connection("88", "86"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "60"));
mapTemplate.Connections.Add(new Connection("89", "77"));
mapTemplate.Connections.Add(new Connection("89", "79"));
mapTemplate.Connections.Add(new Connection("89", "76"));
mapTemplate.Connections.Add(new Connection("89", "78"));
mapTemplate.Connections.Add(new Connection("90", "74"));
mapTemplate.Connections.Add(new Connection("90", "101"));
mapTemplate.Connections.Add(new Connection("90", "102"));
mapTemplate.Connections.Add(new Connection("90", "95"));
mapTemplate.Connections.Add(new Connection("90", "91"));
mapTemplate.Connections.Add(new Connection("90", "77"));
mapTemplate.Connections.Add(new Connection("91", "95"));
mapTemplate.Connections.Add(new Connection("91", "103"));
mapTemplate.Connections.Add(new Connection("91", "79"));
mapTemplate.Connections.Add(new Connection("91", "90"));
mapTemplate.Connections.Add(new Connection("91", "77"));
mapTemplate.Connections.Add(new Connection("92", "93"));
mapTemplate.Connections.Add(new Connection("92", "101"));
mapTemplate.Connections.Add(new Connection("92", "75"));
mapTemplate.Connections.Add(new Connection("93", "96"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "92"));
mapTemplate.Connections.Add(new Connection("93", "101"));
mapTemplate.Connections.Add(new Connection("93", "102"));
mapTemplate.Connections.Add(new Connection("93", "95"));
mapTemplate.Connections.Add(new Connection("94", "96"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("95", "96"));
mapTemplate.Connections.Add(new Connection("95", "93"));
mapTemplate.Connections.Add(new Connection("95", "102"));
mapTemplate.Connections.Add(new Connection("95", "98"));
mapTemplate.Connections.Add(new Connection("95", "90"));
mapTemplate.Connections.Add(new Connection("95", "91"));
mapTemplate.Connections.Add(new Connection("95", "103"));
mapTemplate.Connections.Add(new Connection("95", "97"));
mapTemplate.Connections.Add(new Connection("96", "100"));
mapTemplate.Connections.Add(new Connection("96", "98"));
mapTemplate.Connections.Add(new Connection("96", "95"));
mapTemplate.Connections.Add(new Connection("96", "93"));
mapTemplate.Connections.Add(new Connection("96", "94"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "99"));
mapTemplate.Connections.Add(new Connection("97", "95"));
mapTemplate.Connections.Add(new Connection("97", "105"));
mapTemplate.Connections.Add(new Connection("97", "103"));
mapTemplate.Connections.Add(new Connection("98", "100"));
mapTemplate.Connections.Add(new Connection("98", "96"));
mapTemplate.Connections.Add(new Connection("98", "95"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("99", "100"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("99", "105"));
mapTemplate.Connections.Add(new Connection("99", "97"));
mapTemplate.Connections.Add(new Connection("100", "108"));
mapTemplate.Connections.Add(new Connection("100", "105"));
mapTemplate.Connections.Add(new Connection("100", "99"));
mapTemplate.Connections.Add(new Connection("100", "98"));
mapTemplate.Connections.Add(new Connection("100", "96"));
mapTemplate.Connections.Add(new Connection("101", "93"));
mapTemplate.Connections.Add(new Connection("101", "92"));
mapTemplate.Connections.Add(new Connection("101", "75"));
mapTemplate.Connections.Add(new Connection("101", "74"));
mapTemplate.Connections.Add(new Connection("101", "102"));
mapTemplate.Connections.Add(new Connection("101", "90"));
mapTemplate.Connections.Add(new Connection("102", "93"));
mapTemplate.Connections.Add(new Connection("102", "101"));
mapTemplate.Connections.Add(new Connection("102", "90"));
mapTemplate.Connections.Add(new Connection("102", "95"));
mapTemplate.Connections.Add(new Connection("103", "105"));
mapTemplate.Connections.Add(new Connection("103", "95"));
mapTemplate.Connections.Add(new Connection("103", "91"));
mapTemplate.Connections.Add(new Connection("103", "79"));
mapTemplate.Connections.Add(new Connection("103", "78"));
mapTemplate.Connections.Add(new Connection("103", "109"));
mapTemplate.Connections.Add(new Connection("103", "83"));
mapTemplate.Connections.Add(new Connection("103", "104"));
mapTemplate.Connections.Add(new Connection("103", "97"));
mapTemplate.Connections.Add(new Connection("104", "106"));
mapTemplate.Connections.Add(new Connection("104", "105"));
mapTemplate.Connections.Add(new Connection("104", "103"));
mapTemplate.Connections.Add(new Connection("104", "88"));
mapTemplate.Connections.Add(new Connection("104", "110"));
mapTemplate.Connections.Add(new Connection("104", "83"));
mapTemplate.Connections.Add(new Connection("105", "108"));
mapTemplate.Connections.Add(new Connection("105", "107"));
mapTemplate.Connections.Add(new Connection("105", "106"));
mapTemplate.Connections.Add(new Connection("105", "100"));
mapTemplate.Connections.Add(new Connection("105", "99"));
mapTemplate.Connections.Add(new Connection("105", "104"));
mapTemplate.Connections.Add(new Connection("105", "103"));
mapTemplate.Connections.Add(new Connection("105", "97"));
mapTemplate.Connections.Add(new Connection("106", "107"));
mapTemplate.Connections.Add(new Connection("106", "105"));
mapTemplate.Connections.Add(new Connection("106", "104"));
mapTemplate.Connections.Add(new Connection("107", "108"));
mapTemplate.Connections.Add(new Connection("107", "105"));
mapTemplate.Connections.Add(new Connection("107", "106"));
mapTemplate.Connections.Add(new Connection("108", "100"));
mapTemplate.Connections.Add(new Connection("108", "105"));
mapTemplate.Connections.Add(new Connection("108", "107"));
mapTemplate.Connections.Add(new Connection("109", "103"));
mapTemplate.Connections.Add(new Connection("109", "83"));
mapTemplate.Connections.Add(new Connection("109", "110"));
mapTemplate.Connections.Add(new Connection("109", "78"));
mapTemplate.Connections.Add(new Connection("109", "80"));
mapTemplate.Connections.Add(new Connection("109", "82"));
mapTemplate.Connections.Add(new Connection("110", "104"));
mapTemplate.Connections.Add(new Connection("110", "83"));
mapTemplate.Connections.Add(new Connection("110", "88"));
mapTemplate.Connections.Add(new Connection("110", "84"));
mapTemplate.Connections.Add(new Connection("110", "82"));
mapTemplate.Connections.Add(new Connection("110", "109"));

            return mapTemplate;
		}
    }
}

