using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Infractus()
        {
            var mapTemplate = new MapTemplate("Infractus") { Image = "infractus.jpg" };
            var country1 = new CountryTemplate("1", "Kasch") { X = 22, Y = 210 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Suven") { X = 349, Y = 41 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Aschkent") { X = 222, Y = 107 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Schandra") { X = 127, Y = 25 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Knutziea") { X = 37, Y = 569 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Alitania") { X = 264, Y = 569 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Tomasu") { X = 660, Y = 29 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Patorikku") { X = 503, Y = 65 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Qian") { X = 1038, Y = 230 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Nirusu") { X = 392, Y = 127 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Arekusandora") { X = 351, Y = 206 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Heinthricha") { X = 310, Y = 739 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Xian") { X = 971, Y = 14 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Shianlian") { X = 1193, Y = 88 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Shao-Mia") { X = 1063, Y = 142 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Lunnae") { X = 382, Y = 585 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Timeifoi") { X = 318, Y = 597 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Alo") { X = 540, Y = 485 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Lubecea") { X = 131, Y = 547 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Natasshaf") { X = 386, Y = 252 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Keksck") { X = 249, Y = 328 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Genosien") { X = 1155, Y = 372 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Impernia") { X = 1214, Y = 477 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Torunia") { X = 1012, Y = 484 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Burycia") { X = 1030, Y = 359 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Tuvin") { X = 911, Y = 399 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Xantlo") { X = 1138, Y = 676 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Hydutknoi") { X = 151, Y = 733 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Keschan") { X = 214, Y = 210 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Kiakao") { X = 580, Y = 317 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Fuu") { X = 578, Y = 419 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Schendora") { X = 881, Y = 251 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Beragiora") { X = 778, Y = 323 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Wasglttli") { X = 1228, Y = 633 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Axtli") { X = 1243, Y = 745 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Melbeco") { X = 874, Y = 533 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Verpicio") { X = 1102, Y = 587 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Ildecia") { X = 1127, Y = 499 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Digiss") { X = 466, Y = 387 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Sirrisa") { X = 1200, Y = 241 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Zhou") { X = 996, Y = 89 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Moalxia") { X = 1181, Y = 764 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Kalonia") { X = 1232, Y = 524 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Landarsi") { X = 727, Y = 392 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Locsheada") { X = 948, Y = 189 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Kataleois") { X = 494, Y = 748 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Roneos") { X = 29, Y = 713 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Heren") { X = 446, Y = 158 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Oora") { X = 604, Y = 71 };
            mapTemplate.Countries.Add(country49);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country3);
            continent2.Countries.Add(country4);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 6);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            continent3.Countries.Add(country12);
            continent3.Countries.Add(country13);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country15);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country7);
            continent4.Countries.Add(country8);
            continent4.Countries.Add(country9);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country16);
            continent5.Countries.Add(country17);
            continent5.Countries.Add(country18);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country19);
            continent6.Countries.Add(country20);
            continent6.Countries.Add(country21);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 3);
            continent7.Countries.Add(country22);
            continent7.Countries.Add(country23);
            continent7.Countries.Add(country24);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country25);
            continent8.Countries.Add(country26);
            continent8.Countries.Add(country27);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 4);
            continent9.Countries.Add(country28);
            continent9.Countries.Add(country29);
            continent9.Countries.Add(country30);
            continent9.Countries.Add(country31);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 4);
            continent10.Countries.Add(country32);
            continent10.Countries.Add(country33);
            continent10.Countries.Add(country34);
            continent10.Countries.Add(country35);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 4);
            continent11.Countries.Add(country36);
            continent11.Countries.Add(country37);
            continent11.Countries.Add(country38);
            continent11.Countries.Add(country39);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 2);
            continent12.Countries.Add(country40);
            continent12.Countries.Add(country41);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 2);
            continent13.Countries.Add(country42);
            continent13.Countries.Add(country43);
            mapTemplate.Continents.Add(continent13);
            var continent14 = new Continent("14", 2);
            continent14.Countries.Add(country44);
            continent14.Countries.Add(country45);
            mapTemplate.Continents.Add(continent14);
            var continent15 = new Continent("15", 4);
            continent15.Countries.Add(country46);
            continent15.Countries.Add(country47);
            continent15.Countries.Add(country48);
            continent15.Countries.Add(country49);
            mapTemplate.Continents.Add(continent15);
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "11"));
            mapTemplate.Connections.Add(new Connection("2", "10"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "11"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("5", "19"));
            mapTemplate.Connections.Add(new Connection("5", "47"));
            mapTemplate.Connections.Add(new Connection("6", "12"));
            mapTemplate.Connections.Add(new Connection("6", "17"));
            mapTemplate.Connections.Add(new Connection("6", "16"));
            mapTemplate.Connections.Add(new Connection("6", "21"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "49"));
            mapTemplate.Connections.Add(new Connection("7", "20"));
            mapTemplate.Connections.Add(new Connection("7", "13"));
            mapTemplate.Connections.Add(new Connection("8", "48"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "49"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("9", "45"));
            mapTemplate.Connections.Add(new Connection("9", "15"));
            mapTemplate.Connections.Add(new Connection("9", "40"));
            mapTemplate.Connections.Add(new Connection("9", "25"));
            mapTemplate.Connections.Add(new Connection("9", "22"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "2"));
            mapTemplate.Connections.Add(new Connection("10", "48"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("11", "1"));
            mapTemplate.Connections.Add(new Connection("11", "3"));
            mapTemplate.Connections.Add(new Connection("11", "20"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "48"));
            mapTemplate.Connections.Add(new Connection("12", "47"));
            mapTemplate.Connections.Add(new Connection("12", "19"));
            mapTemplate.Connections.Add(new Connection("12", "28"));
            mapTemplate.Connections.Add(new Connection("12", "46"));
            mapTemplate.Connections.Add(new Connection("12", "6"));
            mapTemplate.Connections.Add(new Connection("13", "41"));
            mapTemplate.Connections.Add(new Connection("13", "7"));
            mapTemplate.Connections.Add(new Connection("13", "32"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "40"));
            mapTemplate.Connections.Add(new Connection("15", "45"));
            mapTemplate.Connections.Add(new Connection("15", "41"));
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "9"));
            mapTemplate.Connections.Add(new Connection("15", "40"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "6"));
            mapTemplate.Connections.Add(new Connection("17", "6"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("18", "31"));
            mapTemplate.Connections.Add(new Connection("18", "46"));
            mapTemplate.Connections.Add(new Connection("19", "5"));
            mapTemplate.Connections.Add(new Connection("19", "47"));
            mapTemplate.Connections.Add(new Connection("19", "12"));
            mapTemplate.Connections.Add(new Connection("20", "29"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "11"));
            mapTemplate.Connections.Add(new Connection("20", "48"));
            mapTemplate.Connections.Add(new Connection("20", "7"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "6"));
            mapTemplate.Connections.Add(new Connection("21", "30"));
            mapTemplate.Connections.Add(new Connection("22", "25"));
            mapTemplate.Connections.Add(new Connection("22", "9"));
            mapTemplate.Connections.Add(new Connection("22", "40"));
            mapTemplate.Connections.Add(new Connection("23", "43"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "38"));
            mapTemplate.Connections.Add(new Connection("25", "9"));
            mapTemplate.Connections.Add(new Connection("25", "22"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("26", "32"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "36"));
            mapTemplate.Connections.Add(new Connection("27", "37"));
            mapTemplate.Connections.Add(new Connection("27", "34"));
            mapTemplate.Connections.Add(new Connection("27", "42"));
            mapTemplate.Connections.Add(new Connection("27", "46"));
            mapTemplate.Connections.Add(new Connection("27", "44"));
            mapTemplate.Connections.Add(new Connection("27", "35"));
            mapTemplate.Connections.Add(new Connection("28", "47"));
            mapTemplate.Connections.Add(new Connection("28", "12"));
            mapTemplate.Connections.Add(new Connection("29", "20"));
            mapTemplate.Connections.Add(new Connection("30", "39"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "21"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "39"));
            mapTemplate.Connections.Add(new Connection("31", "18"));
            mapTemplate.Connections.Add(new Connection("32", "13"));
            mapTemplate.Connections.Add(new Connection("32", "45"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "26"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "44"));
            mapTemplate.Connections.Add(new Connection("34", "43"));
            mapTemplate.Connections.Add(new Connection("34", "38"));
            mapTemplate.Connections.Add(new Connection("34", "27"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "37"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "42"));
            mapTemplate.Connections.Add(new Connection("35", "27"));
            mapTemplate.Connections.Add(new Connection("36", "26"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "27"));
            mapTemplate.Connections.Add(new Connection("37", "34"));
            mapTemplate.Connections.Add(new Connection("38", "24"));
            mapTemplate.Connections.Add(new Connection("38", "43"));
            mapTemplate.Connections.Add(new Connection("38", "34"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("39", "30"));
            mapTemplate.Connections.Add(new Connection("39", "31"));
            mapTemplate.Connections.Add(new Connection("40", "15"));
            mapTemplate.Connections.Add(new Connection("40", "14"));
            mapTemplate.Connections.Add(new Connection("40", "9"));
            mapTemplate.Connections.Add(new Connection("40", "22"));
            mapTemplate.Connections.Add(new Connection("41", "13"));
            mapTemplate.Connections.Add(new Connection("41", "45"));
            mapTemplate.Connections.Add(new Connection("41", "15"));
            mapTemplate.Connections.Add(new Connection("42", "35"));
            mapTemplate.Connections.Add(new Connection("42", "27"));
            mapTemplate.Connections.Add(new Connection("43", "38"));
            mapTemplate.Connections.Add(new Connection("43", "23"));
            mapTemplate.Connections.Add(new Connection("43", "34"));
            mapTemplate.Connections.Add(new Connection("44", "33"));
            mapTemplate.Connections.Add(new Connection("44", "27"));
            mapTemplate.Connections.Add(new Connection("45", "41"));
            mapTemplate.Connections.Add(new Connection("45", "15"));
            mapTemplate.Connections.Add(new Connection("45", "32"));
            mapTemplate.Connections.Add(new Connection("45", "9"));
            mapTemplate.Connections.Add(new Connection("46", "12"));
            mapTemplate.Connections.Add(new Connection("46", "18"));
            mapTemplate.Connections.Add(new Connection("46", "27"));
            mapTemplate.Connections.Add(new Connection("47", "19"));
            mapTemplate.Connections.Add(new Connection("47", "5"));
            mapTemplate.Connections.Add(new Connection("47", "12"));
            mapTemplate.Connections.Add(new Connection("47", "28"));
            mapTemplate.Connections.Add(new Connection("48", "10"));
            mapTemplate.Connections.Add(new Connection("48", "20"));
            mapTemplate.Connections.Add(new Connection("48", "8"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "11"));
            mapTemplate.Connections.Add(new Connection("49", "8"));
            mapTemplate.Connections.Add(new Connection("49", "7"));
            mapTemplate.Connections.Add(new Connection("49", "48"));

            return mapTemplate;
        }
    }
}
