
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Niedersachsen()
        {

var mapTemplate = new MapTemplate("Niedersachsen") { Image = "niedersachsen.png" };
var country1 = new CountryTemplate("1", "Borkum") { X = 5, Y = 81 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Juist") { X = 61, Y = 52 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Norderney") { X = 121, Y = 37 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Langeoog") { X = 184, Y = 29 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Spiekeroog") { X = 243, Y = 16 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Wangerooge") { X = 313, Y = 25 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Leer") { X = 180, Y = 225 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Emden") { X = 102, Y = 192 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Aurich") { X = 155, Y = 134 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Wittmund") { X = 239, Y = 109 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Friesland") { X = 284, Y = 113 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Wilhelmshaven") { X = 323, Y = 103 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Emsland") { X = 151, Y = 400 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Cloppenburg") { X = 284, Y = 366 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Grafschaft-Bentheim") { X = 82, Y = 517 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Osnabrück") { X = 251, Y = 507 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Osnabrück Stadt") { X = 289, Y = 590 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Wesermarsch") { X = 380, Y = 199 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Oldenburg") { X = 377, Y = 318 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Oldenburg Stadt") { X = 347, Y = 273 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Ammerland") { X = 293, Y = 249 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Bremerhaven") { X = 439, Y = 118 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Bremen") { X = 479, Y = 297 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Delmenhorst") { X = 432, Y = 315 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Diepholz") { X = 446, Y = 424 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Nienburg-Weser") { X = 553, Y = 455 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Verden") { X = 559, Y = 348 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Vechta") { X = 333, Y = 453 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Cuxhaven") { X = 482, Y = 76 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Stade") { X = 610, Y = 90 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Rotenburg") { X = 583, Y = 217 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Osterholz") { X = 477, Y = 226 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Harburg") { X = 727, Y = 220 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Lüneburg") { X = 860, Y = 240 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Uelzen") { X = 858, Y = 315 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Lüchow-Dannenberg") { X = 1003, Y = 319 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Soltau-Fallingbostel") { X = 684, Y = 361 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Celle") { X = 769, Y = 418 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Helmstedt") { X = 954, Y = 601 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Wolfenbüttel") { X = 896, Y = 641 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Wolfsburg") { X = 929, Y = 542 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Braunschweig") { X = 862, Y = 599 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Salzgitter") { X = 826, Y = 650 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Peine") { X = 804, Y = 586 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Gifhorn") { X = 888, Y = 485 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Hildesheim") { X = 729, Y = 677 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Gosslar") { X = 824, Y = 742 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Osterode am Harz") { X = 856, Y = 842 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Northeim") { X = 708, Y = 797 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Holzminden") { X = 640, Y = 756 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Göttingen") { X = 714, Y = 886 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Region Hannover") { X = 686, Y = 546 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Schaumburg") { X = 566, Y = 580 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Hameln-Pyrmont") { X = 597, Y = 657 };
mapTemplate.Countries.Add(country54);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
continent4.Countries.Add(country28);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country22);
continent5.Countries.Add(country23);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country24);
continent6.Countries.Add(country25);
continent6.Countries.Add(country26);
continent6.Countries.Add(country27);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 3);
continent7.Countries.Add(country29);
continent7.Countries.Add(country30);
continent7.Countries.Add(country31);
continent7.Countries.Add(country32);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country33);
continent8.Countries.Add(country34);
continent8.Countries.Add(country35);
continent8.Countries.Add(country36);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country37);
continent9.Countries.Add(country38);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 4);
continent10.Countries.Add(country39);
continent10.Countries.Add(country40);
continent10.Countries.Add(country41);
continent10.Countries.Add(country42);
continent10.Countries.Add(country43);
continent10.Countries.Add(country44);
continent10.Countries.Add(country45);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country46);
continent11.Countries.Add(country47);
continent11.Countries.Add(country48);
continent11.Countries.Add(country49);
continent11.Countries.Add(country50);
continent11.Countries.Add(country51);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 2);
continent12.Countries.Add(country52);
continent12.Countries.Add(country53);
continent12.Countries.Add(country54);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "8"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "9"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "9"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "10"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "10"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "12"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("6", "22"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("7", "13"));
mapTemplate.Connections.Add(new Connection("7", "14"));
mapTemplate.Connections.Add(new Connection("7", "21"));
mapTemplate.Connections.Add(new Connection("8", "1"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "2"));
mapTemplate.Connections.Add(new Connection("9", "3"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "4"));
mapTemplate.Connections.Add(new Connection("10", "5"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "6"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("11", "21"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "6"));
mapTemplate.Connections.Add(new Connection("12", "22"));
mapTemplate.Connections.Add(new Connection("13", "7"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("14", "7"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "21"));
mapTemplate.Connections.Add(new Connection("14", "28"));
mapTemplate.Connections.Add(new Connection("14", "19"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "28"));
mapTemplate.Connections.Add(new Connection("16", "25"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("18", "23"));
mapTemplate.Connections.Add(new Connection("18", "24"));
mapTemplate.Connections.Add(new Connection("18", "32"));
mapTemplate.Connections.Add(new Connection("18", "29"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "28"));
mapTemplate.Connections.Add(new Connection("19", "24"));
mapTemplate.Connections.Add(new Connection("19", "25"));
mapTemplate.Connections.Add(new Connection("19", "14"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "11"));
mapTemplate.Connections.Add(new Connection("21", "7"));
mapTemplate.Connections.Add(new Connection("21", "14"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "12"));
mapTemplate.Connections.Add(new Connection("22", "29"));
mapTemplate.Connections.Add(new Connection("22", "6"));
mapTemplate.Connections.Add(new Connection("23", "18"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "32"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "19"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "18"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "19"));
mapTemplate.Connections.Add(new Connection("25", "16"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "37"));
mapTemplate.Connections.Add(new Connection("26", "53"));
mapTemplate.Connections.Add(new Connection("26", "52"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "31"));
mapTemplate.Connections.Add(new Connection("27", "32"));
mapTemplate.Connections.Add(new Connection("27", "37"));
mapTemplate.Connections.Add(new Connection("28", "14"));
mapTemplate.Connections.Add(new Connection("28", "16"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("28", "19"));
mapTemplate.Connections.Add(new Connection("29", "22"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("29", "18"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "27"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "37"));
mapTemplate.Connections.Add(new Connection("32", "29"));
mapTemplate.Connections.Add(new Connection("32", "18"));
mapTemplate.Connections.Add(new Connection("32", "23"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "37"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "45"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("37", "26"));
mapTemplate.Connections.Add(new Connection("37", "27"));
mapTemplate.Connections.Add(new Connection("37", "31"));
mapTemplate.Connections.Add(new Connection("37", "33"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "35"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "52"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "45"));
mapTemplate.Connections.Add(new Connection("38", "52"));
mapTemplate.Connections.Add(new Connection("39", "45"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "43"));
mapTemplate.Connections.Add(new Connection("40", "47"));
mapTemplate.Connections.Add(new Connection("40", "46"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("41", "45"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("42", "45"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "40"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "52"));
mapTemplate.Connections.Add(new Connection("45", "35"));
mapTemplate.Connections.Add(new Connection("45", "38"));
mapTemplate.Connections.Add(new Connection("45", "39"));
mapTemplate.Connections.Add(new Connection("45", "41"));
mapTemplate.Connections.Add(new Connection("45", "42"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "52"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "49"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "54"));
mapTemplate.Connections.Add(new Connection("46", "50"));
mapTemplate.Connections.Add(new Connection("46", "52"));
mapTemplate.Connections.Add(new Connection("46", "40"));
mapTemplate.Connections.Add(new Connection("47", "40"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "51"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "46"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("50", "46"));
mapTemplate.Connections.Add(new Connection("51", "48"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("52", "46"));
mapTemplate.Connections.Add(new Connection("52", "26"));
mapTemplate.Connections.Add(new Connection("52", "37"));
mapTemplate.Connections.Add(new Connection("52", "38"));
mapTemplate.Connections.Add(new Connection("52", "44"));
mapTemplate.Connections.Add(new Connection("52", "45"));
mapTemplate.Connections.Add(new Connection("53", "26"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "46"));
mapTemplate.Connections.Add(new Connection("54", "50"));

            return mapTemplate;
		}
    }
}

