
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Graffiti()
        {

var mapTemplate = new MapTemplate("Graffiti") { Image = "graffiti.png" };
var country1 = new CountryTemplate("1", "Stresswespe") { X = 140, Y = 53 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Ziggy") { X = 62, Y = 99 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Sunshine") { X = 114, Y = 133 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Wastl") { X = 91, Y = 234 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Sebbl") { X = 156, Y = 266 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "DerZini") { X = 96, Y = 288 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Lockhead") { X = 230, Y = 193 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Nickzj") { X = 306, Y = 187 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Alita") { X = 223, Y = 305 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Jaan") { X = 313, Y = 275 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "CoCo") { X = 392, Y = 178 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Anarki") { X = 390, Y = 275 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Shark") { X = 466, Y = 189 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Amog") { X = 597, Y = 178 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Franz") { X = 482, Y = 260 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "spqr") { X = 578, Y = 247 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Allo") { X = 473, Y = 323 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Luis") { X = 507, Y = 357 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Parsifal") { X = 710, Y = 163 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Juerk") { X = 773, Y = 168 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Sten") { X = 737, Y = 222 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Iron") { X = 660, Y = 242 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Burgi") { X = 656, Y = 300 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Schurik") { X = 722, Y = 307 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Pepito") { X = 831, Y = 182 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Tiggo") { X = 885, Y = 187 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Ussi") { X = 925, Y = 154 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Pet") { X = 856, Y = 266 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Lotta") { X = 924, Y = 236 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Lichti") { X = 837, Y = 305 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Nicki") { X = 1012, Y = 174 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Podium") { X = 1086, Y = 153 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Fanta") { X = 1102, Y = 217 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Graskarle") { X = 996, Y = 258 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Rudolfius") { X = 981, Y = 303 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Maedl") { X = 1114, Y = 305 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Schorsau") { X = 173, Y = 398 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Humungus") { X = 235, Y = 372 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Olfnhob") { X = 124, Y = 515 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Knutzelchen") { X = 166, Y = 569 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Armaniaboy") { X = 276, Y = 501 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Genesis") { X = 348, Y = 463 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "John") { X = 437, Y = 466 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Luna") { X = 360, Y = 537 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Khea") { X = 451, Y = 533 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Sdamian") { X = 351, Y = 581 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Trogl") { X = 455, Y = 597 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Gandhi") { X = 535, Y = 405 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "7even") { X = 571, Y = 451 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Speed") { X = 566, Y = 505 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Keks") { X = 563, Y = 558 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Rocky") { X = 575, Y = 592 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Ombre") { X = 681, Y = 400 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Prada") { X = 675, Y = 474 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Floxi") { X = 668, Y = 510 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Olli") { X = 636, Y = 599 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Mj") { X = 691, Y = 603 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Dworschi") { X = 776, Y = 441 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Whiteangel") { X = 877, Y = 425 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Lucky") { X = 784, Y = 513 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Beat") { X = 886, Y = 508 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Katarina") { X = 775, Y = 573 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Tycoon") { X = 884, Y = 583 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Krafti") { X = 1011, Y = 388 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Crook") { X = 1079, Y = 370 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Jopi") { X = 1002, Y = 456 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Natascha") { X = 957, Y = 528 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Stoffi") { X = 968, Y = 619 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Duessel") { X = 1089, Y = 537 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Hamari") { X = 262, Y = 447 };
mapTemplate.Countries.Add(country70);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country34);
continent6.Countries.Add(country35);
continent6.Countries.Add(country36);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 3);
continent7.Countries.Add(country37);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
continent7.Countries.Add(country41);
continent7.Countries.Add(country70);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country42);
continent8.Countries.Add(country43);
continent8.Countries.Add(country44);
continent8.Countries.Add(country45);
continent8.Countries.Add(country46);
continent8.Countries.Add(country47);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country48);
continent9.Countries.Add(country49);
continent9.Countries.Add(country50);
continent9.Countries.Add(country51);
continent9.Countries.Add(country52);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 2);
continent10.Countries.Add(country53);
continent10.Countries.Add(country54);
continent10.Countries.Add(country55);
continent10.Countries.Add(country56);
continent10.Countries.Add(country57);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country58);
continent11.Countries.Add(country59);
continent11.Countries.Add(country60);
continent11.Countries.Add(country61);
continent11.Countries.Add(country62);
continent11.Countries.Add(country63);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 3);
continent12.Countries.Add(country64);
continent12.Countries.Add(country65);
continent12.Countries.Add(country66);
continent12.Countries.Add(country67);
continent12.Countries.Add(country68);
continent12.Countries.Add(country69);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "5"));
mapTemplate.Connections.Add(new Connection("9", "38"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "22"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "48"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "25"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "16"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "20"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "34"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "36"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "29"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "64"));
mapTemplate.Connections.Add(new Connection("36", "33"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "65"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "70"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "70"));
mapTemplate.Connections.Add(new Connection("38", "9"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "70"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("47", "52"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "18"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("52", "56"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "47"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "52"));
mapTemplate.Connections.Add(new Connection("57", "62"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "60"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "58"));
mapTemplate.Connections.Add(new Connection("60", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("61", "67"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("62", "60"));
mapTemplate.Connections.Add(new Connection("62", "57"));
mapTemplate.Connections.Add(new Connection("63", "68"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("64", "35"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "66"));
mapTemplate.Connections.Add(new Connection("65", "36"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("66", "64"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "61"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("68", "63"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("70", "41"));
mapTemplate.Connections.Add(new Connection("70", "37"));
mapTemplate.Connections.Add(new Connection("70", "38"));

            return mapTemplate;
		}
    }
}

