using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate WorldDeluxe()
        {
            var mapTemplate = new MapTemplate("WorldDeluxe") { Image = "worlddeluxe.jpg" };
            var country1 = new CountryTemplate("1", "Alaska") { X = 81, Y = 124 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Nordwest-Territorium") { X = 159, Y = 124 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Groenland") { X = 393, Y = 78 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Quebec") { X = 315, Y = 193 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Ontario") { X = 237, Y = 192 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Alberta") { X = 159, Y = 170 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Weststaaten") { X = 159, Y = 239 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Oststaaten") { X = 237, Y = 262 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Mittel-Amerika") { X = 185, Y = 308 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Venezuela") { X = 237, Y = 378 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Brasilien") { X = 315, Y = 423 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Peru") { X = 263, Y = 446 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Argentinien") { X = 263, Y = 538 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Nordwest-Afrika") { X = 445, Y = 354 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "Aegypten") { X = 523, Y = 331 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Ost-Afrika") { X = 575, Y = 423 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Kongo") { X = 523, Y = 446 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Sued-Afrika") { X = 523, Y = 538 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Madagaskar") { X = 601, Y = 538 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "West-Europa") { X = 445, Y = 262 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Sued-Europa") { X = 497, Y = 262 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Mittel-Europa") { X = 497, Y = 216 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Gross-Britannien") { X = 419, Y = 217 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Island") { X = 419, Y = 147 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Skandinavien") { X = 497, Y = 147 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Ukraine") { X = 575, Y = 193 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Mittlerer-Osten") { X = 601, Y = 308 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Afghanistan") { X = 653, Y = 239 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Ural") { X = 679, Y = 170 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Sibirien") { X = 731, Y = 124 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Jakutien") { X = 809, Y = 124 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Kamtschatka") { X = 887, Y = 124 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Irkutsk") { X = 783, Y = 193 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Mongolei") { X = 785, Y = 240 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Japan") { X = 887, Y = 262 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "China") { X = 757, Y = 285 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Indien") { X = 705, Y = 354 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Siam") { X = 783, Y = 376 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Indonesien") { X = 835, Y = 446 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Neu-Guinea") { X = 913, Y = 469 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Ost-Australien") { X = 913, Y = 561 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "West-Australien") { X = 835, Y = 561 };
            mapTemplate.Countries.Add(country42);
            var continent1 = new Continent("1", 5);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            continent1.Countries.Add(country6);
            continent1.Countries.Add(country7);
            continent1.Countries.Add(country8);
            continent1.Countries.Add(country9);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 2);
            continent2.Countries.Add(country10);
            continent2.Countries.Add(country11);
            continent2.Countries.Add(country12);
            continent2.Countries.Add(country13);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country14);
            continent3.Countries.Add(country15);
            continent3.Countries.Add(country16);
            continent3.Countries.Add(country17);
            continent3.Countries.Add(country18);
            continent3.Countries.Add(country19);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 5);
            continent4.Countries.Add(country24);
            continent4.Countries.Add(country23);
            continent4.Countries.Add(country20);
            continent4.Countries.Add(country21);
            continent4.Countries.Add(country22);
            continent4.Countries.Add(country26);
            continent4.Countries.Add(country25);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 7);
            continent5.Countries.Add(country27);
            continent5.Countries.Add(country28);
            continent5.Countries.Add(country29);
            continent5.Countries.Add(country30);
            continent5.Countries.Add(country31);
            continent5.Countries.Add(country32);
            continent5.Countries.Add(country33);
            continent5.Countries.Add(country34);
            continent5.Countries.Add(country36);
            continent5.Countries.Add(country37);
            continent5.Countries.Add(country38);
            continent5.Countries.Add(country35);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 2);
            continent6.Countries.Add(country39);
            continent6.Countries.Add(country40);
            continent6.Countries.Add(country41);
            continent6.Countries.Add(country42);
            mapTemplate.Continents.Add(continent6);
            mapTemplate.Connections.Add(new Connection("15", "14"));
            mapTemplate.Connections.Add(new Connection("15", "21"));
            mapTemplate.Connections.Add(new Connection("15", "27"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "34"));
            mapTemplate.Connections.Add(new Connection("30", "36"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("8", "4"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "25"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "33"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("16", "19"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "14"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "32"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("22", "25"));
            mapTemplate.Connections.Add(new Connection("22", "26"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "32"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "30"));
            mapTemplate.Connections.Add(new Connection("34", "36"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "34"));
            mapTemplate.Connections.Add(new Connection("32", "35"));
            mapTemplate.Connections.Add(new Connection("32", "1"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "31"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "26"));
            mapTemplate.Connections.Add(new Connection("21", "27"));
            mapTemplate.Connections.Add(new Connection("21", "15"));
            mapTemplate.Connections.Add(new Connection("21", "14"));
            mapTemplate.Connections.Add(new Connection("6", "1"));
            mapTemplate.Connections.Add(new Connection("6", "2"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("1", "6"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "32"));
            mapTemplate.Connections.Add(new Connection("29", "26"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "36"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("14", "11"));
            mapTemplate.Connections.Add(new Connection("14", "17"));
            mapTemplate.Connections.Add(new Connection("14", "16"));
            mapTemplate.Connections.Add(new Connection("14", "15"));
            mapTemplate.Connections.Add(new Connection("14", "21"));
            mapTemplate.Connections.Add(new Connection("14", "20"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("42", "39"));
            mapTemplate.Connections.Add(new Connection("24", "3"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("4", "8"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "28"));
            mapTemplate.Connections.Add(new Connection("36", "29"));
            mapTemplate.Connections.Add(new Connection("36", "30"));
            mapTemplate.Connections.Add(new Connection("36", "34"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "16"));
            mapTemplate.Connections.Add(new Connection("26", "29"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "21"));
            mapTemplate.Connections.Add(new Connection("26", "22"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "14"));
            mapTemplate.Connections.Add(new Connection("11", "13"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("3", "24"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "42"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("27", "37"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "21"));
            mapTemplate.Connections.Add(new Connection("27", "15"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "14"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "6"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "11"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "36"));
            mapTemplate.Connections.Add(new Connection("28", "37"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "14"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "28"));
            mapTemplate.Connections.Add(new Connection("37", "27"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "23"));
            mapTemplate.Connections.Add(new Connection("25", "22"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("5", "3"));

            return mapTemplate;
        }
    }
}
