
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Stadt_Muenster()
        {

var mapTemplate = new MapTemplate("Stadt_Muenster") { Image = "stadt_muenster.jpg" };
var country1 = new CountryTemplate("1", "Uppenberg") { X = 320, Y = 264 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Kemperviertel") { X = 382, Y = 266 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Schlossviertel") { X = 278, Y = 330 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Kreuzviertel") { X = 350, Y = 296 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Mauritzviertel") { X = 399, Y = 319 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Altstadt") { X = 338, Y = 333 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Aaseestadt") { X = 286, Y = 398 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Geistviertel") { X = 330, Y = 398 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Hafenviertel") { X = 376, Y = 380 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Sprakel") { X = 316, Y = 42 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Sandrup") { X = 302, Y = 106 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Kinderhaus") { X = 286, Y = 200 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Coerheide") { X = 388, Y = 114 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Coerde") { X = 382, Y = 198 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Gittrup") { X = 428, Y = 38 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Gelmer") { X = 460, Y = 100 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Mariendorf") { X = 460, Y = 256 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "St Mauritz") { X = 466, Y = 350 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Suedmuehle") { X = 486, Y = 190 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Dorbaum") { X = 526, Y = 148 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Verth") { X = 586, Y = 134 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Handorf") { X = 544, Y = 242 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Kasewinkel") { X = 562, Y = 338 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Loddenheide") { X = 404, Y = 420 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Gremmendorf") { X = 456, Y = 458 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Angelmodde") { X = 522, Y = 482 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Wolbeck") { X = 598, Y = 506 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Berg Fidel") { X = 340, Y = 478 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Hiltrup") { X = 390, Y = 566 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Loevelingloh") { X = 248, Y = 544 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Amelsbueren") { X = 294, Y = 626 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Sudhoff") { X = 232, Y = 668 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Wildbrenning") { X = 172, Y = 590 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Uhlenbrock") { X = 208, Y = 42 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Haegar") { X = 182, Y = 108 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Nienberge") { X = 142, Y = 208 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Gievenbeck") { X = 214, Y = 288 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Roxel") { X = 124, Y = 364 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Mecklenbeck") { X = 214, Y = 443 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Albachten") { X = 112, Y = 486 };
mapTemplate.Countries.Add(country40);
var continent1 = new Continent("1", 6);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
continent3.Countries.Add(country21);
continent3.Countries.Add(country22);
continent3.Countries.Add(country23);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country34);
continent6.Countries.Add(country35);
continent6.Countries.Add(country36);
continent6.Countries.Add(country37);
continent6.Countries.Add(country38);
continent6.Countries.Add(country39);
continent6.Countries.Add(country40);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "37"));
mapTemplate.Connections.Add(new Connection("1", "12"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "14"));
mapTemplate.Connections.Add(new Connection("2", "17"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("3", "37"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "39"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("5", "18"));
mapTemplate.Connections.Add(new Connection("5", "17"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "39"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("8", "28"));
mapTemplate.Connections.Add(new Connection("8", "39"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("9", "24"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "5"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "34"));
mapTemplate.Connections.Add(new Connection("10", "35"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "35"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "36"));
mapTemplate.Connections.Add(new Connection("12", "37"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "1"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "2"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("17", "2"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "5"));
mapTemplate.Connections.Add(new Connection("18", "23"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "25"));
mapTemplate.Connections.Add(new Connection("18", "24"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "5"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "18"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "18"));
mapTemplate.Connections.Add(new Connection("24", "28"));
mapTemplate.Connections.Add(new Connection("24", "9"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "18"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("28", "24"));
mapTemplate.Connections.Add(new Connection("28", "8"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "39"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "39"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "40"));
mapTemplate.Connections.Add(new Connection("34", "10"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "11"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "10"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "12"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "12"));
mapTemplate.Connections.Add(new Connection("37", "3"));
mapTemplate.Connections.Add(new Connection("37", "1"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("39", "30"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "3"));
mapTemplate.Connections.Add(new Connection("39", "7"));
mapTemplate.Connections.Add(new Connection("39", "8"));
mapTemplate.Connections.Add(new Connection("39", "28"));
mapTemplate.Connections.Add(new Connection("40", "33"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "38"));

            return mapTemplate;
		}
    }
}

