using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Europa()
        {
            var mapTemplate = new MapTemplate("Europa") { Image = "europa.jpg" };
            var country1 = new CountryTemplate("1", "Marokko") { X = 137, Y = 1131 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Algerien") { X = 300, Y = 1132 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Tunesien") { X = 472, Y = 1111 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Portugal") { X = 63, Y = 925 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Spanien") { X = 174, Y = 957 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Andorra") { X = 346, Y = 966 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Monaco") { X = 408, Y = 924 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Frankreich") { X = 321, Y = 754 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Vereinigtes Königreich") { X = 274, Y = 609 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Irland") { X = 157, Y = 545 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Island") { X = 119, Y = 152 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "Malta") { X = 635, Y = 1110 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Italien") { X = 513, Y = 813 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Vatikanstadt") { X = 534, Y = 975 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "San Marino") { X = 619, Y = 906 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "Schweiz") { X = 446, Y = 792 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Lichtenstein") { X = 522, Y = 733 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "Österreich") { X = 599, Y = 747 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "Deutschland") { X = 517, Y = 624 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Luxemburg") { X = 460, Y = 656 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Belgien") { X = 385, Y = 666 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Niederlande") { X = 400, Y = 614 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Dänemark") { X = 474, Y = 489 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Schweden") { X = 598, Y = 178 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Norwegen") { X = 478, Y = 364 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Finnland") { X = 724, Y = 281 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Estland") { X = 749, Y = 388 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Lettland") { X = 763, Y = 440 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Litauen") { X = 753, Y = 496 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Polen") { X = 660, Y = 595 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Tschechien") { X = 588, Y = 695 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Slowakei") { X = 678, Y = 717 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Ungarn") { X = 686, Y = 770 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Slowenien") { X = 587, Y = 813 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Kroatien") { X = 635, Y = 805 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Bosnien und Herzegowina") { X = 672, Y = 876 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Serbien") { X = 753, Y = 854 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Montenegro") { X = 707, Y = 897 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Kosovo") { X = 743, Y = 902 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Albanien") { X = 727, Y = 957 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Mazedonien") { X = 754, Y = 933 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Griechenland") { X = 781, Y = 1007 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Zypern") { X = 1094, Y = 1054 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Bulgarien") { X = 841, Y = 879 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Rumänien") { X = 799, Y = 769 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Moldawien") { X = 892, Y = 732 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Ukraine") { X = 920, Y = 648 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Weissrussland") { X = 825, Y = 539 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Russland") { X = 1052, Y = 359 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Kasachstan") { X = 1359, Y = 455 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Georgien") { X = 1242, Y = 762 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Aserbaidschan") { X = 1364, Y = 740 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Türkei") { X = 1061, Y = 942 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Armenien") { X = 1289, Y = 783 };
            mapTemplate.Countries.Add(country54);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 3);
            continent2.Countries.Add(country4);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            continent2.Countries.Add(country8);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 1);
            continent3.Countries.Add(country9);
            continent3.Countries.Add(country10);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 2);
            continent4.Countries.Add(country12);
            continent4.Countries.Add(country13);
            continent4.Countries.Add(country14);
            continent4.Countries.Add(country15);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 4);
            continent5.Countries.Add(country16);
            continent5.Countries.Add(country17);
            continent5.Countries.Add(country18);
            continent5.Countries.Add(country19);
            continent5.Countries.Add(country20);
            continent5.Countries.Add(country21);
            continent5.Countries.Add(country22);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 3);
            continent6.Countries.Add(country11);
            continent6.Countries.Add(country23);
            continent6.Countries.Add(country24);
            continent6.Countries.Add(country25);
            continent6.Countries.Add(country26);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country27);
            continent7.Countries.Add(country28);
            continent7.Countries.Add(country29);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country30);
            continent8.Countries.Add(country31);
            continent8.Countries.Add(country32);
            continent8.Countries.Add(country33);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 4);
            continent9.Countries.Add(country34);
            continent9.Countries.Add(country35);
            continent9.Countries.Add(country36);
            continent9.Countries.Add(country37);
            continent9.Countries.Add(country38);
            continent9.Countries.Add(country39);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 3);
            continent10.Countries.Add(country40);
            continent10.Countries.Add(country41);
            continent10.Countries.Add(country42);
            continent10.Countries.Add(country43);
            continent10.Countries.Add(country53);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 2);
            continent11.Countries.Add(country44);
            continent11.Countries.Add(country45);
            continent11.Countries.Add(country46);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 3);
            continent12.Countries.Add(country47);
            continent12.Countries.Add(country48);
            continent12.Countries.Add(country49);
            continent12.Countries.Add(country50);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 2);
            continent13.Countries.Add(country51);
            continent13.Countries.Add(country52);
            continent13.Countries.Add(country54);
            mapTemplate.Continents.Add(continent13);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "5"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("3", "12"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("5", "1"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "8"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("8", "6"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "13"));
            mapTemplate.Connections.Add(new Connection("8", "16"));
            mapTemplate.Connections.Add(new Connection("8", "21"));
            mapTemplate.Connections.Add(new Connection("8", "20"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "19"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "25"));
            mapTemplate.Connections.Add(new Connection("12", "3"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("13", "8"));
            mapTemplate.Connections.Add(new Connection("13", "16"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "15"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "42"));
            mapTemplate.Connections.Add(new Connection("13", "18"));
            mapTemplate.Connections.Add(new Connection("13", "34"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("15", "13"));
            mapTemplate.Connections.Add(new Connection("16", "8"));
            mapTemplate.Connections.Add(new Connection("16", "19"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "13"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("18", "13"));
            mapTemplate.Connections.Add(new Connection("18", "34"));
            mapTemplate.Connections.Add(new Connection("18", "33"));
            mapTemplate.Connections.Add(new Connection("18", "32"));
            mapTemplate.Connections.Add(new Connection("18", "31"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "22"));
            mapTemplate.Connections.Add(new Connection("19", "23"));
            mapTemplate.Connections.Add(new Connection("19", "30"));
            mapTemplate.Connections.Add(new Connection("19", "31"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "16"));
            mapTemplate.Connections.Add(new Connection("19", "8"));
            mapTemplate.Connections.Add(new Connection("20", "8"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("21", "8"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "19"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "19"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "26"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("25", "11"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "49"));
            mapTemplate.Connections.Add(new Connection("26", "24"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "49"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "49"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "49"));
            mapTemplate.Connections.Add(new Connection("28", "48"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "48"));
            mapTemplate.Connections.Add(new Connection("30", "19"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "48"));
            mapTemplate.Connections.Add(new Connection("30", "47"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("31", "19"));
            mapTemplate.Connections.Add(new Connection("31", "18"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "18"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "47"));
            mapTemplate.Connections.Add(new Connection("33", "18"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "47"));
            mapTemplate.Connections.Add(new Connection("33", "37"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "35"));
            mapTemplate.Connections.Add(new Connection("33", "45"));
            mapTemplate.Connections.Add(new Connection("34", "18"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "13"));
            mapTemplate.Connections.Add(new Connection("35", "37"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "33"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("37", "45"));
            mapTemplate.Connections.Add(new Connection("37", "41"));
            mapTemplate.Connections.Add(new Connection("37", "39"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "35"));
            mapTemplate.Connections.Add(new Connection("37", "33"));
            mapTemplate.Connections.Add(new Connection("37", "44"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "37"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "44"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "37"));
            mapTemplate.Connections.Add(new Connection("42", "13"));
            mapTemplate.Connections.Add(new Connection("42", "53"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "44"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "53"));
            mapTemplate.Connections.Add(new Connection("44", "42"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "53"));
            mapTemplate.Connections.Add(new Connection("44", "41"));
            mapTemplate.Connections.Add(new Connection("44", "37"));
            mapTemplate.Connections.Add(new Connection("45", "47"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "37"));
            mapTemplate.Connections.Add(new Connection("45", "33"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("47", "30"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "45"));
            mapTemplate.Connections.Add(new Connection("47", "32"));
            mapTemplate.Connections.Add(new Connection("47", "33"));
            mapTemplate.Connections.Add(new Connection("48", "30"));
            mapTemplate.Connections.Add(new Connection("48", "28"));
            mapTemplate.Connections.Add(new Connection("48", "29"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("49", "26"));
            mapTemplate.Connections.Add(new Connection("49", "25"));
            mapTemplate.Connections.Add(new Connection("49", "27"));
            mapTemplate.Connections.Add(new Connection("49", "28"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("49", "50"));
            mapTemplate.Connections.Add(new Connection("49", "51"));
            mapTemplate.Connections.Add(new Connection("49", "52"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("50", "49"));
            mapTemplate.Connections.Add(new Connection("51", "49"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "54"));
            mapTemplate.Connections.Add(new Connection("52", "49"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "54"));
            mapTemplate.Connections.Add(new Connection("53", "42"));
            mapTemplate.Connections.Add(new Connection("53", "43"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "44"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "52"));
            mapTemplate.Connections.Add(new Connection("54", "51"));

            return mapTemplate;
        }
    }
}
