
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Psycube()
        {

var mapTemplate = new MapTemplate("Psycube") { Image = "psycube.jpg" };
var country1 = new CountryTemplate("1", "A") { X = 458, Y = 118 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "B") { X = 593, Y = 129 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "C") { X = 599, Y = 219 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "D") { X = 518, Y = 181 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "F") { X = 694, Y = 271 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "G") { X = 761, Y = 350 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "H") { X = 695, Y = 348 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "E") { X = 638, Y = 343 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "I") { X = 969, Y = 301 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "J") { X = 1025, Y = 373 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "K") { X = 971, Y = 496 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "L") { X = 973, Y = 375 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "M") { X = 444, Y = 595 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "N") { X = 456, Y = 489 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "O") { X = 603, Y = 492 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "P") { X = 529, Y = 541 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Q") { X = 203, Y = 383 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "R") { X = 124, Y = 504 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "S") { X = 82, Y = 375 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "T") { X = 135, Y = 398 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "U") { X = 374, Y = 407 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "V") { X = 299, Y = 318 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "W") { X = 353, Y = 265 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "X") { X = 376, Y = 332 };
mapTemplate.Countries.Add(country24);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country13);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
continent4.Countries.Add(country16);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
continent5.Countries.Add(country20);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "9"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "16"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "20"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "2"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "24"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("13", "18"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "21"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "4"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "13"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "7"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "14"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "12"));

            return mapTemplate;
		}
    }
}

