using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate BT_3130()
        {
            var mapTemplate = new MapTemplate("BT_3130") { Image = "BT-3130.jpg" };
            var country1 = new CountryTemplate("1", "Regulus") { X = 369, Y = 875 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "Oriente Protektorat") { X = 440, Y = 872 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Herzogtum Andurien") { X = 464, Y = 928 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "Freier Raum") { X = 369, Y = 959 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "Marik-Stewart Commonwealth") { X = 394, Y = 774 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Herzogtum Tamarand-Abbey") { X = 289, Y = 771 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Rim Kommunalitat") { X = 257, Y = 938 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Robinson") { X = 708, Y = 683 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Mark Draconis") { X = 911, Y = 679 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Kathil") { X = 614, Y = 835 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Mark Sarna") { X = 679, Y = 893 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "New Avalon") { X = 704, Y = 763 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "Mineite") { X = 868, Y = 813 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "Chirikoff") { X = 778, Y = 902 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "X") { X = 503, Y = 716 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "III-V") { X = 542, Y = 760 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "VI-VII") { X = 481, Y = 767 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "I-II") { X = 515, Y = 642 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "VIII-IX") { X = 452, Y = 649 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "Bolan") { X = 326, Y = 698 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "Alarion") { X = 225, Y = 662 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Coventry") { X = 290, Y = 518 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Tharkad") { X = 387, Y = 536 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Hesperus") { X = 414, Y = 632 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "Sarna") { X = 558, Y = 813 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "Capella") { X = 552, Y = 846 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "St Ives") { X = 558, Y = 907 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "Sian") { X = 495, Y = 888 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "Larsha") { X = 518, Y = 1036 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "Benjamin") { X = 595, Y = 584 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Luthien") { X = 679, Y = 463 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "Galedon") { X = 742, Y = 582 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Brasha") { X = 852, Y = 556 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "Alpheratz") { X = 886, Y = 592 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Praxton") { X = 948, Y = 603 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Afarsin") { X = 343, Y = 994 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "Canopus") { X = 393, Y = 1019 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "Brixtana") { X = 455, Y = 1015 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "Plejaden") { X = 668, Y = 956 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Taurus") { X = 646, Y = 1000 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "Lothario") { X = 166, Y = 845 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Alphard") { X = 165, Y = 914 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Clan Wolf") { X = 455, Y = 551 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Clan Jadefalke") { X = 392, Y = 447 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "Clan Hoellenroesser") { X = 432, Y = 413 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Geisterbaeren Dominion") { X = 547, Y = 443 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "The Barrens") { X = 449, Y = 332 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Pentagon Welten") { X = 511, Y = 214 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "Clan Heimatwelten") { X = 591, Y = 136 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "Mica Majoritaet") { X = 1049, Y = 703 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "Calderon Protektorat") { X = 833, Y = 1073 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "Filtvet Coalition") { X = 906, Y = 848 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Tortuga Dominion") { X = 1017, Y = 884 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Rim Territorien") { X = 197, Y = 414 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Rim Collection") { X = 125, Y = 581 };
            mapTemplate.Countries.Add(country55);
            var continent1 = new Continent("1", 4);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            continent1.Countries.Add(country6);
            continent1.Countries.Add(country7);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country8);
            continent2.Countries.Add(country9);
            continent2.Countries.Add(country10);
            continent2.Countries.Add(country11);
            continent2.Countries.Add(country12);
            continent2.Countries.Add(country13);
            continent2.Countries.Add(country14);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country15);
            continent3.Countries.Add(country16);
            continent3.Countries.Add(country17);
            continent3.Countries.Add(country18);
            continent3.Countries.Add(country19);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 3);
            continent4.Countries.Add(country20);
            continent4.Countries.Add(country21);
            continent4.Countries.Add(country22);
            continent4.Countries.Add(country23);
            continent4.Countries.Add(country24);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 3);
            continent5.Countries.Add(country25);
            continent5.Countries.Add(country26);
            continent5.Countries.Add(country27);
            continent5.Countries.Add(country28);
            continent5.Countries.Add(country29);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 2);
            continent6.Countries.Add(country30);
            continent6.Countries.Add(country31);
            continent6.Countries.Add(country32);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country33);
            continent7.Countries.Add(country34);
            continent7.Countries.Add(country35);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 2);
            continent8.Countries.Add(country36);
            continent8.Countries.Add(country37);
            continent8.Countries.Add(country38);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 1);
            continent9.Countries.Add(country39);
            continent9.Countries.Add(country40);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 1);
            continent10.Countries.Add(country41);
            continent10.Countries.Add(country42);
            mapTemplate.Continents.Add(continent10);
            var continent11 = new Continent("11", 3);
            continent11.Countries.Add(country43);
            continent11.Countries.Add(country44);
            continent11.Countries.Add(country45);
            continent11.Countries.Add(country46);
            continent11.Countries.Add(country47);
            continent11.Countries.Add(country48);
            continent11.Countries.Add(country49);
            mapTemplate.Continents.Add(continent11);
            var continent12 = new Continent("12", 2);
            continent12.Countries.Add(country50);
            continent12.Countries.Add(country51);
            continent12.Countries.Add(country52);
            continent12.Countries.Add(country53);
            mapTemplate.Continents.Add(continent12);
            var continent13 = new Continent("13", 1);
            continent13.Countries.Add(country54);
            continent13.Countries.Add(country55);
            mapTemplate.Continents.Add(continent13);
            mapTemplate.Connections.Add(new Connection("1", "4"));
            mapTemplate.Connections.Add(new Connection("2", "17"));
            mapTemplate.Connections.Add(new Connection("2", "25"));
            mapTemplate.Connections.Add(new Connection("2", "26"));
            mapTemplate.Connections.Add(new Connection("2", "28"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("3", "28"));
            mapTemplate.Connections.Add(new Connection("3", "38"));
            mapTemplate.Connections.Add(new Connection("3", "37"));
            mapTemplate.Connections.Add(new Connection("3", "36"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("4", "17"));
            mapTemplate.Connections.Add(new Connection("4", "21"));
            mapTemplate.Connections.Add(new Connection("4", "20"));
            mapTemplate.Connections.Add(new Connection("4", "36"));
            mapTemplate.Connections.Add(new Connection("4", "41"));
            mapTemplate.Connections.Add(new Connection("4", "7"));
            mapTemplate.Connections.Add(new Connection("4", "6"));
            mapTemplate.Connections.Add(new Connection("4", "5"));
            mapTemplate.Connections.Add(new Connection("4", "1"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "42"));
            mapTemplate.Connections.Add(new Connection("5", "20"));
            mapTemplate.Connections.Add(new Connection("5", "24"));
            mapTemplate.Connections.Add(new Connection("5", "17"));
            mapTemplate.Connections.Add(new Connection("5", "19"));
            mapTemplate.Connections.Add(new Connection("5", "4"));
            mapTemplate.Connections.Add(new Connection("6", "21"));
            mapTemplate.Connections.Add(new Connection("6", "20"));
            mapTemplate.Connections.Add(new Connection("6", "4"));
            mapTemplate.Connections.Add(new Connection("7", "4"));
            mapTemplate.Connections.Add(new Connection("8", "30"));
            mapTemplate.Connections.Add(new Connection("8", "32"));
            mapTemplate.Connections.Add(new Connection("8", "16"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "12"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("9", "35"));
            mapTemplate.Connections.Add(new Connection("9", "34"));
            mapTemplate.Connections.Add(new Connection("9", "32"));
            mapTemplate.Connections.Add(new Connection("9", "50"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "12"));
            mapTemplate.Connections.Add(new Connection("9", "13"));
            mapTemplate.Connections.Add(new Connection("10", "16"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "25"));
            mapTemplate.Connections.Add(new Connection("10", "26"));
            mapTemplate.Connections.Add(new Connection("10", "27"));
            mapTemplate.Connections.Add(new Connection("10", "14"));
            mapTemplate.Connections.Add(new Connection("11", "14"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "27"));
            mapTemplate.Connections.Add(new Connection("11", "28"));
            mapTemplate.Connections.Add(new Connection("11", "39"));
            mapTemplate.Connections.Add(new Connection("11", "40"));
            mapTemplate.Connections.Add(new Connection("12", "8"));
            mapTemplate.Connections.Add(new Connection("12", "9"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("13", "52"));
            mapTemplate.Connections.Add(new Connection("13", "9"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("14", "11"));
            mapTemplate.Connections.Add(new Connection("14", "51"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("14", "10"));
            mapTemplate.Connections.Add(new Connection("15", "18"));
            mapTemplate.Connections.Add(new Connection("15", "19"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("16", "30"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "8"));
            mapTemplate.Connections.Add(new Connection("16", "10"));
            mapTemplate.Connections.Add(new Connection("16", "25"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("17", "25"));
            mapTemplate.Connections.Add(new Connection("17", "2"));
            mapTemplate.Connections.Add(new Connection("17", "5"));
            mapTemplate.Connections.Add(new Connection("17", "4"));
            mapTemplate.Connections.Add(new Connection("18", "30"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("18", "15"));
            mapTemplate.Connections.Add(new Connection("18", "24"));
            mapTemplate.Connections.Add(new Connection("19", "24"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("19", "15"));
            mapTemplate.Connections.Add(new Connection("19", "5"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "24"));
            mapTemplate.Connections.Add(new Connection("20", "6"));
            mapTemplate.Connections.Add(new Connection("20", "5"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("20", "4"));
            mapTemplate.Connections.Add(new Connection("21", "55"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "6"));
            mapTemplate.Connections.Add(new Connection("21", "23"));
            mapTemplate.Connections.Add(new Connection("21", "4"));
            mapTemplate.Connections.Add(new Connection("22", "54"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "44"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("23", "43"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "21"));
            mapTemplate.Connections.Add(new Connection("23", "44"));
            mapTemplate.Connections.Add(new Connection("23", "46"));
            mapTemplate.Connections.Add(new Connection("24", "20"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "5"));
            mapTemplate.Connections.Add(new Connection("24", "19"));
            mapTemplate.Connections.Add(new Connection("24", "46"));
            mapTemplate.Connections.Add(new Connection("24", "30"));
            mapTemplate.Connections.Add(new Connection("24", "18"));
            mapTemplate.Connections.Add(new Connection("25", "16"));
            mapTemplate.Connections.Add(new Connection("25", "17"));
            mapTemplate.Connections.Add(new Connection("25", "10"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "2"));
            mapTemplate.Connections.Add(new Connection("26", "10"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "2"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("27", "10"));
            mapTemplate.Connections.Add(new Connection("27", "11"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("28", "11"));
            mapTemplate.Connections.Add(new Connection("28", "40"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "2"));
            mapTemplate.Connections.Add(new Connection("28", "3"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("28", "38"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("29", "40"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "38"));
            mapTemplate.Connections.Add(new Connection("30", "46"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "18"));
            mapTemplate.Connections.Add(new Connection("30", "24"));
            mapTemplate.Connections.Add(new Connection("30", "16"));
            mapTemplate.Connections.Add(new Connection("30", "8"));
            mapTemplate.Connections.Add(new Connection("31", "46"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("32", "34"));
            mapTemplate.Connections.Add(new Connection("32", "9"));
            mapTemplate.Connections.Add(new Connection("32", "8"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("34", "32"));
            mapTemplate.Connections.Add(new Connection("34", "9"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "9"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "4"));
            mapTemplate.Connections.Add(new Connection("36", "3"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "3"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "29"));
            mapTemplate.Connections.Add(new Connection("38", "3"));
            mapTemplate.Connections.Add(new Connection("38", "28"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "11"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "11"));
            mapTemplate.Connections.Add(new Connection("40", "29"));
            mapTemplate.Connections.Add(new Connection("40", "28"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "4"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "4"));
            mapTemplate.Connections.Add(new Connection("43", "45"));
            mapTemplate.Connections.Add(new Connection("43", "46"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "23"));
            mapTemplate.Connections.Add(new Connection("44", "45"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "22"));
            mapTemplate.Connections.Add(new Connection("44", "23"));
            mapTemplate.Connections.Add(new Connection("45", "47"));
            mapTemplate.Connections.Add(new Connection("45", "44"));
            mapTemplate.Connections.Add(new Connection("45", "43"));
            mapTemplate.Connections.Add(new Connection("45", "46"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("46", "45"));
            mapTemplate.Connections.Add(new Connection("46", "31"));
            mapTemplate.Connections.Add(new Connection("46", "30"));
            mapTemplate.Connections.Add(new Connection("46", "43"));
            mapTemplate.Connections.Add(new Connection("46", "24"));
            mapTemplate.Connections.Add(new Connection("46", "23"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "45"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("50", "9"));
            mapTemplate.Connections.Add(new Connection("51", "14"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("52", "13"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("54", "22"));
            mapTemplate.Connections.Add(new Connection("55", "21"));

            return mapTemplate;
        }
    }
}
