
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Spiegelwelt()
        {

var mapTemplate = new MapTemplate("Spiegelwelt") { Image = "spiegelwelt.jpg" };
var country1 = new CountryTemplate("1", "oAlaska") { X = 322, Y = 113 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "oNordwest-Territorium") { X = 406, Y = 121 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "oGr�nland") { X = 636, Y = 78 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "oAlberta") { X = 383, Y = 168 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "oOntario") { X = 453, Y = 185 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "oQuebec") { X = 518, Y = 187 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "oWeststaaten") { X = 360, Y = 228 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "oOststaaten") { X = 418, Y = 256 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "oMittelamerika") { X = 339, Y = 301 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "oVenezuela") { X = 371, Y = 367 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "oPeru") { X = 349, Y = 442 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "oBrasilien") { X = 414, Y = 415 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "oArgentinien") { X = 325, Y = 524 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "oIsland") { X = 644, Y = 142 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "oSkandinavien") { X = 743, Y = 131 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "oUkraine") { X = 797, Y = 187 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "oGross-Britannien") { X = 642, Y = 201 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "oMittel-Europa") { X = 686, Y = 213 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "oWest-Europa") { X = 621, Y = 251 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "oS�d-Europa") { X = 687, Y = 255 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "oNordwest-Afrika") { X = 580, Y = 355 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "o�gypten") { X = 670, Y = 329 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "oOst-Afrika") { X = 678, Y = 414 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "oKongo") { X = 617, Y = 445 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "oS�d-Afrika") { X = 579, Y = 531 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "oMadagaskar") { X = 654, Y = 531 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "oMittlerer-Osten") { X = 751, Y = 302 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "oAfghanistan") { X = 844, Y = 232 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "oUral") { X = 896, Y = 166 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "oSibirien") { X = 957, Y = 119 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "oJakutien") { X = 1051, Y = 117 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "oKamtschatka") { X = 1144, Y = 124 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "oIrkutsk") { X = 1003, Y = 187 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "oMongolei") { X = 968, Y = 230 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "oJapan") { X = 1077, Y = 251 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "oChina") { X = 930, Y = 278 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "oIndien") { X = 842, Y = 307 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "oSiam") { X = 919, Y = 374 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "oIndonesien") { X = 928, Y = 440 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "oNeu-Guinea") { X = 1001, Y = 459 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "oWest-Australien") { X = 878, Y = 542 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "oOst-Australien") { X = 966, Y = 553 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "uAlaska") { X = 323, Y = 753 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "uNordwest-Territorium") { X = 399, Y = 758 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "uGr�nland") { X = 638, Y = 714 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "uAlberta") { X = 380, Y = 808 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "uOntario") { X = 453, Y = 825 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "uQuebec") { X = 515, Y = 828 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "uWeststaaten") { X = 358, Y = 868 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "uOststaaten") { X = 418, Y = 897 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "uMittel-Amerika") { X = 338, Y = 944 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "uVenezuela") { X = 373, Y = 1005 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "uPeru") { X = 345, Y = 1076 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "uBrasilien") { X = 415, Y = 1055 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "uArgentinien") { X = 318, Y = 1168 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "uIsland") { X = 646, Y = 779 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "uSkandinavien") { X = 745, Y = 771 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "uUkraine") { X = 803, Y = 828 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "uGross-Britannien") { X = 639, Y = 840 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "uMittel-Europa") { X = 687, Y = 853 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "uWest-Europa") { X = 620, Y = 894 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "uS�d-Europa") { X = 689, Y = 894 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "uNordwest-Afrika") { X = 584, Y = 993 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "u�gypten") { X = 670, Y = 967 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "uOst-Afrika") { X = 677, Y = 1054 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "uKongo") { X = 619, Y = 1083 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "uS�d-Afrika") { X = 573, Y = 1171 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "uMadagaskar") { X = 652, Y = 1172 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "uMittlerer-Osten") { X = 751, Y = 940 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "uAfghanistan") { X = 841, Y = 873 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "uUral") { X = 896, Y = 806 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "uSibirien") { X = 955, Y = 757 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "uJakutien") { X = 1050, Y = 754 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "uKamtschatka") { X = 1144, Y = 762 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "uIrkutsk") { X = 1001, Y = 826 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "uMongolei") { X = 968, Y = 869 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "uJapan") { X = 1073, Y = 889 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "uChina") { X = 931, Y = 913 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "uIndien") { X = 841, Y = 944 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "uSiam") { X = 917, Y = 1013 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "uIndonesien") { X = 934, Y = 1078 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "uNeu-Guinea") { X = 1001, Y = 1096 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "uWest-Australien") { X = 878, Y = 1188 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "uOst-Australien") { X = 963, Y = 1194 };
mapTemplate.Countries.Add(country84);
var continent1 = new Continent("1", 5);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country21);
continent4.Countries.Add(country22);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 7);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
continent5.Countries.Add(country31);
continent5.Countries.Add(country32);
continent5.Countries.Add(country33);
continent5.Countries.Add(country34);
continent5.Countries.Add(country35);
continent5.Countries.Add(country36);
continent5.Countries.Add(country37);
continent5.Countries.Add(country38);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country39);
continent6.Countries.Add(country40);
continent6.Countries.Add(country41);
continent6.Countries.Add(country42);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country43);
continent7.Countries.Add(country44);
continent7.Countries.Add(country45);
continent7.Countries.Add(country46);
continent7.Countries.Add(country47);
continent7.Countries.Add(country48);
continent7.Countries.Add(country49);
continent7.Countries.Add(country50);
continent7.Countries.Add(country51);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country52);
continent8.Countries.Add(country53);
continent8.Countries.Add(country54);
continent8.Countries.Add(country55);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 5);
continent9.Countries.Add(country56);
continent9.Countries.Add(country57);
continent9.Countries.Add(country58);
continent9.Countries.Add(country59);
continent9.Countries.Add(country60);
continent9.Countries.Add(country61);
continent9.Countries.Add(country62);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country63);
continent10.Countries.Add(country64);
continent10.Countries.Add(country65);
continent10.Countries.Add(country66);
continent10.Countries.Add(country67);
continent10.Countries.Add(country68);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 7);
continent11.Countries.Add(country69);
continent11.Countries.Add(country70);
continent11.Countries.Add(country71);
continent11.Countries.Add(country72);
continent11.Countries.Add(country73);
continent11.Countries.Add(country74);
continent11.Countries.Add(country75);
continent11.Countries.Add(country76);
continent11.Countries.Add(country77);
continent11.Countries.Add(country78);
continent11.Countries.Add(country79);
continent11.Countries.Add(country80);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 2);
continent12.Countries.Add(country81);
continent12.Countries.Add(country82);
continent12.Countries.Add(country83);
continent12.Countries.Add(country84);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "32"));
mapTemplate.Connections.Add(new Connection("1", "43"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "44"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "14"));
mapTemplate.Connections.Add(new Connection("3", "45"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "46"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "47"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "48"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "49"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "50"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "51"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "52"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "53"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "21"));
mapTemplate.Connections.Add(new Connection("12", "54"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "55"));
mapTemplate.Connections.Add(new Connection("14", "3"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("14", "56"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "57"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "29"));
mapTemplate.Connections.Add(new Connection("16", "28"));
mapTemplate.Connections.Add(new Connection("16", "27"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "58"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "59"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "60"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "61"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "27"));
mapTemplate.Connections.Add(new Connection("20", "62"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "12"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("21", "63"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "27"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "64"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "65"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "66"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "67"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "68"));
mapTemplate.Connections.Add(new Connection("27", "16"));
mapTemplate.Connections.Add(new Connection("27", "20"));
mapTemplate.Connections.Add(new Connection("27", "22"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "37"));
mapTemplate.Connections.Add(new Connection("27", "69"));
mapTemplate.Connections.Add(new Connection("28", "16"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "36"));
mapTemplate.Connections.Add(new Connection("28", "37"));
mapTemplate.Connections.Add(new Connection("28", "70"));
mapTemplate.Connections.Add(new Connection("29", "16"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "36"));
mapTemplate.Connections.Add(new Connection("29", "71"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "36"));
mapTemplate.Connections.Add(new Connection("30", "72"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "73"));
mapTemplate.Connections.Add(new Connection("32", "1"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "74"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "75"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "76"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "77"));
mapTemplate.Connections.Add(new Connection("36", "28"));
mapTemplate.Connections.Add(new Connection("36", "29"));
mapTemplate.Connections.Add(new Connection("36", "30"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "78"));
mapTemplate.Connections.Add(new Connection("37", "27"));
mapTemplate.Connections.Add(new Connection("37", "28"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "79"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "80"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("39", "81"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "82"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "83"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "84"));
mapTemplate.Connections.Add(new Connection("43", "1"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "74"));
mapTemplate.Connections.Add(new Connection("44", "2"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "47"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("45", "3"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "56"));
mapTemplate.Connections.Add(new Connection("45", "48"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("46", "4"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "49"));
mapTemplate.Connections.Add(new Connection("47", "5"));
mapTemplate.Connections.Add(new Connection("47", "44"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("48", "6"));
mapTemplate.Connections.Add(new Connection("48", "45"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("49", "7"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "46"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("50", "8"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("51", "9"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("52", "10"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "11"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "55"));
mapTemplate.Connections.Add(new Connection("54", "12"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "63"));
mapTemplate.Connections.Add(new Connection("55", "13"));
mapTemplate.Connections.Add(new Connection("55", "53"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("56", "14"));
mapTemplate.Connections.Add(new Connection("56", "45"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "59"));
mapTemplate.Connections.Add(new Connection("57", "15"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("57", "59"));
mapTemplate.Connections.Add(new Connection("58", "16"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "71"));
mapTemplate.Connections.Add(new Connection("58", "70"));
mapTemplate.Connections.Add(new Connection("58", "69"));
mapTemplate.Connections.Add(new Connection("58", "62"));
mapTemplate.Connections.Add(new Connection("58", "60"));
mapTemplate.Connections.Add(new Connection("59", "17"));
mapTemplate.Connections.Add(new Connection("59", "56"));
mapTemplate.Connections.Add(new Connection("59", "57"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("60", "18"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("60", "58"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "62"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "19"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("62", "20"));
mapTemplate.Connections.Add(new Connection("62", "58"));
mapTemplate.Connections.Add(new Connection("62", "60"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("62", "64"));
mapTemplate.Connections.Add(new Connection("62", "69"));
mapTemplate.Connections.Add(new Connection("63", "21"));
mapTemplate.Connections.Add(new Connection("63", "54"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("63", "65"));
mapTemplate.Connections.Add(new Connection("63", "66"));
mapTemplate.Connections.Add(new Connection("64", "22"));
mapTemplate.Connections.Add(new Connection("64", "62"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "69"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("65", "23"));
mapTemplate.Connections.Add(new Connection("65", "63"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "68"));
mapTemplate.Connections.Add(new Connection("65", "67"));
mapTemplate.Connections.Add(new Connection("66", "24"));
mapTemplate.Connections.Add(new Connection("66", "63"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("67", "25"));
mapTemplate.Connections.Add(new Connection("67", "65"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("68", "26"));
mapTemplate.Connections.Add(new Connection("68", "65"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("69", "27"));
mapTemplate.Connections.Add(new Connection("69", "58"));
mapTemplate.Connections.Add(new Connection("69", "62"));
mapTemplate.Connections.Add(new Connection("69", "64"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "79"));
mapTemplate.Connections.Add(new Connection("70", "28"));
mapTemplate.Connections.Add(new Connection("70", "58"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "78"));
mapTemplate.Connections.Add(new Connection("70", "79"));
mapTemplate.Connections.Add(new Connection("71", "29"));
mapTemplate.Connections.Add(new Connection("71", "58"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "78"));
mapTemplate.Connections.Add(new Connection("72", "30"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("72", "75"));
mapTemplate.Connections.Add(new Connection("72", "76"));
mapTemplate.Connections.Add(new Connection("72", "78"));
mapTemplate.Connections.Add(new Connection("73", "31"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("74", "32"));
mapTemplate.Connections.Add(new Connection("74", "43"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("74", "76"));
mapTemplate.Connections.Add(new Connection("74", "77"));
mapTemplate.Connections.Add(new Connection("75", "33"));
mapTemplate.Connections.Add(new Connection("75", "72"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("76", "34"));
mapTemplate.Connections.Add(new Connection("76", "72"));
mapTemplate.Connections.Add(new Connection("76", "74"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "78"));
mapTemplate.Connections.Add(new Connection("77", "35"));
mapTemplate.Connections.Add(new Connection("77", "74"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("78", "36"));
mapTemplate.Connections.Add(new Connection("78", "70"));
mapTemplate.Connections.Add(new Connection("78", "71"));
mapTemplate.Connections.Add(new Connection("78", "72"));
mapTemplate.Connections.Add(new Connection("78", "76"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("78", "80"));
mapTemplate.Connections.Add(new Connection("79", "37"));
mapTemplate.Connections.Add(new Connection("79", "69"));
mapTemplate.Connections.Add(new Connection("79", "70"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("80", "38"));
mapTemplate.Connections.Add(new Connection("80", "78"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("80", "82"));
mapTemplate.Connections.Add(new Connection("81", "39"));
mapTemplate.Connections.Add(new Connection("81", "83"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("82", "40"));
mapTemplate.Connections.Add(new Connection("82", "80"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("82", "84"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("83", "41"));
mapTemplate.Connections.Add(new Connection("83", "81"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("84", "42"));
mapTemplate.Connections.Add(new Connection("84", "82"));
mapTemplate.Connections.Add(new Connection("84", "83"));

            return mapTemplate;
		}
    }
}

