
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Essen()
        {

var mapTemplate = new MapTemplate("Essen") { Image = "Essen.jpg" };
var country1 = new CountryTemplate("1", "Karnap") { X = 369, Y = 34 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Altenessen-Nord") { X = 415, Y = 105 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Vogelheim") { X = 309, Y = 227 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Altenessen-Süd") { X = 379, Y = 236 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Karternberg") { X = 488, Y = 139 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Stoppenberg") { X = 452, Y = 240 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Schonnebeck") { X = 558, Y = 305 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Kray") { X = 597, Y = 335 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Leithe") { X = 650, Y = 380 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Steele") { X = 603, Y = 430 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Freisenbruch") { X = 700, Y = 397 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Horst") { X = 716, Y = 483 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Burgaltendorf") { X = 729, Y = 554 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Überruhr-Hinsel") { X = 590, Y = 491 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Überruhr-Holthausen") { X = 630, Y = 566 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Byfang") { X = 710, Y = 741 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Kupferdreh") { X = 625, Y = 746 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Heisingen") { X = 559, Y = 680 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Fischlaken") { X = 512, Y = 775 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Bredeney") { X = 340, Y = 615 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Heidhausen") { X = 358, Y = 869 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Werden") { X = 370, Y = 740 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Kettwig") { X = 179, Y = 912 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Schuir") { X = 240, Y = 706 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Haarzopf") { X = 204, Y = 643 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Margarethenhöhe") { X = 288, Y = 573 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Fulerum") { X = 235, Y = 505 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Holsterhausen") { X = 322, Y = 440 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Frohnhausen") { X = 247, Y = 481 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Altendorf") { X = 231, Y = 394 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Essen") { X = 394, Y = 411 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Westviertel") { X = 328, Y = 404 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Südviertel") { X = 417, Y = 461 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Huttrop") { X = 504, Y = 426 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Südostviertel") { X = 444, Y = 441 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Ostviertel") { X = 436, Y = 392 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Frillendorf") { X = 524, Y = 332 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Nordviertel") { X = 380, Y = 354 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Röttenscheid") { X = 341, Y = 549 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Stadtwald") { X = 482, Y = 602 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Rellinghausen") { X = 530, Y = 580 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Bergerhausen") { X = 470, Y = 513 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Bergeborbeck") { X = 242, Y = 240 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Bochold") { X = 225, Y = 340 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Schönebeck") { X = 107, Y = 418 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Borbeck") { X = 162, Y = 355 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Bedingrade") { X = 113, Y = 305 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Frintrop") { X = 42, Y = 265 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Dellwig") { X = 135, Y = 204 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Gerschede") { X = 145, Y = 280 };
mapTemplate.Countries.Add(country50);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country31);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country32);
continent2.Countries.Add(country33);
continent2.Countries.Add(country34);
continent2.Countries.Add(country35);
continent2.Countries.Add(country36);
continent2.Countries.Add(country37);
continent2.Countries.Add(country38);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country39);
continent3.Countries.Add(country40);
continent3.Countries.Add(country41);
continent3.Countries.Add(country42);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
continent4.Countries.Add(country28);
continent4.Countries.Add(country29);
continent4.Countries.Add(country30);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 5);
continent5.Countries.Add(country43);
continent5.Countries.Add(country44);
continent5.Countries.Add(country45);
continent5.Countries.Add(country46);
continent5.Countries.Add(country47);
continent5.Countries.Add(country48);
continent5.Countries.Add(country49);
continent5.Countries.Add(country50);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country1);
continent6.Countries.Add(country2);
continent6.Countries.Add(country3);
continent6.Countries.Add(country4);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country5);
continent7.Countries.Add(country6);
continent7.Countries.Add(country7);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country8);
continent8.Countries.Add(country9);
continent8.Countries.Add(country10);
continent8.Countries.Add(country11);
continent8.Countries.Add(country12);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country13);
continent9.Countries.Add(country14);
continent9.Countries.Add(country15);
continent9.Countries.Add(country16);
continent9.Countries.Add(country17);
continent9.Countries.Add(country18);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country19);
continent10.Countries.Add(country20);
continent10.Countries.Add(country21);
continent10.Countries.Add(country22);
continent10.Countries.Add(country23);
continent10.Countries.Add(country24);
mapTemplate.Continents.Add(continent10);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "43"));
mapTemplate.Connections.Add(new Connection("3", "44"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "38"));
mapTemplate.Connections.Add(new Connection("4", "44"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "36"));
mapTemplate.Connections.Add(new Connection("6", "38"));
mapTemplate.Connections.Add(new Connection("6", "37"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "37"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "37"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "34"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "34"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "42"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "42"));
mapTemplate.Connections.Add(new Connection("14", "41"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "41"));
mapTemplate.Connections.Add(new Connection("18", "40"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "40"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "24"));
mapTemplate.Connections.Add(new Connection("20", "26"));
mapTemplate.Connections.Add(new Connection("20", "39"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "20"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("26", "20"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "39"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "39"));
mapTemplate.Connections.Add(new Connection("28", "33"));
mapTemplate.Connections.Add(new Connection("28", "32"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "45"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "45"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "44"));
mapTemplate.Connections.Add(new Connection("30", "38"));
mapTemplate.Connections.Add(new Connection("31", "36"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "38"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "28"));
mapTemplate.Connections.Add(new Connection("32", "38"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "29"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "28"));
mapTemplate.Connections.Add(new Connection("33", "39"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "36"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "10"));
mapTemplate.Connections.Add(new Connection("34", "8"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "39"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "31"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "6"));
mapTemplate.Connections.Add(new Connection("36", "33"));
mapTemplate.Connections.Add(new Connection("37", "7"));
mapTemplate.Connections.Add(new Connection("37", "8"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "6"));
mapTemplate.Connections.Add(new Connection("38", "31"));
mapTemplate.Connections.Add(new Connection("38", "32"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "30"));
mapTemplate.Connections.Add(new Connection("38", "4"));
mapTemplate.Connections.Add(new Connection("38", "6"));
mapTemplate.Connections.Add(new Connection("38", "44"));
mapTemplate.Connections.Add(new Connection("39", "20"));
mapTemplate.Connections.Add(new Connection("39", "26"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("39", "28"));
mapTemplate.Connections.Add(new Connection("39", "33"));
mapTemplate.Connections.Add(new Connection("39", "34"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "18"));
mapTemplate.Connections.Add(new Connection("40", "20"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("41", "18"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "14"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "14"));
mapTemplate.Connections.Add(new Connection("42", "34"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("42", "10"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "3"));
mapTemplate.Connections.Add(new Connection("43", "49"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "50"));
mapTemplate.Connections.Add(new Connection("44", "30"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "38"));
mapTemplate.Connections.Add(new Connection("44", "4"));
mapTemplate.Connections.Add(new Connection("44", "3"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "30"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "29"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "50"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("49", "43"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("50", "46"));
mapTemplate.Connections.Add(new Connection("50", "43"));

            return mapTemplate;
		}
    }
}

