
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Japan()
        {

var mapTemplate = new MapTemplate("Japan") { Image = "japan.jpg" };
var country1 = new CountryTemplate("1", "Osiu") { X = 769, Y = 67 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Dewa") { X = 713, Y = 137 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Eitat") { X = 754, Y = 200 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Kodsk") { X = 703, Y = 218 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Jetsingo") { X = 662, Y = 182 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Jetsiu") { X = 601, Y = 227 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Sinano") { X = 613, Y = 282 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Musasi") { X = 697, Y = 279 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Simosa") { X = 744, Y = 271 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Kausus") { X = 752, Y = 329 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Awa") { X = 741, Y = 379 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Sagoami") { X = 679, Y = 320 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Kay") { X = 653, Y = 293 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Farro") { X = 647, Y = 335 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Totomi") { X = 628, Y = 368 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Icawa") { X = 599, Y = 369 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Mino") { X = 552, Y = 330 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Owar") { X = 569, Y = 361 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Noto") { X = 552, Y = 180 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Kaga") { X = 552, Y = 242 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Jetsdien") { X = 528, Y = 300 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Wakasa") { X = 475, Y = 339 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Oomi") { X = 517, Y = 373 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Isje Sma") { X = 559, Y = 420 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Fida") { X = 577, Y = 277 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Tango") { X = 428, Y = 344 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Tasima") { X = 389, Y = 367 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Tanba") { X = 445, Y = 385 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Isnaba") { X = 356, Y = 389 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Foki") { X = 322, Y = 413 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Mimasaca") { X = 371, Y = 438 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Sitz") { X = 462, Y = 421 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Farima") { X = 417, Y = 421 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Bitsiu") { X = 337, Y = 456 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Sanuk") { X = 375, Y = 507 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Bingo") { X = 307, Y = 469 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Gok") { X = 484, Y = 382 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Inai") { X = 510, Y = 455 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Kinokini") { X = 532, Y = 500 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Awa2") { X = 405, Y = 530 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Ijo") { X = 319, Y = 549 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Tossa") { X = 356, Y = 570 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Aki") { X = 281, Y = 495 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Idzomo") { X = 265, Y = 415 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Oki") { X = 297, Y = 348 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Uwami") { X = 252, Y = 458 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Suwo") { X = 240, Y = 503 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Nacato") { X = 197, Y = 503 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Budse") { X = 208, Y = 561 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Bongo") { X = 246, Y = 592 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Tsikudsen") { X = 153, Y = 555 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Fidskn") { X = 120, Y = 598 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Tjikuni") { X = 177, Y = 599 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Figo") { X = 211, Y = 626 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Fiuga") { X = 248, Y = 636 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Osumi") { X = 233, Y = 687 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Satsum") { X = 193, Y = 668 };
mapTemplate.Countries.Add(country57);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country11);
continent2.Countries.Add(country10);
continent2.Countries.Add(country9);
continent2.Countries.Add(country8);
continent2.Countries.Add(country12);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 5);
continent4.Countries.Add(country19);
continent4.Countries.Add(country6);
continent4.Countries.Add(country20);
continent4.Countries.Add(country7);
continent4.Countries.Add(country13);
continent4.Countries.Add(country17);
continent4.Countries.Add(country18);
continent4.Countries.Add(country21);
continent4.Countries.Add(country25);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country22);
continent5.Countries.Add(country26);
continent5.Countries.Add(country28);
continent5.Countries.Add(country27);
continent5.Countries.Add(country29);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country31);
continent6.Countries.Add(country34);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country39);
continent7.Countries.Add(country24);
continent7.Countries.Add(country38);
continent7.Countries.Add(country23);
continent7.Countries.Add(country37);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country42);
continent8.Countries.Add(country40);
continent8.Countries.Add(country35);
continent8.Countries.Add(country41);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 4);
continent9.Countries.Add(country45);
continent9.Countries.Add(country44);
continent9.Countries.Add(country30);
continent9.Countries.Add(country36);
continent9.Countries.Add(country43);
continent9.Countries.Add(country46);
continent9.Countries.Add(country47);
continent9.Countries.Add(country48);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country49);
continent10.Countries.Add(country50);
continent10.Countries.Add(country55);
continent10.Countries.Add(country56);
continent10.Countries.Add(country57);
continent10.Countries.Add(country54);
continent10.Countries.Add(country53);
continent10.Countries.Add(country51);
continent10.Countries.Add(country52);
mapTemplate.Continents.Add(continent10);	
mapTemplate.Connections.Add(new Connection("25", "6"));
mapTemplate.Connections.Add(new Connection("25", "7"));
mapTemplate.Connections.Add(new Connection("25", "17"));
mapTemplate.Connections.Add(new Connection("25", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "25"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "6"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "6"));
mapTemplate.Connections.Add(new Connection("18", "24"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "24"));
mapTemplate.Connections.Add(new Connection("17", "23"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "25"));
mapTemplate.Connections.Add(new Connection("17", "7"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "7"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "7"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "7"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("13", "7"));
mapTemplate.Connections.Add(new Connection("13", "8"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "13"));
mapTemplate.Connections.Add(new Connection("7", "14"));
mapTemplate.Connections.Add(new Connection("7", "15"));
mapTemplate.Connections.Add(new Connection("7", "16"));
mapTemplate.Connections.Add(new Connection("7", "17"));
mapTemplate.Connections.Add(new Connection("7", "25"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "25"));
mapTemplate.Connections.Add(new Connection("6", "20"));
mapTemplate.Connections.Add(new Connection("6", "19"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "36"));
mapTemplate.Connections.Add(new Connection("30", "44"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "36"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "35"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("32", "38"));
mapTemplate.Connections.Add(new Connection("32", "37"));
mapTemplate.Connections.Add(new Connection("32", "28"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "36"));
mapTemplate.Connections.Add(new Connection("41", "35"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "33"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "9"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "8"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "33"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "30"));
mapTemplate.Connections.Add(new Connection("44", "36"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("28", "37"));
mapTemplate.Connections.Add(new Connection("28", "22"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "33"));
mapTemplate.Connections.Add(new Connection("28", "32"));
mapTemplate.Connections.Add(new Connection("38", "24"));
mapTemplate.Connections.Add(new Connection("38", "23"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "32"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "54"));
mapTemplate.Connections.Add(new Connection("37", "22"));
mapTemplate.Connections.Add(new Connection("37", "28"));
mapTemplate.Connections.Add(new Connection("37", "32"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "23"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "12"));
mapTemplate.Connections.Add(new Connection("8", "13"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("23", "17"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "37"));
mapTemplate.Connections.Add(new Connection("23", "38"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("40", "35"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "31"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "40"));
mapTemplate.Connections.Add(new Connection("35", "42"));
mapTemplate.Connections.Add(new Connection("35", "41"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "56"));
mapTemplate.Connections.Add(new Connection("54", "57"));
mapTemplate.Connections.Add(new Connection("54", "50"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "37"));
mapTemplate.Connections.Add(new Connection("22", "28"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("9", "3"));
mapTemplate.Connections.Add(new Connection("9", "4"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "28"));
mapTemplate.Connections.Add(new Connection("33", "27"));
mapTemplate.Connections.Add(new Connection("33", "29"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("24", "18"));
mapTemplate.Connections.Add(new Connection("24", "17"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "38"));
mapTemplate.Connections.Add(new Connection("24", "39"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "35"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "9"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "30"));
mapTemplate.Connections.Add(new Connection("36", "44"));
mapTemplate.Connections.Add(new Connection("36", "46"));
mapTemplate.Connections.Add(new Connection("36", "43"));
mapTemplate.Connections.Add(new Connection("36", "41"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "50"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("50", "55"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("39", "24"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "36"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "54"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "6"));

            return mapTemplate;
		}
    }
}

