
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Nordstaat()
        {

var mapTemplate = new MapTemplate("Nordstaat") { Image = "nordstaat.jpg" };
var country1 = new CountryTemplate("1", "Flensburg") { X = 468, Y = 93 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Kiel") { X = 509, Y = 193 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Nordfriesland") { X = 354, Y = 161 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Dithmarschen") { X = 408, Y = 237 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Steinburg") { X = 462, Y = 292 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Plön") { X = 594, Y = 196 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Segeberg") { X = 555, Y = 298 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Ostholstein") { X = 666, Y = 246 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Lübeck") { X = 634, Y = 345 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Wismar") { X = 734, Y = 336 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Rostock") { X = 923, Y = 243 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Stralsund") { X = 995, Y = 188 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Regen") { X = 1072, Y = 161 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Ludwigslust") { X = 759, Y = 453 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Schwerin") { X = 849, Y = 400 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Güstrow") { X = 948, Y = 289 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Müritz") { X = 964, Y = 410 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Demmin") { X = 1035, Y = 298 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Greifswald") { X = 1127, Y = 294 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Strelitz") { X = 1100, Y = 380 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Randow") { X = 1205, Y = 374 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Pinneberg") { X = 506, Y = 328 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Hamburg") { X = 548, Y = 374 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Harburg") { X = 511, Y = 459 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Lüneburg") { X = 599, Y = 482 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Uelzen") { X = 632, Y = 530 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Lüchow") { X = 722, Y = 514 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Falling") { X = 481, Y = 589 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Celle") { X = 566, Y = 598 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Gifhorn") { X = 653, Y = 629 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Cuxhaven") { X = 340, Y = 396 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Stade") { X = 451, Y = 372 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Rotenburg") { X = 456, Y = 496 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Bremen") { X = 353, Y = 492 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Emden") { X = 110, Y = 387 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Wilhelmshaven") { X = 207, Y = 406 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Amerland") { X = 274, Y = 446 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Leer") { X = 139, Y = 457 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Oldenburg") { X = 297, Y = 557 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Cloppenburg") { X = 212, Y = 556 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Emsland") { X = 114, Y = 569 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Bentheim") { X = 71, Y = 673 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Osnabrück") { X = 186, Y = 658 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Wolfsburg") { X = 671, Y = 760 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Salzgitter") { X = 572, Y = 755 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Hannover") { X = 500, Y = 702 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Goslar") { X = 618, Y = 850 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Harz") { X = 612, Y = 902 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Northeim") { X = 527, Y = 859 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Göttingen") { X = 525, Y = 948 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Diepholz") { X = 342, Y = 590 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Hameln") { X = 425, Y = 747 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Verden") { X = 429, Y = 564 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Nienburg") { X = 393, Y = 652 };
mapTemplate.Countries.Add(country54);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
continent4.Countries.Add(country16);
continent4.Countries.Add(country17);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
continent5.Countries.Add(country20);
continent5.Countries.Add(country21);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country25);
continent7.Countries.Add(country26);
continent7.Countries.Add(country27);
continent7.Countries.Add(country28);
continent7.Countries.Add(country29);
continent7.Countries.Add(country30);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country31);
continent8.Countries.Add(country32);
continent8.Countries.Add(country33);
continent8.Countries.Add(country34);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country35);
continent9.Countries.Add(country36);
continent9.Countries.Add(country37);
continent9.Countries.Add(country38);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country39);
continent10.Countries.Add(country40);
continent10.Countries.Add(country41);
continent10.Countries.Add(country42);
continent10.Countries.Add(country43);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 2);
continent11.Countries.Add(country44);
continent11.Countries.Add(country45);
continent11.Countries.Add(country46);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 2);
continent12.Countries.Add(country47);
continent12.Countries.Add(country48);
continent12.Countries.Add(country49);
continent12.Countries.Add(country50);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 3);
continent13.Countries.Add(country51);
continent13.Countries.Add(country52);
continent13.Countries.Add(country53);
continent13.Countries.Add(country54);
mapTemplate.Continents.Add(continent13);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("2", "7"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "22"));
mapTemplate.Connections.Add(new Connection("5", "32"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("6", "2"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("7", "2"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "22"));
mapTemplate.Connections.Add(new Connection("7", "23"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "14"));
mapTemplate.Connections.Add(new Connection("9", "25"));
mapTemplate.Connections.Add(new Connection("9", "24"));
mapTemplate.Connections.Add(new Connection("9", "23"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("10", "15"));
mapTemplate.Connections.Add(new Connection("10", "16"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("12", "19"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "9"));
mapTemplate.Connections.Add(new Connection("14", "27"));
mapTemplate.Connections.Add(new Connection("14", "25"));
mapTemplate.Connections.Add(new Connection("15", "10"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("16", "10"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("19", "12"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "5"));
mapTemplate.Connections.Add(new Connection("22", "7"));
mapTemplate.Connections.Add(new Connection("22", "32"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "7"));
mapTemplate.Connections.Add(new Connection("23", "9"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "32"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "9"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "32"));
mapTemplate.Connections.Add(new Connection("24", "33"));
mapTemplate.Connections.Add(new Connection("24", "28"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "14"));
mapTemplate.Connections.Add(new Connection("25", "9"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "30"));
mapTemplate.Connections.Add(new Connection("27", "14"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("28", "24"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "46"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "54"));
mapTemplate.Connections.Add(new Connection("28", "53"));
mapTemplate.Connections.Add(new Connection("28", "33"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "46"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("30", "26"));
mapTemplate.Connections.Add(new Connection("30", "44"));
mapTemplate.Connections.Add(new Connection("30", "45"));
mapTemplate.Connections.Add(new Connection("30", "46"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "37"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("32", "5"));
mapTemplate.Connections.Add(new Connection("32", "22"));
mapTemplate.Connections.Add(new Connection("32", "23"));
mapTemplate.Connections.Add(new Connection("32", "24"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "24"));
mapTemplate.Connections.Add(new Connection("33", "28"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "53"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "39"));
mapTemplate.Connections.Add(new Connection("34", "51"));
mapTemplate.Connections.Add(new Connection("34", "53"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("37", "31"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("39", "34"));
mapTemplate.Connections.Add(new Connection("39", "51"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("40", "51"));
mapTemplate.Connections.Add(new Connection("40", "37"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "43"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("43", "51"));
mapTemplate.Connections.Add(new Connection("43", "40"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("44", "30"));
mapTemplate.Connections.Add(new Connection("44", "47"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "30"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "49"));
mapTemplate.Connections.Add(new Connection("45", "52"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "30"));
mapTemplate.Connections.Add(new Connection("46", "52"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "29"));
mapTemplate.Connections.Add(new Connection("46", "28"));
mapTemplate.Connections.Add(new Connection("46", "54"));
mapTemplate.Connections.Add(new Connection("47", "44"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "45"));
mapTemplate.Connections.Add(new Connection("49", "52"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("51", "34"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("51", "39"));
mapTemplate.Connections.Add(new Connection("51", "40"));
mapTemplate.Connections.Add(new Connection("51", "43"));
mapTemplate.Connections.Add(new Connection("52", "49"));
mapTemplate.Connections.Add(new Connection("52", "45"));
mapTemplate.Connections.Add(new Connection("52", "46"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("53", "28"));
mapTemplate.Connections.Add(new Connection("53", "34"));
mapTemplate.Connections.Add(new Connection("53", "33"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "46"));
mapTemplate.Connections.Add(new Connection("54", "28"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "51"));

            return mapTemplate;
		}
    }
}

