
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Iopoly()
        {

var mapTemplate = new MapTemplate("Iopoly") { Image = "iopoly.jpg" };
var country1 = new CountryTemplate("1", "WZ Europa") { X = 897, Y = 840 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Australien") { X = 760, Y = 888 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Sydney") { X = 683, Y = 888 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Neuseeland") { X = 607, Y = 888 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Euro") { X = 530, Y = 888 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "ASEAN") { X = 453, Y = 888 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Russland") { X = 377, Y = 888 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Prag") { X = 299, Y = 888 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Ungarn") { X = 223, Y = 888 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Polen") { X = 146, Y = 887 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "WZ Afrika und Naher Osten") { X = 81, Y = 841 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Brasilien") { X = 24, Y = 765 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "WTO") { X = 24, Y = 688 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Kolumbien") { X = 24, Y = 611 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Argentinien") { X = 24, Y = 536 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "EU") { X = 24, Y = 458 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Deutschland") { X = 24, Y = 381 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Hambrug") { X = 24, Y = 305 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Spanien") { X = 24, Y = 228 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Frankreich") { X = 24, Y = 152 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "WZ Ozeanien und Asien") { X = 80, Y = 31 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Israel") { X = 146, Y = 30 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Dubai") { X = 223, Y = 30 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Iran") { X = 299, Y = 30 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Türkei") { X = 377, Y = 30 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "MERCOSUR") { X = 453, Y = 30 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Südafrika") { X = 530, Y = 30 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Marokko") { X = 607, Y = 30 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Weltbank") { X = 683, Y = 30 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Tansania") { X = 760, Y = 30 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "WZ Amerika") { X = 891, Y = 29 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Japan") { X = 883, Y = 152 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Indien") { X = 883, Y = 228 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Singapur") { X = 883, Y = 305 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "China") { X = 883, Y = 381 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "NAFTA") { X = 883, Y = 458 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Atlanta") { X = 883, Y = 536 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Kanada") { X = 883, Y = 611 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Dollar") { X = 883, Y = 688 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "USA") { X = 883, Y = 765 };
mapTemplate.Countries.Add(country40);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country7);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country12);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country17);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country22);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country27);
continent6.Countries.Add(country28);
continent6.Countries.Add(country30);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country32);
continent7.Countries.Add(country33);
continent7.Countries.Add(country35);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country38);
continent8.Countries.Add(country40);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country5);
continent9.Countries.Add(country39);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country13);
continent10.Countries.Add(country29);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 4);
continent11.Countries.Add(country6);
continent11.Countries.Add(country16);
continent11.Countries.Add(country26);
continent11.Countries.Add(country36);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 3);
continent12.Countries.Add(country8);
continent12.Countries.Add(country23);
continent12.Countries.Add(country37);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 3);
continent13.Countries.Add(country3);
continent13.Countries.Add(country18);
continent13.Countries.Add(country34);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 1);
continent14.Countries.Add(country21);
continent14.Countries.Add(country2);
continent14.Countries.Add(country4);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 1);
continent15.Countries.Add(country1);
continent15.Countries.Add(country7);
continent15.Countries.Add(country9);
continent15.Countries.Add(country10);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 1);
continent16.Countries.Add(country31);
continent16.Countries.Add(country12);
continent16.Countries.Add(country14);
continent16.Countries.Add(country15);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 1);
continent17.Countries.Add(country1);
continent17.Countries.Add(country17);
continent17.Countries.Add(country19);
continent17.Countries.Add(country20);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 1);
continent18.Countries.Add(country11);
continent18.Countries.Add(country22);
continent18.Countries.Add(country24);
continent18.Countries.Add(country25);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 1);
continent19.Countries.Add(country11);
continent19.Countries.Add(country27);
continent19.Countries.Add(country28);
continent19.Countries.Add(country30);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 1);
continent20.Countries.Add(country21);
continent20.Countries.Add(country32);
continent20.Countries.Add(country33);
continent20.Countries.Add(country35);
mapTemplate.Continents.Add(continent20);
var continent21 = new Continent("21", 1);
continent21.Countries.Add(country31);
continent21.Countries.Add(country38);
continent21.Countries.Add(country40);
mapTemplate.Continents.Add(continent21);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "18"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("8", "23"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "34"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "37"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "36"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "3"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "8"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "1"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "1"));
mapTemplate.Connections.Add(new Connection("39", "2"));
mapTemplate.Connections.Add(new Connection("40", "1"));
mapTemplate.Connections.Add(new Connection("40", "2"));
mapTemplate.Connections.Add(new Connection("40", "3"));

            return mapTemplate;
		}
    }
}

