
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Fussball()
        {

var mapTemplate = new MapTemplate("Fussball") { Image = "fussball.jpg" };
var country1 = new CountryTemplate("1", "Kahn") { X = 125, Y = 463 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Nowotny") { X = 285, Y = 486 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Metzelder") { X = 219, Y = 406 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Jansen") { X = 209, Y = 347 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Lahm") { X = 415, Y = 575 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Frings") { X = 507, Y = 444 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Kehl") { X = 413, Y = 384 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Schweinsteiger") { X = 415, Y = 320 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Schneider") { X = 691, Y = 516 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Podolski") { X = 687, Y = 350 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Klose") { X = 761, Y = 396 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Phoenics") { X = 905, Y = 332 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Shadowk") { X = 912, Y = 404 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Shark") { X = 805, Y = 351 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "draegon116") { X = 707, Y = 305 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "alterschlagg") { X = 639, Y = 450 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "bartholomaeus") { X = 549, Y = 396 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Wario") { X = 485, Y = 346 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "ARIANA_FFM") { X = 619, Y = 378 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Lockhead") { X = 259, Y = 381 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Alita") { X = 311, Y = 432 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Stingray") { X = 377, Y = 503 };
mapTemplate.Countries.Add(country22);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country12);
continent4.Countries.Add(country13);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country20);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
mapTemplate.Continents.Add(continent6);
mapTemplate.Connections.Add(new Connection("1", "5"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "21"));
mapTemplate.Connections.Add(new Connection("2", "22"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "21"));
mapTemplate.Connections.Add(new Connection("3", "20"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "20"));
mapTemplate.Connections.Add(new Connection("5", "1"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "22"));
mapTemplate.Connections.Add(new Connection("5", "9"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "16"));
mapTemplate.Connections.Add(new Connection("6", "17"));
mapTemplate.Connections.Add(new Connection("6", "11"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "18"));
mapTemplate.Connections.Add(new Connection("7", "17"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "18"));
mapTemplate.Connections.Add(new Connection("8", "4"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "16"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "15"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "19"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "10"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("16", "6"));
mapTemplate.Connections.Add(new Connection("16", "9"));
mapTemplate.Connections.Add(new Connection("16", "22"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "7"));
mapTemplate.Connections.Add(new Connection("17", "6"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "8"));
mapTemplate.Connections.Add(new Connection("18", "7"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "3"));
mapTemplate.Connections.Add(new Connection("20", "4"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "2"));
mapTemplate.Connections.Add(new Connection("21", "3"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "2"));
mapTemplate.Connections.Add(new Connection("22", "5"));

            return mapTemplate;
		}
    }
}

