
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate RandSwelt()
        {

var mapTemplate = new MapTemplate("RandSwelt") { Image = "randwelt.jpg" };
var country1 = new CountryTemplate("1", "WestlKleineFaeule") { X = 124, Y = 118 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "OestlKleineFaeule") { X = 234, Y = 101 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "WestlicheFaeule") { X = 750, Y = 89 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "ShayolGhul") { X = 832, Y = 98 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "ZentraleFaeule") { X = 919, Y = 142 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "OestlicheFaeule") { X = 1028, Y = 158 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Grenzlande") { X = 794, Y = 155 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Tar Valon") { X = 780, Y = 178 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Cairhien") { X = 811, Y = 245 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Illian") { X = 762, Y = 287 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Tear") { X = 823, Y = 297 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Aridhol") { X = 728, Y = 191 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Andor") { X = 752, Y = 235 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Altara") { X = 718, Y = 272 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Tarabon") { X = 670, Y = 262 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Almoth") { X = 670, Y = 212 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "AradDoman") { X = 678, Y = 174 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Tremalking") { X = 595, Y = 310 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "ArythOzeanInseln") { X = 547, Y = 528 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "MeerderStuermeInseln") { X = 922, Y = 439 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Ancarid") { X = 265, Y = 410 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "NoerdlAielWueste") { X = 873, Y = 210 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "SuedlAielWueste") { X = 900, Y = 250 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Termool") { X = 903, Y = 287 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Nordwest-Shara") { X = 976, Y = 208 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Nordost-Shara") { X = 1055, Y = 230 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "West-Shara") { X = 981, Y = 313 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Ost-Shara") { X = 1060, Y = 320 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Sued-Shara") { X = 1014, Y = 414 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Meervolk H�fen") { X = 1032, Y = 456 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "WestlichesLdW") { X = 684, Y = 626 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "NoerdlLdW") { X = 785, Y = 654 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "SuedlLdW") { X = 745, Y = 746 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "OestlLdW") { X = 851, Y = 715 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Jeranem") { X = 342, Y = 709 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "NorenMShar") { X = 221, Y = 672 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Rampore") { X = 331, Y = 561 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "ShonKifar") { X = 244, Y = 540 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Tzura") { X = 158, Y = 517 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Asinbayar") { X = 107, Y = 548 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Barsabba") { X = 126, Y = 610 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Anagore") { X = 97, Y = 448 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Kirendad") { X = 171, Y = 400 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Sohima") { X = 159, Y = 195 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Imfaral") { X = 180, Y = 263 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Marendalar") { X = 246, Y = 268 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Seander") { X = 228, Y = 350 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Tuel") { X = 58, Y = 299 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Quirat") { X = 88, Y = 371 };
mapTemplate.Countries.Add(country49);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country44);
continent2.Countries.Add(country45);
continent2.Countries.Add(country46);
continent2.Countries.Add(country47);
continent2.Countries.Add(country48);
continent2.Countries.Add(country49);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 4);
continent3.Countries.Add(country35);
continent3.Countries.Add(country36);
continent3.Countries.Add(country37);
continent3.Countries.Add(country38);
continent3.Countries.Add(country39);
continent3.Countries.Add(country40);
continent3.Countries.Add(country41);
continent3.Countries.Add(country42);
continent3.Countries.Add(country43);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
continent5.Countries.Add(country28);
continent5.Countries.Add(country29);
continent5.Countries.Add(country30);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country34);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country12);
continent7.Countries.Add(country13);
continent7.Countries.Add(country14);
continent7.Countries.Add(country15);
continent7.Countries.Add(country16);
continent7.Countries.Add(country17);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country7);
continent8.Countries.Add(country8);
continent8.Countries.Add(country9);
continent8.Countries.Add(country10);
continent8.Countries.Add(country11);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country22);
continent9.Countries.Add(country23);
continent9.Countries.Add(country24);
mapTemplate.Continents.Add(continent9);
mapTemplate.Connections.Add(new Connection("1", "44"));
mapTemplate.Connections.Add(new Connection("1", "45"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "6"));
mapTemplate.Connections.Add(new Connection("2", "45"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "22"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "22"));
mapTemplate.Connections.Add(new Connection("5", "25"));
mapTemplate.Connections.Add(new Connection("6", "1"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "25"));
mapTemplate.Connections.Add(new Connection("6", "26"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "22"));
mapTemplate.Connections.Add(new Connection("7", "17"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "12"));
mapTemplate.Connections.Add(new Connection("8", "13"));
mapTemplate.Connections.Add(new Connection("8", "12"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "22"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("11", "24"));
mapTemplate.Connections.Add(new Connection("11", "20"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("12", "8"));
mapTemplate.Connections.Add(new Connection("12", "7"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("13", "8"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "46"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("17", "7"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("19", "37"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "32"));
mapTemplate.Connections.Add(new Connection("20", "30"));
mapTemplate.Connections.Add(new Connection("20", "11"));
mapTemplate.Connections.Add(new Connection("21", "47"));
mapTemplate.Connections.Add(new Connection("21", "39"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("22", "4"));
mapTemplate.Connections.Add(new Connection("22", "5"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("22", "7"));
mapTemplate.Connections.Add(new Connection("22", "9"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "11"));
mapTemplate.Connections.Add(new Connection("25", "5"));
mapTemplate.Connections.Add(new Connection("25", "6"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("26", "6"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "20"));
mapTemplate.Connections.Add(new Connection("30", "42"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "37"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("32", "20"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("36", "41"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "35"));
mapTemplate.Connections.Add(new Connection("37", "19"));
mapTemplate.Connections.Add(new Connection("37", "31"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("39", "43"));
mapTemplate.Connections.Add(new Connection("39", "21"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "36"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "49"));
mapTemplate.Connections.Add(new Connection("42", "30"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("43", "39"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("44", "48"));
mapTemplate.Connections.Add(new Connection("44", "49"));
mapTemplate.Connections.Add(new Connection("44", "1"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "2"));
mapTemplate.Connections.Add(new Connection("45", "1"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "16"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "21"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("48", "44"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "44"));
mapTemplate.Connections.Add(new Connection("49", "42"));

            return mapTemplate;
		}
    }
}

