
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Central_America()
        {

var mapTemplate = new MapTemplate("Central_America") { Image = "central_america.png" };
var country1 = new CountryTemplate("1", "Florida") { X = 371, Y = 53 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Yucatan") { X = 112, Y = 243 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Quintana Roo") { X = 129, Y = 286 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Campeche") { X = 68, Y = 312 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Chiapas") { X = 5, Y = 385 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "East Guatemala") { X = 82, Y = 393 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "West Guatemala") { X = 42, Y = 448 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Belize") { X = 127, Y = 356 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "West Honduras") { X = 146, Y = 461 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "El Salvador") { X = 96, Y = 482 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "East Honduras") { X = 217, Y = 438 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "North Nicaragua") { X = 245, Y = 497 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "South Nicaragua") { X = 247, Y = 554 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Costa Rica") { X = 259, Y = 613 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Panama") { X = 354, Y = 674 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Abaco") { X = 470, Y = 45 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Andros") { X = 463, Y = 132 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Eleuthera") { X = 521, Y = 117 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Long Island") { X = 547, Y = 171 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Inagua") { X = 602, Y = 200 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Turks and Caicos Islands") { X = 669, Y = 231 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Pinar del Rio") { X = 294, Y = 195 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Havana") { X = 365, Y = 189 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Santa Clara") { X = 412, Y = 207 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Camaguey") { X = 473, Y = 232 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Bayamo") { X = 509, Y = 257 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Guantanamo") { X = 553, Y = 271 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Cayman Islands") { X = 376, Y = 298 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Jamaica") { X = 486, Y = 341 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Haiti") { X = 640, Y = 305 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Dominican Republic") { X = 693, Y = 316 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Puerto Rico") { X = 825, Y = 337 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Virgin Islands") { X = 885, Y = 336 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "St_Kitts") { X = 941, Y = 367 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Antigua") { X = 964, Y = 337 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "West Colombia") { X = 533, Y = 680 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Zulia") { X = 711, Y = 656 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Guarico") { X = 835, Y = 649 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Monagas") { X = 931, Y = 625 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Bolivar") { X = 966, Y = 697 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Netherlands Antilles") { X = 745, Y = 539 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "East Colombia") { X = 621, Y = 687 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Gouadeloupe") { X = 998, Y = 406 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Martinique") { X = 1012, Y = 454 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "St_Vincent") { X = 996, Y = 519 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Barbados") { X = 1061, Y = 483 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Trinidad and Tobago") { X = 1007, Y = 590 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Guyana") { X = 1060, Y = 688 };
mapTemplate.Countries.Add(country48);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country16);
continent4.Countries.Add(country17);
continent4.Countries.Add(country18);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country22);
continent5.Countries.Add(country23);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country28);
continent6.Countries.Add(country29);
continent6.Countries.Add(country30);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country36);
continent7.Countries.Add(country37);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
continent7.Countries.Add(country41);
continent7.Countries.Add(country42);
continent7.Countries.Add(country48);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 4);
continent8.Countries.Add(country34);
continent8.Countries.Add(country35);
continent8.Countries.Add(country43);
continent8.Countries.Add(country44);
continent8.Countries.Add(country45);
continent8.Countries.Add(country46);
continent8.Countries.Add(country47);
mapTemplate.Continents.Add(continent8);
mapTemplate.Connections.Add(new Connection("1", "16"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "22"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "8"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "3"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("11", "29"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("15", "36"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("16", "1"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "24"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "27"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "30"));
mapTemplate.Connections.Add(new Connection("21", "31"));
mapTemplate.Connections.Add(new Connection("22", "3"));
mapTemplate.Connections.Add(new Connection("22", "28"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "17"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "28"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "20"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("28", "22"));
mapTemplate.Connections.Add(new Connection("28", "24"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "11"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "21"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "21"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "41"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "43"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "43"));
mapTemplate.Connections.Add(new Connection("36", "42"));
mapTemplate.Connections.Add(new Connection("36", "15"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "41"));
mapTemplate.Connections.Add(new Connection("37", "42"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "42"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("39", "45"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "47"));
mapTemplate.Connections.Add(new Connection("40", "47"));
mapTemplate.Connections.Add(new Connection("40", "48"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("41", "31"));
mapTemplate.Connections.Add(new Connection("41", "37"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "38"));
mapTemplate.Connections.Add(new Connection("42", "37"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "36"));
mapTemplate.Connections.Add(new Connection("43", "34"));
mapTemplate.Connections.Add(new Connection("43", "35"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "39"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "40"));
mapTemplate.Connections.Add(new Connection("47", "39"));
mapTemplate.Connections.Add(new Connection("48", "40"));

            return mapTemplate;
		}
    }
}

