using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate barcelona()
        {
            var mapTemplate = new MapTemplate("barcelona") { Image = "barcelona.png" };
            var country1 = new CountryTemplate("1", "Prat Vermell") { X = 139, Y = 622 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "la Marina de Port") { X = 169, Y = 562 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "Montjuic") { X = 250, Y = 596 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "el Poble Sec") { X = 334, Y = 591 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "la Bordeta") { X = 187, Y = 499 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "Hostafrancs") { X = 259, Y = 510 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "Sants") { X = 241, Y = 455 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "Sants-Badal") { X = 191, Y = 437 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "Nova Esquerra") { X = 327, Y = 473 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "Antiga Esquerra") { X = 385, Y = 457 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "Sant Antoni") { X = 335, Y = 541 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "la Dreta") { X = 467, Y = 475 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "la Sagrada Familia") { X = 571, Y = 482 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "el Fort Pienc") { X = 536, Y = 527 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "el Raval") { X = 385, Y = 568 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "el Gotic") { X = 423, Y = 597 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "Santa Catarina") { X = 492, Y = 602 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "la Barceloneta") { X = 471, Y = 659 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "la Vila Olimpica") { X = 559, Y = 626 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "el Poblenou") { X = 636, Y = 596 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "el Parc") { X = 568, Y = 562 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "Provencals") { X = 720, Y = 545 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "Diagonal Mar") { X = 722, Y = 603 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "Besos") { X = 771, Y = 559 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "el Camp") { X = 612, Y = 455 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "el Clot") { X = 645, Y = 497 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "Sant Marti") { X = 706, Y = 496 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "la Verneda") { X = 766, Y = 483 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "el Bon Pastor") { X = 849, Y = 398 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "la Sagrera") { X = 715, Y = 423 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "Navas") { X = 668, Y = 431 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "el Congres") { X = 674, Y = 382 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "Sant Andreu") { X = 780, Y = 346 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "la Trinitat Vella") { X = 882, Y = 293 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "Llobeta") { X = 678, Y = 330 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "Porta") { X = 729, Y = 313 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "la Peira") { X = 681, Y = 282 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "la Guineueta") { X = 717, Y = 258 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "la Prosperitat") { X = 775, Y = 279 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "Canyelles") { X = 716, Y = 202 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "les Roquetes") { X = 788, Y = 234 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "Torre Baro") { X = 825, Y = 193 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "Ciutat Meridiana") { X = 857, Y = 160 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "Vallbona") { X = 909, Y = 182 };
            mapTemplate.Countries.Add(country44);
            var country45 = new CountryTemplate("45", "la Trinitat Nova") { X = 834, Y = 263 };
            mapTemplate.Countries.Add(country45);
            var country46 = new CountryTemplate("46", "Horta") { X = 660, Y = 163 };
            mapTemplate.Countries.Add(country46);
            var country47 = new CountryTemplate("47", "Montbau") { X = 570, Y = 127 };
            mapTemplate.Countries.Add(country47);
            var country48 = new CountryTemplate("48", "Sant Genis") { X = 483, Y = 164 };
            mapTemplate.Countries.Add(country48);
            var country49 = new CountryTemplate("49", "la Vall dHebron") { X = 602, Y = 189 };
            mapTemplate.Countries.Add(country49);
            var country50 = new CountryTemplate("50", "la Teixonera") { X = 540, Y = 250 };
            mapTemplate.Countries.Add(country50);
            var country51 = new CountryTemplate("51", "el Carmel") { X = 557, Y = 287 };
            mapTemplate.Countries.Add(country51);
            var country52 = new CountryTemplate("52", "la Font") { X = 625, Y = 333 };
            mapTemplate.Countries.Add(country52);
            var country53 = new CountryTemplate("53", "Can Baro") { X = 564, Y = 360 };
            mapTemplate.Countries.Add(country53);
            var country54 = new CountryTemplate("54", "Guinardo") { X = 614, Y = 395 };
            mapTemplate.Countries.Add(country54);
            var country55 = new CountryTemplate("55", "Vallcarca") { X = 484, Y = 270 };
            mapTemplate.Countries.Add(country55);
            var country56 = new CountryTemplate("56", "la Salut") { X = 519, Y = 332 };
            mapTemplate.Countries.Add(country56);
            var country57 = new CountryTemplate("57", "Vila de Gracia") { X = 451, Y = 414 };
            mapTemplate.Countries.Add(country57);
            var country58 = new CountryTemplate("58", "Gracia Nova") { X = 517, Y = 378 };
            mapTemplate.Countries.Add(country58);
            var country59 = new CountryTemplate("59", "Vallvidrera") { X = 367, Y = 85 };
            mapTemplate.Countries.Add(country59);
            var country60 = new CountryTemplate("60", "Sarria") { X = 287, Y = 229 };
            mapTemplate.Countries.Add(country60);
            var country61 = new CountryTemplate("61", "Bonanova") { X = 392, Y = 246 };
            mapTemplate.Countries.Add(country61);
            var country62 = new CountryTemplate("62", "les Tres Torres") { X = 316, Y = 315 };
            mapTemplate.Countries.Add(country62);
            var country63 = new CountryTemplate("63", "Galvany") { X = 392, Y = 372 };
            mapTemplate.Countries.Add(country63);
            var country64 = new CountryTemplate("64", "el Pudget i Farro") { X = 432, Y = 316 };
            mapTemplate.Countries.Add(country64);
            var country65 = new CountryTemplate("65", "Pedralbes") { X = 203, Y = 269 };
            mapTemplate.Countries.Add(country65);
            var country66 = new CountryTemplate("66", "les Corts") { X = 296, Y = 396 };
            mapTemplate.Countries.Add(country66);
            var country67 = new CountryTemplate("67", "la Maternitat") { X = 190, Y = 357 };
            mapTemplate.Countries.Add(country67);
            var country68 = new CountryTemplate("68", "Zona Franca-Port") { X = 73, Y = 682 };
            mapTemplate.Countries.Add(country68);
            var continent1 = new Continent("1", 5);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            continent1.Countries.Add(country5);
            continent1.Countries.Add(country6);
            continent1.Countries.Add(country7);
            continent1.Countries.Add(country8);
            continent1.Countries.Add(country68);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 4);
            continent2.Countries.Add(country9);
            continent2.Countries.Add(country10);
            continent2.Countries.Add(country11);
            continent2.Countries.Add(country12);
            continent2.Countries.Add(country13);
            continent2.Countries.Add(country14);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 3);
            continent3.Countries.Add(country15);
            continent3.Countries.Add(country16);
            continent3.Countries.Add(country17);
            continent3.Countries.Add(country18);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 5);
            continent4.Countries.Add(country19);
            continent4.Countries.Add(country20);
            continent4.Countries.Add(country21);
            continent4.Countries.Add(country22);
            continent4.Countries.Add(country23);
            continent4.Countries.Add(country24);
            continent4.Countries.Add(country25);
            continent4.Countries.Add(country26);
            continent4.Countries.Add(country27);
            continent4.Countries.Add(country28);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 4);
            continent5.Countries.Add(country29);
            continent5.Countries.Add(country30);
            continent5.Countries.Add(country31);
            continent5.Countries.Add(country32);
            continent5.Countries.Add(country33);
            continent5.Countries.Add(country34);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 6);
            continent6.Countries.Add(country35);
            continent6.Countries.Add(country36);
            continent6.Countries.Add(country37);
            continent6.Countries.Add(country38);
            continent6.Countries.Add(country39);
            continent6.Countries.Add(country40);
            continent6.Countries.Add(country41);
            continent6.Countries.Add(country42);
            continent6.Countries.Add(country43);
            continent6.Countries.Add(country44);
            continent6.Countries.Add(country45);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 5);
            continent7.Countries.Add(country46);
            continent7.Countries.Add(country47);
            continent7.Countries.Add(country48);
            continent7.Countries.Add(country49);
            continent7.Countries.Add(country50);
            continent7.Countries.Add(country51);
            continent7.Countries.Add(country52);
            continent7.Countries.Add(country53);
            continent7.Countries.Add(country54);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 3);
            continent8.Countries.Add(country55);
            continent8.Countries.Add(country56);
            continent8.Countries.Add(country57);
            continent8.Countries.Add(country58);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 4);
            continent9.Countries.Add(country59);
            continent9.Countries.Add(country60);
            continent9.Countries.Add(country61);
            continent9.Countries.Add(country62);
            continent9.Countries.Add(country63);
            continent9.Countries.Add(country64);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 2);
            continent10.Countries.Add(country65);
            continent10.Countries.Add(country66);
            continent10.Countries.Add(country67);
            mapTemplate.Continents.Add(continent10);
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "68"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "3"));
            mapTemplate.Connections.Add(new Connection("2", "5"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "2"));
            mapTemplate.Connections.Add(new Connection("3", "5"));
            mapTemplate.Connections.Add(new Connection("3", "6"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "11"));
            mapTemplate.Connections.Add(new Connection("3", "68"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "11"));
            mapTemplate.Connections.Add(new Connection("4", "15"));
            mapTemplate.Connections.Add(new Connection("4", "68"));
            mapTemplate.Connections.Add(new Connection("5", "2"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("5", "8"));
            mapTemplate.Connections.Add(new Connection("5", "3"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("6", "3"));
            mapTemplate.Connections.Add(new Connection("6", "9"));
            mapTemplate.Connections.Add(new Connection("6", "11"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "8"));
            mapTemplate.Connections.Add(new Connection("7", "9"));
            mapTemplate.Connections.Add(new Connection("7", "66"));
            mapTemplate.Connections.Add(new Connection("8", "5"));
            mapTemplate.Connections.Add(new Connection("8", "7"));
            mapTemplate.Connections.Add(new Connection("8", "67"));
            mapTemplate.Connections.Add(new Connection("8", "66"));
            mapTemplate.Connections.Add(new Connection("9", "6"));
            mapTemplate.Connections.Add(new Connection("9", "7"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("9", "10"));
            mapTemplate.Connections.Add(new Connection("9", "66"));
            mapTemplate.Connections.Add(new Connection("10", "9"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "12"));
            mapTemplate.Connections.Add(new Connection("10", "63"));
            mapTemplate.Connections.Add(new Connection("10", "66"));
            mapTemplate.Connections.Add(new Connection("11", "4"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("11", "3"));
            mapTemplate.Connections.Add(new Connection("11", "12"));
            mapTemplate.Connections.Add(new Connection("11", "15"));
            mapTemplate.Connections.Add(new Connection("11", "6"));
            mapTemplate.Connections.Add(new Connection("12", "10"));
            mapTemplate.Connections.Add(new Connection("12", "11"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "15"));
            mapTemplate.Connections.Add(new Connection("12", "16"));
            mapTemplate.Connections.Add(new Connection("12", "17"));
            mapTemplate.Connections.Add(new Connection("12", "58"));
            mapTemplate.Connections.Add(new Connection("12", "57"));
            mapTemplate.Connections.Add(new Connection("12", "63"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "26"));
            mapTemplate.Connections.Add(new Connection("13", "25"));
            mapTemplate.Connections.Add(new Connection("13", "54"));
            mapTemplate.Connections.Add(new Connection("13", "58"));
            mapTemplate.Connections.Add(new Connection("13", "21"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "17"));
            mapTemplate.Connections.Add(new Connection("14", "21"));
            mapTemplate.Connections.Add(new Connection("15", "4"));
            mapTemplate.Connections.Add(new Connection("15", "11"));
            mapTemplate.Connections.Add(new Connection("15", "12"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "68"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "12"));
            mapTemplate.Connections.Add(new Connection("16", "17"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("17", "16"));
            mapTemplate.Connections.Add(new Connection("17", "12"));
            mapTemplate.Connections.Add(new Connection("17", "14"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "19"));
            mapTemplate.Connections.Add(new Connection("17", "21"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "19"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("19", "18"));
            mapTemplate.Connections.Add(new Connection("19", "17"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "23"));
            mapTemplate.Connections.Add(new Connection("20", "22"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("21", "17"));
            mapTemplate.Connections.Add(new Connection("21", "14"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "22"));
            mapTemplate.Connections.Add(new Connection("21", "26"));
            mapTemplate.Connections.Add(new Connection("21", "13"));
            mapTemplate.Connections.Add(new Connection("22", "21"));
            mapTemplate.Connections.Add(new Connection("22", "20"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("22", "24"));
            mapTemplate.Connections.Add(new Connection("22", "28"));
            mapTemplate.Connections.Add(new Connection("22", "27"));
            mapTemplate.Connections.Add(new Connection("22", "26"));
            mapTemplate.Connections.Add(new Connection("23", "20"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "22"));
            mapTemplate.Connections.Add(new Connection("24", "28"));
            mapTemplate.Connections.Add(new Connection("25", "26"));
            mapTemplate.Connections.Add(new Connection("25", "13"));
            mapTemplate.Connections.Add(new Connection("25", "31"));
            mapTemplate.Connections.Add(new Connection("25", "54"));
            mapTemplate.Connections.Add(new Connection("26", "21"));
            mapTemplate.Connections.Add(new Connection("26", "22"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("26", "13"));
            mapTemplate.Connections.Add(new Connection("26", "25"));
            mapTemplate.Connections.Add(new Connection("26", "31"));
            mapTemplate.Connections.Add(new Connection("26", "30"));
            mapTemplate.Connections.Add(new Connection("27", "22"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "30"));
            mapTemplate.Connections.Add(new Connection("28", "24"));
            mapTemplate.Connections.Add(new Connection("28", "22"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("28", "30"));
            mapTemplate.Connections.Add(new Connection("28", "33"));
            mapTemplate.Connections.Add(new Connection("28", "29"));
            mapTemplate.Connections.Add(new Connection("29", "33"));
            mapTemplate.Connections.Add(new Connection("29", "28"));
            mapTemplate.Connections.Add(new Connection("29", "34"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "32"));
            mapTemplate.Connections.Add(new Connection("30", "26"));
            mapTemplate.Connections.Add(new Connection("30", "27"));
            mapTemplate.Connections.Add(new Connection("30", "28"));
            mapTemplate.Connections.Add(new Connection("30", "33"));
            mapTemplate.Connections.Add(new Connection("30", "35"));
            mapTemplate.Connections.Add(new Connection("31", "25"));
            mapTemplate.Connections.Add(new Connection("31", "26"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "54"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "30"));
            mapTemplate.Connections.Add(new Connection("32", "35"));
            mapTemplate.Connections.Add(new Connection("32", "54"));
            mapTemplate.Connections.Add(new Connection("33", "30"));
            mapTemplate.Connections.Add(new Connection("33", "29"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "28"));
            mapTemplate.Connections.Add(new Connection("33", "35"));
            mapTemplate.Connections.Add(new Connection("33", "36"));
            mapTemplate.Connections.Add(new Connection("33", "39"));
            mapTemplate.Connections.Add(new Connection("33", "45"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "29"));
            mapTemplate.Connections.Add(new Connection("34", "45"));
            mapTemplate.Connections.Add(new Connection("34", "44"));
            mapTemplate.Connections.Add(new Connection("34", "42"));
            mapTemplate.Connections.Add(new Connection("35", "32"));
            mapTemplate.Connections.Add(new Connection("35", "30"));
            mapTemplate.Connections.Add(new Connection("35", "33"));
            mapTemplate.Connections.Add(new Connection("35", "37"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("35", "46"));
            mapTemplate.Connections.Add(new Connection("35", "52"));
            mapTemplate.Connections.Add(new Connection("35", "54"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "33"));
            mapTemplate.Connections.Add(new Connection("36", "39"));
            mapTemplate.Connections.Add(new Connection("36", "38"));
            mapTemplate.Connections.Add(new Connection("37", "35"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("37", "46"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "36"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("38", "41"));
            mapTemplate.Connections.Add(new Connection("38", "40"));
            mapTemplate.Connections.Add(new Connection("38", "46"));
            mapTemplate.Connections.Add(new Connection("39", "36"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "33"));
            mapTemplate.Connections.Add(new Connection("39", "45"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("40", "41"));
            mapTemplate.Connections.Add(new Connection("40", "42"));
            mapTemplate.Connections.Add(new Connection("40", "38"));
            mapTemplate.Connections.Add(new Connection("40", "46"));
            mapTemplate.Connections.Add(new Connection("41", "39"));
            mapTemplate.Connections.Add(new Connection("41", "38"));
            mapTemplate.Connections.Add(new Connection("41", "45"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "45"));
            mapTemplate.Connections.Add(new Connection("42", "44"));
            mapTemplate.Connections.Add(new Connection("42", "40"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("42", "34"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "34"));
            mapTemplate.Connections.Add(new Connection("44", "42"));
            mapTemplate.Connections.Add(new Connection("45", "39"));
            mapTemplate.Connections.Add(new Connection("45", "41"));
            mapTemplate.Connections.Add(new Connection("45", "34"));
            mapTemplate.Connections.Add(new Connection("45", "42"));
            mapTemplate.Connections.Add(new Connection("45", "33"));
            mapTemplate.Connections.Add(new Connection("46", "40"));
            mapTemplate.Connections.Add(new Connection("46", "38"));
            mapTemplate.Connections.Add(new Connection("46", "37"));
            mapTemplate.Connections.Add(new Connection("46", "35"));
            mapTemplate.Connections.Add(new Connection("46", "52"));
            mapTemplate.Connections.Add(new Connection("46", "51"));
            mapTemplate.Connections.Add(new Connection("46", "50"));
            mapTemplate.Connections.Add(new Connection("46", "49"));
            mapTemplate.Connections.Add(new Connection("46", "47"));
            mapTemplate.Connections.Add(new Connection("47", "48"));
            mapTemplate.Connections.Add(new Connection("47", "46"));
            mapTemplate.Connections.Add(new Connection("47", "49"));
            mapTemplate.Connections.Add(new Connection("48", "47"));
            mapTemplate.Connections.Add(new Connection("48", "50"));
            mapTemplate.Connections.Add(new Connection("48", "55"));
            mapTemplate.Connections.Add(new Connection("48", "59"));
            mapTemplate.Connections.Add(new Connection("48", "61"));
            mapTemplate.Connections.Add(new Connection("48", "49"));
            mapTemplate.Connections.Add(new Connection("49", "46"));
            mapTemplate.Connections.Add(new Connection("49", "47"));
            mapTemplate.Connections.Add(new Connection("49", "50"));
            mapTemplate.Connections.Add(new Connection("49", "48"));
            mapTemplate.Connections.Add(new Connection("50", "46"));
            mapTemplate.Connections.Add(new Connection("50", "49"));
            mapTemplate.Connections.Add(new Connection("50", "48"));
            mapTemplate.Connections.Add(new Connection("50", "51"));
            mapTemplate.Connections.Add(new Connection("50", "55"));
            mapTemplate.Connections.Add(new Connection("51", "46"));
            mapTemplate.Connections.Add(new Connection("51", "50"));
            mapTemplate.Connections.Add(new Connection("51", "52"));
            mapTemplate.Connections.Add(new Connection("51", "53"));
            mapTemplate.Connections.Add(new Connection("51", "55"));
            mapTemplate.Connections.Add(new Connection("51", "56"));
            mapTemplate.Connections.Add(new Connection("52", "46"));
            mapTemplate.Connections.Add(new Connection("52", "51"));
            mapTemplate.Connections.Add(new Connection("52", "54"));
            mapTemplate.Connections.Add(new Connection("52", "35"));
            mapTemplate.Connections.Add(new Connection("52", "53"));
            mapTemplate.Connections.Add(new Connection("53", "54"));
            mapTemplate.Connections.Add(new Connection("53", "51"));
            mapTemplate.Connections.Add(new Connection("53", "52"));
            mapTemplate.Connections.Add(new Connection("53", "56"));
            mapTemplate.Connections.Add(new Connection("54", "52"));
            mapTemplate.Connections.Add(new Connection("54", "53"));
            mapTemplate.Connections.Add(new Connection("54", "32"));
            mapTemplate.Connections.Add(new Connection("54", "31"));
            mapTemplate.Connections.Add(new Connection("54", "25"));
            mapTemplate.Connections.Add(new Connection("54", "13"));
            mapTemplate.Connections.Add(new Connection("54", "58"));
            mapTemplate.Connections.Add(new Connection("54", "35"));
            mapTemplate.Connections.Add(new Connection("54", "56"));
            mapTemplate.Connections.Add(new Connection("55", "48"));
            mapTemplate.Connections.Add(new Connection("55", "50"));
            mapTemplate.Connections.Add(new Connection("55", "51"));
            mapTemplate.Connections.Add(new Connection("55", "56"));
            mapTemplate.Connections.Add(new Connection("55", "57"));
            mapTemplate.Connections.Add(new Connection("55", "61"));
            mapTemplate.Connections.Add(new Connection("55", "64"));
            mapTemplate.Connections.Add(new Connection("56", "55"));
            mapTemplate.Connections.Add(new Connection("56", "51"));
            mapTemplate.Connections.Add(new Connection("56", "53"));
            mapTemplate.Connections.Add(new Connection("56", "58"));
            mapTemplate.Connections.Add(new Connection("56", "57"));
            mapTemplate.Connections.Add(new Connection("56", "54"));
            mapTemplate.Connections.Add(new Connection("57", "55"));
            mapTemplate.Connections.Add(new Connection("57", "56"));
            mapTemplate.Connections.Add(new Connection("57", "58"));
            mapTemplate.Connections.Add(new Connection("57", "12"));
            mapTemplate.Connections.Add(new Connection("57", "64"));
            mapTemplate.Connections.Add(new Connection("57", "63"));
            mapTemplate.Connections.Add(new Connection("58", "56"));
            mapTemplate.Connections.Add(new Connection("58", "57"));
            mapTemplate.Connections.Add(new Connection("58", "54"));
            mapTemplate.Connections.Add(new Connection("58", "13"));
            mapTemplate.Connections.Add(new Connection("58", "12"));
            mapTemplate.Connections.Add(new Connection("59", "48"));
            mapTemplate.Connections.Add(new Connection("59", "61"));
            mapTemplate.Connections.Add(new Connection("59", "60"));
            mapTemplate.Connections.Add(new Connection("59", "65"));
            mapTemplate.Connections.Add(new Connection("60", "59"));
            mapTemplate.Connections.Add(new Connection("60", "61"));
            mapTemplate.Connections.Add(new Connection("60", "62"));
            mapTemplate.Connections.Add(new Connection("60", "65"));
            mapTemplate.Connections.Add(new Connection("60", "66"));
            mapTemplate.Connections.Add(new Connection("61", "59"));
            mapTemplate.Connections.Add(new Connection("61", "48"));
            mapTemplate.Connections.Add(new Connection("61", "55"));
            mapTemplate.Connections.Add(new Connection("61", "63"));
            mapTemplate.Connections.Add(new Connection("61", "62"));
            mapTemplate.Connections.Add(new Connection("61", "64"));
            mapTemplate.Connections.Add(new Connection("61", "60"));
            mapTemplate.Connections.Add(new Connection("62", "61"));
            mapTemplate.Connections.Add(new Connection("62", "60"));
            mapTemplate.Connections.Add(new Connection("62", "63"));
            mapTemplate.Connections.Add(new Connection("62", "66"));
            mapTemplate.Connections.Add(new Connection("63", "61"));
            mapTemplate.Connections.Add(new Connection("63", "62"));
            mapTemplate.Connections.Add(new Connection("63", "64"));
            mapTemplate.Connections.Add(new Connection("63", "57"));
            mapTemplate.Connections.Add(new Connection("63", "12"));
            mapTemplate.Connections.Add(new Connection("63", "10"));
            mapTemplate.Connections.Add(new Connection("63", "66"));
            mapTemplate.Connections.Add(new Connection("64", "61"));
            mapTemplate.Connections.Add(new Connection("64", "63"));
            mapTemplate.Connections.Add(new Connection("64", "55"));
            mapTemplate.Connections.Add(new Connection("64", "57"));
            mapTemplate.Connections.Add(new Connection("65", "60"));
            mapTemplate.Connections.Add(new Connection("65", "59"));
            mapTemplate.Connections.Add(new Connection("65", "66"));
            mapTemplate.Connections.Add(new Connection("65", "67"));
            mapTemplate.Connections.Add(new Connection("66", "65"));
            mapTemplate.Connections.Add(new Connection("66", "67"));
            mapTemplate.Connections.Add(new Connection("66", "7"));
            mapTemplate.Connections.Add(new Connection("66", "9"));
            mapTemplate.Connections.Add(new Connection("66", "10"));
            mapTemplate.Connections.Add(new Connection("66", "63"));
            mapTemplate.Connections.Add(new Connection("66", "62"));
            mapTemplate.Connections.Add(new Connection("66", "8"));
            mapTemplate.Connections.Add(new Connection("66", "60"));
            mapTemplate.Connections.Add(new Connection("67", "65"));
            mapTemplate.Connections.Add(new Connection("67", "8"));
            mapTemplate.Connections.Add(new Connection("67", "66"));
            mapTemplate.Connections.Add(new Connection("68", "1"));
            mapTemplate.Connections.Add(new Connection("68", "3"));
            mapTemplate.Connections.Add(new Connection("68", "4"));
            mapTemplate.Connections.Add(new Connection("68", "15"));

            return mapTemplate;
        }
    }
}
