
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Rom()
        {

var mapTemplate = new MapTemplate("Rom") { Image = "rom.jpg" };
var country1 = new CountryTemplate("1", "Britannia Inferior") { X = 114, Y = 48 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Britannia Superior") { X = 124, Y = 121 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Lusitania") { X = 36, Y = 435 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Tarraconensis") { X = 117, Y = 399 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Baetica") { X = 64, Y = 498 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Balearic Is.") { X = 235, Y = 419 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Germanica Inferior") { X = 248, Y = 129 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Germanica Superior") { X = 304, Y = 181 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Belgica") { X = 262, Y = 200 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Lugdunensis") { X = 167, Y = 217 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Aquitania") { X = 187, Y = 295 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Narbonensis") { X = 263, Y = 310 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Mauretania") { X = 178, Y = 558 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Numidia") { X = 331, Y = 521 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Cyrenaica") { X = 511, Y = 591 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Corsica et Sardinia") { X = 359, Y = 397 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Sicily") { X = 480, Y = 443 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Italia") { X = 423, Y = 323 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Raetia") { X = 348, Y = 216 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Noricum") { X = 409, Y = 198 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Pannonia Superior") { X = 459, Y = 209 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Pannonia Inferior") { X = 498, Y = 217 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Illyricum") { X = 504, Y = 260 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Dacia") { X = 591, Y = 171 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Moesia Inferior") { X = 651, Y = 226 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Thracia") { X = 679, Y = 253 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Moesia Superior") { X = 577, Y = 269 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Macedonia") { X = 616, Y = 321 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Epirus") { X = 592, Y = 348 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Archaea") { X = 644, Y = 381 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Crete") { X = 726, Y = 420 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Asia") { X = 757, Y = 319 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Bythinia et Pontus") { X = 829, Y = 192 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Galatia") { X = 839, Y = 277 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Cappadocia") { X = 900, Y = 250 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Pamphylia") { X = 819, Y = 318 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Lycia") { X = 795, Y = 339 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Armenia") { X = 976, Y = 166 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Cilicia") { X = 875, Y = 313 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Commagene") { X = 978, Y = 250 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Syria") { X = 969, Y = 315 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Cyprus") { X = 899, Y = 349 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Judaea") { X = 968, Y = 391 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Arabia") { X = 966, Y = 450 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Aegyptus") { X = 844, Y = 525 };
mapTemplate.Countries.Add(country45);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country13);
continent1.Countries.Add(country14);
continent1.Countries.Add(country15);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country6);
continent2.Countries.Add(country4);
continent2.Countries.Add(country3);
continent2.Countries.Add(country5);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country10);
continent3.Countries.Add(country9);
continent3.Countries.Add(country8);
continent3.Countries.Add(country7);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 1);
continent4.Countries.Add(country2);
continent4.Countries.Add(country1);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country19);
continent5.Countries.Add(country18);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country20);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 3);
continent7.Countries.Add(country27);
continent7.Countries.Add(country28);
continent7.Countries.Add(country29);
continent7.Countries.Add(country30);
continent7.Countries.Add(country31);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country32);
continent8.Countries.Add(country37);
continent8.Countries.Add(country36);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 4);
continent9.Countries.Add(country33);
continent9.Countries.Add(country34);
continent9.Countries.Add(country35);
continent9.Countries.Add(country38);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 4);
continent10.Countries.Add(country39);
continent10.Countries.Add(country40);
continent10.Countries.Add(country42);
continent10.Countries.Add(country41);
continent10.Countries.Add(country43);
continent10.Countries.Add(country44);
continent10.Countries.Add(country45);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country24);
continent11.Countries.Add(country25);
continent11.Countries.Add(country26);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "45"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("8", "19"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "35"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("23", "18"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "28"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "40"));
mapTemplate.Connections.Add(new Connection("35", "39"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "27"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "39"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "37"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "26"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "19"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "2"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "26"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("4", "11"));
mapTemplate.Connections.Add(new Connection("4", "12"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "9"));
mapTemplate.Connections.Add(new Connection("19", "8"));
mapTemplate.Connections.Add(new Connection("26", "33"));
mapTemplate.Connections.Add(new Connection("26", "32"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "4"));
mapTemplate.Connections.Add(new Connection("18", "23"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("39", "34"));
mapTemplate.Connections.Add(new Connection("39", "35"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("12", "4"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "22"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("45", "15"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "10"));
mapTemplate.Connections.Add(new Connection("2", "9"));
mapTemplate.Connections.Add(new Connection("13", "5"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("28", "23"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("37", "32"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("10", "2"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "13"));

            return mapTemplate;
		}
    }
}

