
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Sternbilder()
        {

var mapTemplate = new MapTemplate("Sternbilder") { Image = "sternbilder.jpg" };
var country1 = new CountryTemplate("1", "Botein") { X = 502, Y = 125 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "41Aries") { X = 542, Y = 9 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Hamal") { X = 673, Y = 60 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Sheratan") { X = 747, Y = 97 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Mesartim") { X = 748, Y = 145 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "etaTauri") { X = 378, Y = 50 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "5Tauri") { X = 313, Y = 28 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "lambdaTauri") { X = 323, Y = 115 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "nuTauri") { X = 382, Y = 137 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "muTauri") { X = 326, Y = 186 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Pleiaden") { X = 150, Y = 48 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "deltaTauri") { X = 222, Y = 136 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Ain") { X = 184, Y = 147 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "tauTauri") { X = 130, Y = 174 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Elnath") { X = 57, Y = 270 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "TienKuan") { X = 116, Y = 326 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Aldebaran") { X = 223, Y = 217 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "PrimusHyadum") { X = 264, Y = 174 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Pollux") { X = 41, Y = 718 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Castor") { X = 96, Y = 632 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Wasat") { X = 95, Y = 767 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Mekbuda") { X = 159, Y = 796 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Alhena") { X = 258, Y = 825 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Alzir") { X = 186, Y = 853 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "TejatPrior") { X = 322, Y = 773 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Tejat") { X = 264, Y = 726 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Mebsuta") { X = 185, Y = 727 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "iotaCancri") { X = 518, Y = 783 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "AsellusBorealis") { X = 609, Y = 779 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "AsellusAustralis") { X = 634, Y = 831 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Acubens") { X = 706, Y = 859 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Tarf") { X = 764, Y = 777 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Denebola") { X = 907, Y = 781 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Zozma") { X = 981, Y = 702 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Chertan") { X = 1006, Y = 777 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Regulus") { X = 1214, Y = 804 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "etaLeonis") { X = 1212, Y = 745 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Algieba") { X = 1120, Y = 715 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Adhafera") { X = 1128, Y = 669 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Aasalas") { X = 1213, Y = 626 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Algenubi") { X = 1262, Y = 675 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Vindemiatrix") { X = 1199, Y = 31 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Auva") { X = 1227, Y = 83 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Porrima") { X = 1258, Y = 137 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Spica") { X = 1161, Y = 212 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Syrma") { X = 1077, Y = 174 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "muVirginis") { X = 1031, Y = 176 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "109Virginis") { X = 1015, Y = 91 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "tauVirginis") { X = 1096, Y = 88 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Heze") { X = 1167, Y = 107 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Graffias") { X = 465, Y = 203 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Dschubba") { X = 471, Y = 240 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "piScorpii") { X = 473, Y = 278 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "AlNiyat") { X = 396, Y = 244 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Antares") { X = 349, Y = 255 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "tauScorpii") { X = 320, Y = 292 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Wei") { X = 341, Y = 357 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "muScorpii") { X = 330, Y = 395 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "zetaScorpii") { X = 330, Y = 441 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "etaScorpii") { X = 268, Y = 469 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Sargas") { X = 211, Y = 471 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "iotaScorpii") { X = 155, Y = 424 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Girtab") { X = 170, Y = 392 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Shaula") { X = 223, Y = 352 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Nunki") { X = 253, Y = 534 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "tauSagittarii") { X = 215, Y = 560 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Ascella") { X = 250, Y = 623 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "M70") { X = 315, Y = 654 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "KausAustralis") { X = 381, Y = 678 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "KausMedia") { X = 373, Y = 599 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Nash") { X = 457, Y = 591 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "KausBorealis") { X = 376, Y = 518 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "phiSagittarii") { X = 313, Y = 575 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "tauLibrae") { X = 614, Y = 363 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "ZubenElHakrabi") { X = 590, Y = 305 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Brachium") { X = 679, Y = 318 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "ZubenElGenubi") { X = 734, Y = 223 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "ZubenElChamali") { X = 626, Y = 169 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "ZubenElAkrab") { X = 586, Y = 217 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Algiendi") { X = 757, Y = 575 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Alshat") { X = 639, Y = 609 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "iotaCapricornus") { X = 595, Y = 610 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Scheddi") { X = 526, Y = 605 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "epsilonCapricornus") { X = 535, Y = 667 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "24Capricornus") { X = 615, Y = 717 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "zetaCapricornus") { X = 563, Y = 698 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "omegaCapricornus") { X = 669, Y = 734 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "psiCapricornus") { X = 706, Y = 700 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Dabih") { X = 764, Y = 636 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "98Aquarii") { X = 856, Y = 591 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "88Aquarii") { X = 919, Y = 591 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "phiAquarii") { X = 855, Y = 466 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "etaAquarii") { X = 944, Y = 419 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Skat") { X = 944, Y = 547 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Hydor") { X = 949, Y = 479 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Sadachbia") { X = 999, Y = 453 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Sadalmelik") { X = 1041, Y = 407 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Sadalsuud") { X = 1114, Y = 446 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Abulan") { X = 1129, Y = 522 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Albali") { X = 1205, Y = 491 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "Alrischa") { X = 800, Y = 363 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "muPiscium") { X = 879, Y = 342 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "epsilonPiscium") { X = 931, Y = 333 };
mapTemplate.Countries.Add(country103);
var country104 = new CountryTemplate("104", "omegaPiscium") { X = 1057, Y = 303 };
mapTemplate.Countries.Add(country104);
var country105 = new CountryTemplate("105", "iotaPiscium") { X = 1093, Y = 340 };
mapTemplate.Countries.Add(country105);
var country106 = new CountryTemplate("106", "thetaPiscium") { X = 1119, Y = 299 };
mapTemplate.Countries.Add(country106);
var country107 = new CountryTemplate("107", "gammaPiscium") { X = 1140, Y = 358 };
mapTemplate.Countries.Add(country107);
var country108 = new CountryTemplate("108", "FumAlSamakah") { X = 1193, Y = 308 };
mapTemplate.Countries.Add(country108);
var country109 = new CountryTemplate("109", "TorcSept") { X = 816, Y = 291 };
mapTemplate.Countries.Add(country109);
var country110 = new CountryTemplate("110", "KullatNunu") { X = 901, Y = 255 };
mapTemplate.Countries.Add(country110);
var country111 = new CountryTemplate("111", "ChiPiscium") { X = 931, Y = 222 };
mapTemplate.Countries.Add(country111);
var country112 = new CountryTemplate("112", "ypsilonPiscium") { X = 881, Y = 172 };
mapTemplate.Countries.Add(country112);
var country113 = new CountryTemplate("113", "tauPiscium") { X = 941, Y = 127 };
mapTemplate.Countries.Add(country113);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 7);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
continent2.Countries.Add(country18);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 5);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
continent3.Countries.Add(country21);
continent3.Countries.Add(country22);
continent3.Countries.Add(country23);
continent3.Countries.Add(country24);
continent3.Countries.Add(country25);
continent3.Countries.Add(country26);
continent3.Countries.Add(country27);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country28);
continent4.Countries.Add(country29);
continent4.Countries.Add(country30);
continent4.Countries.Add(country31);
continent4.Countries.Add(country32);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 5);
continent5.Countries.Add(country33);
continent5.Countries.Add(country34);
continent5.Countries.Add(country35);
continent5.Countries.Add(country36);
continent5.Countries.Add(country37);
continent5.Countries.Add(country38);
continent5.Countries.Add(country39);
continent5.Countries.Add(country40);
continent5.Countries.Add(country41);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 5);
continent6.Countries.Add(country42);
continent6.Countries.Add(country43);
continent6.Countries.Add(country44);
continent6.Countries.Add(country45);
continent6.Countries.Add(country46);
continent6.Countries.Add(country47);
continent6.Countries.Add(country48);
continent6.Countries.Add(country49);
continent6.Countries.Add(country50);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 8);
continent7.Countries.Add(country51);
continent7.Countries.Add(country52);
continent7.Countries.Add(country53);
continent7.Countries.Add(country54);
continent7.Countries.Add(country55);
continent7.Countries.Add(country56);
continent7.Countries.Add(country57);
continent7.Countries.Add(country58);
continent7.Countries.Add(country59);
continent7.Countries.Add(country60);
continent7.Countries.Add(country61);
continent7.Countries.Add(country62);
continent7.Countries.Add(country63);
continent7.Countries.Add(country64);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 5);
continent8.Countries.Add(country65);
continent8.Countries.Add(country66);
continent8.Countries.Add(country67);
continent8.Countries.Add(country68);
continent8.Countries.Add(country69);
continent8.Countries.Add(country70);
continent8.Countries.Add(country71);
continent8.Countries.Add(country72);
continent8.Countries.Add(country73);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 4);
continent9.Countries.Add(country74);
continent9.Countries.Add(country75);
continent9.Countries.Add(country76);
continent9.Countries.Add(country77);
continent9.Countries.Add(country78);
continent9.Countries.Add(country79);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 6);
continent10.Countries.Add(country80);
continent10.Countries.Add(country81);
continent10.Countries.Add(country82);
continent10.Countries.Add(country83);
continent10.Countries.Add(country84);
continent10.Countries.Add(country85);
continent10.Countries.Add(country86);
continent10.Countries.Add(country87);
continent10.Countries.Add(country88);
continent10.Countries.Add(country89);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 6);
continent11.Countries.Add(country90);
continent11.Countries.Add(country91);
continent11.Countries.Add(country92);
continent11.Countries.Add(country93);
continent11.Countries.Add(country94);
continent11.Countries.Add(country95);
continent11.Countries.Add(country96);
continent11.Countries.Add(country97);
continent11.Countries.Add(country98);
continent11.Countries.Add(country99);
continent11.Countries.Add(country100);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 7);
continent12.Countries.Add(country101);
continent12.Countries.Add(country102);
continent12.Countries.Add(country103);
continent12.Countries.Add(country104);
continent12.Countries.Add(country105);
continent12.Countries.Add(country106);
continent12.Countries.Add(country107);
continent12.Countries.Add(country108);
continent12.Countries.Add(country109);
continent12.Countries.Add(country110);
continent12.Countries.Add(country111);
continent12.Countries.Add(country112);
continent12.Countries.Add(country113);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "8"));
mapTemplate.Connections.Add(new Connection("4", "9"));
mapTemplate.Connections.Add(new Connection("4", "10"));
mapTemplate.Connections.Add(new Connection("4", "11"));
mapTemplate.Connections.Add(new Connection("4", "12"));
mapTemplate.Connections.Add(new Connection("4", "13"));
mapTemplate.Connections.Add(new Connection("4", "14"));
mapTemplate.Connections.Add(new Connection("4", "15"));
mapTemplate.Connections.Add(new Connection("4", "16"));
mapTemplate.Connections.Add(new Connection("4", "17"));
mapTemplate.Connections.Add(new Connection("4", "18"));
mapTemplate.Connections.Add(new Connection("4", "42"));
mapTemplate.Connections.Add(new Connection("4", "43"));
mapTemplate.Connections.Add(new Connection("4", "44"));
mapTemplate.Connections.Add(new Connection("4", "45"));
mapTemplate.Connections.Add(new Connection("4", "46"));
mapTemplate.Connections.Add(new Connection("4", "47"));
mapTemplate.Connections.Add(new Connection("4", "48"));
mapTemplate.Connections.Add(new Connection("4", "49"));
mapTemplate.Connections.Add(new Connection("4", "50"));
mapTemplate.Connections.Add(new Connection("4", "74"));
mapTemplate.Connections.Add(new Connection("4", "75"));
mapTemplate.Connections.Add(new Connection("4", "76"));
mapTemplate.Connections.Add(new Connection("4", "77"));
mapTemplate.Connections.Add(new Connection("4", "78"));
mapTemplate.Connections.Add(new Connection("4", "79"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "18"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "1"));
mapTemplate.Connections.Add(new Connection("11", "2"));
mapTemplate.Connections.Add(new Connection("11", "3"));
mapTemplate.Connections.Add(new Connection("11", "4"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("11", "19"));
mapTemplate.Connections.Add(new Connection("11", "20"));
mapTemplate.Connections.Add(new Connection("11", "21"));
mapTemplate.Connections.Add(new Connection("11", "22"));
mapTemplate.Connections.Add(new Connection("11", "23"));
mapTemplate.Connections.Add(new Connection("11", "24"));
mapTemplate.Connections.Add(new Connection("11", "25"));
mapTemplate.Connections.Add(new Connection("11", "26"));
mapTemplate.Connections.Add(new Connection("11", "27"));
mapTemplate.Connections.Add(new Connection("11", "51"));
mapTemplate.Connections.Add(new Connection("11", "52"));
mapTemplate.Connections.Add(new Connection("11", "53"));
mapTemplate.Connections.Add(new Connection("11", "54"));
mapTemplate.Connections.Add(new Connection("11", "55"));
mapTemplate.Connections.Add(new Connection("11", "56"));
mapTemplate.Connections.Add(new Connection("11", "57"));
mapTemplate.Connections.Add(new Connection("11", "58"));
mapTemplate.Connections.Add(new Connection("11", "59"));
mapTemplate.Connections.Add(new Connection("11", "60"));
mapTemplate.Connections.Add(new Connection("11", "61"));
mapTemplate.Connections.Add(new Connection("11", "62"));
mapTemplate.Connections.Add(new Connection("11", "63"));
mapTemplate.Connections.Add(new Connection("11", "64"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "17"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "13"));
mapTemplate.Connections.Add(new Connection("17", "1"));
mapTemplate.Connections.Add(new Connection("17", "2"));
mapTemplate.Connections.Add(new Connection("17", "3"));
mapTemplate.Connections.Add(new Connection("17", "4"));
mapTemplate.Connections.Add(new Connection("17", "5"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "23"));
mapTemplate.Connections.Add(new Connection("17", "24"));
mapTemplate.Connections.Add(new Connection("17", "25"));
mapTemplate.Connections.Add(new Connection("17", "26"));
mapTemplate.Connections.Add(new Connection("17", "27"));
mapTemplate.Connections.Add(new Connection("17", "51"));
mapTemplate.Connections.Add(new Connection("17", "52"));
mapTemplate.Connections.Add(new Connection("17", "53"));
mapTemplate.Connections.Add(new Connection("17", "54"));
mapTemplate.Connections.Add(new Connection("17", "55"));
mapTemplate.Connections.Add(new Connection("17", "56"));
mapTemplate.Connections.Add(new Connection("17", "57"));
mapTemplate.Connections.Add(new Connection("17", "58"));
mapTemplate.Connections.Add(new Connection("17", "59"));
mapTemplate.Connections.Add(new Connection("17", "60"));
mapTemplate.Connections.Add(new Connection("17", "61"));
mapTemplate.Connections.Add(new Connection("17", "62"));
mapTemplate.Connections.Add(new Connection("17", "63"));
mapTemplate.Connections.Add(new Connection("17", "64"));
mapTemplate.Connections.Add(new Connection("18", "8"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "6"));
mapTemplate.Connections.Add(new Connection("19", "7"));
mapTemplate.Connections.Add(new Connection("19", "8"));
mapTemplate.Connections.Add(new Connection("19", "9"));
mapTemplate.Connections.Add(new Connection("19", "10"));
mapTemplate.Connections.Add(new Connection("19", "11"));
mapTemplate.Connections.Add(new Connection("19", "12"));
mapTemplate.Connections.Add(new Connection("19", "13"));
mapTemplate.Connections.Add(new Connection("19", "14"));
mapTemplate.Connections.Add(new Connection("19", "15"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "28"));
mapTemplate.Connections.Add(new Connection("19", "29"));
mapTemplate.Connections.Add(new Connection("19", "30"));
mapTemplate.Connections.Add(new Connection("19", "31"));
mapTemplate.Connections.Add(new Connection("19", "32"));
mapTemplate.Connections.Add(new Connection("19", "65"));
mapTemplate.Connections.Add(new Connection("19", "66"));
mapTemplate.Connections.Add(new Connection("19", "67"));
mapTemplate.Connections.Add(new Connection("19", "68"));
mapTemplate.Connections.Add(new Connection("19", "69"));
mapTemplate.Connections.Add(new Connection("19", "70"));
mapTemplate.Connections.Add(new Connection("19", "71"));
mapTemplate.Connections.Add(new Connection("19", "72"));
mapTemplate.Connections.Add(new Connection("19", "73"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "27"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "20"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "19"));
mapTemplate.Connections.Add(new Connection("32", "20"));
mapTemplate.Connections.Add(new Connection("32", "21"));
mapTemplate.Connections.Add(new Connection("32", "22"));
mapTemplate.Connections.Add(new Connection("32", "23"));
mapTemplate.Connections.Add(new Connection("32", "24"));
mapTemplate.Connections.Add(new Connection("32", "25"));
mapTemplate.Connections.Add(new Connection("32", "26"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("32", "37"));
mapTemplate.Connections.Add(new Connection("32", "38"));
mapTemplate.Connections.Add(new Connection("32", "39"));
mapTemplate.Connections.Add(new Connection("32", "40"));
mapTemplate.Connections.Add(new Connection("32", "41"));
mapTemplate.Connections.Add(new Connection("32", "80"));
mapTemplate.Connections.Add(new Connection("32", "81"));
mapTemplate.Connections.Add(new Connection("32", "82"));
mapTemplate.Connections.Add(new Connection("32", "83"));
mapTemplate.Connections.Add(new Connection("32", "84"));
mapTemplate.Connections.Add(new Connection("32", "85"));
mapTemplate.Connections.Add(new Connection("32", "86"));
mapTemplate.Connections.Add(new Connection("32", "87"));
mapTemplate.Connections.Add(new Connection("32", "88"));
mapTemplate.Connections.Add(new Connection("32", "89"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "28"));
mapTemplate.Connections.Add(new Connection("36", "29"));
mapTemplate.Connections.Add(new Connection("36", "30"));
mapTemplate.Connections.Add(new Connection("36", "31"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "42"));
mapTemplate.Connections.Add(new Connection("36", "43"));
mapTemplate.Connections.Add(new Connection("36", "44"));
mapTemplate.Connections.Add(new Connection("36", "45"));
mapTemplate.Connections.Add(new Connection("36", "46"));
mapTemplate.Connections.Add(new Connection("36", "47"));
mapTemplate.Connections.Add(new Connection("36", "48"));
mapTemplate.Connections.Add(new Connection("36", "49"));
mapTemplate.Connections.Add(new Connection("36", "50"));
mapTemplate.Connections.Add(new Connection("36", "90"));
mapTemplate.Connections.Add(new Connection("36", "91"));
mapTemplate.Connections.Add(new Connection("36", "92"));
mapTemplate.Connections.Add(new Connection("36", "93"));
mapTemplate.Connections.Add(new Connection("36", "94"));
mapTemplate.Connections.Add(new Connection("36", "95"));
mapTemplate.Connections.Add(new Connection("36", "96"));
mapTemplate.Connections.Add(new Connection("36", "97"));
mapTemplate.Connections.Add(new Connection("36", "98"));
mapTemplate.Connections.Add(new Connection("36", "99"));
mapTemplate.Connections.Add(new Connection("36", "100"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "50"));
mapTemplate.Connections.Add(new Connection("45", "1"));
mapTemplate.Connections.Add(new Connection("45", "2"));
mapTemplate.Connections.Add(new Connection("45", "3"));
mapTemplate.Connections.Add(new Connection("45", "4"));
mapTemplate.Connections.Add(new Connection("45", "5"));
mapTemplate.Connections.Add(new Connection("45", "33"));
mapTemplate.Connections.Add(new Connection("45", "34"));
mapTemplate.Connections.Add(new Connection("45", "35"));
mapTemplate.Connections.Add(new Connection("45", "36"));
mapTemplate.Connections.Add(new Connection("45", "37"));
mapTemplate.Connections.Add(new Connection("45", "38"));
mapTemplate.Connections.Add(new Connection("45", "39"));
mapTemplate.Connections.Add(new Connection("45", "40"));
mapTemplate.Connections.Add(new Connection("45", "41"));
mapTemplate.Connections.Add(new Connection("45", "101"));
mapTemplate.Connections.Add(new Connection("45", "102"));
mapTemplate.Connections.Add(new Connection("45", "103"));
mapTemplate.Connections.Add(new Connection("45", "104"));
mapTemplate.Connections.Add(new Connection("45", "105"));
mapTemplate.Connections.Add(new Connection("45", "106"));
mapTemplate.Connections.Add(new Connection("45", "107"));
mapTemplate.Connections.Add(new Connection("45", "108"));
mapTemplate.Connections.Add(new Connection("45", "109"));
mapTemplate.Connections.Add(new Connection("45", "110"));
mapTemplate.Connections.Add(new Connection("45", "111"));
mapTemplate.Connections.Add(new Connection("45", "112"));
mapTemplate.Connections.Add(new Connection("45", "113"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("50", "45"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "6"));
mapTemplate.Connections.Add(new Connection("55", "7"));
mapTemplate.Connections.Add(new Connection("55", "8"));
mapTemplate.Connections.Add(new Connection("55", "9"));
mapTemplate.Connections.Add(new Connection("55", "10"));
mapTemplate.Connections.Add(new Connection("55", "11"));
mapTemplate.Connections.Add(new Connection("55", "12"));
mapTemplate.Connections.Add(new Connection("55", "13"));
mapTemplate.Connections.Add(new Connection("55", "14"));
mapTemplate.Connections.Add(new Connection("55", "15"));
mapTemplate.Connections.Add(new Connection("55", "16"));
mapTemplate.Connections.Add(new Connection("55", "17"));
mapTemplate.Connections.Add(new Connection("55", "18"));
mapTemplate.Connections.Add(new Connection("55", "74"));
mapTemplate.Connections.Add(new Connection("55", "75"));
mapTemplate.Connections.Add(new Connection("55", "76"));
mapTemplate.Connections.Add(new Connection("55", "77"));
mapTemplate.Connections.Add(new Connection("55", "78"));
mapTemplate.Connections.Add(new Connection("55", "79"));
mapTemplate.Connections.Add(new Connection("55", "65"));
mapTemplate.Connections.Add(new Connection("55", "66"));
mapTemplate.Connections.Add(new Connection("55", "67"));
mapTemplate.Connections.Add(new Connection("55", "68"));
mapTemplate.Connections.Add(new Connection("55", "69"));
mapTemplate.Connections.Add(new Connection("55", "70"));
mapTemplate.Connections.Add(new Connection("55", "71"));
mapTemplate.Connections.Add(new Connection("55", "72"));
mapTemplate.Connections.Add(new Connection("55", "73"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "6"));
mapTemplate.Connections.Add(new Connection("64", "7"));
mapTemplate.Connections.Add(new Connection("64", "8"));
mapTemplate.Connections.Add(new Connection("64", "9"));
mapTemplate.Connections.Add(new Connection("64", "10"));
mapTemplate.Connections.Add(new Connection("64", "11"));
mapTemplate.Connections.Add(new Connection("64", "12"));
mapTemplate.Connections.Add(new Connection("64", "13"));
mapTemplate.Connections.Add(new Connection("64", "14"));
mapTemplate.Connections.Add(new Connection("64", "15"));
mapTemplate.Connections.Add(new Connection("64", "16"));
mapTemplate.Connections.Add(new Connection("64", "17"));
mapTemplate.Connections.Add(new Connection("64", "18"));
mapTemplate.Connections.Add(new Connection("64", "74"));
mapTemplate.Connections.Add(new Connection("64", "75"));
mapTemplate.Connections.Add(new Connection("64", "76"));
mapTemplate.Connections.Add(new Connection("64", "77"));
mapTemplate.Connections.Add(new Connection("64", "78"));
mapTemplate.Connections.Add(new Connection("64", "79"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "66"));
mapTemplate.Connections.Add(new Connection("64", "67"));
mapTemplate.Connections.Add(new Connection("64", "68"));
mapTemplate.Connections.Add(new Connection("64", "69"));
mapTemplate.Connections.Add(new Connection("64", "70"));
mapTemplate.Connections.Add(new Connection("64", "71"));
mapTemplate.Connections.Add(new Connection("64", "72"));
mapTemplate.Connections.Add(new Connection("64", "73"));
mapTemplate.Connections.Add(new Connection("65", "73"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "73"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("69", "71"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("71", "69"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("72", "51"));
mapTemplate.Connections.Add(new Connection("72", "52"));
mapTemplate.Connections.Add(new Connection("72", "53"));
mapTemplate.Connections.Add(new Connection("72", "54"));
mapTemplate.Connections.Add(new Connection("72", "55"));
mapTemplate.Connections.Add(new Connection("72", "56"));
mapTemplate.Connections.Add(new Connection("72", "57"));
mapTemplate.Connections.Add(new Connection("72", "58"));
mapTemplate.Connections.Add(new Connection("72", "59"));
mapTemplate.Connections.Add(new Connection("72", "60"));
mapTemplate.Connections.Add(new Connection("72", "61"));
mapTemplate.Connections.Add(new Connection("72", "62"));
mapTemplate.Connections.Add(new Connection("72", "63"));
mapTemplate.Connections.Add(new Connection("72", "64"));
mapTemplate.Connections.Add(new Connection("72", "19"));
mapTemplate.Connections.Add(new Connection("72", "20"));
mapTemplate.Connections.Add(new Connection("72", "21"));
mapTemplate.Connections.Add(new Connection("72", "22"));
mapTemplate.Connections.Add(new Connection("72", "23"));
mapTemplate.Connections.Add(new Connection("72", "24"));
mapTemplate.Connections.Add(new Connection("72", "25"));
mapTemplate.Connections.Add(new Connection("72", "26"));
mapTemplate.Connections.Add(new Connection("72", "27"));
mapTemplate.Connections.Add(new Connection("72", "80"));
mapTemplate.Connections.Add(new Connection("72", "81"));
mapTemplate.Connections.Add(new Connection("72", "82"));
mapTemplate.Connections.Add(new Connection("72", "83"));
mapTemplate.Connections.Add(new Connection("72", "84"));
mapTemplate.Connections.Add(new Connection("72", "85"));
mapTemplate.Connections.Add(new Connection("72", "86"));
mapTemplate.Connections.Add(new Connection("72", "87"));
mapTemplate.Connections.Add(new Connection("72", "88"));
mapTemplate.Connections.Add(new Connection("72", "89"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "65"));
mapTemplate.Connections.Add(new Connection("73", "67"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("76", "79"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "51"));
mapTemplate.Connections.Add(new Connection("78", "52"));
mapTemplate.Connections.Add(new Connection("78", "53"));
mapTemplate.Connections.Add(new Connection("78", "54"));
mapTemplate.Connections.Add(new Connection("78", "55"));
mapTemplate.Connections.Add(new Connection("78", "56"));
mapTemplate.Connections.Add(new Connection("78", "57"));
mapTemplate.Connections.Add(new Connection("78", "58"));
mapTemplate.Connections.Add(new Connection("78", "59"));
mapTemplate.Connections.Add(new Connection("78", "60"));
mapTemplate.Connections.Add(new Connection("78", "61"));
mapTemplate.Connections.Add(new Connection("78", "62"));
mapTemplate.Connections.Add(new Connection("78", "63"));
mapTemplate.Connections.Add(new Connection("78", "64"));
mapTemplate.Connections.Add(new Connection("78", "1"));
mapTemplate.Connections.Add(new Connection("78", "2"));
mapTemplate.Connections.Add(new Connection("78", "3"));
mapTemplate.Connections.Add(new Connection("78", "4"));
mapTemplate.Connections.Add(new Connection("78", "5"));
mapTemplate.Connections.Add(new Connection("78", "101"));
mapTemplate.Connections.Add(new Connection("78", "102"));
mapTemplate.Connections.Add(new Connection("78", "103"));
mapTemplate.Connections.Add(new Connection("78", "104"));
mapTemplate.Connections.Add(new Connection("78", "105"));
mapTemplate.Connections.Add(new Connection("78", "106"));
mapTemplate.Connections.Add(new Connection("78", "107"));
mapTemplate.Connections.Add(new Connection("78", "108"));
mapTemplate.Connections.Add(new Connection("78", "109"));
mapTemplate.Connections.Add(new Connection("78", "110"));
mapTemplate.Connections.Add(new Connection("78", "111"));
mapTemplate.Connections.Add(new Connection("78", "112"));
mapTemplate.Connections.Add(new Connection("78", "113"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("79", "76"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("80", "89"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "28"));
mapTemplate.Connections.Add(new Connection("83", "29"));
mapTemplate.Connections.Add(new Connection("83", "30"));
mapTemplate.Connections.Add(new Connection("83", "31"));
mapTemplate.Connections.Add(new Connection("83", "32"));
mapTemplate.Connections.Add(new Connection("83", "65"));
mapTemplate.Connections.Add(new Connection("83", "66"));
mapTemplate.Connections.Add(new Connection("83", "67"));
mapTemplate.Connections.Add(new Connection("83", "68"));
mapTemplate.Connections.Add(new Connection("83", "69"));
mapTemplate.Connections.Add(new Connection("83", "70"));
mapTemplate.Connections.Add(new Connection("83", "71"));
mapTemplate.Connections.Add(new Connection("83", "72"));
mapTemplate.Connections.Add(new Connection("83", "73"));
mapTemplate.Connections.Add(new Connection("83", "90"));
mapTemplate.Connections.Add(new Connection("83", "91"));
mapTemplate.Connections.Add(new Connection("83", "92"));
mapTemplate.Connections.Add(new Connection("83", "93"));
mapTemplate.Connections.Add(new Connection("83", "94"));
mapTemplate.Connections.Add(new Connection("83", "95"));
mapTemplate.Connections.Add(new Connection("83", "96"));
mapTemplate.Connections.Add(new Connection("83", "97"));
mapTemplate.Connections.Add(new Connection("83", "98"));
mapTemplate.Connections.Add(new Connection("83", "99"));
mapTemplate.Connections.Add(new Connection("83", "100"));
mapTemplate.Connections.Add(new Connection("84", "86"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("85", "87"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("86", "84"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "85"));
mapTemplate.Connections.Add(new Connection("88", "89"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("89", "80"));
mapTemplate.Connections.Add(new Connection("89", "88"));
mapTemplate.Connections.Add(new Connection("89", "28"));
mapTemplate.Connections.Add(new Connection("89", "29"));
mapTemplate.Connections.Add(new Connection("89", "30"));
mapTemplate.Connections.Add(new Connection("89", "31"));
mapTemplate.Connections.Add(new Connection("89", "32"));
mapTemplate.Connections.Add(new Connection("89", "65"));
mapTemplate.Connections.Add(new Connection("89", "66"));
mapTemplate.Connections.Add(new Connection("89", "67"));
mapTemplate.Connections.Add(new Connection("89", "68"));
mapTemplate.Connections.Add(new Connection("89", "69"));
mapTemplate.Connections.Add(new Connection("89", "70"));
mapTemplate.Connections.Add(new Connection("89", "71"));
mapTemplate.Connections.Add(new Connection("89", "72"));
mapTemplate.Connections.Add(new Connection("89", "73"));
mapTemplate.Connections.Add(new Connection("89", "90"));
mapTemplate.Connections.Add(new Connection("89", "91"));
mapTemplate.Connections.Add(new Connection("89", "92"));
mapTemplate.Connections.Add(new Connection("89", "93"));
mapTemplate.Connections.Add(new Connection("89", "94"));
mapTemplate.Connections.Add(new Connection("89", "95"));
mapTemplate.Connections.Add(new Connection("89", "96"));
mapTemplate.Connections.Add(new Connection("89", "97"));
mapTemplate.Connections.Add(new Connection("89", "98"));
mapTemplate.Connections.Add(new Connection("89", "99"));
mapTemplate.Connections.Add(new Connection("89", "100"));
mapTemplate.Connections.Add(new Connection("90", "92"));
mapTemplate.Connections.Add(new Connection("90", "91"));
mapTemplate.Connections.Add(new Connection("91", "90"));
mapTemplate.Connections.Add(new Connection("91", "94"));
mapTemplate.Connections.Add(new Connection("92", "95"));
mapTemplate.Connections.Add(new Connection("92", "90"));
mapTemplate.Connections.Add(new Connection("93", "96"));
mapTemplate.Connections.Add(new Connection("93", "95"));
mapTemplate.Connections.Add(new Connection("94", "91"));
mapTemplate.Connections.Add(new Connection("94", "95"));
mapTemplate.Connections.Add(new Connection("94", "33"));
mapTemplate.Connections.Add(new Connection("94", "34"));
mapTemplate.Connections.Add(new Connection("94", "35"));
mapTemplate.Connections.Add(new Connection("94", "36"));
mapTemplate.Connections.Add(new Connection("94", "37"));
mapTemplate.Connections.Add(new Connection("94", "38"));
mapTemplate.Connections.Add(new Connection("94", "39"));
mapTemplate.Connections.Add(new Connection("94", "40"));
mapTemplate.Connections.Add(new Connection("94", "41"));
mapTemplate.Connections.Add(new Connection("94", "80"));
mapTemplate.Connections.Add(new Connection("94", "81"));
mapTemplate.Connections.Add(new Connection("94", "82"));
mapTemplate.Connections.Add(new Connection("94", "83"));
mapTemplate.Connections.Add(new Connection("94", "84"));
mapTemplate.Connections.Add(new Connection("94", "85"));
mapTemplate.Connections.Add(new Connection("94", "86"));
mapTemplate.Connections.Add(new Connection("94", "87"));
mapTemplate.Connections.Add(new Connection("94", "88"));
mapTemplate.Connections.Add(new Connection("94", "89"));
mapTemplate.Connections.Add(new Connection("94", "101"));
mapTemplate.Connections.Add(new Connection("94", "102"));
mapTemplate.Connections.Add(new Connection("94", "103"));
mapTemplate.Connections.Add(new Connection("94", "104"));
mapTemplate.Connections.Add(new Connection("94", "105"));
mapTemplate.Connections.Add(new Connection("94", "106"));
mapTemplate.Connections.Add(new Connection("94", "107"));
mapTemplate.Connections.Add(new Connection("94", "108"));
mapTemplate.Connections.Add(new Connection("94", "109"));
mapTemplate.Connections.Add(new Connection("94", "110"));
mapTemplate.Connections.Add(new Connection("94", "111"));
mapTemplate.Connections.Add(new Connection("94", "112"));
mapTemplate.Connections.Add(new Connection("94", "113"));
mapTemplate.Connections.Add(new Connection("95", "93"));
mapTemplate.Connections.Add(new Connection("95", "92"));
mapTemplate.Connections.Add(new Connection("95", "94"));
mapTemplate.Connections.Add(new Connection("96", "97"));
mapTemplate.Connections.Add(new Connection("96", "93"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "96"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("98", "33"));
mapTemplate.Connections.Add(new Connection("98", "34"));
mapTemplate.Connections.Add(new Connection("98", "35"));
mapTemplate.Connections.Add(new Connection("98", "36"));
mapTemplate.Connections.Add(new Connection("98", "37"));
mapTemplate.Connections.Add(new Connection("98", "38"));
mapTemplate.Connections.Add(new Connection("98", "39"));
mapTemplate.Connections.Add(new Connection("98", "40"));
mapTemplate.Connections.Add(new Connection("98", "41"));
mapTemplate.Connections.Add(new Connection("98", "80"));
mapTemplate.Connections.Add(new Connection("98", "81"));
mapTemplate.Connections.Add(new Connection("98", "82"));
mapTemplate.Connections.Add(new Connection("98", "83"));
mapTemplate.Connections.Add(new Connection("98", "84"));
mapTemplate.Connections.Add(new Connection("98", "85"));
mapTemplate.Connections.Add(new Connection("98", "86"));
mapTemplate.Connections.Add(new Connection("98", "87"));
mapTemplate.Connections.Add(new Connection("98", "88"));
mapTemplate.Connections.Add(new Connection("98", "89"));
mapTemplate.Connections.Add(new Connection("98", "101"));
mapTemplate.Connections.Add(new Connection("98", "102"));
mapTemplate.Connections.Add(new Connection("98", "103"));
mapTemplate.Connections.Add(new Connection("98", "104"));
mapTemplate.Connections.Add(new Connection("98", "105"));
mapTemplate.Connections.Add(new Connection("98", "106"));
mapTemplate.Connections.Add(new Connection("98", "107"));
mapTemplate.Connections.Add(new Connection("98", "108"));
mapTemplate.Connections.Add(new Connection("98", "109"));
mapTemplate.Connections.Add(new Connection("98", "110"));
mapTemplate.Connections.Add(new Connection("98", "111"));
mapTemplate.Connections.Add(new Connection("98", "112"));
mapTemplate.Connections.Add(new Connection("98", "113"));
mapTemplate.Connections.Add(new Connection("99", "100"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("100", "99"));
mapTemplate.Connections.Add(new Connection("101", "102"));
mapTemplate.Connections.Add(new Connection("101", "109"));
mapTemplate.Connections.Add(new Connection("102", "103"));
mapTemplate.Connections.Add(new Connection("102", "101"));
mapTemplate.Connections.Add(new Connection("103", "104"));
mapTemplate.Connections.Add(new Connection("103", "102"));
mapTemplate.Connections.Add(new Connection("104", "105"));
mapTemplate.Connections.Add(new Connection("104", "103"));
mapTemplate.Connections.Add(new Connection("105", "106"));
mapTemplate.Connections.Add(new Connection("105", "104"));
mapTemplate.Connections.Add(new Connection("106", "107"));
mapTemplate.Connections.Add(new Connection("106", "105"));
mapTemplate.Connections.Add(new Connection("107", "108"));
mapTemplate.Connections.Add(new Connection("107", "106"));
mapTemplate.Connections.Add(new Connection("108", "107"));
mapTemplate.Connections.Add(new Connection("108", "42"));
mapTemplate.Connections.Add(new Connection("108", "43"));
mapTemplate.Connections.Add(new Connection("108", "44"));
mapTemplate.Connections.Add(new Connection("108", "45"));
mapTemplate.Connections.Add(new Connection("108", "46"));
mapTemplate.Connections.Add(new Connection("108", "47"));
mapTemplate.Connections.Add(new Connection("108", "48"));
mapTemplate.Connections.Add(new Connection("108", "49"));
mapTemplate.Connections.Add(new Connection("108", "50"));
mapTemplate.Connections.Add(new Connection("108", "74"));
mapTemplate.Connections.Add(new Connection("108", "75"));
mapTemplate.Connections.Add(new Connection("108", "76"));
mapTemplate.Connections.Add(new Connection("108", "77"));
mapTemplate.Connections.Add(new Connection("108", "78"));
mapTemplate.Connections.Add(new Connection("108", "79"));
mapTemplate.Connections.Add(new Connection("108", "90"));
mapTemplate.Connections.Add(new Connection("108", "91"));
mapTemplate.Connections.Add(new Connection("108", "92"));
mapTemplate.Connections.Add(new Connection("108", "93"));
mapTemplate.Connections.Add(new Connection("108", "94"));
mapTemplate.Connections.Add(new Connection("108", "95"));
mapTemplate.Connections.Add(new Connection("108", "96"));
mapTemplate.Connections.Add(new Connection("108", "97"));
mapTemplate.Connections.Add(new Connection("108", "98"));
mapTemplate.Connections.Add(new Connection("108", "99"));
mapTemplate.Connections.Add(new Connection("108", "100"));
mapTemplate.Connections.Add(new Connection("109", "101"));
mapTemplate.Connections.Add(new Connection("109", "110"));
mapTemplate.Connections.Add(new Connection("110", "109"));
mapTemplate.Connections.Add(new Connection("110", "111"));
mapTemplate.Connections.Add(new Connection("110", "42"));
mapTemplate.Connections.Add(new Connection("110", "43"));
mapTemplate.Connections.Add(new Connection("110", "44"));
mapTemplate.Connections.Add(new Connection("110", "45"));
mapTemplate.Connections.Add(new Connection("110", "46"));
mapTemplate.Connections.Add(new Connection("110", "47"));
mapTemplate.Connections.Add(new Connection("110", "48"));
mapTemplate.Connections.Add(new Connection("110", "49"));
mapTemplate.Connections.Add(new Connection("110", "50"));
mapTemplate.Connections.Add(new Connection("110", "74"));
mapTemplate.Connections.Add(new Connection("110", "75"));
mapTemplate.Connections.Add(new Connection("110", "76"));
mapTemplate.Connections.Add(new Connection("110", "77"));
mapTemplate.Connections.Add(new Connection("110", "78"));
mapTemplate.Connections.Add(new Connection("110", "79"));
mapTemplate.Connections.Add(new Connection("110", "90"));
mapTemplate.Connections.Add(new Connection("110", "91"));
mapTemplate.Connections.Add(new Connection("110", "92"));
mapTemplate.Connections.Add(new Connection("110", "93"));
mapTemplate.Connections.Add(new Connection("110", "94"));
mapTemplate.Connections.Add(new Connection("110", "95"));
mapTemplate.Connections.Add(new Connection("110", "96"));
mapTemplate.Connections.Add(new Connection("110", "97"));
mapTemplate.Connections.Add(new Connection("110", "98"));
mapTemplate.Connections.Add(new Connection("110", "99"));
mapTemplate.Connections.Add(new Connection("110", "100"));
mapTemplate.Connections.Add(new Connection("111", "110"));
mapTemplate.Connections.Add(new Connection("111", "112"));
mapTemplate.Connections.Add(new Connection("112", "111"));
mapTemplate.Connections.Add(new Connection("112", "113"));
mapTemplate.Connections.Add(new Connection("113", "112"));

            return mapTemplate;
		}
    }
}

