
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Italien()
        {

var mapTemplate = new MapTemplate("Italien") { Image = "italien.png" };
var country1 = new CountryTemplate("1", "Valle dAosta") { X = 52, Y = 179 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Verbano-Cusio-Ossola") { X = 142, Y = 126 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Vercelli") { X = 116, Y = 157 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Biella") { X = 114, Y = 186 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Novara") { X = 154, Y = 181 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Torino") { X = 71, Y = 235 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Cuneo") { X = 85, Y = 346 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Asti") { X = 123, Y = 285 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Alessandria") { X = 180, Y = 283 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Varese") { X = 185, Y = 164 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Milan") { X = 208, Y = 214 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Como") { X = 206, Y = 127 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Pavia") { X = 189, Y = 241 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Monza") { X = 212, Y = 184 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Lecco") { X = 238, Y = 139 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Bergamo") { X = 274, Y = 157 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Sondrio") { X = 271, Y = 101 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Brescia") { X = 321, Y = 182 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Lodi") { X = 261, Y = 247 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Cremona") { X = 279, Y = 221 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Bolzano") { X = 411, Y = 56 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Trento") { X = 377, Y = 125 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Belluno") { X = 485, Y = 94 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Vicenza") { X = 425, Y = 185 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Verona") { X = 379, Y = 202 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Padova") { X = 460, Y = 220 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Treviso") { X = 489, Y = 169 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Venezia") { X = 517, Y = 206 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Rovigo") { X = 445, Y = 263 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Pordenone") { X = 536, Y = 126 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Udine") { X = 582, Y = 118 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Gorizia") { X = 622, Y = 146 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Trieste") { X = 650, Y = 173 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Imperia") { X = 87, Y = 403 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Savona") { X = 142, Y = 361 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Genoa") { X = 205, Y = 343 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "La Spezia") { X = 255, Y = 364 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Massa-Carrara") { X = 293, Y = 358 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Piacenza") { X = 254, Y = 286 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Parma") { X = 297, Y = 313 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Reggio Emilia") { X = 337, Y = 326 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Modena") { X = 377, Y = 316 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Bologna") { X = 415, Y = 345 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Ferrara") { X = 468, Y = 300 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Ravenna") { X = 478, Y = 336 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Forli-Cesena") { X = 464, Y = 399 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Rimini") { X = 534, Y = 395 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Lucca") { X = 327, Y = 398 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Pistoia") { X = 365, Y = 402 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Prato") { X = 401, Y = 395 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Firenze") { X = 418, Y = 427 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Arezzo") { X = 455, Y = 456 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Siena") { X = 410, Y = 483 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Pisa") { X = 358, Y = 470 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Livorno") { X = 317, Y = 502 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Grosseto") { X = 392, Y = 529 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Perugia") { X = 520, Y = 504 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Terni") { X = 516, Y = 564 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Pesaro-Urbino") { X = 529, Y = 431 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Ancona") { X = 559, Y = 457 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Macerata") { X = 574, Y = 495 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Fermo") { X = 622, Y = 498 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Ascoli Piceno") { X = 610, Y = 531 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Viterbo") { X = 464, Y = 591 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Roma") { X = 517, Y = 640 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Rieti") { X = 558, Y = 601 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Frosinone") { X = 615, Y = 681 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Latina") { X = 563, Y = 710 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Teramo") { X = 624, Y = 565 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Pescara") { X = 650, Y = 590 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "LAquila") { X = 619, Y = 635 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Chieti") { X = 691, Y = 634 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Isernia") { X = 679, Y = 674 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Campobasso") { X = 732, Y = 663 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Caserta") { X = 662, Y = 739 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Benevento") { X = 720, Y = 724 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Avellino") { X = 751, Y = 757 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Salerno") { X = 769, Y = 834 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Napoli") { X = 682, Y = 778 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Foggia") { X = 791, Y = 701 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Barletta-Andria-Trani") { X = 860, Y = 725 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Bari") { X = 894, Y = 762 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Taranto") { X = 934, Y = 807 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Brindisi") { X = 994, Y = 795 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Lecce") { X = 1032, Y = 855 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Potenza") { X = 817, Y = 805 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Matera") { X = 876, Y = 820 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Cosenza") { X = 854, Y = 924 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Crotone") { X = 921, Y = 966 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Catanzaro") { X = 879, Y = 999 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Vibo Valentia") { X = 843, Y = 1028 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Reggio Calabria") { X = 837, Y = 1077 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Messina") { X = 757, Y = 1105 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Catania") { X = 744, Y = 1155 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Enna") { X = 695, Y = 1149 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Palermo") { X = 595, Y = 1112 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Trapani") { X = 535, Y = 1134 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Agrigento") { X = 599, Y = 1175 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Caltanissetta") { X = 668, Y = 1202 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Ragusa") { X = 711, Y = 1246 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "Siracusa") { X = 750, Y = 1212 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "Olbia-Tempio") { X = 222, Y = 783 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "Sassari") { X = 167, Y = 808 };
mapTemplate.Countries.Add(country103);
var country104 = new CountryTemplate("104", "Oristano") { X = 175, Y = 886 };
mapTemplate.Countries.Add(country104);
var country105 = new CountryTemplate("105", "Nuoro") { X = 224, Y = 855 };
mapTemplate.Countries.Add(country105);
var country106 = new CountryTemplate("106", "Ogliastra") { X = 244, Y = 894 };
mapTemplate.Countries.Add(country106);
var country107 = new CountryTemplate("107", "Cagliari") { X = 227, Y = 952 };
mapTemplate.Countries.Add(country107);
var country108 = new CountryTemplate("108", "Medio Campidano") { X = 174, Y = 932 };
mapTemplate.Countries.Add(country108);
var country109 = new CountryTemplate("109", "Carbonia-Iglesias") { X = 158, Y = 978 };
mapTemplate.Countries.Add(country109);
var country110 = new CountryTemplate("110", "Mantova") { X = 345, Y = 241 };
mapTemplate.Countries.Add(country110);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country1);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 4);
continent2.Countries.Add(country2);
continent2.Countries.Add(country3);
continent2.Countries.Add(country4);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 6);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
continent3.Countries.Add(country19);
continent3.Countries.Add(country20);
continent3.Countries.Add(country110);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country34);
continent4.Countries.Add(country35);
continent4.Countries.Add(country36);
continent4.Countries.Add(country37);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country21);
continent5.Countries.Add(country22);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
continent6.Countries.Add(country25);
continent6.Countries.Add(country26);
continent6.Countries.Add(country27);
continent6.Countries.Add(country28);
continent6.Countries.Add(country29);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country30);
continent7.Countries.Add(country31);
continent7.Countries.Add(country32);
continent7.Countries.Add(country33);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 6);
continent8.Countries.Add(country39);
continent8.Countries.Add(country40);
continent8.Countries.Add(country41);
continent8.Countries.Add(country42);
continent8.Countries.Add(country43);
continent8.Countries.Add(country44);
continent8.Countries.Add(country45);
continent8.Countries.Add(country46);
continent8.Countries.Add(country47);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 6);
continent9.Countries.Add(country38);
continent9.Countries.Add(country48);
continent9.Countries.Add(country49);
continent9.Countries.Add(country50);
continent9.Countries.Add(country51);
continent9.Countries.Add(country52);
continent9.Countries.Add(country53);
continent9.Countries.Add(country54);
continent9.Countries.Add(country55);
continent9.Countries.Add(country56);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 1);
continent10.Countries.Add(country57);
continent10.Countries.Add(country58);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country59);
continent11.Countries.Add(country60);
continent11.Countries.Add(country61);
continent11.Countries.Add(country62);
continent11.Countries.Add(country63);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 3);
continent12.Countries.Add(country64);
continent12.Countries.Add(country65);
continent12.Countries.Add(country66);
continent12.Countries.Add(country67);
continent12.Countries.Add(country68);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 2);
continent13.Countries.Add(country69);
continent13.Countries.Add(country70);
continent13.Countries.Add(country71);
continent13.Countries.Add(country72);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 1);
continent14.Countries.Add(country73);
continent14.Countries.Add(country74);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 3);
continent15.Countries.Add(country75);
continent15.Countries.Add(country76);
continent15.Countries.Add(country77);
continent15.Countries.Add(country78);
continent15.Countries.Add(country79);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 4);
continent16.Countries.Add(country80);
continent16.Countries.Add(country81);
continent16.Countries.Add(country82);
continent16.Countries.Add(country83);
continent16.Countries.Add(country84);
continent16.Countries.Add(country85);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 1);
continent17.Countries.Add(country86);
continent17.Countries.Add(country87);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 2);
continent18.Countries.Add(country88);
continent18.Countries.Add(country89);
continent18.Countries.Add(country90);
continent18.Countries.Add(country91);
continent18.Countries.Add(country92);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 3);
continent19.Countries.Add(country93);
continent19.Countries.Add(country94);
continent19.Countries.Add(country95);
continent19.Countries.Add(country96);
continent19.Countries.Add(country97);
continent19.Countries.Add(country98);
continent19.Countries.Add(country99);
continent19.Countries.Add(country100);
continent19.Countries.Add(country101);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 3);
continent20.Countries.Add(country102);
continent20.Countries.Add(country103);
continent20.Countries.Add(country104);
continent20.Countries.Add(country105);
continent20.Countries.Add(country106);
continent20.Countries.Add(country107);
continent20.Countries.Add(country108);
continent20.Countries.Add(country109);
mapTemplate.Continents.Add(continent20);
mapTemplate.Connections.Add(new Connection("1", "6"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "10"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "9"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "13"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "10"));
mapTemplate.Connections.Add(new Connection("5", "11"));
mapTemplate.Connections.Add(new Connection("5", "13"));
mapTemplate.Connections.Add(new Connection("6", "1"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "35"));
mapTemplate.Connections.Add(new Connection("7", "34"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "35"));
mapTemplate.Connections.Add(new Connection("9", "3"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("9", "36"));
mapTemplate.Connections.Add(new Connection("9", "35"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "39"));
mapTemplate.Connections.Add(new Connection("10", "2"));
mapTemplate.Connections.Add(new Connection("10", "5"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "14"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("11", "20"));
mapTemplate.Connections.Add(new Connection("11", "19"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("13", "5"));
mapTemplate.Connections.Add(new Connection("13", "3"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("13", "19"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "39"));
mapTemplate.Connections.Add(new Connection("14", "10"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "110"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("18", "25"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "13"));
mapTemplate.Connections.Add(new Connection("19", "11"));
mapTemplate.Connections.Add(new Connection("19", "39"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "11"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "39"));
mapTemplate.Connections.Add(new Connection("20", "40"));
mapTemplate.Connections.Add(new Connection("20", "110"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "25"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "30"));
mapTemplate.Connections.Add(new Connection("23", "31"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "110"));
mapTemplate.Connections.Add(new Connection("25", "18"));
mapTemplate.Connections.Add(new Connection("25", "22"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "85"));
mapTemplate.Connections.Add(new Connection("29", "110"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("29", "44"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "23"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("31", "23"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "7"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("35", "9"));
mapTemplate.Connections.Add(new Connection("35", "8"));
mapTemplate.Connections.Add(new Connection("35", "7"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "9"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "40"));
mapTemplate.Connections.Add(new Connection("36", "102"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "48"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("39", "19"));
mapTemplate.Connections.Add(new Connection("39", "13"));
mapTemplate.Connections.Add(new Connection("39", "20"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "9"));
mapTemplate.Connections.Add(new Connection("40", "36"));
mapTemplate.Connections.Add(new Connection("40", "37"));
mapTemplate.Connections.Add(new Connection("40", "20"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("41", "110"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "48"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "110"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "48"));
mapTemplate.Connections.Add(new Connection("42", "49"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "49"));
mapTemplate.Connections.Add(new Connection("43", "50"));
mapTemplate.Connections.Add(new Connection("43", "51"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("44", "110"));
mapTemplate.Connections.Add(new Connection("44", "29"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "51"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "51"));
mapTemplate.Connections.Add(new Connection("46", "52"));
mapTemplate.Connections.Add(new Connection("46", "59"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "59"));
mapTemplate.Connections.Add(new Connection("48", "41"));
mapTemplate.Connections.Add(new Connection("48", "42"));
mapTemplate.Connections.Add(new Connection("48", "38"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "51"));
mapTemplate.Connections.Add(new Connection("48", "54"));
mapTemplate.Connections.Add(new Connection("49", "42"));
mapTemplate.Connections.Add(new Connection("49", "43"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("50", "43"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("51", "43"));
mapTemplate.Connections.Add(new Connection("51", "45"));
mapTemplate.Connections.Add(new Connection("51", "46"));
mapTemplate.Connections.Add(new Connection("51", "48"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("52", "46"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "59"));
mapTemplate.Connections.Add(new Connection("52", "57"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "57"));
mapTemplate.Connections.Add(new Connection("53", "58"));
mapTemplate.Connections.Add(new Connection("53", "64"));
mapTemplate.Connections.Add(new Connection("53", "56"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("54", "48"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "56"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("56", "53"));
mapTemplate.Connections.Add(new Connection("56", "64"));
mapTemplate.Connections.Add(new Connection("56", "54"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("57", "52"));
mapTemplate.Connections.Add(new Connection("57", "53"));
mapTemplate.Connections.Add(new Connection("57", "59"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("57", "61"));
mapTemplate.Connections.Add(new Connection("57", "63"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "66"));
mapTemplate.Connections.Add(new Connection("58", "53"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "66"));
mapTemplate.Connections.Add(new Connection("58", "64"));
mapTemplate.Connections.Add(new Connection("59", "46"));
mapTemplate.Connections.Add(new Connection("59", "47"));
mapTemplate.Connections.Add(new Connection("59", "52"));
mapTemplate.Connections.Add(new Connection("59", "57"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "57"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "57"));
mapTemplate.Connections.Add(new Connection("63", "66"));
mapTemplate.Connections.Add(new Connection("63", "69"));
mapTemplate.Connections.Add(new Connection("64", "53"));
mapTemplate.Connections.Add(new Connection("64", "56"));
mapTemplate.Connections.Add(new Connection("64", "58"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "66"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "102"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "67"));
mapTemplate.Connections.Add(new Connection("65", "68"));
mapTemplate.Connections.Add(new Connection("65", "71"));
mapTemplate.Connections.Add(new Connection("66", "63"));
mapTemplate.Connections.Add(new Connection("66", "57"));
mapTemplate.Connections.Add(new Connection("66", "58"));
mapTemplate.Connections.Add(new Connection("66", "64"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "71"));
mapTemplate.Connections.Add(new Connection("66", "69"));
mapTemplate.Connections.Add(new Connection("67", "65"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "75"));
mapTemplate.Connections.Add(new Connection("67", "73"));
mapTemplate.Connections.Add(new Connection("67", "71"));
mapTemplate.Connections.Add(new Connection("68", "65"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "75"));
mapTemplate.Connections.Add(new Connection("69", "63"));
mapTemplate.Connections.Add(new Connection("69", "66"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "71"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("71", "65"));
mapTemplate.Connections.Add(new Connection("71", "67"));
mapTemplate.Connections.Add(new Connection("71", "66"));
mapTemplate.Connections.Add(new Connection("71", "69"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "73"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "74"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("73", "67"));
mapTemplate.Connections.Add(new Connection("73", "71"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("74", "72"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "80"));
mapTemplate.Connections.Add(new Connection("74", "76"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("75", "68"));
mapTemplate.Connections.Add(new Connection("75", "67"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("75", "79"));
mapTemplate.Connections.Add(new Connection("76", "74"));
mapTemplate.Connections.Add(new Connection("76", "80"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "79"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("77", "79"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("77", "80"));
mapTemplate.Connections.Add(new Connection("77", "86"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "86"));
mapTemplate.Connections.Add(new Connection("79", "76"));
mapTemplate.Connections.Add(new Connection("79", "75"));
mapTemplate.Connections.Add(new Connection("79", "77"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("80", "74"));
mapTemplate.Connections.Add(new Connection("80", "76"));
mapTemplate.Connections.Add(new Connection("80", "77"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("80", "86"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("81", "86"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("82", "86"));
mapTemplate.Connections.Add(new Connection("82", "87"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "84"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "87"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "85"));
mapTemplate.Connections.Add(new Connection("84", "82"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "83"));
mapTemplate.Connections.Add(new Connection("85", "28"));
mapTemplate.Connections.Add(new Connection("86", "77"));
mapTemplate.Connections.Add(new Connection("86", "78"));
mapTemplate.Connections.Add(new Connection("86", "80"));
mapTemplate.Connections.Add(new Connection("86", "81"));
mapTemplate.Connections.Add(new Connection("86", "82"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("87", "82"));
mapTemplate.Connections.Add(new Connection("87", "83"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "86"));
mapTemplate.Connections.Add(new Connection("88", "89"));
mapTemplate.Connections.Add(new Connection("88", "90"));
mapTemplate.Connections.Add(new Connection("89", "88"));
mapTemplate.Connections.Add(new Connection("89", "90"));
mapTemplate.Connections.Add(new Connection("90", "88"));
mapTemplate.Connections.Add(new Connection("90", "89"));
mapTemplate.Connections.Add(new Connection("90", "91"));
mapTemplate.Connections.Add(new Connection("90", "92"));
mapTemplate.Connections.Add(new Connection("91", "90"));
mapTemplate.Connections.Add(new Connection("91", "92"));
mapTemplate.Connections.Add(new Connection("92", "90"));
mapTemplate.Connections.Add(new Connection("92", "91"));
mapTemplate.Connections.Add(new Connection("92", "93"));
mapTemplate.Connections.Add(new Connection("93", "92"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "95"));
mapTemplate.Connections.Add(new Connection("93", "96"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("94", "95"));
mapTemplate.Connections.Add(new Connection("94", "101"));
mapTemplate.Connections.Add(new Connection("94", "100"));
mapTemplate.Connections.Add(new Connection("94", "99"));
mapTemplate.Connections.Add(new Connection("95", "93"));
mapTemplate.Connections.Add(new Connection("95", "94"));
mapTemplate.Connections.Add(new Connection("95", "99"));
mapTemplate.Connections.Add(new Connection("95", "96"));
mapTemplate.Connections.Add(new Connection("96", "93"));
mapTemplate.Connections.Add(new Connection("96", "99"));
mapTemplate.Connections.Add(new Connection("96", "95"));
mapTemplate.Connections.Add(new Connection("96", "98"));
mapTemplate.Connections.Add(new Connection("96", "97"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "96"));
mapTemplate.Connections.Add(new Connection("97", "107"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("98", "96"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("99", "94"));
mapTemplate.Connections.Add(new Connection("99", "100"));
mapTemplate.Connections.Add(new Connection("99", "95"));
mapTemplate.Connections.Add(new Connection("99", "96"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("100", "94"));
mapTemplate.Connections.Add(new Connection("100", "101"));
mapTemplate.Connections.Add(new Connection("100", "99"));
mapTemplate.Connections.Add(new Connection("101", "94"));
mapTemplate.Connections.Add(new Connection("101", "100"));
mapTemplate.Connections.Add(new Connection("102", "36"));
mapTemplate.Connections.Add(new Connection("102", "65"));
mapTemplate.Connections.Add(new Connection("102", "105"));
mapTemplate.Connections.Add(new Connection("102", "103"));
mapTemplate.Connections.Add(new Connection("103", "104"));
mapTemplate.Connections.Add(new Connection("103", "105"));
mapTemplate.Connections.Add(new Connection("103", "102"));
mapTemplate.Connections.Add(new Connection("104", "108"));
mapTemplate.Connections.Add(new Connection("104", "105"));
mapTemplate.Connections.Add(new Connection("104", "103"));
mapTemplate.Connections.Add(new Connection("105", "104"));
mapTemplate.Connections.Add(new Connection("105", "107"));
mapTemplate.Connections.Add(new Connection("105", "106"));
mapTemplate.Connections.Add(new Connection("105", "108"));
mapTemplate.Connections.Add(new Connection("105", "103"));
mapTemplate.Connections.Add(new Connection("105", "102"));
mapTemplate.Connections.Add(new Connection("106", "107"));
mapTemplate.Connections.Add(new Connection("106", "105"));
mapTemplate.Connections.Add(new Connection("107", "97"));
mapTemplate.Connections.Add(new Connection("107", "109"));
mapTemplate.Connections.Add(new Connection("107", "108"));
mapTemplate.Connections.Add(new Connection("107", "105"));
mapTemplate.Connections.Add(new Connection("107", "106"));
mapTemplate.Connections.Add(new Connection("108", "109"));
mapTemplate.Connections.Add(new Connection("108", "107"));
mapTemplate.Connections.Add(new Connection("108", "104"));
mapTemplate.Connections.Add(new Connection("108", "105"));
mapTemplate.Connections.Add(new Connection("109", "107"));
mapTemplate.Connections.Add(new Connection("109", "108"));
mapTemplate.Connections.Add(new Connection("110", "20"));
mapTemplate.Connections.Add(new Connection("110", "18"));
mapTemplate.Connections.Add(new Connection("110", "25"));
mapTemplate.Connections.Add(new Connection("110", "29"));
mapTemplate.Connections.Add(new Connection("110", "44"));
mapTemplate.Connections.Add(new Connection("110", "42"));
mapTemplate.Connections.Add(new Connection("110", "41"));

            return mapTemplate;
		}
    }
}

