
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Muehldorf()
        {

var mapTemplate = new MapTemplate("Muehldorf") { Image = "Muehldorf.jpg" };
var country1 = new CountryTemplate("1", "Maitenbeth") { X = 77, Y = 476 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Rechtmehring") { X = 174, Y = 542 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Haag") { X = 132, Y = 442 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Kirchdorf") { X = 185, Y = 411 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Reichertsheim") { X = 255, Y = 441 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Gars") { X = 343, Y = 446 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Unterreit") { X = 398, Y = 501 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Jettenbach") { X = 402, Y = 433 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Taufkirchen") { X = 501, Y = 512 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Kraiburg") { X = 471, Y = 428 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Waldkraiburg") { X = 438, Y = 404 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Oberneukirchen") { X = 569, Y = 427 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Polling") { X = 619, Y = 401 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Muehldorf") { X = 585, Y = 282 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Mettenheim") { X = 501, Y = 291 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Erharting") { X = 639, Y = 244 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Niederbergkirchen") { X = 583, Y = 223 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Niedertaufkirchen") { X = 613, Y = 157 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Neumarkt") { X = 575, Y = 46 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Egglkofen") { X = 506, Y = 43 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Schoenberg") { X = 471, Y = 129 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Lohkirchen") { X = 509, Y = 185 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Oberbergkirchen") { X = 410, Y = 179 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Zangberg") { X = 464, Y = 260 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Buchbach") { X = 306, Y = 204 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Schwindegg") { X = 267, Y = 276 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Obertaufkirchen") { X = 298, Y = 306 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Ampfing") { X = 385, Y = 251 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Heldenstein") { X = 401, Y = 308 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Rattenkirchen") { X = 345, Y = 320 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Aschau") { X = 393, Y = 373 };
mapTemplate.Countries.Add(country31);
var continent1 = new Continent("1", 1);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country28);
continent2.Countries.Add(country29);
continent2.Countries.Add(country30);
continent2.Countries.Add(country31);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 1);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country5);
continent4.Countries.Add(country6);
continent4.Countries.Add(country7);
continent4.Countries.Add(country8);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country13);
continent5.Countries.Add(country14);
continent5.Countries.Add(country15);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 1);
continent6.Countries.Add(country18);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country21);
continent7.Countries.Add(country22);
continent7.Countries.Add(country23);
continent7.Countries.Add(country24);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country25);
continent8.Countries.Add(country26);
continent8.Countries.Add(country27);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country9);
continent9.Countries.Add(country10);
continent9.Countries.Add(country11);
continent9.Countries.Add(country12);
mapTemplate.Continents.Add(continent9);
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "27"));
mapTemplate.Connections.Add(new Connection("5", "30"));
mapTemplate.Connections.Add(new Connection("5", "31"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "31"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "31"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "13"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "15"));
mapTemplate.Connections.Add(new Connection("11", "28"));
mapTemplate.Connections.Add(new Connection("11", "29"));
mapTemplate.Connections.Add(new Connection("11", "31"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "10"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "11"));
mapTemplate.Connections.Add(new Connection("15", "28"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "24"));
mapTemplate.Connections.Add(new Connection("15", "22"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "15"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "28"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("24", "28"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "15"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "28"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "30"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "5"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "25"));
mapTemplate.Connections.Add(new Connection("28", "11"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "23"));
mapTemplate.Connections.Add(new Connection("28", "24"));
mapTemplate.Connections.Add(new Connection("28", "15"));
mapTemplate.Connections.Add(new Connection("29", "11"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("30", "5"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "26"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "6"));
mapTemplate.Connections.Add(new Connection("31", "5"));
mapTemplate.Connections.Add(new Connection("31", "8"));
mapTemplate.Connections.Add(new Connection("31", "11"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "30"));

            return mapTemplate;
		}
    }
}

