using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Abstractum()
        {
            var mapTemplate = new MapTemplate("Abstractum") { Image = "abstractum.jpg" };
            var country1 = new CountryTemplate("1", "gelb1") { X = 243, Y = 37 };
            mapTemplate.Countries.Add(country1);
            var country2 = new CountryTemplate("2", "gelb2") { X = 329, Y = 37 };
            mapTemplate.Countries.Add(country2);
            var country3 = new CountryTemplate("3", "gelb3") { X = 250, Y = 102 };
            mapTemplate.Countries.Add(country3);
            var country4 = new CountryTemplate("4", "gelb4") { X = 325, Y = 101 };
            mapTemplate.Countries.Add(country4);
            var country5 = new CountryTemplate("5", "lila1") { X = 434, Y = 96 };
            mapTemplate.Countries.Add(country5);
            var country6 = new CountryTemplate("6", "lila2") { X = 482, Y = 145 };
            mapTemplate.Countries.Add(country6);
            var country7 = new CountryTemplate("7", "lila3") { X = 418, Y = 159 };
            mapTemplate.Countries.Add(country7);
            var country8 = new CountryTemplate("8", "rot1") { X = 475, Y = 252 };
            mapTemplate.Countries.Add(country8);
            var country9 = new CountryTemplate("9", "rot2") { X = 540, Y = 251 };
            mapTemplate.Countries.Add(country9);
            var country10 = new CountryTemplate("10", "rot3") { X = 473, Y = 333 };
            mapTemplate.Countries.Add(country10);
            var country11 = new CountryTemplate("11", "rot4") { X = 542, Y = 336 };
            mapTemplate.Countries.Add(country11);
            var country12 = new CountryTemplate("12", "braun1") { X = 418, Y = 424 };
            mapTemplate.Countries.Add(country12);
            var country13 = new CountryTemplate("13", "braun2") { X = 481, Y = 439 };
            mapTemplate.Countries.Add(country13);
            var country14 = new CountryTemplate("14", "braun3") { X = 432, Y = 486 };
            mapTemplate.Countries.Add(country14);
            var country15 = new CountryTemplate("15", "blau1") { X = 248, Y = 479 };
            mapTemplate.Countries.Add(country15);
            var country16 = new CountryTemplate("16", "blau2") { X = 324, Y = 479 };
            mapTemplate.Countries.Add(country16);
            var country17 = new CountryTemplate("17", "blau3") { X = 243, Y = 544 };
            mapTemplate.Countries.Add(country17);
            var country18 = new CountryTemplate("18", "blau4") { X = 331, Y = 543 };
            mapTemplate.Countries.Add(country18);
            var country19 = new CountryTemplate("19", "beige1") { X = 155, Y = 422 };
            mapTemplate.Countries.Add(country19);
            var country20 = new CountryTemplate("20", "beige2") { X = 140, Y = 485 };
            mapTemplate.Countries.Add(country20);
            var country21 = new CountryTemplate("21", "beige3") { X = 91, Y = 438 };
            mapTemplate.Countries.Add(country21);
            var country22 = new CountryTemplate("22", "rosa1") { X = 31, Y = 251 };
            mapTemplate.Countries.Add(country22);
            var country23 = new CountryTemplate("23", "rosa2") { X = 92, Y = 254 };
            mapTemplate.Countries.Add(country23);
            var country24 = new CountryTemplate("24", "rosa3") { X = 94, Y = 330 };
            mapTemplate.Countries.Add(country24);
            var country25 = new CountryTemplate("25", "rosa4") { X = 33, Y = 332 };
            mapTemplate.Countries.Add(country25);
            var country26 = new CountryTemplate("26", "gruen1") { X = 140, Y = 97 };
            mapTemplate.Countries.Add(country26);
            var country27 = new CountryTemplate("27", "gruen2") { X = 154, Y = 159 };
            mapTemplate.Countries.Add(country27);
            var country28 = new CountryTemplate("28", "gruen3") { X = 91, Y = 146 };
            mapTemplate.Countries.Add(country28);
            var country29 = new CountryTemplate("29", "neutral1") { X = 286, Y = 154 };
            mapTemplate.Countries.Add(country29);
            var country30 = new CountryTemplate("30", "neutral2") { X = 351, Y = 163 };
            mapTemplate.Countries.Add(country30);
            var country31 = new CountryTemplate("31", "neutral3") { X = 415, Y = 225 };
            mapTemplate.Countries.Add(country31);
            var country32 = new CountryTemplate("32", "neutral4") { X = 424, Y = 292 };
            mapTemplate.Countries.Add(country32);
            var country33 = new CountryTemplate("33", "neutral5") { X = 413, Y = 356 };
            mapTemplate.Countries.Add(country33);
            var country34 = new CountryTemplate("34", "neutral6") { X = 352, Y = 418 };
            mapTemplate.Countries.Add(country34);
            var country35 = new CountryTemplate("35", "neutral7") { X = 285, Y = 428 };
            mapTemplate.Countries.Add(country35);
            var country36 = new CountryTemplate("36", "neutral8") { X = 223, Y = 420 };
            mapTemplate.Countries.Add(country36);
            var country37 = new CountryTemplate("37", "neutral9") { X = 158, Y = 357 };
            mapTemplate.Countries.Add(country37);
            var country38 = new CountryTemplate("38", "neutral10") { X = 149, Y = 292 };
            mapTemplate.Countries.Add(country38);
            var country39 = new CountryTemplate("39", "neutral11") { X = 158, Y = 223 };
            mapTemplate.Countries.Add(country39);
            var country40 = new CountryTemplate("40", "neutral12") { X = 223, Y = 164 };
            mapTemplate.Countries.Add(country40);
            var country41 = new CountryTemplate("41", "core1") { X = 247, Y = 253 };
            mapTemplate.Countries.Add(country41);
            var country42 = new CountryTemplate("42", "core2") { X = 324, Y = 252 };
            mapTemplate.Countries.Add(country42);
            var country43 = new CountryTemplate("43", "core3") { X = 327, Y = 329 };
            mapTemplate.Countries.Add(country43);
            var country44 = new CountryTemplate("44", "core4") { X = 248, Y = 330 };
            mapTemplate.Countries.Add(country44);
            var continent1 = new Continent("1", 2);
            continent1.Countries.Add(country1);
            continent1.Countries.Add(country2);
            continent1.Countries.Add(country3);
            continent1.Countries.Add(country4);
            mapTemplate.Continents.Add(continent1);
            var continent2 = new Continent("2", 1);
            continent2.Countries.Add(country5);
            continent2.Countries.Add(country6);
            continent2.Countries.Add(country7);
            mapTemplate.Continents.Add(continent2);
            var continent3 = new Continent("3", 2);
            continent3.Countries.Add(country8);
            continent3.Countries.Add(country9);
            continent3.Countries.Add(country10);
            continent3.Countries.Add(country11);
            mapTemplate.Continents.Add(continent3);
            var continent4 = new Continent("4", 1);
            continent4.Countries.Add(country12);
            continent4.Countries.Add(country13);
            continent4.Countries.Add(country14);
            mapTemplate.Continents.Add(continent4);
            var continent5 = new Continent("5", 2);
            continent5.Countries.Add(country15);
            continent5.Countries.Add(country16);
            continent5.Countries.Add(country17);
            continent5.Countries.Add(country18);
            mapTemplate.Continents.Add(continent5);
            var continent6 = new Continent("6", 1);
            continent6.Countries.Add(country19);
            continent6.Countries.Add(country20);
            continent6.Countries.Add(country21);
            mapTemplate.Continents.Add(continent6);
            var continent7 = new Continent("7", 2);
            continent7.Countries.Add(country22);
            continent7.Countries.Add(country23);
            continent7.Countries.Add(country24);
            continent7.Countries.Add(country25);
            mapTemplate.Continents.Add(continent7);
            var continent8 = new Continent("8", 1);
            continent8.Countries.Add(country26);
            continent8.Countries.Add(country27);
            continent8.Countries.Add(country28);
            mapTemplate.Continents.Add(continent8);
            var continent9 = new Continent("9", 8);
            continent9.Countries.Add(country29);
            continent9.Countries.Add(country30);
            continent9.Countries.Add(country31);
            continent9.Countries.Add(country32);
            continent9.Countries.Add(country33);
            continent9.Countries.Add(country34);
            continent9.Countries.Add(country35);
            continent9.Countries.Add(country36);
            continent9.Countries.Add(country37);
            continent9.Countries.Add(country38);
            continent9.Countries.Add(country39);
            continent9.Countries.Add(country40);
            mapTemplate.Continents.Add(continent9);
            var continent10 = new Continent("10", 4);
            continent10.Countries.Add(country41);
            continent10.Countries.Add(country42);
            continent10.Countries.Add(country43);
            continent10.Countries.Add(country44);
            mapTemplate.Continents.Add(continent10);
            mapTemplate.Connections.Add(new Connection("1", "2"));
            mapTemplate.Connections.Add(new Connection("1", "3"));
            mapTemplate.Connections.Add(new Connection("2", "1"));
            mapTemplate.Connections.Add(new Connection("2", "4"));
            mapTemplate.Connections.Add(new Connection("3", "1"));
            mapTemplate.Connections.Add(new Connection("3", "4"));
            mapTemplate.Connections.Add(new Connection("3", "40"));
            mapTemplate.Connections.Add(new Connection("3", "29"));
            mapTemplate.Connections.Add(new Connection("4", "2"));
            mapTemplate.Connections.Add(new Connection("4", "3"));
            mapTemplate.Connections.Add(new Connection("4", "29"));
            mapTemplate.Connections.Add(new Connection("4", "30"));
            mapTemplate.Connections.Add(new Connection("5", "6"));
            mapTemplate.Connections.Add(new Connection("5", "7"));
            mapTemplate.Connections.Add(new Connection("6", "5"));
            mapTemplate.Connections.Add(new Connection("6", "7"));
            mapTemplate.Connections.Add(new Connection("7", "6"));
            mapTemplate.Connections.Add(new Connection("7", "5"));
            mapTemplate.Connections.Add(new Connection("7", "30"));
            mapTemplate.Connections.Add(new Connection("7", "31"));
            mapTemplate.Connections.Add(new Connection("8", "9"));
            mapTemplate.Connections.Add(new Connection("8", "10"));
            mapTemplate.Connections.Add(new Connection("8", "31"));
            mapTemplate.Connections.Add(new Connection("8", "32"));
            mapTemplate.Connections.Add(new Connection("9", "8"));
            mapTemplate.Connections.Add(new Connection("9", "11"));
            mapTemplate.Connections.Add(new Connection("10", "11"));
            mapTemplate.Connections.Add(new Connection("10", "8"));
            mapTemplate.Connections.Add(new Connection("10", "32"));
            mapTemplate.Connections.Add(new Connection("10", "33"));
            mapTemplate.Connections.Add(new Connection("11", "9"));
            mapTemplate.Connections.Add(new Connection("11", "10"));
            mapTemplate.Connections.Add(new Connection("12", "13"));
            mapTemplate.Connections.Add(new Connection("12", "14"));
            mapTemplate.Connections.Add(new Connection("12", "34"));
            mapTemplate.Connections.Add(new Connection("12", "33"));
            mapTemplate.Connections.Add(new Connection("13", "14"));
            mapTemplate.Connections.Add(new Connection("13", "12"));
            mapTemplate.Connections.Add(new Connection("14", "13"));
            mapTemplate.Connections.Add(new Connection("14", "12"));
            mapTemplate.Connections.Add(new Connection("15", "16"));
            mapTemplate.Connections.Add(new Connection("15", "17"));
            mapTemplate.Connections.Add(new Connection("15", "36"));
            mapTemplate.Connections.Add(new Connection("15", "35"));
            mapTemplate.Connections.Add(new Connection("16", "18"));
            mapTemplate.Connections.Add(new Connection("16", "15"));
            mapTemplate.Connections.Add(new Connection("16", "35"));
            mapTemplate.Connections.Add(new Connection("16", "34"));
            mapTemplate.Connections.Add(new Connection("17", "18"));
            mapTemplate.Connections.Add(new Connection("17", "15"));
            mapTemplate.Connections.Add(new Connection("18", "17"));
            mapTemplate.Connections.Add(new Connection("18", "16"));
            mapTemplate.Connections.Add(new Connection("19", "21"));
            mapTemplate.Connections.Add(new Connection("19", "20"));
            mapTemplate.Connections.Add(new Connection("19", "37"));
            mapTemplate.Connections.Add(new Connection("19", "36"));
            mapTemplate.Connections.Add(new Connection("20", "21"));
            mapTemplate.Connections.Add(new Connection("20", "19"));
            mapTemplate.Connections.Add(new Connection("21", "20"));
            mapTemplate.Connections.Add(new Connection("21", "19"));
            mapTemplate.Connections.Add(new Connection("22", "25"));
            mapTemplate.Connections.Add(new Connection("22", "23"));
            mapTemplate.Connections.Add(new Connection("23", "24"));
            mapTemplate.Connections.Add(new Connection("23", "22"));
            mapTemplate.Connections.Add(new Connection("23", "38"));
            mapTemplate.Connections.Add(new Connection("23", "39"));
            mapTemplate.Connections.Add(new Connection("24", "25"));
            mapTemplate.Connections.Add(new Connection("24", "23"));
            mapTemplate.Connections.Add(new Connection("24", "38"));
            mapTemplate.Connections.Add(new Connection("24", "37"));
            mapTemplate.Connections.Add(new Connection("25", "22"));
            mapTemplate.Connections.Add(new Connection("25", "24"));
            mapTemplate.Connections.Add(new Connection("26", "28"));
            mapTemplate.Connections.Add(new Connection("26", "27"));
            mapTemplate.Connections.Add(new Connection("27", "28"));
            mapTemplate.Connections.Add(new Connection("27", "26"));
            mapTemplate.Connections.Add(new Connection("27", "40"));
            mapTemplate.Connections.Add(new Connection("27", "39"));
            mapTemplate.Connections.Add(new Connection("28", "26"));
            mapTemplate.Connections.Add(new Connection("28", "27"));
            mapTemplate.Connections.Add(new Connection("29", "3"));
            mapTemplate.Connections.Add(new Connection("29", "4"));
            mapTemplate.Connections.Add(new Connection("29", "40"));
            mapTemplate.Connections.Add(new Connection("29", "30"));
            mapTemplate.Connections.Add(new Connection("30", "7"));
            mapTemplate.Connections.Add(new Connection("30", "4"));
            mapTemplate.Connections.Add(new Connection("30", "31"));
            mapTemplate.Connections.Add(new Connection("30", "29"));
            mapTemplate.Connections.Add(new Connection("30", "42"));
            mapTemplate.Connections.Add(new Connection("31", "7"));
            mapTemplate.Connections.Add(new Connection("31", "8"));
            mapTemplate.Connections.Add(new Connection("31", "30"));
            mapTemplate.Connections.Add(new Connection("31", "32"));
            mapTemplate.Connections.Add(new Connection("32", "8"));
            mapTemplate.Connections.Add(new Connection("32", "10"));
            mapTemplate.Connections.Add(new Connection("32", "31"));
            mapTemplate.Connections.Add(new Connection("32", "33"));
            mapTemplate.Connections.Add(new Connection("33", "12"));
            mapTemplate.Connections.Add(new Connection("33", "10"));
            mapTemplate.Connections.Add(new Connection("33", "32"));
            mapTemplate.Connections.Add(new Connection("33", "34"));
            mapTemplate.Connections.Add(new Connection("33", "43"));
            mapTemplate.Connections.Add(new Connection("34", "12"));
            mapTemplate.Connections.Add(new Connection("34", "16"));
            mapTemplate.Connections.Add(new Connection("34", "33"));
            mapTemplate.Connections.Add(new Connection("34", "35"));
            mapTemplate.Connections.Add(new Connection("35", "15"));
            mapTemplate.Connections.Add(new Connection("35", "16"));
            mapTemplate.Connections.Add(new Connection("35", "34"));
            mapTemplate.Connections.Add(new Connection("35", "36"));
            mapTemplate.Connections.Add(new Connection("36", "19"));
            mapTemplate.Connections.Add(new Connection("36", "15"));
            mapTemplate.Connections.Add(new Connection("36", "35"));
            mapTemplate.Connections.Add(new Connection("36", "37"));
            mapTemplate.Connections.Add(new Connection("36", "44"));
            mapTemplate.Connections.Add(new Connection("37", "19"));
            mapTemplate.Connections.Add(new Connection("37", "24"));
            mapTemplate.Connections.Add(new Connection("37", "36"));
            mapTemplate.Connections.Add(new Connection("37", "38"));
            mapTemplate.Connections.Add(new Connection("38", "23"));
            mapTemplate.Connections.Add(new Connection("38", "24"));
            mapTemplate.Connections.Add(new Connection("38", "37"));
            mapTemplate.Connections.Add(new Connection("38", "39"));
            mapTemplate.Connections.Add(new Connection("39", "27"));
            mapTemplate.Connections.Add(new Connection("39", "23"));
            mapTemplate.Connections.Add(new Connection("39", "38"));
            mapTemplate.Connections.Add(new Connection("39", "40"));
            mapTemplate.Connections.Add(new Connection("39", "41"));
            mapTemplate.Connections.Add(new Connection("40", "27"));
            mapTemplate.Connections.Add(new Connection("40", "3"));
            mapTemplate.Connections.Add(new Connection("40", "39"));
            mapTemplate.Connections.Add(new Connection("40", "29"));
            mapTemplate.Connections.Add(new Connection("41", "40"));
            mapTemplate.Connections.Add(new Connection("41", "42"));
            mapTemplate.Connections.Add(new Connection("41", "44"));
            mapTemplate.Connections.Add(new Connection("42", "31"));
            mapTemplate.Connections.Add(new Connection("42", "41"));
            mapTemplate.Connections.Add(new Connection("42", "43"));
            mapTemplate.Connections.Add(new Connection("43", "34"));
            mapTemplate.Connections.Add(new Connection("43", "42"));
            mapTemplate.Connections.Add(new Connection("43", "44"));
            mapTemplate.Connections.Add(new Connection("44", "37"));
            mapTemplate.Connections.Add(new Connection("44", "43"));
            mapTemplate.Connections.Add(new Connection("44", "41"));

            return mapTemplate;
        }
    }
}
