
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Mittelalter()
        {

var mapTemplate = new MapTemplate("Mittelalter") { Image = "mittelalter.jpg" };
var country1 = new CountryTemplate("1", "Munster") { X = 112, Y = 443 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Leinster") { X = 151, Y = 403 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Connaught") { X = 93, Y = 398 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Ulster") { X = 135, Y = 367 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Wales") { X = 269, Y = 437 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Shetland Inseln") { X = 376, Y = 102 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Orkney Inseln") { X = 300, Y = 175 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Caledonien") { X = 212, Y = 242 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Lothian") { X = 250, Y = 335 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Northumbria") { X = 295, Y = 357 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Mercia") { X = 342, Y = 404 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Anglia") { X = 371, Y = 452 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Wessex") { X = 300, Y = 456 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Cornwall") { X = 223, Y = 501 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Normandie") { X = 364, Y = 558 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Bretagne") { X = 258, Y = 577 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Anjou") { X = 402, Y = 578 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Poitou") { X = 324, Y = 624 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Guyenne") { X = 374, Y = 672 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Gascogne") { X = 388, Y = 721 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Asturien") { X = 245, Y = 737 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Galizien") { X = 158, Y = 750 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Leon") { X = 201, Y = 782 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Porto") { X = 138, Y = 791 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Lissabon") { X = 130, Y = 821 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Algarve") { X = 134, Y = 869 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Granada") { X = 286, Y = 892 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Andalusien") { X = 179, Y = 879 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Castilien") { X = 289, Y = 815 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Navarra") { X = 286, Y = 758 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Aragon") { X = 348, Y = 764 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Valencia") { X = 337, Y = 867 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Balearen") { X = 423, Y = 857 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Catalonien") { X = 424, Y = 770 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Languedoc") { X = 450, Y = 717 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Auvergne") { X = 470, Y = 652 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Orleans") { X = 486, Y = 628 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Paris") { X = 446, Y = 555 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Champagne") { X = 501, Y = 530 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Sizilien") { X = 774, Y = 904 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Apulien") { X = 820, Y = 831 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Kampanien") { X = 764, Y = 763 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Rom") { X = 724, Y = 752 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Korsika") { X = 612, Y = 758 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Toskana") { X = 672, Y = 721 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Genua") { X = 588, Y = 695 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Mailand") { X = 667, Y = 634 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Venedig") { X = 703, Y = 659 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Tirol") { X = 703, Y = 617 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Schweiz") { X = 632, Y = 599 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Provence") { X = 528, Y = 703 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Avignon") { X = 546, Y = 669 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Savoyen") { X = 588, Y = 650 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Lyon") { X = 529, Y = 634 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Lothringen") { X = 568, Y = 578 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Elsass") { X = 549, Y = 498 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Flandern") { X = 450, Y = 496 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Holland") { X = 548, Y = 430 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Friesland") { X = 620, Y = 389 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Mecklemburg") { X = 699, Y = 403 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Hannover") { X = 685, Y = 442 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Franken") { X = 587, Y = 472 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Hessen") { X = 644, Y = 483 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Schwaben") { X = 640, Y = 538 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Bayern") { X = 710, Y = 532 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Juetland") { X = 612, Y = 274 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Sealand") { X = 695, Y = 319 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Skane") { X = 747, Y = 280 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Hordaland") { X = 565, Y = 62 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Rogaland") { X = 554, Y = 133 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Agder") { X = 598, Y = 165 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Oppland") { X = 636, Y = 127 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Hedmark") { X = 670, Y = 75 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Herjadalen") { X = 778, Y = 51 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Dalekarlien") { X = 751, Y = 108 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Soedermanland") { X = 814, Y = 170 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Smaland") { X = 741, Y = 182 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Gothland u Oeland") { X = 849, Y = 238 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Finnland") { X = 1031, Y = 74 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Tavastien") { X = 1130, Y = 58 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "West-Karelien") { X = 1190, Y = 60 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Ost-Karelien") { X = 1324, Y = 76 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "St Petersburg") { X = 1221, Y = 114 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Pskow") { X = 1183, Y = 221 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Toropez") { X = 1301, Y = 274 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Wologda") { X = 1379, Y = 77 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Susdal") { X = 1448, Y = 129 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Rostov") { X = 1375, Y = 141 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Moskau") { X = 1425, Y = 234 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Kaluga") { X = 1441, Y = 292 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Severien") { X = 1374, Y = 393 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Kasan") { X = 1456, Y = 381 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Tambow") { X = 1439, Y = 465 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Woronesch") { X = 1379, Y = 516 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Astrachan") { X = 1454, Y = 577 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Asow") { X = 1389, Y = 621 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "Saporogische Kosaken") { X = 1394, Y = 578 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "Taurien") { X = 1296, Y = 616 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "Krim") { X = 1295, Y = 671 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "Jedisan") { X = 1268, Y = 579 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "Moldau") { X = 1165, Y = 587 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "Kiew") { X = 1200, Y = 521 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "Wladimir") { X = 1102, Y = 520 };
mapTemplate.Countries.Add(country103);
var country104 = new CountryTemplate("104", "Bielgorod") { X = 1332, Y = 509 };
mapTemplate.Countries.Add(country104);
var country105 = new CountryTemplate("105", "Kursk") { X = 1318, Y = 461 };
mapTemplate.Countries.Add(country105);
var country106 = new CountryTemplate("106", "Turow-Pinsk") { X = 1214, Y = 457 };
mapTemplate.Countries.Add(country106);
var country107 = new CountryTemplate("107", "Moghilev") { X = 1241, Y = 384 };
mapTemplate.Countries.Add(country107);
var country108 = new CountryTemplate("108", "Briansk") { X = 1303, Y = 393 };
mapTemplate.Countries.Add(country108);
var country109 = new CountryTemplate("109", "Witebsk") { X = 1326, Y = 356 };
mapTemplate.Countries.Add(country109);
var country110 = new CountryTemplate("110", "Polotsk") { X = 1193, Y = 339 };
mapTemplate.Countries.Add(country110);
var country111 = new CountryTemplate("111", "Minsk") { X = 1138, Y = 405 };
mapTemplate.Countries.Add(country111);
var country112 = new CountryTemplate("112", "Troki") { X = 1064, Y = 414 };
mapTemplate.Countries.Add(country112);
var country113 = new CountryTemplate("113", "Wilna") { X = 1058, Y = 381 };
mapTemplate.Countries.Add(country113);
var country114 = new CountryTemplate("114", "Samogitien") { X = 1062, Y = 332 };
mapTemplate.Countries.Add(country114);
var country115 = new CountryTemplate("115", "Estland") { X = 1069, Y = 175 };
mapTemplate.Countries.Add(country115);
var country116 = new CountryTemplate("116", "Dagoe u Oesel") { X = 993, Y = 196 };
mapTemplate.Countries.Add(country116);
var country117 = new CountryTemplate("117", "Livland") { X = 1113, Y = 270 };
mapTemplate.Countries.Add(country117);
var country118 = new CountryTemplate("118", "Kurland") { X = 993, Y = 281 };
mapTemplate.Countries.Add(country118);
var country119 = new CountryTemplate("119", "Koenigsberg") { X = 950, Y = 367 };
mapTemplate.Countries.Add(country119);
var country120 = new CountryTemplate("120", "Podlesien") { X = 1074, Y = 479 };
mapTemplate.Countries.Add(country120);
var country121 = new CountryTemplate("121", "Podolien") { X = 1004, Y = 536 };
mapTemplate.Countries.Add(country121);
var country122 = new CountryTemplate("122", "Wolynien") { X = 1010, Y = 469 };
mapTemplate.Countries.Add(country122);
var country123 = new CountryTemplate("123", "Masowien") { X = 915, Y = 442 };
mapTemplate.Countries.Add(country123);
var country124 = new CountryTemplate("124", "Posen") { X = 844, Y = 439 };
mapTemplate.Countries.Add(country124);
var country125 = new CountryTemplate("125", "Pommern") { X = 835, Y = 393 };
mapTemplate.Countries.Add(country125);
var country126 = new CountryTemplate("126", "Brandenburg") { X = 740, Y = 432 };
mapTemplate.Countries.Add(country126);
var country127 = new CountryTemplate("127", "Sachsen") { X = 756, Y = 507 };
mapTemplate.Countries.Add(country127);
var country128 = new CountryTemplate("128", "Schlesien") { X = 819, Y = 480 };
mapTemplate.Countries.Add(country128);
var country129 = new CountryTemplate("129", "Prag") { X = 836, Y = 524 };
mapTemplate.Countries.Add(country129);
var country130 = new CountryTemplate("130", "Maehren") { X = 891, Y = 511 };
mapTemplate.Countries.Add(country130);
var country131 = new CountryTemplate("131", "Siebenbuergen") { X = 1031, Y = 597 };
mapTemplate.Countries.Add(country131);
var country132 = new CountryTemplate("132", "Buda") { X = 911, Y = 556 };
mapTemplate.Countries.Add(country132);
var country133 = new CountryTemplate("133", "Banat") { X = 946, Y = 617 };
mapTemplate.Countries.Add(country133);
var country134 = new CountryTemplate("134", "Dakien") { X = 1012, Y = 660 };
mapTemplate.Countries.Add(country134);
var country135 = new CountryTemplate("135", "Pannonien") { X = 827, Y = 623 };
mapTemplate.Countries.Add(country135);
var country136 = new CountryTemplate("136", "Steiermark") { X = 786, Y = 565 };
mapTemplate.Countries.Add(country136);
var country137 = new CountryTemplate("137", "Kaernten") { X = 750, Y = 601 };
mapTemplate.Countries.Add(country137);
var country138 = new CountryTemplate("138", "Krain") { X = 775, Y = 658 };
mapTemplate.Countries.Add(country138);
var country139 = new CountryTemplate("139", "Dalmatien") { X = 843, Y = 717 };
mapTemplate.Countries.Add(country139);
var country140 = new CountryTemplate("140", "Bosnien") { X = 875, Y = 699 };
mapTemplate.Countries.Add(country140);
var country141 = new CountryTemplate("141", "Serbien") { X = 924, Y = 681 };
mapTemplate.Countries.Add(country141);
var country142 = new CountryTemplate("142", "Raszien") { X = 925, Y = 725 };
mapTemplate.Countries.Add(country142);
var country143 = new CountryTemplate("143", "Epirus") { X = 949, Y = 839 };
mapTemplate.Countries.Add(country143);
var country144 = new CountryTemplate("144", "Thessalien") { X = 1022, Y = 796 };
mapTemplate.Countries.Add(country144);
var country145 = new CountryTemplate("145", "Athen") { X = 992, Y = 881 };
mapTemplate.Countries.Add(country145);
var country146 = new CountryTemplate("146", "Kreta") { X = 1088, Y = 961 };
mapTemplate.Countries.Add(country146);
var country147 = new CountryTemplate("147", "Mazedonien") { X = 958, Y = 759 };
mapTemplate.Countries.Add(country147);
var country148 = new CountryTemplate("148", "Vidin") { X = 1034, Y = 725 };
mapTemplate.Countries.Add(country148);
var country149 = new CountryTemplate("149", "Moesia") { X = 1073, Y = 681 };
mapTemplate.Countries.Add(country149);
var country150 = new CountryTemplate("150", "Muntenien") { X = 1087, Y = 631 };
mapTemplate.Countries.Add(country150);
var country151 = new CountryTemplate("151", "Pechenengs") { X = 1206, Y = 640 };
mapTemplate.Countries.Add(country151);
var country152 = new CountryTemplate("152", "Karvun") { X = 1137, Y = 645 };
mapTemplate.Countries.Add(country152);
var country153 = new CountryTemplate("153", "Dobritch") { X = 1100, Y = 726 };
mapTemplate.Countries.Add(country153);
var country154 = new CountryTemplate("154", "Rumelien") { X = 1073, Y = 781 };
mapTemplate.Countries.Add(country154);
var country155 = new CountryTemplate("155", "Thrakien") { X = 1124, Y = 781 };
mapTemplate.Countries.Add(country155);
var country156 = new CountryTemplate("156", "Nicaea") { X = 1156, Y = 843 };
mapTemplate.Countries.Add(country156);
var country157 = new CountryTemplate("157", "Anatolien") { X = 1160, Y = 894 };
mapTemplate.Countries.Add(country157);
var country158 = new CountryTemplate("158", "Abkhasien") { X = 1457, Y = 680 };
mapTemplate.Countries.Add(country158);
var country159 = new CountryTemplate("159", "Trapezunt") { X = 1451, Y = 768 };
mapTemplate.Countries.Add(country159);
var country160 = new CountryTemplate("160", "Karaman") { X = 1431, Y = 838 };
mapTemplate.Countries.Add(country160);
var country161 = new CountryTemplate("161", "Zypern") { X = 1356, Y = 934 };
mapTemplate.Countries.Add(country161);
var country162 = new CountryTemplate("162", "Aleppo") { X = 1444, Y = 906 };
mapTemplate.Countries.Add(country162);
var country163 = new CountryTemplate("163", "Libanon") { X = 1443, Y = 974 };
mapTemplate.Countries.Add(country163);
var country164 = new CountryTemplate("164", "Damaskus") { X = 1425, Y = 1086 };
mapTemplate.Countries.Add(country164);
var country165 = new CountryTemplate("165", "Suez") { X = 1349, Y = 1097 };
mapTemplate.Countries.Add(country165);
var country166 = new CountryTemplate("166", "Kairo") { X = 1251, Y = 1087 };
mapTemplate.Countries.Add(country166);
var country167 = new CountryTemplate("167", "Alexandria") { X = 1141, Y = 1094 };
mapTemplate.Countries.Add(country167);
var country168 = new CountryTemplate("168", "Cyrenaika") { X = 1022, Y = 1073 };
mapTemplate.Countries.Add(country168);
var country169 = new CountryTemplate("169", "Bengasi") { X = 965, Y = 1068 };
mapTemplate.Countries.Add(country169);
var country170 = new CountryTemplate("170", "Syrtus") { X = 835, Y = 1100 };
mapTemplate.Countries.Add(country170);
var country171 = new CountryTemplate("171", "Gabes") { X = 747, Y = 1053 };
mapTemplate.Countries.Add(country171);
var country172 = new CountryTemplate("172", "Ghadames") { X = 653, Y = 1082 };
mapTemplate.Countries.Add(country172);
var country173 = new CountryTemplate("173", "Gafsa") { X = 650, Y = 1042 };
mapTemplate.Countries.Add(country173);
var country174 = new CountryTemplate("174", "Hasfid") { X = 647, Y = 1003 };
mapTemplate.Countries.Add(country174);
var country175 = new CountryTemplate("175", "Sardinien") { X = 616, Y = 811 };
mapTemplate.Countries.Add(country175);
var country176 = new CountryTemplate("176", "Bizerta") { X = 615, Y = 962 };
mapTemplate.Countries.Add(country176);
var country177 = new CountryTemplate("177", "Constantine") { X = 548, Y = 981 };
mapTemplate.Countries.Add(country177);
var country178 = new CountryTemplate("178", "Ouargla") { X = 524, Y = 1098 };
mapTemplate.Countries.Add(country178);
var country179 = new CountryTemplate("179", "Touggourt") { X = 542, Y = 1057 };
mapTemplate.Countries.Add(country179);
var country180 = new CountryTemplate("180", "Mzab") { X = 450, Y = 1052 };
mapTemplate.Countries.Add(country180);
var country181 = new CountryTemplate("181", "Bechar") { X = 326, Y = 1091 };
mapTemplate.Countries.Add(country181);
var country182 = new CountryTemplate("182", "Kuko") { X = 483, Y = 982 };
mapTemplate.Countries.Add(country182);
var country183 = new CountryTemplate("183", "Quarsenis") { X = 454, Y = 1016 };
mapTemplate.Countries.Add(country183);
var country184 = new CountryTemplate("184", "Tlemcen") { X = 423, Y = 957 };
mapTemplate.Countries.Add(country184);
var country185 = new CountryTemplate("185", "Fuguig") { X = 302, Y = 1037 };
mapTemplate.Countries.Add(country185);
var country186 = new CountryTemplate("186", "Oran") { X = 313, Y = 983 };
mapTemplate.Countries.Add(country186);
var country187 = new CountryTemplate("187", "Fes") { X = 198, Y = 990 };
mapTemplate.Countries.Add(country187);
var country188 = new CountryTemplate("188", "Marrakesch") { X = 117, Y = 1049 };
mapTemplate.Countries.Add(country188);
var country189 = new CountryTemplate("189", "Sinop") { X = 1325, Y = 782 };
mapTemplate.Countries.Add(country189);
var country190 = new CountryTemplate("190", "Pontus") { X = 1286, Y = 791 };
mapTemplate.Countries.Add(country190);
var country191 = new CountryTemplate("191", "Galatien") { X = 1267, Y = 848 };
mapTemplate.Countries.Add(country191);
var country192 = new CountryTemplate("192", "Lycien") { X = 1224, Y = 898 };
mapTemplate.Countries.Add(country192);
var country193 = new CountryTemplate("193", "Pamphylien") { X = 1278, Y = 890 };
mapTemplate.Countries.Add(country193);
var country194 = new CountryTemplate("194", "Kappadokien") { X = 1343, Y = 866 };
mapTemplate.Countries.Add(country194);
var country195 = new CountryTemplate("195", "Twer") { X = 1258, Y = 212 };
mapTemplate.Countries.Add(country195);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 1);
continent2.Countries.Add(country5);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country6);
continent4.Countries.Add(country7);
continent4.Countries.Add(country8);
continent4.Countries.Add(country9);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
continent5.Countries.Add(country20);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country24);
continent7.Countries.Add(country25);
continent7.Countries.Add(country26);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country27);
continent8.Countries.Add(country28);
continent8.Countries.Add(country29);
continent8.Countries.Add(country30);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country31);
continent9.Countries.Add(country32);
continent9.Countries.Add(country33);
continent9.Countries.Add(country34);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country35);
continent10.Countries.Add(country36);
continent10.Countries.Add(country37);
continent10.Countries.Add(country38);
continent10.Countries.Add(country39);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 2);
continent11.Countries.Add(country40);
continent11.Countries.Add(country41);
continent11.Countries.Add(country42);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 1);
continent12.Countries.Add(country43);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 3);
continent13.Countries.Add(country44);
continent13.Countries.Add(country45);
continent13.Countries.Add(country46);
continent13.Countries.Add(country47);
continent13.Countries.Add(country48);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 2);
continent14.Countries.Add(country51);
continent14.Countries.Add(country52);
continent14.Countries.Add(country53);
continent14.Countries.Add(country54);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 1);
continent15.Countries.Add(country55);
continent15.Countries.Add(country56);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 1);
continent16.Countries.Add(country57);
continent16.Countries.Add(country58);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 2);
continent17.Countries.Add(country59);
continent17.Countries.Add(country60);
continent17.Countries.Add(country61);
continent17.Countries.Add(country62);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 2);
continent18.Countries.Add(country50);
continent18.Countries.Add(country63);
continent18.Countries.Add(country64);
continent18.Countries.Add(country65);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 2);
continent19.Countries.Add(country66);
continent19.Countries.Add(country67);
continent19.Countries.Add(country68);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 3);
continent20.Countries.Add(country69);
continent20.Countries.Add(country70);
continent20.Countries.Add(country71);
continent20.Countries.Add(country72);
continent20.Countries.Add(country73);
mapTemplate.Continents.Add(continent20);
var continent21 = new Continent("21", 3);
continent21.Countries.Add(country74);
continent21.Countries.Add(country75);
continent21.Countries.Add(country76);
continent21.Countries.Add(country77);
continent21.Countries.Add(country78);
mapTemplate.Continents.Add(continent21);
var continent22 = new Continent("22", 2);
continent22.Countries.Add(country79);
continent22.Countries.Add(country80);
continent22.Countries.Add(country81);
mapTemplate.Continents.Add(continent22);
var continent23 = new Continent("23", 3);
continent23.Countries.Add(country82);
continent23.Countries.Add(country83);
continent23.Countries.Add(country84);
continent23.Countries.Add(country85);
continent23.Countries.Add(country195);
mapTemplate.Continents.Add(continent23);
var continent24 = new Continent("24", 2);
continent24.Countries.Add(country86);
continent24.Countries.Add(country87);
continent24.Countries.Add(country88);
continent24.Countries.Add(country89);
mapTemplate.Continents.Add(continent24);
var continent25 = new Continent("25", 2);
continent25.Countries.Add(country90);
continent25.Countries.Add(country91);
continent25.Countries.Add(country92);
continent25.Countries.Add(country93);
mapTemplate.Continents.Add(continent25);
var continent26 = new Continent("26", 3);
continent26.Countries.Add(country94);
continent26.Countries.Add(country95);
continent26.Countries.Add(country96);
continent26.Countries.Add(country97);
continent26.Countries.Add(country98);
continent26.Countries.Add(country99);
mapTemplate.Continents.Add(continent26);
var continent27 = new Continent("27", 2);
continent27.Countries.Add(country100);
continent27.Countries.Add(country101);
continent27.Countries.Add(country102);
continent27.Countries.Add(country103);
mapTemplate.Continents.Add(continent27);
var continent28 = new Continent("28", 2);
continent28.Countries.Add(country104);
continent28.Countries.Add(country105);
continent28.Countries.Add(country106);
mapTemplate.Continents.Add(continent28);
var continent29 = new Continent("29", 2);
continent29.Countries.Add(country107);
continent29.Countries.Add(country108);
continent29.Countries.Add(country109);
mapTemplate.Continents.Add(continent29);
var continent30 = new Continent("30", 3);
continent30.Countries.Add(country110);
continent30.Countries.Add(country111);
continent30.Countries.Add(country112);
continent30.Countries.Add(country113);
continent30.Countries.Add(country114);
mapTemplate.Continents.Add(continent30);
var continent31 = new Continent("31", 3);
continent31.Countries.Add(country115);
continent31.Countries.Add(country116);
continent31.Countries.Add(country117);
continent31.Countries.Add(country118);
continent31.Countries.Add(country119);
mapTemplate.Continents.Add(continent31);
var continent32 = new Continent("32", 2);
continent32.Countries.Add(country120);
continent32.Countries.Add(country121);
continent32.Countries.Add(country122);
continent32.Countries.Add(country123);
mapTemplate.Continents.Add(continent32);
var continent33 = new Continent("33", 2);
continent33.Countries.Add(country124);
continent33.Countries.Add(country125);
continent33.Countries.Add(country126);
mapTemplate.Continents.Add(continent33);
var continent34 = new Continent("34", 2);
continent34.Countries.Add(country127);
continent34.Countries.Add(country128);
continent34.Countries.Add(country129);
continent34.Countries.Add(country130);
mapTemplate.Continents.Add(continent34);
var continent35 = new Continent("35", 2);
continent35.Countries.Add(country131);
continent35.Countries.Add(country132);
continent35.Countries.Add(country133);
continent35.Countries.Add(country134);
mapTemplate.Continents.Add(continent35);
var continent36 = new Continent("36", 2);
continent36.Countries.Add(country49);
continent36.Countries.Add(country135);
continent36.Countries.Add(country136);
continent36.Countries.Add(country137);
mapTemplate.Continents.Add(continent36);
var continent37 = new Continent("37", 3);
continent37.Countries.Add(country138);
continent37.Countries.Add(country139);
continent37.Countries.Add(country140);
continent37.Countries.Add(country141);
continent37.Countries.Add(country142);
mapTemplate.Continents.Add(continent37);
var continent38 = new Continent("38", 2);
continent38.Countries.Add(country143);
continent38.Countries.Add(country144);
continent38.Countries.Add(country145);
continent38.Countries.Add(country146);
mapTemplate.Continents.Add(continent38);
var continent39 = new Continent("39", 2);
continent39.Countries.Add(country147);
continent39.Countries.Add(country148);
continent39.Countries.Add(country149);
mapTemplate.Continents.Add(continent39);
var continent40 = new Continent("40", 2);
continent40.Countries.Add(country150);
continent40.Countries.Add(country151);
continent40.Countries.Add(country152);
mapTemplate.Continents.Add(continent40);
var continent41 = new Continent("41", 3);
continent41.Countries.Add(country153);
continent41.Countries.Add(country154);
continent41.Countries.Add(country155);
continent41.Countries.Add(country156);
continent41.Countries.Add(country157);
mapTemplate.Continents.Add(continent41);
var continent42 = new Continent("42", 2);
continent42.Countries.Add(country158);
continent42.Countries.Add(country159);
continent42.Countries.Add(country160);
mapTemplate.Continents.Add(continent42);
var continent43 = new Continent("43", 1);
continent43.Countries.Add(country161);
mapTemplate.Continents.Add(continent43);
var continent44 = new Continent("44", 2);
continent44.Countries.Add(country162);
continent44.Countries.Add(country163);
continent44.Countries.Add(country164);
continent44.Countries.Add(country165);
mapTemplate.Continents.Add(continent44);
var continent45 = new Continent("45", 2);
continent45.Countries.Add(country166);
continent45.Countries.Add(country167);
continent45.Countries.Add(country168);
continent45.Countries.Add(country169);
mapTemplate.Continents.Add(continent45);
var continent46 = new Continent("46", 2);
continent46.Countries.Add(country170);
continent46.Countries.Add(country171);
continent46.Countries.Add(country172);
continent46.Countries.Add(country173);
mapTemplate.Continents.Add(continent46);
var continent47 = new Continent("47", 2);
continent47.Countries.Add(country174);
continent47.Countries.Add(country175);
continent47.Countries.Add(country176);
continent47.Countries.Add(country177);
mapTemplate.Continents.Add(continent47);
var continent48 = new Continent("48", 2);
continent48.Countries.Add(country178);
continent48.Countries.Add(country179);
continent48.Countries.Add(country180);
continent48.Countries.Add(country181);
mapTemplate.Continents.Add(continent48);
var continent49 = new Continent("49", 3);
continent49.Countries.Add(country182);
continent49.Countries.Add(country183);
continent49.Countries.Add(country184);
continent49.Countries.Add(country185);
continent49.Countries.Add(country186);
mapTemplate.Continents.Add(continent49);
var continent50 = new Continent("50", 1);
continent50.Countries.Add(country187);
continent50.Countries.Add(country188);
mapTemplate.Continents.Add(continent50);
var continent51 = new Continent("51", 3);
continent51.Countries.Add(country189);
continent51.Countries.Add(country190);
continent51.Countries.Add(country191);
continent51.Countries.Add(country192);
continent51.Countries.Add(country193);
continent51.Countries.Add(country194);
mapTemplate.Continents.Add(continent51);
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "9"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "13"));
mapTemplate.Connections.Add(new Connection("5", "11"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "69"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "4"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("11", "5"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "5"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "38"));
mapTemplate.Connections.Add(new Connection("15", "57"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "38"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "37"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "37"));
mapTemplate.Connections.Add(new Connection("18", "36"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "36"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "35"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "35"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "31"));
mapTemplate.Connections.Add(new Connection("20", "34"));
mapTemplate.Connections.Add(new Connection("20", "30"));
mapTemplate.Connections.Add(new Connection("21", "24"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "30"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "30"));
mapTemplate.Connections.Add(new Connection("23", "29"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("24", "21"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "32"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "186"));
mapTemplate.Connections.Add(new Connection("27", "187"));
mapTemplate.Connections.Add(new Connection("28", "32"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("29", "32"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("29", "23"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("30", "20"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "21"));
mapTemplate.Connections.Add(new Connection("30", "23"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "20"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "29"));
mapTemplate.Connections.Add(new Connection("32", "28"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "20"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "19"));
mapTemplate.Connections.Add(new Connection("35", "20"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "51"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "18"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "19"));
mapTemplate.Connections.Add(new Connection("36", "51"));
mapTemplate.Connections.Add(new Connection("36", "52"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "18"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "52"));
mapTemplate.Connections.Add(new Connection("37", "54"));
mapTemplate.Connections.Add(new Connection("37", "17"));
mapTemplate.Connections.Add(new Connection("38", "15"));
mapTemplate.Connections.Add(new Connection("38", "17"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "57"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "54"));
mapTemplate.Connections.Add(new Connection("39", "55"));
mapTemplate.Connections.Add(new Connection("39", "56"));
mapTemplate.Connections.Add(new Connection("39", "57"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "174"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "143"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("43", "48"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "175"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "51"));
mapTemplate.Connections.Add(new Connection("46", "52"));
mapTemplate.Connections.Add(new Connection("46", "53"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "53"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("48", "43"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "138"));
mapTemplate.Connections.Add(new Connection("48", "137"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "65"));
mapTemplate.Connections.Add(new Connection("49", "137"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "55"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "64"));
mapTemplate.Connections.Add(new Connection("50", "65"));
mapTemplate.Connections.Add(new Connection("51", "46"));
mapTemplate.Connections.Add(new Connection("51", "35"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "36"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "46"));
mapTemplate.Connections.Add(new Connection("52", "36"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "37"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "46"));
mapTemplate.Connections.Add(new Connection("53", "47"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "55"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "37"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "39"));
mapTemplate.Connections.Add(new Connection("55", "53"));
mapTemplate.Connections.Add(new Connection("55", "50"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "64"));
mapTemplate.Connections.Add(new Connection("55", "39"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "39"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "64"));
mapTemplate.Connections.Add(new Connection("56", "58"));
mapTemplate.Connections.Add(new Connection("56", "62"));
mapTemplate.Connections.Add(new Connection("57", "38"));
mapTemplate.Connections.Add(new Connection("57", "15"));
mapTemplate.Connections.Add(new Connection("57", "39"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "56"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "62"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "62"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("59", "66"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("60", "67"));
mapTemplate.Connections.Add(new Connection("60", "66"));
mapTemplate.Connections.Add(new Connection("60", "126"));
mapTemplate.Connections.Add(new Connection("60", "125"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("61", "126"));
mapTemplate.Connections.Add(new Connection("62", "58"));
mapTemplate.Connections.Add(new Connection("62", "56"));
mapTemplate.Connections.Add(new Connection("62", "59"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "64"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("63", "65"));
mapTemplate.Connections.Add(new Connection("63", "126"));
mapTemplate.Connections.Add(new Connection("64", "55"));
mapTemplate.Connections.Add(new Connection("64", "50"));
mapTemplate.Connections.Add(new Connection("64", "56"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "62"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("65", "50"));
mapTemplate.Connections.Add(new Connection("65", "49"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "63"));
mapTemplate.Connections.Add(new Connection("65", "137"));
mapTemplate.Connections.Add(new Connection("65", "136"));
mapTemplate.Connections.Add(new Connection("65", "129"));
mapTemplate.Connections.Add(new Connection("65", "127"));
mapTemplate.Connections.Add(new Connection("65", "126"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "68"));
mapTemplate.Connections.Add(new Connection("66", "60"));
mapTemplate.Connections.Add(new Connection("66", "59"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "60"));
mapTemplate.Connections.Add(new Connection("68", "72"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "66"));
mapTemplate.Connections.Add(new Connection("68", "77"));
mapTemplate.Connections.Add(new Connection("69", "6"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "72"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("72", "69"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("72", "77"));
mapTemplate.Connections.Add(new Connection("72", "68"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("73", "77"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "75"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("75", "74"));
mapTemplate.Connections.Add(new Connection("75", "77"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "79"));
mapTemplate.Connections.Add(new Connection("77", "73"));
mapTemplate.Connections.Add(new Connection("77", "72"));
mapTemplate.Connections.Add(new Connection("77", "68"));
mapTemplate.Connections.Add(new Connection("77", "75"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "116"));
mapTemplate.Connections.Add(new Connection("79", "76"));
mapTemplate.Connections.Add(new Connection("79", "115"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("79", "81"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("81", "79"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("81", "83"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "86"));
mapTemplate.Connections.Add(new Connection("83", "81"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "195"));
mapTemplate.Connections.Add(new Connection("83", "88"));
mapTemplate.Connections.Add(new Connection("83", "86"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("84", "115"));
mapTemplate.Connections.Add(new Connection("84", "117"));
mapTemplate.Connections.Add(new Connection("84", "110"));
mapTemplate.Connections.Add(new Connection("84", "195"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("85", "110"));
mapTemplate.Connections.Add(new Connection("85", "195"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "89"));
mapTemplate.Connections.Add(new Connection("85", "91"));
mapTemplate.Connections.Add(new Connection("85", "109"));
mapTemplate.Connections.Add(new Connection("86", "82"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("86", "83"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "89"));
mapTemplate.Connections.Add(new Connection("88", "86"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "83"));
mapTemplate.Connections.Add(new Connection("88", "195"));
mapTemplate.Connections.Add(new Connection("88", "89"));
mapTemplate.Connections.Add(new Connection("89", "87"));
mapTemplate.Connections.Add(new Connection("89", "88"));
mapTemplate.Connections.Add(new Connection("89", "195"));
mapTemplate.Connections.Add(new Connection("89", "85"));
mapTemplate.Connections.Add(new Connection("89", "90"));
mapTemplate.Connections.Add(new Connection("89", "91"));
mapTemplate.Connections.Add(new Connection("90", "89"));
mapTemplate.Connections.Add(new Connection("90", "91"));
mapTemplate.Connections.Add(new Connection("90", "92"));
mapTemplate.Connections.Add(new Connection("91", "85"));
mapTemplate.Connections.Add(new Connection("91", "90"));
mapTemplate.Connections.Add(new Connection("91", "92"));
mapTemplate.Connections.Add(new Connection("91", "93"));
mapTemplate.Connections.Add(new Connection("91", "109"));
mapTemplate.Connections.Add(new Connection("91", "108"));
mapTemplate.Connections.Add(new Connection("91", "89"));
mapTemplate.Connections.Add(new Connection("91", "94"));
mapTemplate.Connections.Add(new Connection("91", "104"));
mapTemplate.Connections.Add(new Connection("91", "105"));
mapTemplate.Connections.Add(new Connection("92", "90"));
mapTemplate.Connections.Add(new Connection("92", "91"));
mapTemplate.Connections.Add(new Connection("92", "93"));
mapTemplate.Connections.Add(new Connection("93", "92"));
mapTemplate.Connections.Add(new Connection("93", "91"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "95"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("94", "91"));
mapTemplate.Connections.Add(new Connection("94", "104"));
mapTemplate.Connections.Add(new Connection("94", "97"));
mapTemplate.Connections.Add(new Connection("94", "95"));
mapTemplate.Connections.Add(new Connection("95", "94"));
mapTemplate.Connections.Add(new Connection("95", "97"));
mapTemplate.Connections.Add(new Connection("95", "96"));
mapTemplate.Connections.Add(new Connection("95", "158"));
mapTemplate.Connections.Add(new Connection("95", "93"));
mapTemplate.Connections.Add(new Connection("96", "97"));
mapTemplate.Connections.Add(new Connection("96", "95"));
mapTemplate.Connections.Add(new Connection("96", "158"));
mapTemplate.Connections.Add(new Connection("96", "99"));
mapTemplate.Connections.Add(new Connection("97", "100"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "104"));
mapTemplate.Connections.Add(new Connection("97", "94"));
mapTemplate.Connections.Add(new Connection("97", "95"));
mapTemplate.Connections.Add(new Connection("97", "96"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("98", "100"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("99", "96"));
mapTemplate.Connections.Add(new Connection("100", "102"));
mapTemplate.Connections.Add(new Connection("100", "104"));
mapTemplate.Connections.Add(new Connection("100", "151"));
mapTemplate.Connections.Add(new Connection("100", "101"));
mapTemplate.Connections.Add(new Connection("100", "97"));
mapTemplate.Connections.Add(new Connection("100", "98"));
mapTemplate.Connections.Add(new Connection("101", "103"));
mapTemplate.Connections.Add(new Connection("101", "131"));
mapTemplate.Connections.Add(new Connection("101", "150"));
mapTemplate.Connections.Add(new Connection("101", "151"));
mapTemplate.Connections.Add(new Connection("101", "102"));
mapTemplate.Connections.Add(new Connection("101", "100"));
mapTemplate.Connections.Add(new Connection("102", "103"));
mapTemplate.Connections.Add(new Connection("102", "101"));
mapTemplate.Connections.Add(new Connection("102", "106"));
mapTemplate.Connections.Add(new Connection("102", "105"));
mapTemplate.Connections.Add(new Connection("102", "104"));
mapTemplate.Connections.Add(new Connection("102", "100"));
mapTemplate.Connections.Add(new Connection("103", "106"));
mapTemplate.Connections.Add(new Connection("103", "120"));
mapTemplate.Connections.Add(new Connection("103", "121"));
mapTemplate.Connections.Add(new Connection("103", "131"));
mapTemplate.Connections.Add(new Connection("103", "101"));
mapTemplate.Connections.Add(new Connection("103", "102"));
mapTemplate.Connections.Add(new Connection("104", "94"));
mapTemplate.Connections.Add(new Connection("104", "91"));
mapTemplate.Connections.Add(new Connection("104", "105"));
mapTemplate.Connections.Add(new Connection("104", "102"));
mapTemplate.Connections.Add(new Connection("104", "100"));
mapTemplate.Connections.Add(new Connection("104", "97"));
mapTemplate.Connections.Add(new Connection("105", "104"));
mapTemplate.Connections.Add(new Connection("105", "91"));
mapTemplate.Connections.Add(new Connection("105", "108"));
mapTemplate.Connections.Add(new Connection("105", "107"));
mapTemplate.Connections.Add(new Connection("105", "106"));
mapTemplate.Connections.Add(new Connection("105", "102"));
mapTemplate.Connections.Add(new Connection("106", "107"));
mapTemplate.Connections.Add(new Connection("106", "105"));
mapTemplate.Connections.Add(new Connection("106", "111"));
mapTemplate.Connections.Add(new Connection("106", "120"));
mapTemplate.Connections.Add(new Connection("106", "103"));
mapTemplate.Connections.Add(new Connection("106", "102"));
mapTemplate.Connections.Add(new Connection("107", "108"));
mapTemplate.Connections.Add(new Connection("107", "109"));
mapTemplate.Connections.Add(new Connection("107", "110"));
mapTemplate.Connections.Add(new Connection("107", "111"));
mapTemplate.Connections.Add(new Connection("107", "105"));
mapTemplate.Connections.Add(new Connection("107", "106"));
mapTemplate.Connections.Add(new Connection("108", "91"));
mapTemplate.Connections.Add(new Connection("108", "109"));
mapTemplate.Connections.Add(new Connection("108", "107"));
mapTemplate.Connections.Add(new Connection("108", "105"));
mapTemplate.Connections.Add(new Connection("109", "85"));
mapTemplate.Connections.Add(new Connection("109", "91"));
mapTemplate.Connections.Add(new Connection("109", "108"));
mapTemplate.Connections.Add(new Connection("109", "107"));
mapTemplate.Connections.Add(new Connection("109", "110"));
mapTemplate.Connections.Add(new Connection("110", "114"));
mapTemplate.Connections.Add(new Connection("110", "113"));
mapTemplate.Connections.Add(new Connection("110", "111"));
mapTemplate.Connections.Add(new Connection("110", "117"));
mapTemplate.Connections.Add(new Connection("110", "84"));
mapTemplate.Connections.Add(new Connection("110", "85"));
mapTemplate.Connections.Add(new Connection("110", "109"));
mapTemplate.Connections.Add(new Connection("110", "107"));
mapTemplate.Connections.Add(new Connection("111", "113"));
mapTemplate.Connections.Add(new Connection("111", "112"));
mapTemplate.Connections.Add(new Connection("111", "110"));
mapTemplate.Connections.Add(new Connection("111", "120"));
mapTemplate.Connections.Add(new Connection("111", "107"));
mapTemplate.Connections.Add(new Connection("111", "106"));
mapTemplate.Connections.Add(new Connection("112", "123"));
mapTemplate.Connections.Add(new Connection("112", "122"));
mapTemplate.Connections.Add(new Connection("112", "120"));
mapTemplate.Connections.Add(new Connection("112", "113"));
mapTemplate.Connections.Add(new Connection("112", "111"));
mapTemplate.Connections.Add(new Connection("113", "114"));
mapTemplate.Connections.Add(new Connection("113", "118"));
mapTemplate.Connections.Add(new Connection("113", "119"));
mapTemplate.Connections.Add(new Connection("113", "123"));
mapTemplate.Connections.Add(new Connection("113", "112"));
mapTemplate.Connections.Add(new Connection("113", "110"));
mapTemplate.Connections.Add(new Connection("113", "111"));
mapTemplate.Connections.Add(new Connection("114", "117"));
mapTemplate.Connections.Add(new Connection("114", "118"));
mapTemplate.Connections.Add(new Connection("114", "113"));
mapTemplate.Connections.Add(new Connection("114", "110"));
mapTemplate.Connections.Add(new Connection("115", "79"));
mapTemplate.Connections.Add(new Connection("115", "116"));
mapTemplate.Connections.Add(new Connection("115", "117"));
mapTemplate.Connections.Add(new Connection("115", "84"));
mapTemplate.Connections.Add(new Connection("116", "118"));
mapTemplate.Connections.Add(new Connection("116", "78"));
mapTemplate.Connections.Add(new Connection("116", "115"));
mapTemplate.Connections.Add(new Connection("117", "118"));
mapTemplate.Connections.Add(new Connection("117", "115"));
mapTemplate.Connections.Add(new Connection("117", "84"));
mapTemplate.Connections.Add(new Connection("117", "114"));
mapTemplate.Connections.Add(new Connection("117", "110"));
mapTemplate.Connections.Add(new Connection("118", "119"));
mapTemplate.Connections.Add(new Connection("118", "116"));
mapTemplate.Connections.Add(new Connection("118", "117"));
mapTemplate.Connections.Add(new Connection("118", "114"));
mapTemplate.Connections.Add(new Connection("118", "113"));
mapTemplate.Connections.Add(new Connection("119", "125"));
mapTemplate.Connections.Add(new Connection("119", "124"));
mapTemplate.Connections.Add(new Connection("119", "123"));
mapTemplate.Connections.Add(new Connection("119", "118"));
mapTemplate.Connections.Add(new Connection("119", "113"));
mapTemplate.Connections.Add(new Connection("120", "121"));
mapTemplate.Connections.Add(new Connection("120", "122"));
mapTemplate.Connections.Add(new Connection("120", "112"));
mapTemplate.Connections.Add(new Connection("120", "111"));
mapTemplate.Connections.Add(new Connection("120", "106"));
mapTemplate.Connections.Add(new Connection("120", "103"));
mapTemplate.Connections.Add(new Connection("121", "128"));
mapTemplate.Connections.Add(new Connection("121", "130"));
mapTemplate.Connections.Add(new Connection("121", "132"));
mapTemplate.Connections.Add(new Connection("121", "131"));
mapTemplate.Connections.Add(new Connection("121", "122"));
mapTemplate.Connections.Add(new Connection("121", "120"));
mapTemplate.Connections.Add(new Connection("121", "103"));
mapTemplate.Connections.Add(new Connection("122", "128"));
mapTemplate.Connections.Add(new Connection("122", "121"));
mapTemplate.Connections.Add(new Connection("122", "123"));
mapTemplate.Connections.Add(new Connection("122", "120"));
mapTemplate.Connections.Add(new Connection("122", "112"));
mapTemplate.Connections.Add(new Connection("123", "124"));
mapTemplate.Connections.Add(new Connection("123", "119"));
mapTemplate.Connections.Add(new Connection("123", "128"));
mapTemplate.Connections.Add(new Connection("123", "122"));
mapTemplate.Connections.Add(new Connection("123", "113"));
mapTemplate.Connections.Add(new Connection("123", "112"));
mapTemplate.Connections.Add(new Connection("124", "126"));
mapTemplate.Connections.Add(new Connection("124", "125"));
mapTemplate.Connections.Add(new Connection("124", "128"));
mapTemplate.Connections.Add(new Connection("124", "119"));
mapTemplate.Connections.Add(new Connection("124", "123"));
mapTemplate.Connections.Add(new Connection("125", "60"));
mapTemplate.Connections.Add(new Connection("125", "126"));
mapTemplate.Connections.Add(new Connection("125", "124"));
mapTemplate.Connections.Add(new Connection("125", "119"));
mapTemplate.Connections.Add(new Connection("126", "65"));
mapTemplate.Connections.Add(new Connection("126", "127"));
mapTemplate.Connections.Add(new Connection("126", "63"));
mapTemplate.Connections.Add(new Connection("126", "61"));
mapTemplate.Connections.Add(new Connection("126", "60"));
mapTemplate.Connections.Add(new Connection("126", "128"));
mapTemplate.Connections.Add(new Connection("126", "125"));
mapTemplate.Connections.Add(new Connection("126", "124"));
mapTemplate.Connections.Add(new Connection("127", "65"));
mapTemplate.Connections.Add(new Connection("127", "129"));
mapTemplate.Connections.Add(new Connection("127", "128"));
mapTemplate.Connections.Add(new Connection("127", "126"));
mapTemplate.Connections.Add(new Connection("128", "129"));
mapTemplate.Connections.Add(new Connection("128", "130"));
mapTemplate.Connections.Add(new Connection("128", "127"));
mapTemplate.Connections.Add(new Connection("128", "126"));
mapTemplate.Connections.Add(new Connection("128", "124"));
mapTemplate.Connections.Add(new Connection("128", "123"));
mapTemplate.Connections.Add(new Connection("128", "122"));
mapTemplate.Connections.Add(new Connection("128", "121"));
mapTemplate.Connections.Add(new Connection("129", "130"));
mapTemplate.Connections.Add(new Connection("129", "136"));
mapTemplate.Connections.Add(new Connection("129", "65"));
mapTemplate.Connections.Add(new Connection("129", "127"));
mapTemplate.Connections.Add(new Connection("129", "128"));
mapTemplate.Connections.Add(new Connection("130", "136"));
mapTemplate.Connections.Add(new Connection("130", "132"));
mapTemplate.Connections.Add(new Connection("130", "129"));
mapTemplate.Connections.Add(new Connection("130", "128"));
mapTemplate.Connections.Add(new Connection("130", "121"));
mapTemplate.Connections.Add(new Connection("131", "133"));
mapTemplate.Connections.Add(new Connection("131", "134"));
mapTemplate.Connections.Add(new Connection("131", "150"));
mapTemplate.Connections.Add(new Connection("131", "132"));
mapTemplate.Connections.Add(new Connection("131", "121"));
mapTemplate.Connections.Add(new Connection("131", "103"));
mapTemplate.Connections.Add(new Connection("131", "101"));
mapTemplate.Connections.Add(new Connection("132", "133"));
mapTemplate.Connections.Add(new Connection("132", "131"));
mapTemplate.Connections.Add(new Connection("132", "136"));
mapTemplate.Connections.Add(new Connection("132", "135"));
mapTemplate.Connections.Add(new Connection("132", "130"));
mapTemplate.Connections.Add(new Connection("132", "121"));
mapTemplate.Connections.Add(new Connection("133", "141"));
mapTemplate.Connections.Add(new Connection("133", "140"));
mapTemplate.Connections.Add(new Connection("133", "134"));
mapTemplate.Connections.Add(new Connection("133", "131"));
mapTemplate.Connections.Add(new Connection("133", "135"));
mapTemplate.Connections.Add(new Connection("133", "132"));
mapTemplate.Connections.Add(new Connection("134", "148"));
mapTemplate.Connections.Add(new Connection("134", "149"));
mapTemplate.Connections.Add(new Connection("134", "141"));
mapTemplate.Connections.Add(new Connection("134", "150"));
mapTemplate.Connections.Add(new Connection("134", "133"));
mapTemplate.Connections.Add(new Connection("134", "131"));
mapTemplate.Connections.Add(new Connection("135", "140"));
mapTemplate.Connections.Add(new Connection("135", "133"));
mapTemplate.Connections.Add(new Connection("135", "136"));
mapTemplate.Connections.Add(new Connection("135", "138"));
mapTemplate.Connections.Add(new Connection("135", "137"));
mapTemplate.Connections.Add(new Connection("135", "132"));
mapTemplate.Connections.Add(new Connection("136", "132"));
mapTemplate.Connections.Add(new Connection("136", "135"));
mapTemplate.Connections.Add(new Connection("136", "137"));
mapTemplate.Connections.Add(new Connection("136", "65"));
mapTemplate.Connections.Add(new Connection("136", "130"));
mapTemplate.Connections.Add(new Connection("136", "129"));
mapTemplate.Connections.Add(new Connection("137", "138"));
mapTemplate.Connections.Add(new Connection("137", "135"));
mapTemplate.Connections.Add(new Connection("137", "136"));
mapTemplate.Connections.Add(new Connection("137", "49"));
mapTemplate.Connections.Add(new Connection("137", "65"));
mapTemplate.Connections.Add(new Connection("137", "48"));
mapTemplate.Connections.Add(new Connection("138", "139"));
mapTemplate.Connections.Add(new Connection("138", "140"));
mapTemplate.Connections.Add(new Connection("138", "135"));
mapTemplate.Connections.Add(new Connection("138", "48"));
mapTemplate.Connections.Add(new Connection("138", "137"));
mapTemplate.Connections.Add(new Connection("139", "142"));
mapTemplate.Connections.Add(new Connection("139", "140"));
mapTemplate.Connections.Add(new Connection("139", "138"));
mapTemplate.Connections.Add(new Connection("140", "142"));
mapTemplate.Connections.Add(new Connection("140", "141"));
mapTemplate.Connections.Add(new Connection("140", "139"));
mapTemplate.Connections.Add(new Connection("140", "133"));
mapTemplate.Connections.Add(new Connection("140", "138"));
mapTemplate.Connections.Add(new Connection("140", "135"));
mapTemplate.Connections.Add(new Connection("141", "142"));
mapTemplate.Connections.Add(new Connection("141", "147"));
mapTemplate.Connections.Add(new Connection("141", "148"));
mapTemplate.Connections.Add(new Connection("141", "134"));
mapTemplate.Connections.Add(new Connection("141", "140"));
mapTemplate.Connections.Add(new Connection("141", "133"));
mapTemplate.Connections.Add(new Connection("142", "143"));
mapTemplate.Connections.Add(new Connection("142", "147"));
mapTemplate.Connections.Add(new Connection("142", "141"));
mapTemplate.Connections.Add(new Connection("142", "139"));
mapTemplate.Connections.Add(new Connection("142", "140"));
mapTemplate.Connections.Add(new Connection("143", "145"));
mapTemplate.Connections.Add(new Connection("143", "41"));
mapTemplate.Connections.Add(new Connection("143", "144"));
mapTemplate.Connections.Add(new Connection("143", "147"));
mapTemplate.Connections.Add(new Connection("143", "142"));
mapTemplate.Connections.Add(new Connection("144", "145"));
mapTemplate.Connections.Add(new Connection("144", "143"));
mapTemplate.Connections.Add(new Connection("144", "147"));
mapTemplate.Connections.Add(new Connection("144", "154"));
mapTemplate.Connections.Add(new Connection("145", "146"));
mapTemplate.Connections.Add(new Connection("145", "144"));
mapTemplate.Connections.Add(new Connection("145", "143"));
mapTemplate.Connections.Add(new Connection("146", "168"));
mapTemplate.Connections.Add(new Connection("146", "167"));
mapTemplate.Connections.Add(new Connection("146", "157"));
mapTemplate.Connections.Add(new Connection("146", "145"));
mapTemplate.Connections.Add(new Connection("147", "143"));
mapTemplate.Connections.Add(new Connection("147", "144"));
mapTemplate.Connections.Add(new Connection("147", "154"));
mapTemplate.Connections.Add(new Connection("147", "148"));
mapTemplate.Connections.Add(new Connection("147", "142"));
mapTemplate.Connections.Add(new Connection("147", "141"));
mapTemplate.Connections.Add(new Connection("148", "154"));
mapTemplate.Connections.Add(new Connection("148", "153"));
mapTemplate.Connections.Add(new Connection("148", "147"));
mapTemplate.Connections.Add(new Connection("148", "141"));
mapTemplate.Connections.Add(new Connection("148", "149"));
mapTemplate.Connections.Add(new Connection("148", "134"));
mapTemplate.Connections.Add(new Connection("149", "148"));
mapTemplate.Connections.Add(new Connection("149", "153"));
mapTemplate.Connections.Add(new Connection("149", "134"));
mapTemplate.Connections.Add(new Connection("149", "150"));
mapTemplate.Connections.Add(new Connection("149", "152"));
mapTemplate.Connections.Add(new Connection("150", "149"));
mapTemplate.Connections.Add(new Connection("150", "134"));
mapTemplate.Connections.Add(new Connection("150", "152"));
mapTemplate.Connections.Add(new Connection("150", "151"));
mapTemplate.Connections.Add(new Connection("150", "131"));
mapTemplate.Connections.Add(new Connection("150", "101"));
mapTemplate.Connections.Add(new Connection("151", "152"));
mapTemplate.Connections.Add(new Connection("151", "150"));
mapTemplate.Connections.Add(new Connection("151", "101"));
mapTemplate.Connections.Add(new Connection("151", "100"));
mapTemplate.Connections.Add(new Connection("152", "150"));
mapTemplate.Connections.Add(new Connection("152", "153"));
mapTemplate.Connections.Add(new Connection("152", "149"));
mapTemplate.Connections.Add(new Connection("152", "151"));
mapTemplate.Connections.Add(new Connection("153", "154"));
mapTemplate.Connections.Add(new Connection("153", "155"));
mapTemplate.Connections.Add(new Connection("153", "148"));
mapTemplate.Connections.Add(new Connection("153", "149"));
mapTemplate.Connections.Add(new Connection("153", "152"));
mapTemplate.Connections.Add(new Connection("154", "144"));
mapTemplate.Connections.Add(new Connection("154", "155"));
mapTemplate.Connections.Add(new Connection("154", "147"));
mapTemplate.Connections.Add(new Connection("154", "148"));
mapTemplate.Connections.Add(new Connection("154", "153"));
mapTemplate.Connections.Add(new Connection("155", "154"));
mapTemplate.Connections.Add(new Connection("155", "156"));
mapTemplate.Connections.Add(new Connection("155", "153"));
mapTemplate.Connections.Add(new Connection("156", "157"));
mapTemplate.Connections.Add(new Connection("156", "191"));
mapTemplate.Connections.Add(new Connection("156", "155"));
mapTemplate.Connections.Add(new Connection("157", "192"));
mapTemplate.Connections.Add(new Connection("157", "146"));
mapTemplate.Connections.Add(new Connection("157", "156"));
mapTemplate.Connections.Add(new Connection("157", "191"));
mapTemplate.Connections.Add(new Connection("158", "95"));
mapTemplate.Connections.Add(new Connection("158", "96"));
mapTemplate.Connections.Add(new Connection("158", "159"));
mapTemplate.Connections.Add(new Connection("159", "194"));
mapTemplate.Connections.Add(new Connection("159", "189"));
mapTemplate.Connections.Add(new Connection("159", "160"));
mapTemplate.Connections.Add(new Connection("159", "158"));
mapTemplate.Connections.Add(new Connection("160", "162"));
mapTemplate.Connections.Add(new Connection("160", "193"));
mapTemplate.Connections.Add(new Connection("160", "194"));
mapTemplate.Connections.Add(new Connection("160", "159"));
mapTemplate.Connections.Add(new Connection("161", "163"));
mapTemplate.Connections.Add(new Connection("161", "193"));
mapTemplate.Connections.Add(new Connection("162", "163"));
mapTemplate.Connections.Add(new Connection("162", "160"));
mapTemplate.Connections.Add(new Connection("163", "164"));
mapTemplate.Connections.Add(new Connection("163", "162"));
mapTemplate.Connections.Add(new Connection("163", "161"));
mapTemplate.Connections.Add(new Connection("164", "165"));
mapTemplate.Connections.Add(new Connection("164", "163"));
mapTemplate.Connections.Add(new Connection("165", "166"));
mapTemplate.Connections.Add(new Connection("165", "164"));
mapTemplate.Connections.Add(new Connection("166", "167"));
mapTemplate.Connections.Add(new Connection("166", "165"));
mapTemplate.Connections.Add(new Connection("167", "168"));
mapTemplate.Connections.Add(new Connection("167", "146"));
mapTemplate.Connections.Add(new Connection("167", "166"));
mapTemplate.Connections.Add(new Connection("168", "169"));
mapTemplate.Connections.Add(new Connection("168", "146"));
mapTemplate.Connections.Add(new Connection("168", "167"));
mapTemplate.Connections.Add(new Connection("169", "171"));
mapTemplate.Connections.Add(new Connection("169", "170"));
mapTemplate.Connections.Add(new Connection("169", "168"));
mapTemplate.Connections.Add(new Connection("170", "172"));
mapTemplate.Connections.Add(new Connection("170", "171"));
mapTemplate.Connections.Add(new Connection("170", "169"));
mapTemplate.Connections.Add(new Connection("171", "174"));
mapTemplate.Connections.Add(new Connection("171", "172"));
mapTemplate.Connections.Add(new Connection("171", "170"));
mapTemplate.Connections.Add(new Connection("171", "169"));
mapTemplate.Connections.Add(new Connection("171", "173"));
mapTemplate.Connections.Add(new Connection("172", "179"));
mapTemplate.Connections.Add(new Connection("172", "178"));
mapTemplate.Connections.Add(new Connection("172", "173"));
mapTemplate.Connections.Add(new Connection("172", "171"));
mapTemplate.Connections.Add(new Connection("172", "170"));
mapTemplate.Connections.Add(new Connection("173", "174"));
mapTemplate.Connections.Add(new Connection("173", "179"));
mapTemplate.Connections.Add(new Connection("173", "172"));
mapTemplate.Connections.Add(new Connection("173", "171"));
mapTemplate.Connections.Add(new Connection("174", "177"));
mapTemplate.Connections.Add(new Connection("174", "176"));
mapTemplate.Connections.Add(new Connection("174", "179"));
mapTemplate.Connections.Add(new Connection("174", "40"));
mapTemplate.Connections.Add(new Connection("174", "171"));
mapTemplate.Connections.Add(new Connection("174", "173"));
mapTemplate.Connections.Add(new Connection("175", "176"));
mapTemplate.Connections.Add(new Connection("175", "44"));
mapTemplate.Connections.Add(new Connection("176", "177"));
mapTemplate.Connections.Add(new Connection("176", "174"));
mapTemplate.Connections.Add(new Connection("176", "175"));
mapTemplate.Connections.Add(new Connection("177", "182"));
mapTemplate.Connections.Add(new Connection("177", "183"));
mapTemplate.Connections.Add(new Connection("177", "180"));
mapTemplate.Connections.Add(new Connection("177", "179"));
mapTemplate.Connections.Add(new Connection("177", "176"));
mapTemplate.Connections.Add(new Connection("177", "174"));
mapTemplate.Connections.Add(new Connection("178", "181"));
mapTemplate.Connections.Add(new Connection("178", "180"));
mapTemplate.Connections.Add(new Connection("178", "179"));
mapTemplate.Connections.Add(new Connection("178", "172"));
mapTemplate.Connections.Add(new Connection("179", "180"));
mapTemplate.Connections.Add(new Connection("179", "178"));
mapTemplate.Connections.Add(new Connection("179", "177"));
mapTemplate.Connections.Add(new Connection("179", "174"));
mapTemplate.Connections.Add(new Connection("179", "173"));
mapTemplate.Connections.Add(new Connection("179", "172"));
mapTemplate.Connections.Add(new Connection("180", "183"));
mapTemplate.Connections.Add(new Connection("180", "178"));
mapTemplate.Connections.Add(new Connection("180", "177"));
mapTemplate.Connections.Add(new Connection("180", "179"));
mapTemplate.Connections.Add(new Connection("180", "181"));
mapTemplate.Connections.Add(new Connection("181", "188"));
mapTemplate.Connections.Add(new Connection("181", "185"));
mapTemplate.Connections.Add(new Connection("181", "183"));
mapTemplate.Connections.Add(new Connection("181", "178"));
mapTemplate.Connections.Add(new Connection("181", "180"));
mapTemplate.Connections.Add(new Connection("182", "183"));
mapTemplate.Connections.Add(new Connection("182", "184"));
mapTemplate.Connections.Add(new Connection("182", "177"));
mapTemplate.Connections.Add(new Connection("183", "185"));
mapTemplate.Connections.Add(new Connection("183", "181"));
mapTemplate.Connections.Add(new Connection("183", "184"));
mapTemplate.Connections.Add(new Connection("183", "180"));
mapTemplate.Connections.Add(new Connection("183", "182"));
mapTemplate.Connections.Add(new Connection("183", "177"));
mapTemplate.Connections.Add(new Connection("184", "186"));
mapTemplate.Connections.Add(new Connection("184", "185"));
mapTemplate.Connections.Add(new Connection("184", "183"));
mapTemplate.Connections.Add(new Connection("184", "182"));
mapTemplate.Connections.Add(new Connection("185", "188"));
mapTemplate.Connections.Add(new Connection("185", "187"));
mapTemplate.Connections.Add(new Connection("185", "186"));
mapTemplate.Connections.Add(new Connection("185", "181"));
mapTemplate.Connections.Add(new Connection("185", "184"));
mapTemplate.Connections.Add(new Connection("185", "183"));
mapTemplate.Connections.Add(new Connection("186", "27"));
mapTemplate.Connections.Add(new Connection("186", "187"));
mapTemplate.Connections.Add(new Connection("186", "185"));
mapTemplate.Connections.Add(new Connection("186", "184"));
mapTemplate.Connections.Add(new Connection("187", "27"));
mapTemplate.Connections.Add(new Connection("187", "188"));
mapTemplate.Connections.Add(new Connection("187", "185"));
mapTemplate.Connections.Add(new Connection("187", "186"));
mapTemplate.Connections.Add(new Connection("188", "187"));
mapTemplate.Connections.Add(new Connection("188", "181"));
mapTemplate.Connections.Add(new Connection("188", "185"));
mapTemplate.Connections.Add(new Connection("189", "190"));
mapTemplate.Connections.Add(new Connection("189", "194"));
mapTemplate.Connections.Add(new Connection("189", "159"));
mapTemplate.Connections.Add(new Connection("190", "191"));
mapTemplate.Connections.Add(new Connection("190", "194"));
mapTemplate.Connections.Add(new Connection("190", "189"));
mapTemplate.Connections.Add(new Connection("191", "157"));
mapTemplate.Connections.Add(new Connection("191", "192"));
mapTemplate.Connections.Add(new Connection("191", "193"));
mapTemplate.Connections.Add(new Connection("191", "156"));
mapTemplate.Connections.Add(new Connection("191", "190"));
mapTemplate.Connections.Add(new Connection("191", "194"));
mapTemplate.Connections.Add(new Connection("192", "193"));
mapTemplate.Connections.Add(new Connection("192", "157"));
mapTemplate.Connections.Add(new Connection("192", "191"));
mapTemplate.Connections.Add(new Connection("193", "161"));
mapTemplate.Connections.Add(new Connection("193", "192"));
mapTemplate.Connections.Add(new Connection("193", "160"));
mapTemplate.Connections.Add(new Connection("193", "191"));
mapTemplate.Connections.Add(new Connection("193", "194"));
mapTemplate.Connections.Add(new Connection("194", "191"));
mapTemplate.Connections.Add(new Connection("194", "160"));
mapTemplate.Connections.Add(new Connection("194", "190"));
mapTemplate.Connections.Add(new Connection("194", "189"));
mapTemplate.Connections.Add(new Connection("194", "193"));
mapTemplate.Connections.Add(new Connection("194", "159"));
mapTemplate.Connections.Add(new Connection("195", "84"));
mapTemplate.Connections.Add(new Connection("195", "83"));
mapTemplate.Connections.Add(new Connection("195", "85"));
mapTemplate.Connections.Add(new Connection("195", "88"));
mapTemplate.Connections.Add(new Connection("195", "89"));

            return mapTemplate;
		}
    }
}

