
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate erfurt()
        {

var mapTemplate = new MapTemplate("erfurt") { Image = "erfurt.jpg" };
var country1 = new CountryTemplate("1", "Sto I") { X = 1183, Y = 128 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Sto II") { X = 1263, Y = 127 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Sto III") { X = 1247, Y = 232 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Sto IV") { X = 1097, Y = 318 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Sto V") { X = 1270, Y = 321 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Sto VI") { X = 1381, Y = 259 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Sto VII") { X = 1167, Y = 419 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Abfahrt Schw") { X = 1457, Y = 349 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Schw II") { X = 1439, Y = 411 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Schw I") { X = 1330, Y = 412 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Schw III") { X = 1264, Y = 494 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Schw IV") { X = 1379, Y = 501 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "T�t I") { X = 1533, Y = 543 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "T�t II") { X = 1493, Y = 575 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "T�t III") { X = 1558, Y = 649 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Ker I") { X = 1361, Y = 617 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Ker II") { X = 1309, Y = 717 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Ker III") { X = 1404, Y = 675 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Ker IV") { X = 1483, Y = 696 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Ker VII") { X = 1571, Y = 762 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Ker VI") { X = 1470, Y = 777 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Ker V") { X = 1366, Y = 784 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Sul") { X = 1111, Y = 536 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Hoh I") { X = 1085, Y = 580 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Hoh II") { X = 1177, Y = 590 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Hoh III") { X = 1062, Y = 661 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Hoh IV") { X = 1183, Y = 689 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Hoh V") { X = 1180, Y = 745 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Rot 2") { X = 999, Y = 633 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Rot 3") { X = 893, Y = 693 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Rot 4") { X = 907, Y = 737 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Rot 5") { X = 955, Y = 728 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Rot 6") { X = 1060, Y = 842 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Ilv I") { X = 1074, Y = 743 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Ilv II") { X = 1005, Y = 822 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "And I") { X = 914, Y = 826 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "And II") { X = 944, Y = 887 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "And III") { X = 948, Y = 968 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Joh I") { X = 1061, Y = 895 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Joh II") { X = 1135, Y = 858 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Joh III") { X = 1252, Y = 823 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Kr� ") { X = 1120, Y = 942 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Kr� II") { X = 1258, Y = 900 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Kr� III") { X = 1196, Y = 998 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Kr� IV") { X = 1278, Y = 990 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Azm I") { X = 1435, Y = 854 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Azm III") { X = 1437, Y = 903 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Azm II") { X = 1570, Y = 882 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Vie I") { X = 1634, Y = 792 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Vie II") { X = 1764, Y = 793 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Vie III") { X = 1853, Y = 876 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Vie IV") { X = 1767, Y = 884 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Wal I") { X = 1766, Y = 695 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Wal II") { X = 1820, Y = 719 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Hoc I") { X = 1691, Y = 922 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Hoc II") { X = 1772, Y = 974 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Hoc III") { X = 1656, Y = 1006 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Lin I") { X = 1385, Y = 957 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Lin II") { X = 1444, Y = 985 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Lin III") { X = 1518, Y = 957 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Lin IV") { X = 1450, Y = 1047 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "B�s I") { X = 1567, Y = 1040 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "B�s II") { X = 1633, Y = 1119 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "B�s III") { X = 1534, Y = 1152 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "B�s IV") { X = 1599, Y = 1236 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Urb I") { X = 1404, Y = 1094 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Urb II") { X = 1460, Y = 1167 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Urb III") { X = 1420, Y = 1206 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Nie I") { X = 1498, Y = 1273 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Nie II") { X = 1544, Y = 1353 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Roh I") { X = 1662, Y = 1335 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Nie III") { X = 1568, Y = 1423 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Roh II") { X = 1704, Y = 1433 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Abfahrt Roh") { X = 1767, Y = 1432 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Dit I") { X = 1264, Y = 1093 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Dit II") { X = 1327, Y = 1144 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Dab I") { X = 1144, Y = 1068 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Dab II") { X = 1167, Y = 1137 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Dab III") { X = 1220, Y = 1067 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Dab IV") { X = 1339, Y = 1048 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Her I") { X = 1227, Y = 1158 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Her II") { X = 1311, Y = 1216 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Her III") { X = 1390, Y = 1255 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Wie") { X = 1234, Y = 1263 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Mel I") { X = 1203, Y = 1309 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Mel II") { X = 1315, Y = 1283 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Mel IV") { X = 1206, Y = 1392 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Mel III") { X = 1290, Y = 1374 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Win I") { X = 1424, Y = 1319 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Win II") { X = 1462, Y = 1408 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Egs I") { X = 1148, Y = 1460 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Egs II") { X = 1351, Y = 1468 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Egs III") { X = 1169, Y = 1593 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Egs IV") { X = 1298, Y = 1586 };
mapTemplate.Countries.Add(country94);
var country95 = new CountryTemplate("95", "Egs V") { X = 1436, Y = 1524 };
mapTemplate.Countries.Add(country95);
var country96 = new CountryTemplate("96", "Abfahrt Egs") { X = 1230, Y = 1629 };
mapTemplate.Countries.Add(country96);
var country97 = new CountryTemplate("97", "L�b I") { X = 980, Y = 1179 };
mapTemplate.Countries.Add(country97);
var country98 = new CountryTemplate("98", "L�b II") { X = 1074, Y = 1135 };
mapTemplate.Countries.Add(country98);
var country99 = new CountryTemplate("99", "L�b III") { X = 1092, Y = 1211 };
mapTemplate.Countries.Add(country99);
var country100 = new CountryTemplate("100", "L�b IV") { X = 1009, Y = 1305 };
mapTemplate.Countries.Add(country100);
var country101 = new CountryTemplate("101", "L�b VI") { X = 1102, Y = 1330 };
mapTemplate.Countries.Add(country101);
var country102 = new CountryTemplate("102", "L�b VII") { X = 1062, Y = 1383 };
mapTemplate.Countries.Add(country102);
var country103 = new CountryTemplate("103", "L�b V") { X = 933, Y = 1318 };
mapTemplate.Countries.Add(country103);
var country104 = new CountryTemplate("104", "Hoch I") { X = 802, Y = 1211 };
mapTemplate.Countries.Add(country104);
var country105 = new CountryTemplate("105", "Hoch II") { X = 882, Y = 1210 };
mapTemplate.Countries.Add(country105);
var country106 = new CountryTemplate("106", "Alt I") { X = 1044, Y = 956 };
mapTemplate.Countries.Add(country106);
var country107 = new CountryTemplate("107", "Alt II") { X = 989, Y = 997 };
mapTemplate.Countries.Add(country107);
var country108 = new CountryTemplate("108", "Alt III") { X = 1023, Y = 1054 };
mapTemplate.Countries.Add(country108);
var country109 = new CountryTemplate("109", "Br� I") { X = 830, Y = 950 };
mapTemplate.Countries.Add(country109);
var country110 = new CountryTemplate("110", "Br� II") { X = 803, Y = 1024 };
mapTemplate.Countries.Add(country110);
var country111 = new CountryTemplate("111", "Br� III") { X = 844, Y = 1088 };
mapTemplate.Countries.Add(country111);
var country112 = new CountryTemplate("112", "Br� IV") { X = 891, Y = 1025 };
mapTemplate.Countries.Add(country112);
var country113 = new CountryTemplate("113", "Mar I") { X = 692, Y = 843 };
mapTemplate.Countries.Add(country113);
var country114 = new CountryTemplate("114", "Mar II") { X = 824, Y = 794 };
mapTemplate.Countries.Add(country114);
var country115 = new CountryTemplate("115", "Mar III") { X = 745, Y = 907 };
mapTemplate.Countries.Add(country115);
var country116 = new CountryTemplate("116", "Abfahrt Mar") { X = 884, Y = 880 };
mapTemplate.Countries.Add(country116);
var country117 = new CountryTemplate("117", "Walt I") { X = 1043, Y = 1524 };
mapTemplate.Countries.Add(country117);
var country118 = new CountryTemplate("118", "Walt II") { X = 930, Y = 1609 };
mapTemplate.Countries.Add(country118);
var country119 = new CountryTemplate("119", "Walt III") { X = 1047, Y = 1617 };
mapTemplate.Countries.Add(country119);
var country120 = new CountryTemplate("120", "M�b I") { X = 764, Y = 1581 };
mapTemplate.Countries.Add(country120);
var country121 = new CountryTemplate("121", "M�b II") { X = 855, Y = 1568 };
mapTemplate.Countries.Add(country121);
var country122 = new CountryTemplate("122", "M�b III") { X = 959, Y = 1444 };
mapTemplate.Countries.Add(country122);
var country123 = new CountryTemplate("123", "Ste I") { X = 806, Y = 1322 };
mapTemplate.Countries.Add(country123);
var country124 = new CountryTemplate("124", "Ste II") { X = 684, Y = 1386 };
mapTemplate.Countries.Add(country124);
var country125 = new CountryTemplate("125", "Ste III") { X = 720, Y = 1464 };
mapTemplate.Countries.Add(country125);
var country126 = new CountryTemplate("126", "Ste IV") { X = 808, Y = 1428 };
mapTemplate.Countries.Add(country126);
var country127 = new CountryTemplate("127", "Mol I") { X = 502, Y = 1708 };
mapTemplate.Countries.Add(country127);
var country128 = new CountryTemplate("128", "Mol II") { X = 576, Y = 1668 };
mapTemplate.Countries.Add(country128);
var country129 = new CountryTemplate("129", "Mol III") { X = 639, Y = 1603 };
mapTemplate.Countries.Add(country129);
var country130 = new CountryTemplate("130", "Mol IV") { X = 702, Y = 1659 };
mapTemplate.Countries.Add(country130);
var country131 = new CountryTemplate("131", "Mol V") { X = 644, Y = 1726 };
mapTemplate.Countries.Add(country131);
var country132 = new CountryTemplate("132", "Abfahrt Mol") { X = 559, Y = 1748 };
mapTemplate.Countries.Add(country132);
var country133 = new CountryTemplate("133", "Schm I") { X = 688, Y = 1183 };
mapTemplate.Countries.Add(country133);
var country134 = new CountryTemplate("134", "Schm II") { X = 585, Y = 1248 };
mapTemplate.Countries.Add(country134);
var country135 = new CountryTemplate("135", "Schm III") { X = 681, Y = 1299 };
mapTemplate.Countries.Add(country135);
var country136 = new CountryTemplate("136", "Abfahrt Schm") { X = 594, Y = 1308 };
mapTemplate.Countries.Add(country136);
var country137 = new CountryTemplate("137", "Bin I") { X = 539, Y = 1011 };
mapTemplate.Countries.Add(country137);
var country138 = new CountryTemplate("138", "Bin II") { X = 663, Y = 1004 };
mapTemplate.Countries.Add(country138);
var country139 = new CountryTemplate("139", "Bin III") { X = 557, Y = 1123 };
mapTemplate.Countries.Add(country139);
var country140 = new CountryTemplate("140", "Fri I") { X = 302, Y = 1158 };
mapTemplate.Countries.Add(country140);
var country141 = new CountryTemplate("141", "Fri II") { X = 443, Y = 1139 };
mapTemplate.Countries.Add(country141);
var country142 = new CountryTemplate("142", "Fri III") { X = 362, Y = 1210 };
mapTemplate.Countries.Add(country142);
var country143 = new CountryTemplate("143", "Fri IV") { X = 313, Y = 1276 };
mapTemplate.Countries.Add(country143);
var country144 = new CountryTemplate("144", "Fri V") { X = 409, Y = 1269 };
mapTemplate.Countries.Add(country144);
var country145 = new CountryTemplate("145", "Got I") { X = 314, Y = 1022 };
mapTemplate.Countries.Add(country145);
var country146 = new CountryTemplate("146", "Gto II") { X = 379, Y = 1069 };
mapTemplate.Countries.Add(country146);
var country147 = new CountryTemplate("147", "Erm I") { X = 216, Y = 992 };
mapTemplate.Countries.Add(country147);
var country148 = new CountryTemplate("148", "Erm II") { X = 120, Y = 1044 };
mapTemplate.Countries.Add(country148);
var country149 = new CountryTemplate("149", "Erm III") { X = 240, Y = 1095 };
mapTemplate.Countries.Add(country149);
var country150 = new CountryTemplate("150", "Ala I") { X = 344, Y = 805 };
mapTemplate.Countries.Add(country150);
var country151 = new CountryTemplate("151", "Ala II") { X = 514, Y = 838 };
mapTemplate.Countries.Add(country151);
var country152 = new CountryTemplate("152", "Ala III") { X = 315, Y = 914 };
mapTemplate.Countries.Add(country152);
var country153 = new CountryTemplate("153", "Ala IV") { X = 431, Y = 937 };
mapTemplate.Countries.Add(country153);
var country154 = new CountryTemplate("154", "Abfahrt Ala") { X = 351, Y = 853 };
mapTemplate.Countries.Add(country154);
var country155 = new CountryTemplate("155", "T�tt II") { X = 158, Y = 607 };
mapTemplate.Countries.Add(country155);
var country156 = new CountryTemplate("156", "T�tt I") { X = 73, Y = 611 };
mapTemplate.Countries.Add(country156);
var country157 = new CountryTemplate("157", "T�tt III") { X = 121, Y = 697 };
mapTemplate.Countries.Add(country157);
var country158 = new CountryTemplate("158", "T�tt IV") { X = 247, Y = 678 };
mapTemplate.Countries.Add(country158);
var country159 = new CountryTemplate("159", "T�tt V") { X = 258, Y = 768 };
mapTemplate.Countries.Add(country159);
var country160 = new CountryTemplate("160", "T�tt VI") { X = 326, Y = 718 };
mapTemplate.Countries.Add(country160);
var country161 = new CountryTemplate("161", "Scha ") { X = 437, Y = 675 };
mapTemplate.Countries.Add(country161);
var country162 = new CountryTemplate("162", "Tie I") { X = 564, Y = 535 };
mapTemplate.Countries.Add(country162);
var country163 = new CountryTemplate("163", "Tie II") { X = 510, Y = 651 };
mapTemplate.Countries.Add(country163);
var country164 = new CountryTemplate("164", "Tie III") { X = 608, Y = 647 };
mapTemplate.Countries.Add(country164);
var country165 = new CountryTemplate("165", "Sal I") { X = 533, Y = 727 };
mapTemplate.Countries.Add(country165);
var country166 = new CountryTemplate("166", "Sal II") { X = 656, Y = 731 };
mapTemplate.Countries.Add(country166);
var country167 = new CountryTemplate("167", "Sal III") { X = 611, Y = 820 };
mapTemplate.Countries.Add(country167);
var country168 = new CountryTemplate("168", "Gis I") { X = 791, Y = 550 };
mapTemplate.Countries.Add(country168);
var country169 = new CountryTemplate("169", "Gis II") { X = 886, Y = 554 };
mapTemplate.Countries.Add(country169);
var country170 = new CountryTemplate("170", "Gis IV") { X = 866, Y = 628 };
mapTemplate.Countries.Add(country170);
var country171 = new CountryTemplate("171", "Gis III") { X = 753, Y = 642 };
mapTemplate.Countries.Add(country171);
var country172 = new CountryTemplate("172", "Gis V") { X = 790, Y = 722 };
mapTemplate.Countries.Add(country172);
var country173 = new CountryTemplate("173", "K�h I") { X = 748, Y = 443 };
mapTemplate.Countries.Add(country173);
var country174 = new CountryTemplate("174", "K�h II") { X = 675, Y = 519 };
mapTemplate.Countries.Add(country174);
var country175 = new CountryTemplate("175", "Mit I") { X = 788, Y = 224 };
mapTemplate.Countries.Add(country175);
var country176 = new CountryTemplate("176", "Mit II") { X = 906, Y = 287 };
mapTemplate.Countries.Add(country176);
var country177 = new CountryTemplate("177", "Mit III") { X = 993, Y = 277 };
mapTemplate.Countries.Add(country177);
var country178 = new CountryTemplate("178", "Mit IV") { X = 877, Y = 398 };
mapTemplate.Countries.Add(country178);
var country179 = new CountryTemplate("179", "Mit V") { X = 938, Y = 449 };
mapTemplate.Countries.Add(country179);
var country180 = new CountryTemplate("180", "Mit VI") { X = 1004, Y = 391 };
mapTemplate.Countries.Add(country180);
var country181 = new CountryTemplate("181", "Abfahrt Gis") { X = 868, Y = 493 };
mapTemplate.Countries.Add(country181);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country175);
continent2.Countries.Add(country176);
continent2.Countries.Add(country177);
continent2.Countries.Add(country178);
continent2.Countries.Add(country179);
continent2.Countries.Add(country180);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
continent4.Countries.Add(country28);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country23);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country13);
continent6.Countries.Add(country14);
continent6.Countries.Add(country15);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country16);
continent7.Countries.Add(country17);
continent7.Countries.Add(country18);
continent7.Countries.Add(country19);
continent7.Countries.Add(country20);
continent7.Countries.Add(country21);
continent7.Countries.Add(country22);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country53);
continent8.Countries.Add(country54);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country49);
continent9.Countries.Add(country50);
continent9.Countries.Add(country51);
continent9.Countries.Add(country52);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 2);
continent10.Countries.Add(country46);
continent10.Countries.Add(country47);
continent10.Countries.Add(country48);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 2);
continent11.Countries.Add(country55);
continent11.Countries.Add(country56);
continent11.Countries.Add(country57);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 3);
continent12.Countries.Add(country62);
continent12.Countries.Add(country63);
continent12.Countries.Add(country64);
continent12.Countries.Add(country65);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 3);
continent13.Countries.Add(country58);
continent13.Countries.Add(country59);
continent13.Countries.Add(country60);
continent13.Countries.Add(country61);
mapTemplate.Continents.Add(continent13);
var continent14 = new Continent("14", 3);
continent14.Countries.Add(country42);
continent14.Countries.Add(country43);
continent14.Countries.Add(country44);
continent14.Countries.Add(country45);
mapTemplate.Continents.Add(continent14);
var continent15 = new Continent("15", 2);
continent15.Countries.Add(country39);
continent15.Countries.Add(country40);
continent15.Countries.Add(country41);
mapTemplate.Continents.Add(continent15);
var continent16 = new Continent("16", 2);
continent16.Countries.Add(country66);
continent16.Countries.Add(country67);
continent16.Countries.Add(country68);
mapTemplate.Continents.Add(continent16);
var continent17 = new Continent("17", 1);
continent17.Countries.Add(country75);
continent17.Countries.Add(country76);
mapTemplate.Continents.Add(continent17);
var continent18 = new Continent("18", 2);
continent18.Countries.Add(country81);
continent18.Countries.Add(country82);
continent18.Countries.Add(country83);
mapTemplate.Continents.Add(continent18);
var continent19 = new Continent("19", 2);
continent19.Countries.Add(country69);
continent19.Countries.Add(country70);
continent19.Countries.Add(country72);
mapTemplate.Continents.Add(continent19);
var continent20 = new Continent("20", 1);
continent20.Countries.Add(country89);
continent20.Countries.Add(country90);
mapTemplate.Continents.Add(continent20);
var continent21 = new Continent("21", 1);
continent21.Countries.Add(country71);
continent21.Countries.Add(country73);
mapTemplate.Continents.Add(continent21);
var continent22 = new Continent("22", 3);
continent22.Countries.Add(country85);
continent22.Countries.Add(country86);
continent22.Countries.Add(country87);
continent22.Countries.Add(country88);
mapTemplate.Continents.Add(continent22);
var continent23 = new Continent("23", 1);
continent23.Countries.Add(country84);
mapTemplate.Continents.Add(continent23);
var continent24 = new Continent("24", 4);
continent24.Countries.Add(country91);
continent24.Countries.Add(country92);
continent24.Countries.Add(country93);
continent24.Countries.Add(country94);
continent24.Countries.Add(country95);
mapTemplate.Continents.Add(continent24);
var continent25 = new Continent("25", 1);
continent25.Countries.Add(country104);
continent25.Countries.Add(country105);
mapTemplate.Continents.Add(continent25);
var continent26 = new Continent("26", 2);
continent26.Countries.Add(country133);
continent26.Countries.Add(country134);
continent26.Countries.Add(country135);
mapTemplate.Continents.Add(continent26);
var continent27 = new Continent("27", 3);
continent27.Countries.Add(country123);
continent27.Countries.Add(country124);
continent27.Countries.Add(country125);
continent27.Countries.Add(country126);
mapTemplate.Continents.Add(continent27);
var continent28 = new Continent("28", 2);
continent28.Countries.Add(country120);
continent28.Countries.Add(country121);
continent28.Countries.Add(country122);
mapTemplate.Continents.Add(continent28);
var continent29 = new Continent("29", 2);
continent29.Countries.Add(country117);
continent29.Countries.Add(country118);
continent29.Countries.Add(country119);
mapTemplate.Continents.Add(continent29);
var continent30 = new Continent("30", 4);
continent30.Countries.Add(country127);
continent30.Countries.Add(country128);
continent30.Countries.Add(country129);
continent30.Countries.Add(country130);
continent30.Countries.Add(country131);
mapTemplate.Continents.Add(continent30);
var continent31 = new Continent("31", 3);
continent31.Countries.Add(country106);
continent31.Countries.Add(country107);
continent31.Countries.Add(country108);
mapTemplate.Continents.Add(continent31);
var continent32 = new Continent("32", 3);
continent32.Countries.Add(country109);
continent32.Countries.Add(country110);
continent32.Countries.Add(country111);
continent32.Countries.Add(country112);
mapTemplate.Continents.Add(continent32);
var continent33 = new Continent("33", 2);
continent33.Countries.Add(country137);
continent33.Countries.Add(country138);
continent33.Countries.Add(country139);
mapTemplate.Continents.Add(continent33);
var continent34 = new Continent("34", 2);
continent34.Countries.Add(country113);
continent34.Countries.Add(country114);
continent34.Countries.Add(country115);
mapTemplate.Continents.Add(continent34);
var continent35 = new Continent("35", 1);
continent35.Countries.Add(country34);
continent35.Countries.Add(country35);
mapTemplate.Continents.Add(continent35);
var continent36 = new Continent("36", 1);
continent36.Countries.Add(country173);
continent36.Countries.Add(country174);
mapTemplate.Continents.Add(continent36);
var continent37 = new Continent("37", 4);
continent37.Countries.Add(country168);
continent37.Countries.Add(country169);
continent37.Countries.Add(country170);
continent37.Countries.Add(country171);
continent37.Countries.Add(country172);
mapTemplate.Continents.Add(continent37);
var continent38 = new Continent("38", 2);
continent38.Countries.Add(country162);
continent38.Countries.Add(country163);
continent38.Countries.Add(country164);
mapTemplate.Continents.Add(continent38);
var continent39 = new Continent("39", 2);
continent39.Countries.Add(country165);
continent39.Countries.Add(country166);
continent39.Countries.Add(country167);
mapTemplate.Continents.Add(continent39);
var continent40 = new Continent("40", 4);
continent40.Countries.Add(country29);
continent40.Countries.Add(country30);
continent40.Countries.Add(country31);
continent40.Countries.Add(country32);
continent40.Countries.Add(country33);
mapTemplate.Continents.Add(continent40);
var continent41 = new Continent("41", 3);
continent41.Countries.Add(country155);
continent41.Countries.Add(country156);
continent41.Countries.Add(country157);
continent41.Countries.Add(country158);
continent41.Countries.Add(country159);
continent41.Countries.Add(country160);
mapTemplate.Continents.Add(continent41);
var continent42 = new Continent("42", 1);
continent42.Countries.Add(country161);
mapTemplate.Continents.Add(continent42);
var continent43 = new Continent("43", 3);
continent43.Countries.Add(country150);
continent43.Countries.Add(country151);
continent43.Countries.Add(country152);
continent43.Countries.Add(country153);
mapTemplate.Continents.Add(continent43);
var continent44 = new Continent("44", 1);
continent44.Countries.Add(country145);
continent44.Countries.Add(country146);
mapTemplate.Continents.Add(continent44);
var continent45 = new Continent("45", 2);
continent45.Countries.Add(country147);
continent45.Countries.Add(country148);
continent45.Countries.Add(country149);
mapTemplate.Continents.Add(continent45);
var continent46 = new Continent("46", 3);
continent46.Countries.Add(country140);
continent46.Countries.Add(country141);
continent46.Countries.Add(country142);
continent46.Countries.Add(country143);
continent46.Countries.Add(country144);
mapTemplate.Continents.Add(continent46);
var continent47 = new Continent("47", 4);
continent47.Countries.Add(country8);
continent47.Countries.Add(country74);
continent47.Countries.Add(country96);
continent47.Countries.Add(country116);
continent47.Countries.Add(country132);
continent47.Countries.Add(country136);
continent47.Countries.Add(country154);
continent47.Countries.Add(country181);
mapTemplate.Continents.Add(continent47);
var continent48 = new Continent("48", 2);
continent48.Countries.Add(country36);
continent48.Countries.Add(country37);
continent48.Countries.Add(country38);
mapTemplate.Continents.Add(continent48);
var continent49 = new Continent("49", 3);
continent49.Countries.Add(country77);
continent49.Countries.Add(country78);
continent49.Countries.Add(country79);
continent49.Countries.Add(country80);
mapTemplate.Continents.Add(continent49);
var continent50 = new Continent("50", 5);
continent50.Countries.Add(country97);
continent50.Countries.Add(country98);
continent50.Countries.Add(country99);
continent50.Countries.Add(country100);
continent50.Countries.Add(country101);
continent50.Countries.Add(country102);
continent50.Countries.Add(country103);
mapTemplate.Continents.Add(continent50);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "177"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "6"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "26"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("4", "177"));
mapTemplate.Connections.Add(new Connection("4", "180"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "10"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("6", "2"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "23"));
mapTemplate.Connections.Add(new Connection("7", "24"));
mapTemplate.Connections.Add(new Connection("7", "25"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "180"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "181"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "13"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "5"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "25"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "25"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("13", "9"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("14", "18"));
mapTemplate.Connections.Add(new Connection("14", "19"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "19"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "20"));
mapTemplate.Connections.Add(new Connection("15", "42"));
mapTemplate.Connections.Add(new Connection("15", "56"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "25"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "25"));
mapTemplate.Connections.Add(new Connection("17", "27"));
mapTemplate.Connections.Add(new Connection("17", "28"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "41"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "14"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "14"));
mapTemplate.Connections.Add(new Connection("19", "15"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "15"));
mapTemplate.Connections.Add(new Connection("20", "49"));
mapTemplate.Connections.Add(new Connection("20", "48"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "48"));
mapTemplate.Connections.Add(new Connection("21", "46"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "46"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "41"));
mapTemplate.Connections.Add(new Connection("23", "7"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("24", "7"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "169"));
mapTemplate.Connections.Add(new Connection("24", "180"));
mapTemplate.Connections.Add(new Connection("24", "29"));
mapTemplate.Connections.Add(new Connection("25", "7"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "11"));
mapTemplate.Connections.Add(new Connection("25", "12"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "16"));
mapTemplate.Connections.Add(new Connection("25", "17"));
mapTemplate.Connections.Add(new Connection("26", "3"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "34"));
mapTemplate.Connections.Add(new Connection("26", "170"));
mapTemplate.Connections.Add(new Connection("26", "42"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "17"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "34"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "17"));
mapTemplate.Connections.Add(new Connection("28", "40"));
mapTemplate.Connections.Add(new Connection("28", "41"));
mapTemplate.Connections.Add(new Connection("28", "34"));
mapTemplate.Connections.Add(new Connection("29", "170"));
mapTemplate.Connections.Add(new Connection("29", "169"));
mapTemplate.Connections.Add(new Connection("29", "24"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "170"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "172"));
mapTemplate.Connections.Add(new Connection("30", "171"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "36"));
mapTemplate.Connections.Add(new Connection("31", "172"));
mapTemplate.Connections.Add(new Connection("32", "170"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "34"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "36"));
mapTemplate.Connections.Add(new Connection("33", "39"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "40"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "40"));
mapTemplate.Connections.Add(new Connection("34", "28"));
mapTemplate.Connections.Add(new Connection("34", "27"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "26"));
mapTemplate.Connections.Add(new Connection("34", "32"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("35", "39"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "32"));
mapTemplate.Connections.Add(new Connection("36", "31"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "114"));
mapTemplate.Connections.Add(new Connection("36", "172"));
mapTemplate.Connections.Add(new Connection("37", "106"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "35"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "116"));
mapTemplate.Connections.Add(new Connection("37", "109"));
mapTemplate.Connections.Add(new Connection("37", "114"));
mapTemplate.Connections.Add(new Connection("38", "112"));
mapTemplate.Connections.Add(new Connection("38", "109"));
mapTemplate.Connections.Add(new Connection("38", "107"));
mapTemplate.Connections.Add(new Connection("38", "106"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("39", "106"));
mapTemplate.Connections.Add(new Connection("39", "42"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "35"));
mapTemplate.Connections.Add(new Connection("39", "33"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "42"));
mapTemplate.Connections.Add(new Connection("40", "43"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "28"));
mapTemplate.Connections.Add(new Connection("40", "33"));
mapTemplate.Connections.Add(new Connection("40", "34"));
mapTemplate.Connections.Add(new Connection("41", "22"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "28"));
mapTemplate.Connections.Add(new Connection("41", "17"));
mapTemplate.Connections.Add(new Connection("42", "15"));
mapTemplate.Connections.Add(new Connection("42", "106"));
mapTemplate.Connections.Add(new Connection("42", "44"));
mapTemplate.Connections.Add(new Connection("42", "39"));
mapTemplate.Connections.Add(new Connection("42", "40"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "112"));
mapTemplate.Connections.Add(new Connection("42", "95"));
mapTemplate.Connections.Add(new Connection("42", "26"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "47"));
mapTemplate.Connections.Add(new Connection("43", "45"));
mapTemplate.Connections.Add(new Connection("43", "40"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("44", "106"));
mapTemplate.Connections.Add(new Connection("44", "42"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "77"));
mapTemplate.Connections.Add(new Connection("44", "79"));
mapTemplate.Connections.Add(new Connection("45", "43"));
mapTemplate.Connections.Add(new Connection("45", "58"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "80"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "79"));
mapTemplate.Connections.Add(new Connection("46", "21"));
mapTemplate.Connections.Add(new Connection("46", "22"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "60"));
mapTemplate.Connections.Add(new Connection("47", "59"));
mapTemplate.Connections.Add(new Connection("47", "58"));
mapTemplate.Connections.Add(new Connection("47", "43"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("48", "52"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "55"));
mapTemplate.Connections.Add(new Connection("48", "60"));
mapTemplate.Connections.Add(new Connection("48", "20"));
mapTemplate.Connections.Add(new Connection("48", "21"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "53"));
mapTemplate.Connections.Add(new Connection("49", "20"));
mapTemplate.Connections.Add(new Connection("49", "52"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("50", "52"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("52", "55"));
mapTemplate.Connections.Add(new Connection("52", "56"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "50"));
mapTemplate.Connections.Add(new Connection("52", "49"));
mapTemplate.Connections.Add(new Connection("52", "48"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "49"));
mapTemplate.Connections.Add(new Connection("54", "50"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("55", "60"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "52"));
mapTemplate.Connections.Add(new Connection("55", "48"));
mapTemplate.Connections.Add(new Connection("56", "15"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "52"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("57", "62"));
mapTemplate.Connections.Add(new Connection("57", "63"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "47"));
mapTemplate.Connections.Add(new Connection("58", "45"));
mapTemplate.Connections.Add(new Connection("58", "80"));
mapTemplate.Connections.Add(new Connection("59", "47"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "80"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("59", "66"));
mapTemplate.Connections.Add(new Connection("60", "48"));
mapTemplate.Connections.Add(new Connection("60", "55"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("60", "62"));
mapTemplate.Connections.Add(new Connection("60", "47"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "66"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("62", "57"));
mapTemplate.Connections.Add(new Connection("62", "60"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "66"));
mapTemplate.Connections.Add(new Connection("62", "64"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "57"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("63", "65"));
mapTemplate.Connections.Add(new Connection("64", "66"));
mapTemplate.Connections.Add(new Connection("64", "67"));
mapTemplate.Connections.Add(new Connection("64", "62"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("64", "69"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "63"));
mapTemplate.Connections.Add(new Connection("65", "69"));
mapTemplate.Connections.Add(new Connection("65", "71"));
mapTemplate.Connections.Add(new Connection("66", "80"));
mapTemplate.Connections.Add(new Connection("66", "76"));
mapTemplate.Connections.Add(new Connection("66", "61"));
mapTemplate.Connections.Add(new Connection("66", "59"));
mapTemplate.Connections.Add(new Connection("66", "62"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "64"));
mapTemplate.Connections.Add(new Connection("67", "83"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "76"));
mapTemplate.Connections.Add(new Connection("67", "69"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "64"));
mapTemplate.Connections.Add(new Connection("68", "76"));
mapTemplate.Connections.Add(new Connection("68", "83"));
mapTemplate.Connections.Add(new Connection("68", "82"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("69", "83"));
mapTemplate.Connections.Add(new Connection("69", "67"));
mapTemplate.Connections.Add(new Connection("69", "89"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "65"));
mapTemplate.Connections.Add(new Connection("69", "64"));
mapTemplate.Connections.Add(new Connection("69", "71"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "89"));
mapTemplate.Connections.Add(new Connection("70", "90"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("71", "65"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("71", "72"));
mapTemplate.Connections.Add(new Connection("71", "73"));
mapTemplate.Connections.Add(new Connection("71", "69"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("72", "90"));
mapTemplate.Connections.Add(new Connection("72", "71"));
mapTemplate.Connections.Add(new Connection("73", "71"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "96"));
mapTemplate.Connections.Add(new Connection("75", "80"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("75", "81"));
mapTemplate.Connections.Add(new Connection("75", "79"));
mapTemplate.Connections.Add(new Connection("76", "66"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "80"));
mapTemplate.Connections.Add(new Connection("76", "67"));
mapTemplate.Connections.Add(new Connection("76", "68"));
mapTemplate.Connections.Add(new Connection("76", "82"));
mapTemplate.Connections.Add(new Connection("76", "81"));
mapTemplate.Connections.Add(new Connection("77", "98"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("77", "79"));
mapTemplate.Connections.Add(new Connection("77", "108"));
mapTemplate.Connections.Add(new Connection("77", "106"));
mapTemplate.Connections.Add(new Connection("77", "44"));
mapTemplate.Connections.Add(new Connection("78", "85"));
mapTemplate.Connections.Add(new Connection("78", "81"));
mapTemplate.Connections.Add(new Connection("78", "99"));
mapTemplate.Connections.Add(new Connection("78", "98"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("79", "77"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("79", "81"));
mapTemplate.Connections.Add(new Connection("79", "75"));
mapTemplate.Connections.Add(new Connection("79", "80"));
mapTemplate.Connections.Add(new Connection("79", "44"));
mapTemplate.Connections.Add(new Connection("79", "45"));
mapTemplate.Connections.Add(new Connection("80", "45"));
mapTemplate.Connections.Add(new Connection("80", "58"));
mapTemplate.Connections.Add(new Connection("80", "59"));
mapTemplate.Connections.Add(new Connection("80", "66"));
mapTemplate.Connections.Add(new Connection("80", "75"));
mapTemplate.Connections.Add(new Connection("80", "76"));
mapTemplate.Connections.Add(new Connection("80", "79"));
mapTemplate.Connections.Add(new Connection("81", "76"));
mapTemplate.Connections.Add(new Connection("81", "75"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("81", "85"));
mapTemplate.Connections.Add(new Connection("81", "78"));
mapTemplate.Connections.Add(new Connection("81", "79"));
mapTemplate.Connections.Add(new Connection("82", "76"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "68"));
mapTemplate.Connections.Add(new Connection("82", "84"));
mapTemplate.Connections.Add(new Connection("82", "86"));
mapTemplate.Connections.Add(new Connection("82", "85"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "68"));
mapTemplate.Connections.Add(new Connection("83", "86"));
mapTemplate.Connections.Add(new Connection("83", "89"));
mapTemplate.Connections.Add(new Connection("83", "69"));
mapTemplate.Connections.Add(new Connection("83", "67"));
mapTemplate.Connections.Add(new Connection("84", "82"));
mapTemplate.Connections.Add(new Connection("84", "86"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("85", "88"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("85", "87"));
mapTemplate.Connections.Add(new Connection("85", "81"));
mapTemplate.Connections.Add(new Connection("85", "82"));
mapTemplate.Connections.Add(new Connection("85", "78"));
mapTemplate.Connections.Add(new Connection("85", "101"));
mapTemplate.Connections.Add(new Connection("85", "99"));
mapTemplate.Connections.Add(new Connection("86", "84"));
mapTemplate.Connections.Add(new Connection("86", "82"));
mapTemplate.Connections.Add(new Connection("86", "83"));
mapTemplate.Connections.Add(new Connection("86", "89"));
mapTemplate.Connections.Add(new Connection("86", "92"));
mapTemplate.Connections.Add(new Connection("86", "88"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("87", "92"));
mapTemplate.Connections.Add(new Connection("87", "91"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "85"));
mapTemplate.Connections.Add(new Connection("87", "101"));
mapTemplate.Connections.Add(new Connection("88", "92"));
mapTemplate.Connections.Add(new Connection("88", "86"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "85"));
mapTemplate.Connections.Add(new Connection("89", "86"));
mapTemplate.Connections.Add(new Connection("89", "83"));
mapTemplate.Connections.Add(new Connection("89", "90"));
mapTemplate.Connections.Add(new Connection("89", "69"));
mapTemplate.Connections.Add(new Connection("89", "70"));
mapTemplate.Connections.Add(new Connection("89", "92"));
mapTemplate.Connections.Add(new Connection("90", "89"));
mapTemplate.Connections.Add(new Connection("90", "70"));
mapTemplate.Connections.Add(new Connection("90", "92"));
mapTemplate.Connections.Add(new Connection("90", "72"));
mapTemplate.Connections.Add(new Connection("90", "95"));
mapTemplate.Connections.Add(new Connection("91", "93"));
mapTemplate.Connections.Add(new Connection("91", "94"));
mapTemplate.Connections.Add(new Connection("91", "92"));
mapTemplate.Connections.Add(new Connection("91", "87"));
mapTemplate.Connections.Add(new Connection("91", "102"));
mapTemplate.Connections.Add(new Connection("91", "101"));
mapTemplate.Connections.Add(new Connection("91", "117"));
mapTemplate.Connections.Add(new Connection("92", "90"));
mapTemplate.Connections.Add(new Connection("92", "89"));
mapTemplate.Connections.Add(new Connection("92", "86"));
mapTemplate.Connections.Add(new Connection("92", "88"));
mapTemplate.Connections.Add(new Connection("92", "95"));
mapTemplate.Connections.Add(new Connection("92", "94"));
mapTemplate.Connections.Add(new Connection("92", "91"));
mapTemplate.Connections.Add(new Connection("92", "87"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("93", "96"));
mapTemplate.Connections.Add(new Connection("93", "91"));
mapTemplate.Connections.Add(new Connection("93", "117"));
mapTemplate.Connections.Add(new Connection("93", "119"));
mapTemplate.Connections.Add(new Connection("94", "96"));
mapTemplate.Connections.Add(new Connection("94", "95"));
mapTemplate.Connections.Add(new Connection("94", "92"));
mapTemplate.Connections.Add(new Connection("94", "93"));
mapTemplate.Connections.Add(new Connection("94", "91"));
mapTemplate.Connections.Add(new Connection("95", "94"));
mapTemplate.Connections.Add(new Connection("95", "92"));
mapTemplate.Connections.Add(new Connection("95", "90"));
mapTemplate.Connections.Add(new Connection("95", "112"));
mapTemplate.Connections.Add(new Connection("95", "42"));
mapTemplate.Connections.Add(new Connection("96", "74"));
mapTemplate.Connections.Add(new Connection("96", "94"));
mapTemplate.Connections.Add(new Connection("96", "93"));
mapTemplate.Connections.Add(new Connection("96", "132"));
mapTemplate.Connections.Add(new Connection("97", "112"));
mapTemplate.Connections.Add(new Connection("97", "100"));
mapTemplate.Connections.Add(new Connection("97", "99"));
mapTemplate.Connections.Add(new Connection("97", "98"));
mapTemplate.Connections.Add(new Connection("97", "108"));
mapTemplate.Connections.Add(new Connection("97", "105"));
mapTemplate.Connections.Add(new Connection("97", "111"));
mapTemplate.Connections.Add(new Connection("98", "99"));
mapTemplate.Connections.Add(new Connection("98", "78"));
mapTemplate.Connections.Add(new Connection("98", "77"));
mapTemplate.Connections.Add(new Connection("98", "108"));
mapTemplate.Connections.Add(new Connection("98", "97"));
mapTemplate.Connections.Add(new Connection("99", "78"));
mapTemplate.Connections.Add(new Connection("99", "98"));
mapTemplate.Connections.Add(new Connection("99", "101"));
mapTemplate.Connections.Add(new Connection("99", "85"));
mapTemplate.Connections.Add(new Connection("99", "100"));
mapTemplate.Connections.Add(new Connection("99", "97"));
mapTemplate.Connections.Add(new Connection("100", "99"));
mapTemplate.Connections.Add(new Connection("100", "101"));
mapTemplate.Connections.Add(new Connection("100", "102"));
mapTemplate.Connections.Add(new Connection("100", "97"));
mapTemplate.Connections.Add(new Connection("100", "105"));
mapTemplate.Connections.Add(new Connection("100", "103"));
mapTemplate.Connections.Add(new Connection("100", "122"));
mapTemplate.Connections.Add(new Connection("101", "85"));
mapTemplate.Connections.Add(new Connection("101", "99"));
mapTemplate.Connections.Add(new Connection("101", "100"));
mapTemplate.Connections.Add(new Connection("101", "102"));
mapTemplate.Connections.Add(new Connection("101", "91"));
mapTemplate.Connections.Add(new Connection("101", "87"));
mapTemplate.Connections.Add(new Connection("102", "101"));
mapTemplate.Connections.Add(new Connection("102", "91"));
mapTemplate.Connections.Add(new Connection("102", "100"));
mapTemplate.Connections.Add(new Connection("102", "122"));
mapTemplate.Connections.Add(new Connection("102", "117"));
mapTemplate.Connections.Add(new Connection("103", "100"));
mapTemplate.Connections.Add(new Connection("103", "105"));
mapTemplate.Connections.Add(new Connection("103", "122"));
mapTemplate.Connections.Add(new Connection("103", "126"));
mapTemplate.Connections.Add(new Connection("103", "123"));
mapTemplate.Connections.Add(new Connection("104", "105"));
mapTemplate.Connections.Add(new Connection("104", "111"));
mapTemplate.Connections.Add(new Connection("104", "123"));
mapTemplate.Connections.Add(new Connection("104", "135"));
mapTemplate.Connections.Add(new Connection("104", "133"));
mapTemplate.Connections.Add(new Connection("105", "97"));
mapTemplate.Connections.Add(new Connection("105", "111"));
mapTemplate.Connections.Add(new Connection("105", "104"));
mapTemplate.Connections.Add(new Connection("105", "100"));
mapTemplate.Connections.Add(new Connection("105", "103"));
mapTemplate.Connections.Add(new Connection("105", "123"));
mapTemplate.Connections.Add(new Connection("106", "77"));
mapTemplate.Connections.Add(new Connection("106", "42"));
mapTemplate.Connections.Add(new Connection("106", "44"));
mapTemplate.Connections.Add(new Connection("106", "108"));
mapTemplate.Connections.Add(new Connection("106", "39"));
mapTemplate.Connections.Add(new Connection("106", "107"));
mapTemplate.Connections.Add(new Connection("106", "38"));
mapTemplate.Connections.Add(new Connection("106", "37"));
mapTemplate.Connections.Add(new Connection("107", "106"));
mapTemplate.Connections.Add(new Connection("107", "108"));
mapTemplate.Connections.Add(new Connection("107", "112"));
mapTemplate.Connections.Add(new Connection("107", "38"));
mapTemplate.Connections.Add(new Connection("108", "98"));
mapTemplate.Connections.Add(new Connection("108", "77"));
mapTemplate.Connections.Add(new Connection("108", "106"));
mapTemplate.Connections.Add(new Connection("108", "107"));
mapTemplate.Connections.Add(new Connection("108", "112"));
mapTemplate.Connections.Add(new Connection("108", "97"));
mapTemplate.Connections.Add(new Connection("109", "114"));
mapTemplate.Connections.Add(new Connection("109", "38"));
mapTemplate.Connections.Add(new Connection("109", "37"));
mapTemplate.Connections.Add(new Connection("109", "112"));
mapTemplate.Connections.Add(new Connection("109", "115"));
mapTemplate.Connections.Add(new Connection("109", "167"));
mapTemplate.Connections.Add(new Connection("109", "110"));
mapTemplate.Connections.Add(new Connection("109", "138"));
mapTemplate.Connections.Add(new Connection("110", "138"));
mapTemplate.Connections.Add(new Connection("110", "109"));
mapTemplate.Connections.Add(new Connection("110", "133"));
mapTemplate.Connections.Add(new Connection("110", "111"));
mapTemplate.Connections.Add(new Connection("110", "112"));
mapTemplate.Connections.Add(new Connection("110", "139"));
mapTemplate.Connections.Add(new Connection("111", "133"));
mapTemplate.Connections.Add(new Connection("111", "110"));
mapTemplate.Connections.Add(new Connection("111", "112"));
mapTemplate.Connections.Add(new Connection("111", "105"));
mapTemplate.Connections.Add(new Connection("111", "104"));
mapTemplate.Connections.Add(new Connection("111", "97"));
mapTemplate.Connections.Add(new Connection("112", "42"));
mapTemplate.Connections.Add(new Connection("112", "107"));
mapTemplate.Connections.Add(new Connection("112", "38"));
mapTemplate.Connections.Add(new Connection("112", "109"));
mapTemplate.Connections.Add(new Connection("112", "110"));
mapTemplate.Connections.Add(new Connection("112", "111"));
mapTemplate.Connections.Add(new Connection("112", "108"));
mapTemplate.Connections.Add(new Connection("112", "97"));
mapTemplate.Connections.Add(new Connection("112", "125"));
mapTemplate.Connections.Add(new Connection("112", "95"));
mapTemplate.Connections.Add(new Connection("112", "143"));
mapTemplate.Connections.Add(new Connection("113", "166"));
mapTemplate.Connections.Add(new Connection("113", "114"));
mapTemplate.Connections.Add(new Connection("113", "167"));
mapTemplate.Connections.Add(new Connection("113", "115"));
mapTemplate.Connections.Add(new Connection("113", "172"));
mapTemplate.Connections.Add(new Connection("114", "116"));
mapTemplate.Connections.Add(new Connection("114", "109"));
mapTemplate.Connections.Add(new Connection("114", "37"));
mapTemplate.Connections.Add(new Connection("114", "36"));
mapTemplate.Connections.Add(new Connection("114", "172"));
mapTemplate.Connections.Add(new Connection("114", "113"));
mapTemplate.Connections.Add(new Connection("114", "115"));
mapTemplate.Connections.Add(new Connection("115", "167"));
mapTemplate.Connections.Add(new Connection("115", "113"));
mapTemplate.Connections.Add(new Connection("115", "109"));
mapTemplate.Connections.Add(new Connection("115", "114"));
mapTemplate.Connections.Add(new Connection("116", "37"));
mapTemplate.Connections.Add(new Connection("116", "114"));
mapTemplate.Connections.Add(new Connection("116", "181"));
mapTemplate.Connections.Add(new Connection("116", "154"));
mapTemplate.Connections.Add(new Connection("117", "102"));
mapTemplate.Connections.Add(new Connection("117", "91"));
mapTemplate.Connections.Add(new Connection("117", "93"));
mapTemplate.Connections.Add(new Connection("117", "119"));
mapTemplate.Connections.Add(new Connection("117", "118"));
mapTemplate.Connections.Add(new Connection("117", "122"));
mapTemplate.Connections.Add(new Connection("117", "121"));
mapTemplate.Connections.Add(new Connection("118", "117"));
mapTemplate.Connections.Add(new Connection("118", "119"));
mapTemplate.Connections.Add(new Connection("118", "121"));
mapTemplate.Connections.Add(new Connection("119", "93"));
mapTemplate.Connections.Add(new Connection("119", "117"));
mapTemplate.Connections.Add(new Connection("119", "118"));
mapTemplate.Connections.Add(new Connection("120", "121"));
mapTemplate.Connections.Add(new Connection("120", "125"));
mapTemplate.Connections.Add(new Connection("120", "129"));
mapTemplate.Connections.Add(new Connection("120", "130"));
mapTemplate.Connections.Add(new Connection("121", "118"));
mapTemplate.Connections.Add(new Connection("121", "122"));
mapTemplate.Connections.Add(new Connection("121", "126"));
mapTemplate.Connections.Add(new Connection("121", "120"));
mapTemplate.Connections.Add(new Connection("121", "125"));
mapTemplate.Connections.Add(new Connection("121", "117"));
mapTemplate.Connections.Add(new Connection("122", "103"));
mapTemplate.Connections.Add(new Connection("122", "100"));
mapTemplate.Connections.Add(new Connection("122", "102"));
mapTemplate.Connections.Add(new Connection("122", "121"));
mapTemplate.Connections.Add(new Connection("122", "117"));
mapTemplate.Connections.Add(new Connection("122", "126"));
mapTemplate.Connections.Add(new Connection("123", "103"));
mapTemplate.Connections.Add(new Connection("123", "126"));
mapTemplate.Connections.Add(new Connection("123", "105"));
mapTemplate.Connections.Add(new Connection("123", "104"));
mapTemplate.Connections.Add(new Connection("123", "124"));
mapTemplate.Connections.Add(new Connection("123", "135"));
mapTemplate.Connections.Add(new Connection("124", "126"));
mapTemplate.Connections.Add(new Connection("124", "125"));
mapTemplate.Connections.Add(new Connection("124", "123"));
mapTemplate.Connections.Add(new Connection("124", "135"));
mapTemplate.Connections.Add(new Connection("125", "112"));
mapTemplate.Connections.Add(new Connection("125", "120"));
mapTemplate.Connections.Add(new Connection("125", "121"));
mapTemplate.Connections.Add(new Connection("125", "126"));
mapTemplate.Connections.Add(new Connection("125", "124"));
mapTemplate.Connections.Add(new Connection("126", "121"));
mapTemplate.Connections.Add(new Connection("126", "122"));
mapTemplate.Connections.Add(new Connection("126", "103"));
mapTemplate.Connections.Add(new Connection("126", "123"));
mapTemplate.Connections.Add(new Connection("126", "125"));
mapTemplate.Connections.Add(new Connection("126", "124"));
mapTemplate.Connections.Add(new Connection("127", "132"));
mapTemplate.Connections.Add(new Connection("127", "128"));
mapTemplate.Connections.Add(new Connection("127", "131"));
mapTemplate.Connections.Add(new Connection("128", "129"));
mapTemplate.Connections.Add(new Connection("128", "130"));
mapTemplate.Connections.Add(new Connection("128", "127"));
mapTemplate.Connections.Add(new Connection("128", "131"));
mapTemplate.Connections.Add(new Connection("129", "120"));
mapTemplate.Connections.Add(new Connection("129", "130"));
mapTemplate.Connections.Add(new Connection("129", "128"));
mapTemplate.Connections.Add(new Connection("130", "129"));
mapTemplate.Connections.Add(new Connection("130", "120"));
mapTemplate.Connections.Add(new Connection("130", "128"));
mapTemplate.Connections.Add(new Connection("130", "131"));
mapTemplate.Connections.Add(new Connection("131", "130"));
mapTemplate.Connections.Add(new Connection("131", "132"));
mapTemplate.Connections.Add(new Connection("131", "127"));
mapTemplate.Connections.Add(new Connection("131", "128"));
mapTemplate.Connections.Add(new Connection("132", "96"));
mapTemplate.Connections.Add(new Connection("132", "131"));
mapTemplate.Connections.Add(new Connection("132", "127"));
mapTemplate.Connections.Add(new Connection("132", "136"));
mapTemplate.Connections.Add(new Connection("133", "139"));
mapTemplate.Connections.Add(new Connection("133", "110"));
mapTemplate.Connections.Add(new Connection("133", "111"));
mapTemplate.Connections.Add(new Connection("133", "134"));
mapTemplate.Connections.Add(new Connection("133", "135"));
mapTemplate.Connections.Add(new Connection("133", "104"));
mapTemplate.Connections.Add(new Connection("134", "135"));
mapTemplate.Connections.Add(new Connection("134", "136"));
mapTemplate.Connections.Add(new Connection("134", "133"));
mapTemplate.Connections.Add(new Connection("134", "139"));
mapTemplate.Connections.Add(new Connection("134", "141"));
mapTemplate.Connections.Add(new Connection("134", "144"));
mapTemplate.Connections.Add(new Connection("135", "123"));
mapTemplate.Connections.Add(new Connection("135", "124"));
mapTemplate.Connections.Add(new Connection("135", "136"));
mapTemplate.Connections.Add(new Connection("135", "134"));
mapTemplate.Connections.Add(new Connection("135", "133"));
mapTemplate.Connections.Add(new Connection("135", "104"));
mapTemplate.Connections.Add(new Connection("136", "135"));
mapTemplate.Connections.Add(new Connection("136", "134"));
mapTemplate.Connections.Add(new Connection("136", "132"));
mapTemplate.Connections.Add(new Connection("136", "154"));
mapTemplate.Connections.Add(new Connection("137", "141"));
mapTemplate.Connections.Add(new Connection("137", "139"));
mapTemplate.Connections.Add(new Connection("137", "138"));
mapTemplate.Connections.Add(new Connection("137", "146"));
mapTemplate.Connections.Add(new Connection("137", "153"));
mapTemplate.Connections.Add(new Connection("137", "151"));
mapTemplate.Connections.Add(new Connection("138", "167"));
mapTemplate.Connections.Add(new Connection("138", "110"));
mapTemplate.Connections.Add(new Connection("138", "109"));
mapTemplate.Connections.Add(new Connection("138", "139"));
mapTemplate.Connections.Add(new Connection("138", "137"));
mapTemplate.Connections.Add(new Connection("138", "151"));
mapTemplate.Connections.Add(new Connection("139", "138"));
mapTemplate.Connections.Add(new Connection("139", "133"));
mapTemplate.Connections.Add(new Connection("139", "134"));
mapTemplate.Connections.Add(new Connection("139", "141"));
mapTemplate.Connections.Add(new Connection("139", "137"));
mapTemplate.Connections.Add(new Connection("139", "110"));
mapTemplate.Connections.Add(new Connection("140", "143"));
mapTemplate.Connections.Add(new Connection("140", "142"));
mapTemplate.Connections.Add(new Connection("140", "141"));
mapTemplate.Connections.Add(new Connection("140", "146"));
mapTemplate.Connections.Add(new Connection("140", "149"));
mapTemplate.Connections.Add(new Connection("141", "134"));
mapTemplate.Connections.Add(new Connection("141", "139"));
mapTemplate.Connections.Add(new Connection("141", "144"));
mapTemplate.Connections.Add(new Connection("141", "142"));
mapTemplate.Connections.Add(new Connection("141", "140"));
mapTemplate.Connections.Add(new Connection("141", "146"));
mapTemplate.Connections.Add(new Connection("141", "137"));
mapTemplate.Connections.Add(new Connection("142", "143"));
mapTemplate.Connections.Add(new Connection("142", "144"));
mapTemplate.Connections.Add(new Connection("142", "140"));
mapTemplate.Connections.Add(new Connection("142", "141"));
mapTemplate.Connections.Add(new Connection("143", "142"));
mapTemplate.Connections.Add(new Connection("143", "144"));
mapTemplate.Connections.Add(new Connection("143", "112"));
mapTemplate.Connections.Add(new Connection("143", "140"));
mapTemplate.Connections.Add(new Connection("144", "141"));
mapTemplate.Connections.Add(new Connection("144", "134"));
mapTemplate.Connections.Add(new Connection("144", "142"));
mapTemplate.Connections.Add(new Connection("144", "143"));
mapTemplate.Connections.Add(new Connection("145", "146"));
mapTemplate.Connections.Add(new Connection("145", "147"));
mapTemplate.Connections.Add(new Connection("145", "149"));
mapTemplate.Connections.Add(new Connection("145", "152"));
mapTemplate.Connections.Add(new Connection("145", "153"));
mapTemplate.Connections.Add(new Connection("146", "140"));
mapTemplate.Connections.Add(new Connection("146", "141"));
mapTemplate.Connections.Add(new Connection("146", "137"));
mapTemplate.Connections.Add(new Connection("146", "145"));
mapTemplate.Connections.Add(new Connection("146", "153"));
mapTemplate.Connections.Add(new Connection("146", "149"));
mapTemplate.Connections.Add(new Connection("147", "148"));
mapTemplate.Connections.Add(new Connection("147", "149"));
mapTemplate.Connections.Add(new Connection("147", "145"));
mapTemplate.Connections.Add(new Connection("147", "152"));
mapTemplate.Connections.Add(new Connection("147", "150"));
mapTemplate.Connections.Add(new Connection("148", "149"));
mapTemplate.Connections.Add(new Connection("148", "147"));
mapTemplate.Connections.Add(new Connection("149", "146"));
mapTemplate.Connections.Add(new Connection("149", "140"));
mapTemplate.Connections.Add(new Connection("149", "148"));
mapTemplate.Connections.Add(new Connection("149", "147"));
mapTemplate.Connections.Add(new Connection("149", "145"));
mapTemplate.Connections.Add(new Connection("150", "154"));
mapTemplate.Connections.Add(new Connection("150", "153"));
mapTemplate.Connections.Add(new Connection("150", "152"));
mapTemplate.Connections.Add(new Connection("150", "147"));
mapTemplate.Connections.Add(new Connection("150", "151"));
mapTemplate.Connections.Add(new Connection("150", "161"));
mapTemplate.Connections.Add(new Connection("150", "159"));
mapTemplate.Connections.Add(new Connection("150", "160"));
mapTemplate.Connections.Add(new Connection("151", "153"));
mapTemplate.Connections.Add(new Connection("151", "150"));
mapTemplate.Connections.Add(new Connection("151", "167"));
mapTemplate.Connections.Add(new Connection("151", "137"));
mapTemplate.Connections.Add(new Connection("151", "138"));
mapTemplate.Connections.Add(new Connection("151", "165"));
mapTemplate.Connections.Add(new Connection("151", "161"));
mapTemplate.Connections.Add(new Connection("152", "147"));
mapTemplate.Connections.Add(new Connection("152", "145"));
mapTemplate.Connections.Add(new Connection("152", "150"));
mapTemplate.Connections.Add(new Connection("152", "153"));
mapTemplate.Connections.Add(new Connection("152", "154"));
mapTemplate.Connections.Add(new Connection("153", "146"));
mapTemplate.Connections.Add(new Connection("153", "145"));
mapTemplate.Connections.Add(new Connection("153", "137"));
mapTemplate.Connections.Add(new Connection("153", "150"));
mapTemplate.Connections.Add(new Connection("153", "151"));
mapTemplate.Connections.Add(new Connection("153", "152"));
mapTemplate.Connections.Add(new Connection("154", "116"));
mapTemplate.Connections.Add(new Connection("154", "181"));
mapTemplate.Connections.Add(new Connection("154", "136"));
mapTemplate.Connections.Add(new Connection("154", "152"));
mapTemplate.Connections.Add(new Connection("154", "150"));
mapTemplate.Connections.Add(new Connection("155", "158"));
mapTemplate.Connections.Add(new Connection("155", "156"));
mapTemplate.Connections.Add(new Connection("155", "157"));
mapTemplate.Connections.Add(new Connection("156", "155"));
mapTemplate.Connections.Add(new Connection("156", "157"));
mapTemplate.Connections.Add(new Connection("157", "156"));
mapTemplate.Connections.Add(new Connection("157", "155"));
mapTemplate.Connections.Add(new Connection("157", "158"));
mapTemplate.Connections.Add(new Connection("157", "159"));
mapTemplate.Connections.Add(new Connection("158", "160"));
mapTemplate.Connections.Add(new Connection("158", "155"));
mapTemplate.Connections.Add(new Connection("158", "157"));
mapTemplate.Connections.Add(new Connection("158", "159"));
mapTemplate.Connections.Add(new Connection("159", "150"));
mapTemplate.Connections.Add(new Connection("159", "160"));
mapTemplate.Connections.Add(new Connection("159", "157"));
mapTemplate.Connections.Add(new Connection("159", "158"));
mapTemplate.Connections.Add(new Connection("160", "159"));
mapTemplate.Connections.Add(new Connection("160", "150"));
mapTemplate.Connections.Add(new Connection("160", "161"));
mapTemplate.Connections.Add(new Connection("160", "158"));
mapTemplate.Connections.Add(new Connection("161", "163"));
mapTemplate.Connections.Add(new Connection("161", "165"));
mapTemplate.Connections.Add(new Connection("161", "151"));
mapTemplate.Connections.Add(new Connection("161", "150"));
mapTemplate.Connections.Add(new Connection("161", "160"));
mapTemplate.Connections.Add(new Connection("162", "174"));
mapTemplate.Connections.Add(new Connection("162", "164"));
mapTemplate.Connections.Add(new Connection("162", "163"));
mapTemplate.Connections.Add(new Connection("163", "164"));
mapTemplate.Connections.Add(new Connection("163", "162"));
mapTemplate.Connections.Add(new Connection("163", "161"));
mapTemplate.Connections.Add(new Connection("163", "165"));
mapTemplate.Connections.Add(new Connection("164", "168"));
mapTemplate.Connections.Add(new Connection("164", "174"));
mapTemplate.Connections.Add(new Connection("164", "162"));
mapTemplate.Connections.Add(new Connection("164", "163"));
mapTemplate.Connections.Add(new Connection("164", "165"));
mapTemplate.Connections.Add(new Connection("164", "166"));
mapTemplate.Connections.Add(new Connection("164", "171"));
mapTemplate.Connections.Add(new Connection("165", "161"));
mapTemplate.Connections.Add(new Connection("165", "163"));
mapTemplate.Connections.Add(new Connection("165", "164"));
mapTemplate.Connections.Add(new Connection("165", "166"));
mapTemplate.Connections.Add(new Connection("165", "167"));
mapTemplate.Connections.Add(new Connection("165", "151"));
mapTemplate.Connections.Add(new Connection("166", "164"));
mapTemplate.Connections.Add(new Connection("166", "165"));
mapTemplate.Connections.Add(new Connection("166", "171"));
mapTemplate.Connections.Add(new Connection("166", "172"));
mapTemplate.Connections.Add(new Connection("166", "113"));
mapTemplate.Connections.Add(new Connection("166", "167"));
mapTemplate.Connections.Add(new Connection("167", "113"));
mapTemplate.Connections.Add(new Connection("167", "166"));
mapTemplate.Connections.Add(new Connection("167", "165"));
mapTemplate.Connections.Add(new Connection("167", "115"));
mapTemplate.Connections.Add(new Connection("167", "109"));
mapTemplate.Connections.Add(new Connection("167", "138"));
mapTemplate.Connections.Add(new Connection("167", "151"));
mapTemplate.Connections.Add(new Connection("168", "181"));
mapTemplate.Connections.Add(new Connection("168", "173"));
mapTemplate.Connections.Add(new Connection("168", "169"));
mapTemplate.Connections.Add(new Connection("168", "179"));
mapTemplate.Connections.Add(new Connection("168", "178"));
mapTemplate.Connections.Add(new Connection("168", "174"));
mapTemplate.Connections.Add(new Connection("168", "171"));
mapTemplate.Connections.Add(new Connection("168", "170"));
mapTemplate.Connections.Add(new Connection("168", "164"));
mapTemplate.Connections.Add(new Connection("169", "24"));
mapTemplate.Connections.Add(new Connection("169", "179"));
mapTemplate.Connections.Add(new Connection("169", "181"));
mapTemplate.Connections.Add(new Connection("169", "180"));
mapTemplate.Connections.Add(new Connection("169", "168"));
mapTemplate.Connections.Add(new Connection("169", "170"));
mapTemplate.Connections.Add(new Connection("169", "29"));
mapTemplate.Connections.Add(new Connection("170", "171"));
mapTemplate.Connections.Add(new Connection("170", "168"));
mapTemplate.Connections.Add(new Connection("170", "169"));
mapTemplate.Connections.Add(new Connection("170", "29"));
mapTemplate.Connections.Add(new Connection("170", "26"));
mapTemplate.Connections.Add(new Connection("170", "32"));
mapTemplate.Connections.Add(new Connection("170", "30"));
mapTemplate.Connections.Add(new Connection("171", "168"));
mapTemplate.Connections.Add(new Connection("171", "170"));
mapTemplate.Connections.Add(new Connection("171", "172"));
mapTemplate.Connections.Add(new Connection("171", "30"));
mapTemplate.Connections.Add(new Connection("171", "166"));
mapTemplate.Connections.Add(new Connection("171", "164"));
mapTemplate.Connections.Add(new Connection("172", "31"));
mapTemplate.Connections.Add(new Connection("172", "36"));
mapTemplate.Connections.Add(new Connection("172", "114"));
mapTemplate.Connections.Add(new Connection("172", "30"));
mapTemplate.Connections.Add(new Connection("172", "171"));
mapTemplate.Connections.Add(new Connection("172", "166"));
mapTemplate.Connections.Add(new Connection("172", "113"));
mapTemplate.Connections.Add(new Connection("173", "178"));
mapTemplate.Connections.Add(new Connection("173", "168"));
mapTemplate.Connections.Add(new Connection("173", "174"));
mapTemplate.Connections.Add(new Connection("174", "173"));
mapTemplate.Connections.Add(new Connection("174", "168"));
mapTemplate.Connections.Add(new Connection("174", "164"));
mapTemplate.Connections.Add(new Connection("174", "162"));
mapTemplate.Connections.Add(new Connection("175", "176"));
mapTemplate.Connections.Add(new Connection("175", "178"));
mapTemplate.Connections.Add(new Connection("176", "179"));
mapTemplate.Connections.Add(new Connection("176", "178"));
mapTemplate.Connections.Add(new Connection("176", "177"));
mapTemplate.Connections.Add(new Connection("176", "180"));
mapTemplate.Connections.Add(new Connection("176", "175"));
mapTemplate.Connections.Add(new Connection("177", "176"));
mapTemplate.Connections.Add(new Connection("177", "180"));
mapTemplate.Connections.Add(new Connection("177", "1"));
mapTemplate.Connections.Add(new Connection("177", "4"));
mapTemplate.Connections.Add(new Connection("178", "179"));
mapTemplate.Connections.Add(new Connection("178", "176"));
mapTemplate.Connections.Add(new Connection("178", "175"));
mapTemplate.Connections.Add(new Connection("178", "173"));
mapTemplate.Connections.Add(new Connection("178", "168"));
mapTemplate.Connections.Add(new Connection("179", "169"));
mapTemplate.Connections.Add(new Connection("179", "181"));
mapTemplate.Connections.Add(new Connection("179", "180"));
mapTemplate.Connections.Add(new Connection("179", "176"));
mapTemplate.Connections.Add(new Connection("179", "178"));
mapTemplate.Connections.Add(new Connection("179", "168"));
mapTemplate.Connections.Add(new Connection("180", "179"));
mapTemplate.Connections.Add(new Connection("180", "177"));
mapTemplate.Connections.Add(new Connection("180", "176"));
mapTemplate.Connections.Add(new Connection("180", "169"));
mapTemplate.Connections.Add(new Connection("180", "4"));
mapTemplate.Connections.Add(new Connection("180", "7"));
mapTemplate.Connections.Add(new Connection("180", "24"));
mapTemplate.Connections.Add(new Connection("181", "8"));
mapTemplate.Connections.Add(new Connection("181", "179"));
mapTemplate.Connections.Add(new Connection("181", "169"));
mapTemplate.Connections.Add(new Connection("181", "116"));
mapTemplate.Connections.Add(new Connection("181", "154"));
mapTemplate.Connections.Add(new Connection("181", "168"));

            return mapTemplate;
		}
    }
}

