
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Ostsee()
        {

var mapTemplate = new MapTemplate("Ostsee") { Image = "ostsee.jpg" };
var country1 = new CountryTemplate("1", "Mecklenburg-Vorpommern") { X = 56, Y = 653 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Brandenburg") { X = 21, Y = 735 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Berlin") { X = 82, Y = 749 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "West-Pommern") { X = 161, Y = 683 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Lebus") { X = 162, Y = 759 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Pommern") { X = 302, Y = 628 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Grosspolen") { X = 223, Y = 749 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Kujawien-Pommern") { X = 310, Y = 699 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Ermland-Masuren") { X = 483, Y = 627 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Masowien") { X = 433, Y = 737 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Podlachien") { X = 566, Y = 710 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Brest") { X = 712, Y = 753 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Homjel") { X = 847, Y = 726 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Hrodna") { X = 699, Y = 648 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Minskaja Voblasts") { X = 792, Y = 592 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Minsk") { X = 825, Y = 558 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Vicebsk") { X = 865, Y = 449 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Polazk") { X = 793, Y = 458 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Koenigsberg") { X = 453, Y = 560 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Tilsit") { X = 534, Y = 554 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Cernjahovsk") { X = 467, Y = 585 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Vilnius") { X = 676, Y = 568 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Taurage") { X = 622, Y = 529 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Klaipeda") { X = 521, Y = 435 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Kaunas") { X = 573, Y = 486 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Utena") { X = 722, Y = 483 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Siauliai") { X = 648, Y = 433 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Saldus") { X = 557, Y = 392 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Ventspils") { X = 530, Y = 326 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Riga") { X = 644, Y = 348 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Madona") { X = 627, Y = 398 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Duenaburg") { X = 769, Y = 402 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Balvu") { X = 736, Y = 331 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Valkas") { X = 668, Y = 286 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Saaremaa") { X = 538, Y = 236 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Hiiumaa") { X = 545, Y = 197 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Paemu") { X = 612, Y = 208 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Tallinn") { X = 644, Y = 142 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Kothla-Jaerve") { X = 721, Y = 148 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Tartu") { X = 729, Y = 236 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Pleskau") { X = 838, Y = 311 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Luga") { X = 866, Y = 213 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Novgorod") { X = 829, Y = 125 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "St Petersburg") { X = 851, Y = 16 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Kotka") { X = 707, Y = 17 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Helsinki") { X = 609, Y = 58 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Turku") { X = 554, Y = 13 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Alandinseln") { X = 415, Y = 86 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Uppland") { X = 328, Y = 93 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Gaestrikland") { X = 272, Y = 34 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Dalama") { X = 160, Y = 24 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Vaermland") { X = 128, Y = 104 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Vaestmanland") { X = 233, Y = 92 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Soedemanland") { X = 270, Y = 174 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Vaestergoedland") { X = 101, Y = 242 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Oestergoedland") { X = 230, Y = 253 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Skane") { X = 98, Y = 360 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Smaland") { X = 189, Y = 368 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Oeland") { X = 267, Y = 408 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Gotland") { X = 343, Y = 313 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Akershus") { X = 70, Y = 33 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Oslo") { X = 11, Y = 54 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Moss") { X = 52, Y = 75 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Seeland") { X = 39, Y = 451 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Lolland") { X = 13, Y = 502 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Bornholm") { X = 160, Y = 531 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Ruegen") { X = 82, Y = 569 };
mapTemplate.Countries.Add(country67);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country67);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country4);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
continent2.Countries.Add(country9);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 4);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country14);
continent3.Countries.Add(country15);
continent3.Countries.Add(country16);
continent3.Countries.Add(country17);
continent3.Countries.Add(country18);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country19);
continent4.Countries.Add(country20);
continent4.Countries.Add(country21);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country22);
continent5.Countries.Add(country23);
continent5.Countries.Add(country24);
continent5.Countries.Add(country25);
continent5.Countries.Add(country26);
continent5.Countries.Add(country27);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 5);
continent6.Countries.Add(country28);
continent6.Countries.Add(country29);
continent6.Countries.Add(country30);
continent6.Countries.Add(country31);
continent6.Countries.Add(country32);
continent6.Countries.Add(country33);
continent6.Countries.Add(country34);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country35);
continent7.Countries.Add(country36);
continent7.Countries.Add(country37);
continent7.Countries.Add(country38);
continent7.Countries.Add(country39);
continent7.Countries.Add(country40);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country41);
continent8.Countries.Add(country42);
continent8.Countries.Add(country43);
continent8.Countries.Add(country44);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 2);
continent9.Countries.Add(country45);
continent9.Countries.Add(country46);
continent9.Countries.Add(country47);
continent9.Countries.Add(country48);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 6);
continent10.Countries.Add(country49);
continent10.Countries.Add(country50);
continent10.Countries.Add(country51);
continent10.Countries.Add(country52);
continent10.Countries.Add(country53);
continent10.Countries.Add(country54);
continent10.Countries.Add(country55);
continent10.Countries.Add(country56);
continent10.Countries.Add(country57);
continent10.Countries.Add(country58);
continent10.Countries.Add(country59);
continent10.Countries.Add(country60);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 1);
continent11.Countries.Add(country61);
continent11.Countries.Add(country62);
continent11.Countries.Add(country63);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 2);
continent12.Countries.Add(country64);
continent12.Countries.Add(country65);
continent12.Countries.Add(country66);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("1", "65"));
mapTemplate.Connections.Add(new Connection("1", "67"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "66"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "21"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "19"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "22"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "23"));
mapTemplate.Connections.Add(new Connection("11", "21"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "22"));
mapTemplate.Connections.Add(new Connection("14", "26"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "17"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "41"));
mapTemplate.Connections.Add(new Connection("17", "26"));
mapTemplate.Connections.Add(new Connection("17", "14"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "41"));
mapTemplate.Connections.Add(new Connection("18", "32"));
mapTemplate.Connections.Add(new Connection("18", "26"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "9"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "24"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("21", "9"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "11"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "26"));
mapTemplate.Connections.Add(new Connection("22", "11"));
mapTemplate.Connections.Add(new Connection("22", "14"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "20"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "11"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "28"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "20"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "27"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "22"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "18"));
mapTemplate.Connections.Add(new Connection("26", "14"));
mapTemplate.Connections.Add(new Connection("26", "17"));
mapTemplate.Connections.Add(new Connection("26", "32"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "31"));
mapTemplate.Connections.Add(new Connection("27", "25"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "32"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "24"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("29", "60"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "35"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "27"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "18"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "26"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("33", "40"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "41"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "40"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "29"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "48"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("39", "43"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "34"));
mapTemplate.Connections.Add(new Connection("40", "37"));
mapTemplate.Connections.Add(new Connection("40", "33"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "17"));
mapTemplate.Connections.Add(new Connection("41", "18"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "33"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "39"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "36"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("49", "53"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "61"));
mapTemplate.Connections.Add(new Connection("52", "63"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "55"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "61"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("53", "49"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "55"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "56"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "52"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "63"));
mapTemplate.Connections.Add(new Connection("55", "53"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("56", "54"));
mapTemplate.Connections.Add(new Connection("56", "58"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("57", "64"));
mapTemplate.Connections.Add(new Connection("58", "56"));
mapTemplate.Connections.Add(new Connection("58", "57"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("59", "66"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "29"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "63"));
mapTemplate.Connections.Add(new Connection("61", "51"));
mapTemplate.Connections.Add(new Connection("61", "52"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("63", "52"));
mapTemplate.Connections.Add(new Connection("63", "61"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "55"));
mapTemplate.Connections.Add(new Connection("64", "57"));
mapTemplate.Connections.Add(new Connection("64", "65"));
mapTemplate.Connections.Add(new Connection("65", "64"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "1"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "6"));
mapTemplate.Connections.Add(new Connection("66", "59"));
mapTemplate.Connections.Add(new Connection("67", "1"));

            return mapTemplate;
		}
    }
}

