
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate BerlinBrandenburg()
        {

var mapTemplate = new MapTemplate("BerlinBrandenburg") { Image = "Berlin-Brandenburg.png" };
var country1 = new CountryTemplate("1", "Potsdam-Mittelmark") { X = 311, Y = 544 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Brandenburg an der Havel") { X = 276, Y = 446 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Havelland") { X = 300, Y = 371 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Frankfurt an der Oder") { X = 732, Y = 453 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Prignitz") { X = 137, Y = 199 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Ostprignitz-Ruppin") { X = 312, Y = 260 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Oberhavel") { X = 431, Y = 291 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Uckermark") { X = 568, Y = 151 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Barnim") { X = 543, Y = 278 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "M�rkisch-Oderland") { X = 647, Y = 372 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Oder Sree") { X = 681, Y = 512 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Dahme-Spree") { X = 578, Y = 606 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Cottbus") { X = 709, Y = 657 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Spree-Neisse") { X = 727, Y = 715 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Oberspreewald") { X = 608, Y = 787 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Elbe-Elster") { X = 504, Y = 756 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Teltow-Fl�ming") { X = 452, Y = 587 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Berlin") { X = 472, Y = 410 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Stadt Potsdam") { X = 391, Y = 430 };
mapTemplate.Countries.Add(country19);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country19);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 2);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 1);
continent3.Countries.Add(country8);
continent3.Countries.Add(country9);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country5);
continent4.Countries.Add(country6);
continent4.Countries.Add(country7);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country18);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country4);
continent6.Countries.Add(country10);
continent6.Countries.Add(country11);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 1);
continent7.Countries.Add(country15);
continent7.Countries.Add(country16);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 1);
continent8.Countries.Add(country1);
continent8.Countries.Add(country17);
mapTemplate.Continents.Add(continent8);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "18"));
mapTemplate.Connections.Add(new Connection("1", "17"));
mapTemplate.Connections.Add(new Connection("1", "19"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "6"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "19"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "18"));
mapTemplate.Connections.Add(new Connection("4", "10"));
mapTemplate.Connections.Add(new Connection("4", "11"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "3"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "18"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("10", "18"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "4"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "4"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "1"));
mapTemplate.Connections.Add(new Connection("18", "7"));
mapTemplate.Connections.Add(new Connection("18", "1"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "10"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "3"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "1"));
mapTemplate.Connections.Add(new Connection("19", "3"));

            return mapTemplate;
		}
    }
}

