
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Wien()
        {

var mapTemplate = new MapTemplate("Wien") { Image = "wien.jpg" };
var country1 = new CountryTemplate("1", "Hietzing") { X = 186, Y = 479 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Liesing") { X = 267, Y = 585 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Meidling") { X = 308, Y = 493 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Margareten") { X = 369, Y = 460 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Favoriten") { X = 421, Y = 553 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Simmering") { X = 573, Y = 551 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Donaustadt") { X = 627, Y = 319 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Floridsdorf") { X = 492, Y = 182 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Leopoldstadt") { X = 504, Y = 389 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Brigittenau") { X = 425, Y = 303 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Doebling") { X = 325, Y = 230 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Hernals") { X = 251, Y = 322 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "W�hring") { X = 257, Y = 277 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Penzing") { X = 131, Y = 380 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Ottakring") { X = 261, Y = 370 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Alsergrund") { X = 375, Y = 343 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Innere Stadt") { X = 412, Y = 384 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Landstrasse") { X = 455, Y = 451 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Wieden") { X = 405, Y = 442 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Mariahilf") { X = 345, Y = 436 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Neubau") { X = 341, Y = 410 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Josefstadt") { X = 342, Y = 370 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Rudolfsheim Fuenfhaus") { X = 312, Y = 431 };
mapTemplate.Countries.Add(country23);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country23);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country7);
continent4.Countries.Add(country8);
continent4.Countries.Add(country9);
continent4.Countries.Add(country10);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 1);
continent5.Countries.Add(country17);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 5);
continent6.Countries.Add(country16);
continent6.Countries.Add(country18);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
continent6.Countries.Add(country21);
continent6.Countries.Add(country22);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country5);
continent7.Countries.Add(country6);
mapTemplate.Continents.Add(continent7);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "14"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "23"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "19"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "20"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "19"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "18"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "18"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "10"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "17"));
mapTemplate.Connections.Add(new Connection("9", "18"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "16"));
mapTemplate.Connections.Add(new Connection("10", "8"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "16"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "16"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "16"));
mapTemplate.Connections.Add(new Connection("14", "1"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "23"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "23"));
mapTemplate.Connections.Add(new Connection("15", "21"));
mapTemplate.Connections.Add(new Connection("15", "22"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("16", "10"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("16", "13"));
mapTemplate.Connections.Add(new Connection("16", "22"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("16", "12"));
mapTemplate.Connections.Add(new Connection("16", "9"));
mapTemplate.Connections.Add(new Connection("17", "9"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("18", "6"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "9"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "5"));
mapTemplate.Connections.Add(new Connection("19", "5"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "4"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "4"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "23"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "15"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "16"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "15"));
mapTemplate.Connections.Add(new Connection("23", "14"));
mapTemplate.Connections.Add(new Connection("23", "15"));
mapTemplate.Connections.Add(new Connection("23", "3"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "20"));

            return mapTemplate;
		}
    }
}

