
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate BerlinCity()
        {

var mapTemplate = new MapTemplate("BerlinCity") { Image = "berlin.gif" };
var country1 = new CountryTemplate("1", "Kladow") { X = 67, Y = 535 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Gatow") { X = 114, Y = 469 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Wilhelmstadt") { X = 142, Y = 406 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Staaken") { X = 75, Y = 353 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Falkenhagener Feld") { X = 122, Y = 298 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Hakenfelde") { X = 160, Y = 238 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Spandau") { X = 167, Y = 342 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Haselhorst") { X = 219, Y = 321 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Siemensstadt") { X = 264, Y = 332 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Konradshoehe") { X = 209, Y = 204 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Tegel") { X = 314, Y = 246 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Heiligensee") { X = 231, Y = 148 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Frohnau") { X = 321, Y = 78 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Hermsdorf") { X = 343, Y = 113 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Luebars") { X = 417, Y = 123 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Waidmannslust") { X = 366, Y = 145 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Maerkisches Viertel") { X = 429, Y = 173 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Wittenau") { X = 374, Y = 192 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Reinickendorf") { X = 401, Y = 242 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Blankenfelde") { X = 493, Y = 107 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Rosenthal") { X = 473, Y = 177 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Wilhelmsruh") { X = 438, Y = 202 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Niederschoenhausen") { X = 492, Y = 219 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Pankow") { X = 518, Y = 262 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Prenzlauer Berg") { X = 541, Y = 329 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Weissensee") { X = 592, Y = 293 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Heinersdorf") { X = 566, Y = 248 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Stadtrandsiedlung Malchow") { X = 612, Y = 237 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Blankenburg") { X = 588, Y = 174 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Franzoesisch Buchholz") { X = 551, Y = 154 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Karow") { X = 626, Y = 143 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Buch") { X = 631, Y = 66 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Wedding") { X = 410, Y = 300 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Gesundbrunnen") { X = 467, Y = 301 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Moabit") { X = 397, Y = 362 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Hansaviertel") { X = 414, Y = 391 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Tiergarten") { X = 432, Y = 418 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Mitte") { X = 494, Y = 375 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Charlottenburg Nord") { X = 330, Y = 324 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Westend") { X = 260, Y = 396 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Charlottenburg Sued") { X = 342, Y = 394 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Wilmersdorf") { X = 366, Y = 468 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Schmargendorf") { X = 317, Y = 490 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Grunewald") { X = 226, Y = 476 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Wannsee") { X = 74, Y = 649 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Nikolasee") { X = 168, Y = 615 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Zehlendorf") { X = 251, Y = 606 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Dahlem") { X = 298, Y = 551 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Lichterfelde") { X = 338, Y = 629 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Steglitz") { X = 383, Y = 555 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Lankwitz") { X = 406, Y = 620 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Friedenau") { X = 375, Y = 511 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Schoeneberg") { X = 423, Y = 470 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Tempelhof") { X = 465, Y = 505 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Mariendorf") { X = 478, Y = 597 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Marienfelde") { X = 443, Y = 687 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Lichtenrade") { X = 509, Y = 724 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Rudow") { X = 652, Y = 674 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Gropiusstadt") { X = 594, Y = 630 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Buckow") { X = 539, Y = 660 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Britz") { X = 553, Y = 584 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Neukoelln") { X = 561, Y = 512 };
mapTemplate.Countries.Add(country62);
var country63 = new CountryTemplate("63", "Kreuzberg") { X = 485, Y = 442 };
mapTemplate.Countries.Add(country63);
var country64 = new CountryTemplate("64", "Friedrichshain") { X = 566, Y = 394 };
mapTemplate.Countries.Add(country64);
var country65 = new CountryTemplate("65", "Malchow") { X = 642, Y = 230 };
mapTemplate.Countries.Add(country65);
var country66 = new CountryTemplate("66", "Wartenburg") { X = 694, Y = 212 };
mapTemplate.Countries.Add(country66);
var country67 = new CountryTemplate("67", "Falkenberg") { X = 750, Y = 237 };
mapTemplate.Countries.Add(country67);
var country68 = new CountryTemplate("68", "Neuhohenschoenhausen") { X = 676, Y = 260 };
mapTemplate.Countries.Add(country68);
var country69 = new CountryTemplate("69", "Althohenschoenhausen") { X = 663, Y = 326 };
mapTemplate.Countries.Add(country69);
var country70 = new CountryTemplate("70", "Lichtenberg") { X = 638, Y = 391 };
mapTemplate.Countries.Add(country70);
var country71 = new CountryTemplate("71", "Fennpfuhl") { X = 614, Y = 359 };
mapTemplate.Countries.Add(country71);
var country72 = new CountryTemplate("72", "Rummelsburg") { X = 624, Y = 438 };
mapTemplate.Countries.Add(country72);
var country73 = new CountryTemplate("73", "Friedrichsfelde") { X = 681, Y = 436 };
mapTemplate.Countries.Add(country73);
var country74 = new CountryTemplate("74", "Karlshorst") { X = 705, Y = 480 };
mapTemplate.Countries.Add(country74);
var country75 = new CountryTemplate("75", "Marzahn") { X = 745, Y = 303 };
mapTemplate.Countries.Add(country75);
var country76 = new CountryTemplate("76", "Hellersdorf") { X = 828, Y = 338 };
mapTemplate.Countries.Add(country76);
var country77 = new CountryTemplate("77", "Biesdorf") { X = 754, Y = 428 };
mapTemplate.Countries.Add(country77);
var country78 = new CountryTemplate("78", "Kaulsdorf") { X = 799, Y = 416 };
mapTemplate.Countries.Add(country78);
var country79 = new CountryTemplate("79", "Mahlsdorf") { X = 835, Y = 438 };
mapTemplate.Countries.Add(country79);
var country80 = new CountryTemplate("80", "Alttreptow") { X = 576, Y = 463 };
mapTemplate.Countries.Add(country80);
var country81 = new CountryTemplate("81", "Plaenterwald") { X = 621, Y = 495 };
mapTemplate.Countries.Add(country81);
var country82 = new CountryTemplate("82", "Baumschulenweg") { X = 610, Y = 569 };
mapTemplate.Countries.Add(country82);
var country83 = new CountryTemplate("83", "Johannisthal") { X = 679, Y = 603 };
mapTemplate.Countries.Add(country83);
var country84 = new CountryTemplate("84", "Niederschoeneweide") { X = 701, Y = 567 };
mapTemplate.Countries.Add(country84);
var country85 = new CountryTemplate("85", "Oberschoeneweide") { X = 725, Y = 540 };
mapTemplate.Countries.Add(country85);
var country86 = new CountryTemplate("86", "Koepenick") { X = 843, Y = 629 };
mapTemplate.Countries.Add(country86);
var country87 = new CountryTemplate("87", "Adlershof") { X = 727, Y = 594 };
mapTemplate.Countries.Add(country87);
var country88 = new CountryTemplate("88", "Altglienicke") { X = 725, Y = 676 };
mapTemplate.Countries.Add(country88);
var country89 = new CountryTemplate("89", "Bohnsdorf") { X = 766, Y = 704 };
mapTemplate.Countries.Add(country89);
var country90 = new CountryTemplate("90", "Friedrichshagen") { X = 885, Y = 547 };
mapTemplate.Countries.Add(country90);
var country91 = new CountryTemplate("91", "Rahnsdorf") { X = 988, Y = 592 };
mapTemplate.Countries.Add(country91);
var country92 = new CountryTemplate("92", "Mueggelheim") { X = 946, Y = 696 };
mapTemplate.Countries.Add(country92);
var country93 = new CountryTemplate("93", "Gruenau") { X = 826, Y = 708 };
mapTemplate.Countries.Add(country93);
var country94 = new CountryTemplate("94", "Schmoeckwitz") { X = 913, Y = 789 };
mapTemplate.Countries.Add(country94);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
continent1.Countries.Add(country8);
continent1.Countries.Add(country9);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country10);
continent2.Countries.Add(country11);
continent2.Countries.Add(country12);
continent2.Countries.Add(country13);
continent2.Countries.Add(country14);
continent2.Countries.Add(country15);
continent2.Countries.Add(country16);
continent2.Countries.Add(country17);
continent2.Countries.Add(country18);
continent2.Countries.Add(country19);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 7);
continent3.Countries.Add(country20);
continent3.Countries.Add(country21);
continent3.Countries.Add(country22);
continent3.Countries.Add(country23);
continent3.Countries.Add(country24);
continent3.Countries.Add(country25);
continent3.Countries.Add(country26);
continent3.Countries.Add(country27);
continent3.Countries.Add(country28);
continent3.Countries.Add(country29);
continent3.Countries.Add(country30);
continent3.Countries.Add(country31);
continent3.Countries.Add(country32);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country33);
continent4.Countries.Add(country34);
continent4.Countries.Add(country35);
continent4.Countries.Add(country36);
continent4.Countries.Add(country37);
continent4.Countries.Add(country38);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country39);
continent5.Countries.Add(country40);
continent5.Countries.Add(country41);
continent5.Countries.Add(country42);
continent5.Countries.Add(country43);
continent5.Countries.Add(country44);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 4);
continent6.Countries.Add(country45);
continent6.Countries.Add(country46);
continent6.Countries.Add(country47);
continent6.Countries.Add(country48);
continent6.Countries.Add(country49);
continent6.Countries.Add(country50);
continent6.Countries.Add(country51);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 5);
continent7.Countries.Add(country52);
continent7.Countries.Add(country53);
continent7.Countries.Add(country54);
continent7.Countries.Add(country55);
continent7.Countries.Add(country56);
continent7.Countries.Add(country57);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country58);
continent8.Countries.Add(country59);
continent8.Countries.Add(country60);
continent8.Countries.Add(country61);
continent8.Countries.Add(country62);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country63);
continent9.Countries.Add(country64);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 6);
continent10.Countries.Add(country65);
continent10.Countries.Add(country66);
continent10.Countries.Add(country67);
continent10.Countries.Add(country68);
continent10.Countries.Add(country69);
continent10.Countries.Add(country70);
continent10.Countries.Add(country71);
continent10.Countries.Add(country72);
continent10.Countries.Add(country73);
continent10.Countries.Add(country74);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country75);
continent11.Countries.Add(country76);
continent11.Countries.Add(country77);
continent11.Countries.Add(country78);
continent11.Countries.Add(country79);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 8);
continent12.Countries.Add(country80);
continent12.Countries.Add(country81);
continent12.Countries.Add(country82);
continent12.Countries.Add(country83);
continent12.Countries.Add(country84);
continent12.Countries.Add(country85);
continent12.Countries.Add(country86);
continent12.Countries.Add(country87);
continent12.Countries.Add(country88);
continent12.Countries.Add(country89);
continent12.Countries.Add(country90);
continent12.Countries.Add(country91);
continent12.Countries.Add(country92);
continent12.Countries.Add(country93);
continent12.Countries.Add(country94);
mapTemplate.Continents.Add(continent12);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "40"));
mapTemplate.Connections.Add(new Connection("3", "44"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "7"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "4"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("7", "40"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "39"));
mapTemplate.Connections.Add(new Connection("9", "40"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("11", "8"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "14"));
mapTemplate.Connections.Add(new Connection("11", "16"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("11", "19"));
mapTemplate.Connections.Add(new Connection("11", "33"));
mapTemplate.Connections.Add(new Connection("11", "39"));
mapTemplate.Connections.Add(new Connection("11", "54"));
mapTemplate.Connections.Add(new Connection("11", "89"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("14", "11"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "20"));
mapTemplate.Connections.Add(new Connection("15", "21"));
mapTemplate.Connections.Add(new Connection("16", "11"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "18"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("17", "21"));
mapTemplate.Connections.Add(new Connection("17", "22"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "16"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("19", "11"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("19", "23"));
mapTemplate.Connections.Add(new Connection("19", "33"));
mapTemplate.Connections.Add(new Connection("19", "34"));
mapTemplate.Connections.Add(new Connection("19", "24"));
mapTemplate.Connections.Add(new Connection("20", "15"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "30"));
mapTemplate.Connections.Add(new Connection("20", "32"));
mapTemplate.Connections.Add(new Connection("21", "15"));
mapTemplate.Connections.Add(new Connection("21", "17"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("21", "30"));
mapTemplate.Connections.Add(new Connection("22", "17"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("23", "19"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "30"));
mapTemplate.Connections.Add(new Connection("23", "34"));
mapTemplate.Connections.Add(new Connection("24", "19"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "27"));
mapTemplate.Connections.Add(new Connection("24", "29"));
mapTemplate.Connections.Add(new Connection("24", "30"));
mapTemplate.Connections.Add(new Connection("24", "34"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "34"));
mapTemplate.Connections.Add(new Connection("25", "38"));
mapTemplate.Connections.Add(new Connection("25", "64"));
mapTemplate.Connections.Add(new Connection("25", "70"));
mapTemplate.Connections.Add(new Connection("25", "71"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "28"));
mapTemplate.Connections.Add(new Connection("26", "68"));
mapTemplate.Connections.Add(new Connection("26", "69"));
mapTemplate.Connections.Add(new Connection("26", "71"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("27", "24"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("28", "26"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "31"));
mapTemplate.Connections.Add(new Connection("28", "65"));
mapTemplate.Connections.Add(new Connection("28", "66"));
mapTemplate.Connections.Add(new Connection("28", "68"));
mapTemplate.Connections.Add(new Connection("29", "24"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "31"));
mapTemplate.Connections.Add(new Connection("30", "20"));
mapTemplate.Connections.Add(new Connection("30", "21"));
mapTemplate.Connections.Add(new Connection("30", "23"));
mapTemplate.Connections.Add(new Connection("30", "24"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("31", "28"));
mapTemplate.Connections.Add(new Connection("31", "29"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "20"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("33", "11"));
mapTemplate.Connections.Add(new Connection("33", "19"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "38"));
mapTemplate.Connections.Add(new Connection("33", "39"));
mapTemplate.Connections.Add(new Connection("34", "19"));
mapTemplate.Connections.Add(new Connection("34", "23"));
mapTemplate.Connections.Add(new Connection("34", "24"));
mapTemplate.Connections.Add(new Connection("34", "25"));
mapTemplate.Connections.Add(new Connection("34", "38"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "37"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "39"));
mapTemplate.Connections.Add(new Connection("35", "41"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "41"));
mapTemplate.Connections.Add(new Connection("37", "35"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "41"));
mapTemplate.Connections.Add(new Connection("37", "53"));
mapTemplate.Connections.Add(new Connection("37", "63"));
mapTemplate.Connections.Add(new Connection("38", "25"));
mapTemplate.Connections.Add(new Connection("38", "33"));
mapTemplate.Connections.Add(new Connection("38", "34"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "63"));
mapTemplate.Connections.Add(new Connection("38", "64"));
mapTemplate.Connections.Add(new Connection("39", "9"));
mapTemplate.Connections.Add(new Connection("39", "11"));
mapTemplate.Connections.Add(new Connection("39", "33"));
mapTemplate.Connections.Add(new Connection("39", "35"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "41"));
mapTemplate.Connections.Add(new Connection("40", "3"));
mapTemplate.Connections.Add(new Connection("40", "7"));
mapTemplate.Connections.Add(new Connection("40", "9"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "44"));
mapTemplate.Connections.Add(new Connection("41", "35"));
mapTemplate.Connections.Add(new Connection("41", "36"));
mapTemplate.Connections.Add(new Connection("41", "37"));
mapTemplate.Connections.Add(new Connection("41", "39"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("41", "53"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "48"));
mapTemplate.Connections.Add(new Connection("42", "50"));
mapTemplate.Connections.Add(new Connection("42", "52"));
mapTemplate.Connections.Add(new Connection("42", "53"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "48"));
mapTemplate.Connections.Add(new Connection("44", "3"));
mapTemplate.Connections.Add(new Connection("44", "40"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "47"));
mapTemplate.Connections.Add(new Connection("44", "48"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "44"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "49"));
mapTemplate.Connections.Add(new Connection("48", "42"));
mapTemplate.Connections.Add(new Connection("48", "43"));
mapTemplate.Connections.Add(new Connection("48", "44"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("49", "47"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("49", "56"));
mapTemplate.Connections.Add(new Connection("50", "42"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "52"));
mapTemplate.Connections.Add(new Connection("50", "53"));
mapTemplate.Connections.Add(new Connection("50", "54"));
mapTemplate.Connections.Add(new Connection("50", "55"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("51", "55"));
mapTemplate.Connections.Add(new Connection("51", "56"));
mapTemplate.Connections.Add(new Connection("52", "42"));
mapTemplate.Connections.Add(new Connection("52", "50"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "37"));
mapTemplate.Connections.Add(new Connection("53", "41"));
mapTemplate.Connections.Add(new Connection("53", "42"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "63"));
mapTemplate.Connections.Add(new Connection("53", "50"));
mapTemplate.Connections.Add(new Connection("54", "11"));
mapTemplate.Connections.Add(new Connection("54", "50"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "61"));
mapTemplate.Connections.Add(new Connection("54", "62"));
mapTemplate.Connections.Add(new Connection("54", "63"));
mapTemplate.Connections.Add(new Connection("54", "89"));
mapTemplate.Connections.Add(new Connection("55", "50"));
mapTemplate.Connections.Add(new Connection("55", "51"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "60"));
mapTemplate.Connections.Add(new Connection("55", "61"));
mapTemplate.Connections.Add(new Connection("56", "49"));
mapTemplate.Connections.Add(new Connection("56", "51"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "61"));
mapTemplate.Connections.Add(new Connection("58", "82"));
mapTemplate.Connections.Add(new Connection("58", "83"));
mapTemplate.Connections.Add(new Connection("58", "88"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("60", "55"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("61", "54"));
mapTemplate.Connections.Add(new Connection("61", "55"));
mapTemplate.Connections.Add(new Connection("61", "58"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "82"));
mapTemplate.Connections.Add(new Connection("62", "54"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "63"));
mapTemplate.Connections.Add(new Connection("62", "80"));
mapTemplate.Connections.Add(new Connection("62", "81"));
mapTemplate.Connections.Add(new Connection("62", "82"));
mapTemplate.Connections.Add(new Connection("63", "37"));
mapTemplate.Connections.Add(new Connection("63", "38"));
mapTemplate.Connections.Add(new Connection("63", "53"));
mapTemplate.Connections.Add(new Connection("63", "54"));
mapTemplate.Connections.Add(new Connection("63", "62"));
mapTemplate.Connections.Add(new Connection("63", "64"));
mapTemplate.Connections.Add(new Connection("63", "80"));
mapTemplate.Connections.Add(new Connection("64", "25"));
mapTemplate.Connections.Add(new Connection("64", "38"));
mapTemplate.Connections.Add(new Connection("64", "63"));
mapTemplate.Connections.Add(new Connection("64", "70"));
mapTemplate.Connections.Add(new Connection("64", "72"));
mapTemplate.Connections.Add(new Connection("64", "80"));
mapTemplate.Connections.Add(new Connection("65", "28"));
mapTemplate.Connections.Add(new Connection("65", "66"));
mapTemplate.Connections.Add(new Connection("65", "68"));
mapTemplate.Connections.Add(new Connection("66", "28"));
mapTemplate.Connections.Add(new Connection("66", "65"));
mapTemplate.Connections.Add(new Connection("66", "67"));
mapTemplate.Connections.Add(new Connection("66", "68"));
mapTemplate.Connections.Add(new Connection("67", "66"));
mapTemplate.Connections.Add(new Connection("67", "68"));
mapTemplate.Connections.Add(new Connection("67", "75"));
mapTemplate.Connections.Add(new Connection("68", "26"));
mapTemplate.Connections.Add(new Connection("68", "28"));
mapTemplate.Connections.Add(new Connection("68", "65"));
mapTemplate.Connections.Add(new Connection("68", "66"));
mapTemplate.Connections.Add(new Connection("68", "67"));
mapTemplate.Connections.Add(new Connection("68", "69"));
mapTemplate.Connections.Add(new Connection("68", "75"));
mapTemplate.Connections.Add(new Connection("69", "26"));
mapTemplate.Connections.Add(new Connection("69", "68"));
mapTemplate.Connections.Add(new Connection("69", "70"));
mapTemplate.Connections.Add(new Connection("69", "71"));
mapTemplate.Connections.Add(new Connection("69", "75"));
mapTemplate.Connections.Add(new Connection("70", "69"));
mapTemplate.Connections.Add(new Connection("70", "71"));
mapTemplate.Connections.Add(new Connection("70", "72"));
mapTemplate.Connections.Add(new Connection("70", "73"));
mapTemplate.Connections.Add(new Connection("70", "75"));
mapTemplate.Connections.Add(new Connection("70", "64"));
mapTemplate.Connections.Add(new Connection("70", "25"));
mapTemplate.Connections.Add(new Connection("71", "25"));
mapTemplate.Connections.Add(new Connection("71", "26"));
mapTemplate.Connections.Add(new Connection("71", "69"));
mapTemplate.Connections.Add(new Connection("71", "70"));
mapTemplate.Connections.Add(new Connection("72", "64"));
mapTemplate.Connections.Add(new Connection("72", "70"));
mapTemplate.Connections.Add(new Connection("72", "73"));
mapTemplate.Connections.Add(new Connection("72", "74"));
mapTemplate.Connections.Add(new Connection("72", "85"));
mapTemplate.Connections.Add(new Connection("73", "70"));
mapTemplate.Connections.Add(new Connection("73", "72"));
mapTemplate.Connections.Add(new Connection("73", "74"));
mapTemplate.Connections.Add(new Connection("73", "75"));
mapTemplate.Connections.Add(new Connection("73", "77"));
mapTemplate.Connections.Add(new Connection("74", "72"));
mapTemplate.Connections.Add(new Connection("74", "73"));
mapTemplate.Connections.Add(new Connection("74", "77"));
mapTemplate.Connections.Add(new Connection("74", "85"));
mapTemplate.Connections.Add(new Connection("74", "86"));
mapTemplate.Connections.Add(new Connection("75", "67"));
mapTemplate.Connections.Add(new Connection("75", "68"));
mapTemplate.Connections.Add(new Connection("75", "69"));
mapTemplate.Connections.Add(new Connection("75", "70"));
mapTemplate.Connections.Add(new Connection("75", "73"));
mapTemplate.Connections.Add(new Connection("75", "77"));
mapTemplate.Connections.Add(new Connection("75", "76"));
mapTemplate.Connections.Add(new Connection("76", "75"));
mapTemplate.Connections.Add(new Connection("76", "77"));
mapTemplate.Connections.Add(new Connection("76", "78"));
mapTemplate.Connections.Add(new Connection("76", "79"));
mapTemplate.Connections.Add(new Connection("77", "73"));
mapTemplate.Connections.Add(new Connection("77", "74"));
mapTemplate.Connections.Add(new Connection("77", "76"));
mapTemplate.Connections.Add(new Connection("77", "78"));
mapTemplate.Connections.Add(new Connection("77", "86"));
mapTemplate.Connections.Add(new Connection("77", "75"));
mapTemplate.Connections.Add(new Connection("78", "76"));
mapTemplate.Connections.Add(new Connection("78", "77"));
mapTemplate.Connections.Add(new Connection("78", "79"));
mapTemplate.Connections.Add(new Connection("78", "86"));
mapTemplate.Connections.Add(new Connection("79", "76"));
mapTemplate.Connections.Add(new Connection("79", "78"));
mapTemplate.Connections.Add(new Connection("79", "86"));
mapTemplate.Connections.Add(new Connection("80", "62"));
mapTemplate.Connections.Add(new Connection("80", "63"));
mapTemplate.Connections.Add(new Connection("80", "64"));
mapTemplate.Connections.Add(new Connection("80", "81"));
mapTemplate.Connections.Add(new Connection("81", "62"));
mapTemplate.Connections.Add(new Connection("81", "80"));
mapTemplate.Connections.Add(new Connection("81", "82"));
mapTemplate.Connections.Add(new Connection("82", "58"));
mapTemplate.Connections.Add(new Connection("82", "61"));
mapTemplate.Connections.Add(new Connection("82", "62"));
mapTemplate.Connections.Add(new Connection("82", "81"));
mapTemplate.Connections.Add(new Connection("82", "83"));
mapTemplate.Connections.Add(new Connection("82", "84"));
mapTemplate.Connections.Add(new Connection("83", "58"));
mapTemplate.Connections.Add(new Connection("83", "82"));
mapTemplate.Connections.Add(new Connection("83", "84"));
mapTemplate.Connections.Add(new Connection("83", "87"));
mapTemplate.Connections.Add(new Connection("83", "88"));
mapTemplate.Connections.Add(new Connection("84", "82"));
mapTemplate.Connections.Add(new Connection("84", "83"));
mapTemplate.Connections.Add(new Connection("84", "85"));
mapTemplate.Connections.Add(new Connection("84", "86"));
mapTemplate.Connections.Add(new Connection("84", "87"));
mapTemplate.Connections.Add(new Connection("85", "72"));
mapTemplate.Connections.Add(new Connection("85", "74"));
mapTemplate.Connections.Add(new Connection("85", "84"));
mapTemplate.Connections.Add(new Connection("85", "86"));
mapTemplate.Connections.Add(new Connection("86", "74"));
mapTemplate.Connections.Add(new Connection("86", "77"));
mapTemplate.Connections.Add(new Connection("86", "78"));
mapTemplate.Connections.Add(new Connection("86", "79"));
mapTemplate.Connections.Add(new Connection("86", "84"));
mapTemplate.Connections.Add(new Connection("86", "85"));
mapTemplate.Connections.Add(new Connection("86", "87"));
mapTemplate.Connections.Add(new Connection("86", "90"));
mapTemplate.Connections.Add(new Connection("86", "92"));
mapTemplate.Connections.Add(new Connection("86", "93"));
mapTemplate.Connections.Add(new Connection("87", "83"));
mapTemplate.Connections.Add(new Connection("87", "84"));
mapTemplate.Connections.Add(new Connection("87", "86"));
mapTemplate.Connections.Add(new Connection("87", "88"));
mapTemplate.Connections.Add(new Connection("87", "93"));
mapTemplate.Connections.Add(new Connection("88", "58"));
mapTemplate.Connections.Add(new Connection("88", "83"));
mapTemplate.Connections.Add(new Connection("88", "87"));
mapTemplate.Connections.Add(new Connection("88", "89"));
mapTemplate.Connections.Add(new Connection("88", "93"));
mapTemplate.Connections.Add(new Connection("89", "11"));
mapTemplate.Connections.Add(new Connection("89", "54"));
mapTemplate.Connections.Add(new Connection("89", "88"));
mapTemplate.Connections.Add(new Connection("89", "93"));
mapTemplate.Connections.Add(new Connection("90", "86"));
mapTemplate.Connections.Add(new Connection("90", "91"));
mapTemplate.Connections.Add(new Connection("91", "90"));
mapTemplate.Connections.Add(new Connection("92", "86"));
mapTemplate.Connections.Add(new Connection("93", "86"));
mapTemplate.Connections.Add(new Connection("93", "87"));
mapTemplate.Connections.Add(new Connection("93", "88"));
mapTemplate.Connections.Add(new Connection("93", "89"));
mapTemplate.Connections.Add(new Connection("93", "94"));
mapTemplate.Connections.Add(new Connection("94", "93"));

            return mapTemplate;
		}
    }
}

