
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Magdeburg()
        {

var mapTemplate = new MapTemplate("Magdeburg") { Image = "magdeburg.png" };
var country1 = new CountryTemplate("1", "Diesdorf") { X = 103, Y = 493 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Ottersleben") { X = 89, Y = 670 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Sudenburg") { X = 203, Y = 554 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Lemsdorf") { X = 230, Y = 621 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Stadfeld west") { X = 202, Y = 464 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "neu olvenstedt") { X = 200, Y = 363 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "alt olvenstedt") { X = 138, Y = 356 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "groer silberberg") { X = 188, Y = 288 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "reform") { X = 245, Y = 679 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "beyendorfer grund") { X = 244, Y = 737 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "beyendorf sohlen") { X = 300, Y = 805 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "salbke") { X = 397, Y = 714 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "westerh�sen") { X = 443, Y = 801 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "fermersleben") { X = 413, Y = 642 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "buckau") { X = 357, Y = 601 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "leipziger strae") { X = 283, Y = 590 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "werder") { X = 371, Y = 538 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "stadtfeld ost") { X = 276, Y = 454 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "nordwest") { X = 283, Y = 401 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "altstadt") { X = 336, Y = 457 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", " alte neustadt") { X = 390, Y = 383 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "neue neustadt") { X = 363, Y = 332 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "neust�tter feld") { X = 291, Y = 316 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "kannenstieg") { X = 303, Y = 261 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "s�lzegrund") { X = 265, Y = 252 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "barleber see") { X = 440, Y = 38 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "gewerbegebiet norg") { X = 434, Y = 150 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "rothensee") { X = 412, Y = 235 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "industrie hafen") { X = 450, Y = 297 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "herrenkrug") { X = 508, Y = 353 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "br�ckfeld") { X = 462, Y = 477 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "berliner chausee") { X = 520, Y = 490 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "cracau") { X = 433, Y = 520 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "prester") { X = 472, Y = 602 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "zipkeleben") { X = 534, Y = 549 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "pechau") { X = 611, Y = 654 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "kreuzhorst") { X = 514, Y = 707 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "randau-calenberge") { X = 545, Y = 786 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "neust�tter see") { X = 347, Y = 232 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "hopfengarten") { X = 328, Y = 686 };
mapTemplate.Countries.Add(country40);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 4);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
continent3.Countries.Add(country13);
continent3.Countries.Add(country40);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 3);
continent4.Countries.Add(country14);
continent4.Countries.Add(country15);
continent4.Countries.Add(country16);
continent4.Countries.Add(country17);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 3);
continent5.Countries.Add(country18);
continent5.Countries.Add(country19);
continent5.Countries.Add(country20);
continent5.Countries.Add(country21);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country22);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
continent6.Countries.Add(country25);
continent6.Countries.Add(country39);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 2);
continent7.Countries.Add(country26);
continent7.Countries.Add(country27);
continent7.Countries.Add(country28);
continent7.Countries.Add(country29);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 2);
continent8.Countries.Add(country30);
continent8.Countries.Add(country31);
continent8.Countries.Add(country32);
continent8.Countries.Add(country33);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country34);
continent9.Countries.Add(country35);
continent9.Countries.Add(country36);
continent9.Countries.Add(country37);
continent9.Countries.Add(country38);
mapTemplate.Continents.Add(continent9);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "7"));
mapTemplate.Connections.Add(new Connection("1", "3"));
mapTemplate.Connections.Add(new Connection("1", "5"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "9"));
mapTemplate.Connections.Add(new Connection("2", "10"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "1"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "16"));
mapTemplate.Connections.Add(new Connection("3", "18"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "20"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "9"));
mapTemplate.Connections.Add(new Connection("4", "16"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "1"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "18"));
mapTemplate.Connections.Add(new Connection("5", "19"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "19"));
mapTemplate.Connections.Add(new Connection("6", "23"));
mapTemplate.Connections.Add(new Connection("6", "8"));
mapTemplate.Connections.Add(new Connection("6", "18"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "20"));
mapTemplate.Connections.Add(new Connection("7", "1"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "25"));
mapTemplate.Connections.Add(new Connection("8", "23"));
mapTemplate.Connections.Add(new Connection("8", "6"));
mapTemplate.Connections.Add(new Connection("9", "2"));
mapTemplate.Connections.Add(new Connection("9", "4"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "40"));
mapTemplate.Connections.Add(new Connection("9", "16"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("10", "2"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "40"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "13"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "40"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "37"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("13", "11"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "30"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "40"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "40"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "20"));
mapTemplate.Connections.Add(new Connection("16", "40"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "3"));
mapTemplate.Connections.Add(new Connection("16", "4"));
mapTemplate.Connections.Add(new Connection("16", "9"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("17", "33"));
mapTemplate.Connections.Add(new Connection("17", "20"));
mapTemplate.Connections.Add(new Connection("18", "3"));
mapTemplate.Connections.Add(new Connection("18", "5"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("18", "20"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "6"));
mapTemplate.Connections.Add(new Connection("19", "5"));
mapTemplate.Connections.Add(new Connection("19", "6"));
mapTemplate.Connections.Add(new Connection("19", "23"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "15"));
mapTemplate.Connections.Add(new Connection("20", "18"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "17"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "6"));
mapTemplate.Connections.Add(new Connection("20", "32"));
mapTemplate.Connections.Add(new Connection("20", "29"));
mapTemplate.Connections.Add(new Connection("20", "3"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "29"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("22", "39"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "23"));
mapTemplate.Connections.Add(new Connection("22", "28"));
mapTemplate.Connections.Add(new Connection("22", "29"));
mapTemplate.Connections.Add(new Connection("22", "24"));
mapTemplate.Connections.Add(new Connection("23", "25"));
mapTemplate.Connections.Add(new Connection("23", "8"));
mapTemplate.Connections.Add(new Connection("23", "6"));
mapTemplate.Connections.Add(new Connection("23", "19"));
mapTemplate.Connections.Add(new Connection("23", "22"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("23", "39"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "39"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "22"));
mapTemplate.Connections.Add(new Connection("25", "8"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "39"));
mapTemplate.Connections.Add(new Connection("25", "23"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "29"));
mapTemplate.Connections.Add(new Connection("27", "39"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "39"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "22"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "22"));
mapTemplate.Connections.Add(new Connection("29", "21"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "20"));
mapTemplate.Connections.Add(new Connection("29", "26"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "13"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("32", "35"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "20"));
mapTemplate.Connections.Add(new Connection("32", "38"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "17"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("35", "32"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("37", "12"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "32"));
mapTemplate.Connections.Add(new Connection("39", "25"));
mapTemplate.Connections.Add(new Connection("39", "27"));
mapTemplate.Connections.Add(new Connection("39", "28"));
mapTemplate.Connections.Add(new Connection("39", "24"));
mapTemplate.Connections.Add(new Connection("39", "22"));
mapTemplate.Connections.Add(new Connection("39", "23"));
mapTemplate.Connections.Add(new Connection("40", "10"));
mapTemplate.Connections.Add(new Connection("40", "9"));
mapTemplate.Connections.Add(new Connection("40", "12"));
mapTemplate.Connections.Add(new Connection("40", "14"));
mapTemplate.Connections.Add(new Connection("40", "15"));
mapTemplate.Connections.Add(new Connection("40", "16"));

            return mapTemplate;
		}
    }
}

