
using ImperaPlus.Domain.Map;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate GreatBritain()
        {

var mapTemplate = new MapTemplate("GreatBritain") { Image = "greatbritain.gif" };
var country1 = new CountryTemplate("1", "Sutherland and Caithness") { X = 356, Y = 44 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Ross and Cromarty") { X = 316, Y = 81 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Inverness-shire") { X = 325, Y = 136 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Morayshire") { X = 390, Y = 105 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Aberdeenshire") { X = 435, Y = 125 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Angus") { X = 417, Y = 174 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Perthshire") { X = 358, Y = 182 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Stirlingshire") { X = 333, Y = 219 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Argyllshire") { X = 284, Y = 199 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Shetland Islands") { X = 632, Y = 47 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Orkney Islands") { X = 594, Y = 119 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Ayrshire") { X = 322, Y = 272 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Lanarkshire") { X = 358, Y = 259 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Peebles-shire") { X = 394, Y = 264 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Fife") { X = 402, Y = 224 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Roxburghshire") { X = 429, Y = 255 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Wigtownshire") { X = 309, Y = 335 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Kirkcudbrightshire") { X = 352, Y = 320 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Dumfries-shire") { X = 385, Y = 305 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Northumberland") { X = 452, Y = 300 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Cumberland") { X = 383, Y = 352 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Isle of Man") { X = 322, Y = 388 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Westmorland") { X = 418, Y = 371 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Lancashire") { X = 410, Y = 430 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Cheshire") { X = 426, Y = 468 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Yorkshire") { X = 486, Y = 400 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "County Durham") { X = 468, Y = 344 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Caernarvonshire") { X = 334, Y = 484 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Denbighshire") { X = 380, Y = 478 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Montgomeryshire") { X = 363, Y = 516 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Cardiganshire") { X = 339, Y = 549 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Pembrokeshire") { X = 293, Y = 588 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Carmarthenshire") { X = 335, Y = 585 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Breconshire") { X = 377, Y = 567 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Glamorgan") { X = 375, Y = 611 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Cornwall") { X = 299, Y = 700 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Devon") { X = 350, Y = 677 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Somerset") { X = 405, Y = 644 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Dorset") { X = 431, Y = 680 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Wiltshire") { X = 454, Y = 627 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Gloucestershire") { X = 443, Y = 593 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Herefordshire") { X = 411, Y = 566 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Shropshire") { X = 412, Y = 522 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Staffordshire") { X = 444, Y = 504 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Warwickshire") { X = 475, Y = 547 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Worcestershire") { X = 443, Y = 555 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Oxfordshire") { X = 484, Y = 605 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Hampshire") { X = 488, Y = 655 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Sussex") { X = 551, Y = 667 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Kent") { X = 595, Y = 636 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Middlesex") { X = 549, Y = 613 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Buckinghamshire") { X = 522, Y = 592 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Bedford") { X = 536, Y = 546 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "Cambridgeshire") { X = 561, Y = 533 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Essex") { X = 584, Y = 589 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Suffolk") { X = 620, Y = 556 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "Norfolk") { X = 602, Y = 513 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Northamptonshire") { X = 506, Y = 544 };
mapTemplate.Countries.Add(country58);
var country59 = new CountryTemplate("59", "Leicestershire") { X = 499, Y = 513 };
mapTemplate.Countries.Add(country59);
var country60 = new CountryTemplate("60", "Lincolnshire") { X = 544, Y = 465 };
mapTemplate.Countries.Add(country60);
var country61 = new CountryTemplate("61", "Nottinghamshire") { X = 504, Y = 472 };
mapTemplate.Countries.Add(country61);
var country62 = new CountryTemplate("62", "Derbyshire") { X = 473, Y = 479 };
mapTemplate.Countries.Add(country62);
var continent1 = new Continent("1", 4);
continent1.Countries.Add(country53);
continent1.Countries.Add(country54);
continent1.Countries.Add(country57);
continent1.Countries.Add(country56);
continent1.Countries.Add(country55);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 5);
continent2.Countries.Add(country58);
continent2.Countries.Add(country59);
continent2.Countries.Add(country62);
continent2.Countries.Add(country61);
continent2.Countries.Add(country60);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 6);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country1);
continent3.Countries.Add(country2);
continent3.Countries.Add(country3);
continent3.Countries.Add(country4);
continent3.Countries.Add(country5);
continent3.Countries.Add(country6);
continent3.Countries.Add(country7);
continent3.Countries.Add(country8);
continent3.Countries.Add(country9);
continent3.Countries.Add(country9);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 1);
continent4.Countries.Add(country51);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country20);
continent5.Countries.Add(country27);
continent5.Countries.Add(country26);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 3);
continent6.Countries.Add(country22);
continent6.Countries.Add(country21);
continent6.Countries.Add(country23);
continent6.Countries.Add(country24);
continent6.Countries.Add(country25);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 4);
continent7.Countries.Add(country47);
continent7.Countries.Add(country52);
continent7.Countries.Add(country50);
continent7.Countries.Add(country49);
continent7.Countries.Add(country48);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 6);
continent8.Countries.Add(country12);
continent8.Countries.Add(country13);
continent8.Countries.Add(country15);
continent8.Countries.Add(country14);
continent8.Countries.Add(country16);
continent8.Countries.Add(country19);
continent8.Countries.Add(country18);
continent8.Countries.Add(country17);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country40);
continent9.Countries.Add(country39);
continent9.Countries.Add(country38);
continent9.Countries.Add(country37);
continent9.Countries.Add(country36);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 5);
continent10.Countries.Add(country29);
continent10.Countries.Add(country28);
continent10.Countries.Add(country30);
continent10.Countries.Add(country34);
continent10.Countries.Add(country35);
continent10.Countries.Add(country31);
continent10.Countries.Add(country33);
continent10.Countries.Add(country32);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 5);
continent11.Countries.Add(country43);
continent11.Countries.Add(country44);
continent11.Countries.Add(country42);
continent11.Countries.Add(country46);
continent11.Countries.Add(country45);
continent11.Countries.Add(country41);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("62", "25"));
mapTemplate.Connections.Add(new Connection("62", "26"));
mapTemplate.Connections.Add(new Connection("62", "61"));
mapTemplate.Connections.Add(new Connection("62", "59"));
mapTemplate.Connections.Add(new Connection("62", "44"));
mapTemplate.Connections.Add(new Connection("15", "8"));
mapTemplate.Connections.Add(new Connection("15", "7"));
mapTemplate.Connections.Add(new Connection("15", "6"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("30", "28"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("30", "43"));
mapTemplate.Connections.Add(new Connection("30", "34"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("43", "34"));
mapTemplate.Connections.Add(new Connection("43", "30"));
mapTemplate.Connections.Add(new Connection("43", "29"));
mapTemplate.Connections.Add(new Connection("43", "25"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "46"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("16", "14"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("16", "21"));
mapTemplate.Connections.Add(new Connection("16", "20"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "33"));
mapTemplate.Connections.Add(new Connection("31", "34"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("48", "39"));
mapTemplate.Connections.Add(new Connection("48", "40"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("59", "62"));
mapTemplate.Connections.Add(new Connection("59", "61"));
mapTemplate.Connections.Add(new Connection("59", "60"));
mapTemplate.Connections.Add(new Connection("59", "53"));
mapTemplate.Connections.Add(new Connection("59", "58"));
mapTemplate.Connections.Add(new Connection("59", "45"));
mapTemplate.Connections.Add(new Connection("59", "44"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "33"));
mapTemplate.Connections.Add(new Connection("34", "31"));
mapTemplate.Connections.Add(new Connection("34", "30"));
mapTemplate.Connections.Add(new Connection("34", "43"));
mapTemplate.Connections.Add(new Connection("34", "42"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "47"));
mapTemplate.Connections.Add(new Connection("41", "45"));
mapTemplate.Connections.Add(new Connection("41", "46"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "35"));
mapTemplate.Connections.Add(new Connection("60", "26"));
mapTemplate.Connections.Add(new Connection("60", "61"));
mapTemplate.Connections.Add(new Connection("60", "59"));
mapTemplate.Connections.Add(new Connection("60", "53"));
mapTemplate.Connections.Add(new Connection("60", "54"));
mapTemplate.Connections.Add(new Connection("60", "57"));
mapTemplate.Connections.Add(new Connection("61", "62"));
mapTemplate.Connections.Add(new Connection("61", "59"));
mapTemplate.Connections.Add(new Connection("61", "60"));
mapTemplate.Connections.Add(new Connection("61", "26"));
mapTemplate.Connections.Add(new Connection("1", "11"));
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "43"));
mapTemplate.Connections.Add(new Connection("29", "25"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "19"));
mapTemplate.Connections.Add(new Connection("14", "16"));
mapTemplate.Connections.Add(new Connection("47", "45"));
mapTemplate.Connections.Add(new Connection("47", "41"));
mapTemplate.Connections.Add(new Connection("47", "40"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("47", "50"));
mapTemplate.Connections.Add(new Connection("47", "52"));
mapTemplate.Connections.Add(new Connection("47", "58"));
mapTemplate.Connections.Add(new Connection("58", "45"));
mapTemplate.Connections.Add(new Connection("58", "59"));
mapTemplate.Connections.Add(new Connection("58", "53"));
mapTemplate.Connections.Add(new Connection("58", "52"));
mapTemplate.Connections.Add(new Connection("58", "47"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "5"));
mapTemplate.Connections.Add(new Connection("3", "7"));
mapTemplate.Connections.Add(new Connection("3", "9"));
mapTemplate.Connections.Add(new Connection("12", "8"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "19"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("27", "20"));
mapTemplate.Connections.Add(new Connection("27", "21"));
mapTemplate.Connections.Add(new Connection("27", "23"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("44", "59"));
mapTemplate.Connections.Add(new Connection("44", "62"));
mapTemplate.Connections.Add(new Connection("44", "25"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "8"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "19"));
mapTemplate.Connections.Add(new Connection("28", "30"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "40"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("57", "60"));
mapTemplate.Connections.Add(new Connection("57", "54"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "55"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "15"));
mapTemplate.Connections.Add(new Connection("8", "13"));
mapTemplate.Connections.Add(new Connection("8", "12"));
mapTemplate.Connections.Add(new Connection("23", "21"));
mapTemplate.Connections.Add(new Connection("23", "27"));
mapTemplate.Connections.Add(new Connection("23", "26"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("40", "39"));
mapTemplate.Connections.Add(new Connection("40", "38"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "47"));
mapTemplate.Connections.Add(new Connection("40", "48"));
mapTemplate.Connections.Add(new Connection("35", "41"));
mapTemplate.Connections.Add(new Connection("35", "42"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "33"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "15"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "5"));
mapTemplate.Connections.Add(new Connection("7", "3"));
mapTemplate.Connections.Add(new Connection("7", "9"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "52"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("54", "56"));
mapTemplate.Connections.Add(new Connection("54", "57"));
mapTemplate.Connections.Add(new Connection("54", "60"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("53", "58"));
mapTemplate.Connections.Add(new Connection("53", "59"));
mapTemplate.Connections.Add(new Connection("53", "60"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("9", "3"));
mapTemplate.Connections.Add(new Connection("9", "7"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "19"));
mapTemplate.Connections.Add(new Connection("21", "16"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "27"));
mapTemplate.Connections.Add(new Connection("21", "23"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "31"));
mapTemplate.Connections.Add(new Connection("33", "34"));
mapTemplate.Connections.Add(new Connection("33", "35"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "15"));
mapTemplate.Connections.Add(new Connection("52", "47"));
mapTemplate.Connections.Add(new Connection("52", "50"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "55"));
mapTemplate.Connections.Add(new Connection("52", "54"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("52", "58"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("24", "26"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("42", "35"));
mapTemplate.Connections.Add(new Connection("42", "34"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "46"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "12"));
mapTemplate.Connections.Add(new Connection("19", "13"));
mapTemplate.Connections.Add(new Connection("19", "14"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("19", "21"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("55", "50"));
mapTemplate.Connections.Add(new Connection("55", "51"));
mapTemplate.Connections.Add(new Connection("55", "52"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("26", "60"));
mapTemplate.Connections.Add(new Connection("26", "61"));
mapTemplate.Connections.Add(new Connection("26", "62"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "24"));
mapTemplate.Connections.Add(new Connection("26", "23"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "1"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("50", "47"));
mapTemplate.Connections.Add(new Connection("50", "52"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "55"));
mapTemplate.Connections.Add(new Connection("39", "48"));
mapTemplate.Connections.Add(new Connection("39", "40"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("45", "41"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "59"));
mapTemplate.Connections.Add(new Connection("45", "58"));
mapTemplate.Connections.Add(new Connection("45", "47"));
mapTemplate.Connections.Add(new Connection("20", "16"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("20", "27"));
mapTemplate.Connections.Add(new Connection("46", "41"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "43"));
mapTemplate.Connections.Add(new Connection("46", "42"));
mapTemplate.Connections.Add(new Connection("25", "29"));
mapTemplate.Connections.Add(new Connection("25", "43"));
mapTemplate.Connections.Add(new Connection("25", "44"));
mapTemplate.Connections.Add(new Connection("25", "62"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "54"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "7"));
mapTemplate.Connections.Add(new Connection("5", "3"));
mapTemplate.Connections.Add(new Connection("5", "4"));

            return mapTemplate;
		}
    }
}

