
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Spanien()
        {
var mapTemplate = new MapTemplate("Spanien") { Image = "espana.png" };
var country1 = new CountryTemplate("1", "Coruna") { X = 129, Y = 42 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Lugo") { X = 184, Y = 67 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Orense") { X = 172, Y = 129 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Ponte-Vedra") { X = 115, Y = 106 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Asturias") { X = 273, Y = 30 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Cantabria") { X = 392, Y = 53 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Navarra") { X = 553, Y = 92 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "La Rioja") { X = 487, Y = 127 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Vizcaya") { X = 470, Y = 44 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Guipuzcoa") { X = 514, Y = 46 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Alava") { X = 487, Y = 90 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Huesca") { X = 651, Y = 122 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Zaragoza") { X = 579, Y = 180 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Teruel") { X = 599, Y = 261 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Lerida") { X = 725, Y = 135 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Gerona") { X = 838, Y = 130 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Barcelona") { X = 788, Y = 151 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Tarragona") { X = 699, Y = 228 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Castellon") { X = 656, Y = 296 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "Valencia") { X = 619, Y = 377 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Alicante") { X = 628, Y = 452 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Murcia") { X = 572, Y = 487 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Tenerifa") { X = 784, Y = 668 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Las Palmas") { X = 971, Y = 655 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "Leon") { X = 282, Y = 95 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "Palencia") { X = 364, Y = 122 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Burgos") { X = 428, Y = 140 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Soria") { X = 491, Y = 177 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Segovia") { X = 397, Y = 222 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Valladolid") { X = 345, Y = 195 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Zamora") { X = 280, Y = 179 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Salamanca") { X = 265, Y = 248 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "Avila") { X = 347, Y = 265 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Madrid") { X = 427, Y = 276 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Guadalajara") { X = 485, Y = 254 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Cuenca") { X = 520, Y = 341 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Toledo") { X = 393, Y = 333 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Ciudad Real") { X = 420, Y = 414 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Albacete") { X = 528, Y = 422 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Caceres") { X = 264, Y = 339 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Badajoz") { X = 246, Y = 427 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "Huelva") { X = 202, Y = 521 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Sevilla") { X = 279, Y = 536 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "Cordoba") { X = 343, Y = 492 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Jaen") { X = 434, Y = 485 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Granada") { X = 440, Y = 559 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Almeria") { X = 521, Y = 555 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Malaga") { X = 349, Y = 581 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Cadiz") { X = 273, Y = 611 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Islas Baleares") { X = 867, Y = 332 };
mapTemplate.Countries.Add(country50);
var continent1 = new Continent("1", 2);
continent1.Countries.Add(country1);
continent1.Countries.Add(country2);
continent1.Countries.Add(country3);
continent1.Countries.Add(country4);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 3);
continent2.Countries.Add(country5);
continent2.Countries.Add(country6);
continent2.Countries.Add(country7);
continent2.Countries.Add(country8);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 2);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 2);
continent4.Countries.Add(country12);
continent4.Countries.Add(country13);
continent4.Countries.Add(country14);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 2);
continent5.Countries.Add(country15);
continent5.Countries.Add(country16);
continent5.Countries.Add(country17);
continent5.Countries.Add(country18);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country19);
continent6.Countries.Add(country20);
continent6.Countries.Add(country21);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 1);
continent7.Countries.Add(country22);
continent7.Countries.Add(country50);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 7);
continent8.Countries.Add(country25);
continent8.Countries.Add(country26);
continent8.Countries.Add(country27);
continent8.Countries.Add(country28);
continent8.Countries.Add(country29);
continent8.Countries.Add(country30);
continent8.Countries.Add(country31);
continent8.Countries.Add(country32);
continent8.Countries.Add(country33);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 1);
continent9.Countries.Add(country34);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 4);
continent10.Countries.Add(country35);
continent10.Countries.Add(country36);
continent10.Countries.Add(country37);
continent10.Countries.Add(country38);
continent10.Countries.Add(country39);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 2);
continent11.Countries.Add(country40);
continent11.Countries.Add(country41);
mapTemplate.Continents.Add(continent11);
var continent12 = new Continent("12", 6);
continent12.Countries.Add(country42);
continent12.Countries.Add(country43);
continent12.Countries.Add(country44);
continent12.Countries.Add(country45);
continent12.Countries.Add(country46);
continent12.Countries.Add(country47);
continent12.Countries.Add(country48);
continent12.Countries.Add(country49);
mapTemplate.Continents.Add(continent12);
var continent13 = new Continent("13", 2);
continent13.Countries.Add(country23);
continent13.Countries.Add(country24);
mapTemplate.Continents.Add(continent13);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "25"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "4"));
mapTemplate.Connections.Add(new Connection("3", "31"));
mapTemplate.Connections.Add(new Connection("3", "25"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "3"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "25"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "25"));
mapTemplate.Connections.Add(new Connection("6", "26"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "27"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "8"));
mapTemplate.Connections.Add(new Connection("7", "12"));
mapTemplate.Connections.Add(new Connection("7", "13"));
mapTemplate.Connections.Add(new Connection("8", "11"));
mapTemplate.Connections.Add(new Connection("8", "27"));
mapTemplate.Connections.Add(new Connection("8", "28"));
mapTemplate.Connections.Add(new Connection("8", "7"));
mapTemplate.Connections.Add(new Connection("8", "13"));
mapTemplate.Connections.Add(new Connection("9", "11"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "27"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "9"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("11", "27"));
mapTemplate.Connections.Add(new Connection("12", "7"));
mapTemplate.Connections.Add(new Connection("12", "13"));
mapTemplate.Connections.Add(new Connection("12", "15"));
mapTemplate.Connections.Add(new Connection("13", "28"));
mapTemplate.Connections.Add(new Connection("13", "7"));
mapTemplate.Connections.Add(new Connection("13", "12"));
mapTemplate.Connections.Add(new Connection("13", "35"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "18"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("13", "8"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "18"));
mapTemplate.Connections.Add(new Connection("14", "19"));
mapTemplate.Connections.Add(new Connection("14", "20"));
mapTemplate.Connections.Add(new Connection("14", "36"));
mapTemplate.Connections.Add(new Connection("14", "35"));
mapTemplate.Connections.Add(new Connection("15", "12"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "18"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("18", "13"));
mapTemplate.Connections.Add(new Connection("18", "14"));
mapTemplate.Connections.Add(new Connection("18", "15"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "14"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("20", "14"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "36"));
mapTemplate.Connections.Add(new Connection("20", "39"));
mapTemplate.Connections.Add(new Connection("20", "21"));
mapTemplate.Connections.Add(new Connection("21", "20"));
mapTemplate.Connections.Add(new Connection("21", "39"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "39"));
mapTemplate.Connections.Add(new Connection("22", "46"));
mapTemplate.Connections.Add(new Connection("22", "47"));
mapTemplate.Connections.Add(new Connection("22", "50"));
mapTemplate.Connections.Add(new Connection("23", "42"));
mapTemplate.Connections.Add(new Connection("24", "49"));
mapTemplate.Connections.Add(new Connection("25", "2"));
mapTemplate.Connections.Add(new Connection("25", "3"));
mapTemplate.Connections.Add(new Connection("25", "6"));
mapTemplate.Connections.Add(new Connection("25", "31"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("25", "30"));
mapTemplate.Connections.Add(new Connection("25", "5"));
mapTemplate.Connections.Add(new Connection("26", "6"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "30"));
mapTemplate.Connections.Add(new Connection("27", "11"));
mapTemplate.Connections.Add(new Connection("27", "6"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "9"));
mapTemplate.Connections.Add(new Connection("27", "8"));
mapTemplate.Connections.Add(new Connection("27", "28"));
mapTemplate.Connections.Add(new Connection("27", "29"));
mapTemplate.Connections.Add(new Connection("27", "30"));
mapTemplate.Connections.Add(new Connection("28", "27"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "8"));
mapTemplate.Connections.Add(new Connection("28", "13"));
mapTemplate.Connections.Add(new Connection("28", "35"));
mapTemplate.Connections.Add(new Connection("29", "27"));
mapTemplate.Connections.Add(new Connection("29", "30"));
mapTemplate.Connections.Add(new Connection("29", "33"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "34"));
mapTemplate.Connections.Add(new Connection("29", "35"));
mapTemplate.Connections.Add(new Connection("30", "25"));
mapTemplate.Connections.Add(new Connection("30", "26"));
mapTemplate.Connections.Add(new Connection("30", "27"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("30", "32"));
mapTemplate.Connections.Add(new Connection("30", "33"));
mapTemplate.Connections.Add(new Connection("30", "29"));
mapTemplate.Connections.Add(new Connection("31", "3"));
mapTemplate.Connections.Add(new Connection("31", "25"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "30"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "40"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "30"));
mapTemplate.Connections.Add(new Connection("33", "29"));
mapTemplate.Connections.Add(new Connection("33", "37"));
mapTemplate.Connections.Add(new Connection("33", "40"));
mapTemplate.Connections.Add(new Connection("34", "29"));
mapTemplate.Connections.Add(new Connection("34", "37"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "28"));
mapTemplate.Connections.Add(new Connection("35", "13"));
mapTemplate.Connections.Add(new Connection("35", "29"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("35", "14"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "14"));
mapTemplate.Connections.Add(new Connection("36", "20"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "39"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "33"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "34"));
mapTemplate.Connections.Add(new Connection("37", "41"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "41"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "45"));
mapTemplate.Connections.Add(new Connection("38", "44"));
mapTemplate.Connections.Add(new Connection("39", "20"));
mapTemplate.Connections.Add(new Connection("39", "21"));
mapTemplate.Connections.Add(new Connection("39", "36"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "22"));
mapTemplate.Connections.Add(new Connection("39", "45"));
mapTemplate.Connections.Add(new Connection("39", "46"));
mapTemplate.Connections.Add(new Connection("40", "32"));
mapTemplate.Connections.Add(new Connection("40", "37"));
mapTemplate.Connections.Add(new Connection("40", "41"));
mapTemplate.Connections.Add(new Connection("40", "33"));
mapTemplate.Connections.Add(new Connection("41", "37"));
mapTemplate.Connections.Add(new Connection("41", "40"));
mapTemplate.Connections.Add(new Connection("41", "38"));
mapTemplate.Connections.Add(new Connection("41", "44"));
mapTemplate.Connections.Add(new Connection("41", "43"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "23"));
mapTemplate.Connections.Add(new Connection("43", "41"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "44"));
mapTemplate.Connections.Add(new Connection("43", "48"));
mapTemplate.Connections.Add(new Connection("43", "49"));
mapTemplate.Connections.Add(new Connection("44", "41"));
mapTemplate.Connections.Add(new Connection("44", "38"));
mapTemplate.Connections.Add(new Connection("44", "43"));
mapTemplate.Connections.Add(new Connection("44", "48"));
mapTemplate.Connections.Add(new Connection("44", "46"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "38"));
mapTemplate.Connections.Add(new Connection("45", "39"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("46", "39"));
mapTemplate.Connections.Add(new Connection("46", "22"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("46", "44"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "22"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("48", "43"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "44"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("49", "43"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "24"));
mapTemplate.Connections.Add(new Connection("50", "22"));

            return mapTemplate;
		}
    }
}

