
using ImperaPlus.Domain.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImperaPlus.DataAccess.ConvertedMaps
{
    public static partial class Maps
    {
        public static MapTemplate Californa()
        {

var mapTemplate = new MapTemplate("Californa") { Image = "california.png" };
var country1 = new CountryTemplate("1", "Del Norte") { X = 154, Y = 35 };
mapTemplate.Countries.Add(country1);
var country2 = new CountryTemplate("2", "Siskiyou") { X = 279, Y = 51 };
mapTemplate.Countries.Add(country2);
var country3 = new CountryTemplate("3", "Modoc") { X = 423, Y = 55 };
mapTemplate.Countries.Add(country3);
var country4 = new CountryTemplate("4", "Humboldt") { X = 150, Y = 194 };
mapTemplate.Countries.Add(country4);
var country5 = new CountryTemplate("5", "Trinity") { X = 212, Y = 160 };
mapTemplate.Countries.Add(country5);
var country6 = new CountryTemplate("6", "Mendocino") { X = 184, Y = 327 };
mapTemplate.Countries.Add(country6);
var country7 = new CountryTemplate("7", "Lake") { X = 248, Y = 352 };
mapTemplate.Countries.Add(country7);
var country8 = new CountryTemplate("8", "Shasta") { X = 315, Y = 154 };
mapTemplate.Countries.Add(country8);
var country9 = new CountryTemplate("9", "Tehama") { X = 294, Y = 231 };
mapTemplate.Countries.Add(country9);
var country10 = new CountryTemplate("10", "Glenn") { X = 281, Y = 290 };
mapTemplate.Countries.Add(country10);
var country11 = new CountryTemplate("11", "Colusa") { X = 295, Y = 341 };
mapTemplate.Countries.Add(country11);
var country12 = new CountryTemplate("12", "Butte") { X = 351, Y = 287 };
mapTemplate.Countries.Add(country12);
var country13 = new CountryTemplate("13", "Lassen") { X = 434, Y = 149 };
mapTemplate.Countries.Add(country13);
var country14 = new CountryTemplate("14", "Plumas") { X = 424, Y = 248 };
mapTemplate.Countries.Add(country14);
var country15 = new CountryTemplate("15", "Sierra") { X = 433, Y = 285 };
mapTemplate.Countries.Add(country15);
var country16 = new CountryTemplate("16", "Nevada") { X = 401, Y = 322 };
mapTemplate.Countries.Add(country16);
var country17 = new CountryTemplate("17", "Yuba") { X = 362, Y = 334 };
mapTemplate.Countries.Add(country17);
var country18 = new CountryTemplate("18", "Sutter") { X = 332, Y = 331 };
mapTemplate.Countries.Add(country18);
var country19 = new CountryTemplate("19", "Placer") { X = 430, Y = 342 };
mapTemplate.Countries.Add(country19);
var country20 = new CountryTemplate("20", "El Dorado") { X = 421, Y = 376 };
mapTemplate.Countries.Add(country20);
var country21 = new CountryTemplate("21", "Yolo") { X = 319, Y = 391 };
mapTemplate.Countries.Add(country21);
var country22 = new CountryTemplate("22", "Sacramento") { X = 375, Y = 400 };
mapTemplate.Countries.Add(country22);
var country23 = new CountryTemplate("23", "Sonoma") { X = 246, Y = 422 };
mapTemplate.Countries.Add(country23);
var country24 = new CountryTemplate("24", "Marin") { X = 134, Y = 453 };
mapTemplate.Countries.Add(country24);
var country25 = new CountryTemplate("25", "San Francisco") { X = 152, Y = 496 };
mapTemplate.Countries.Add(country25);
var country26 = new CountryTemplate("26", "San Mateo") { X = 173, Y = 538 };
mapTemplate.Countries.Add(country26);
var country27 = new CountryTemplate("27", "Santa Cruz") { X = 203, Y = 588 };
mapTemplate.Countries.Add(country27);
var country28 = new CountryTemplate("28", "Solano") { X = 321, Y = 422 };
mapTemplate.Countries.Add(country28);
var country29 = new CountryTemplate("29", "Napa") { X = 278, Y = 399 };
mapTemplate.Countries.Add(country29);
var country30 = new CountryTemplate("30", "Contra Costa") { X = 295, Y = 476 };
mapTemplate.Countries.Add(country30);
var country31 = new CountryTemplate("31", "Alameda") { X = 332, Y = 507 };
mapTemplate.Countries.Add(country31);
var country32 = new CountryTemplate("32", "Santa Clara") { X = 311, Y = 546 };
mapTemplate.Countries.Add(country32);
var country33 = new CountryTemplate("33", "San Benito") { X = 408, Y = 656 };
mapTemplate.Countries.Add(country33);
var country34 = new CountryTemplate("34", "Amador") { X = 416, Y = 423 };
mapTemplate.Countries.Add(country34);
var country35 = new CountryTemplate("35", "Calaveras") { X = 420, Y = 453 };
mapTemplate.Countries.Add(country35);
var country36 = new CountryTemplate("36", "Alpine") { X = 508, Y = 394 };
mapTemplate.Countries.Add(country36);
var country37 = new CountryTemplate("37", "Mono") { X = 606, Y = 501 };
mapTemplate.Countries.Add(country37);
var country38 = new CountryTemplate("38", "Tuolumne") { X = 497, Y = 447 };
mapTemplate.Countries.Add(country38);
var country39 = new CountryTemplate("39", "Mariposa") { X = 501, Y = 514 };
mapTemplate.Countries.Add(country39);
var country40 = new CountryTemplate("40", "Inyo") { X = 724, Y = 658 };
mapTemplate.Countries.Add(country40);
var country41 = new CountryTemplate("41", "Monterey") { X = 360, Y = 668 };
mapTemplate.Countries.Add(country41);
var country42 = new CountryTemplate("42", "San Luis Obispo") { X = 444, Y = 752 };
mapTemplate.Countries.Add(country42);
var country43 = new CountryTemplate("43", "Santa Barbara") { X = 486, Y = 833 };
mapTemplate.Countries.Add(country43);
var country44 = new CountryTemplate("44", "San Joaquin") { X = 380, Y = 459 };
mapTemplate.Countries.Add(country44);
var country45 = new CountryTemplate("45", "Stanislaus") { X = 381, Y = 538 };
mapTemplate.Countries.Add(country45);
var country46 = new CountryTemplate("46", "Merced") { X = 405, Y = 587 };
mapTemplate.Countries.Add(country46);
var country47 = new CountryTemplate("47", "Madera") { X = 486, Y = 589 };
mapTemplate.Countries.Add(country47);
var country48 = new CountryTemplate("48", "Fresno") { X = 490, Y = 638 };
mapTemplate.Countries.Add(country48);
var country49 = new CountryTemplate("49", "Kings") { X = 515, Y = 677 };
mapTemplate.Countries.Add(country49);
var country50 = new CountryTemplate("50", "Tulare") { X = 606, Y = 660 };
mapTemplate.Countries.Add(country50);
var country51 = new CountryTemplate("51", "Kern") { X = 617, Y = 767 };
mapTemplate.Countries.Add(country51);
var country52 = new CountryTemplate("52", "Ventura") { X = 576, Y = 864 };
mapTemplate.Countries.Add(country52);
var country53 = new CountryTemplate("53", "Los Angeles") { X = 659, Y = 876 };
mapTemplate.Countries.Add(country53);
var country54 = new CountryTemplate("54", "San Bernadino") { X = 846, Y = 810 };
mapTemplate.Countries.Add(country54);
var country55 = new CountryTemplate("55", "Orange") { X = 701, Y = 996 };
mapTemplate.Countries.Add(country55);
var country56 = new CountryTemplate("56", "Riverside") { X = 883, Y = 948 };
mapTemplate.Countries.Add(country56);
var country57 = new CountryTemplate("57", "San Diego") { X = 801, Y = 1034 };
mapTemplate.Countries.Add(country57);
var country58 = new CountryTemplate("58", "Imperial") { X = 935, Y = 1021 };
mapTemplate.Countries.Add(country58);
var continent1 = new Continent("1", 3);
continent1.Countries.Add(country1);
continent1.Countries.Add(country4);
continent1.Countries.Add(country5);
continent1.Countries.Add(country6);
continent1.Countries.Add(country7);
mapTemplate.Continents.Add(continent1);
var continent2 = new Continent("2", 1);
continent2.Countries.Add(country2);
continent2.Countries.Add(country3);
mapTemplate.Continents.Add(continent2);
var continent3 = new Continent("3", 3);
continent3.Countries.Add(country8);
continent3.Countries.Add(country9);
continent3.Countries.Add(country10);
continent3.Countries.Add(country11);
continent3.Countries.Add(country12);
mapTemplate.Continents.Add(continent3);
var continent4 = new Continent("4", 4);
continent4.Countries.Add(country23);
continent4.Countries.Add(country24);
continent4.Countries.Add(country25);
continent4.Countries.Add(country26);
continent4.Countries.Add(country27);
continent4.Countries.Add(country28);
continent4.Countries.Add(country29);
continent4.Countries.Add(country30);
continent4.Countries.Add(country31);
continent4.Countries.Add(country32);
continent4.Countries.Add(country33);
mapTemplate.Continents.Add(continent4);
var continent5 = new Continent("5", 4);
continent5.Countries.Add(country44);
continent5.Countries.Add(country45);
continent5.Countries.Add(country46);
continent5.Countries.Add(country47);
continent5.Countries.Add(country48);
continent5.Countries.Add(country49);
continent5.Countries.Add(country50);
continent5.Countries.Add(country51);
mapTemplate.Continents.Add(continent5);
var continent6 = new Continent("6", 2);
continent6.Countries.Add(country41);
continent6.Countries.Add(country42);
continent6.Countries.Add(country43);
mapTemplate.Continents.Add(continent6);
var continent7 = new Continent("7", 1);
continent7.Countries.Add(country57);
continent7.Countries.Add(country58);
mapTemplate.Continents.Add(continent7);
var continent8 = new Continent("8", 3);
continent8.Countries.Add(country52);
continent8.Countries.Add(country53);
continent8.Countries.Add(country54);
continent8.Countries.Add(country55);
continent8.Countries.Add(country56);
mapTemplate.Continents.Add(continent8);
var continent9 = new Continent("9", 3);
continent9.Countries.Add(country34);
continent9.Countries.Add(country35);
continent9.Countries.Add(country36);
continent9.Countries.Add(country37);
continent9.Countries.Add(country38);
continent9.Countries.Add(country39);
continent9.Countries.Add(country40);
mapTemplate.Continents.Add(continent9);
var continent10 = new Continent("10", 3);
continent10.Countries.Add(country17);
continent10.Countries.Add(country18);
continent10.Countries.Add(country19);
continent10.Countries.Add(country20);
continent10.Countries.Add(country21);
continent10.Countries.Add(country22);
mapTemplate.Continents.Add(continent10);
var continent11 = new Continent("11", 3);
continent11.Countries.Add(country13);
continent11.Countries.Add(country14);
continent11.Countries.Add(country15);
continent11.Countries.Add(country16);
mapTemplate.Continents.Add(continent11);
mapTemplate.Connections.Add(new Connection("1", "2"));
mapTemplate.Connections.Add(new Connection("1", "4"));
mapTemplate.Connections.Add(new Connection("2", "1"));
mapTemplate.Connections.Add(new Connection("2", "5"));
mapTemplate.Connections.Add(new Connection("2", "4"));
mapTemplate.Connections.Add(new Connection("2", "3"));
mapTemplate.Connections.Add(new Connection("2", "8"));
mapTemplate.Connections.Add(new Connection("3", "2"));
mapTemplate.Connections.Add(new Connection("3", "13"));
mapTemplate.Connections.Add(new Connection("3", "8"));
mapTemplate.Connections.Add(new Connection("4", "1"));
mapTemplate.Connections.Add(new Connection("4", "2"));
mapTemplate.Connections.Add(new Connection("4", "5"));
mapTemplate.Connections.Add(new Connection("4", "6"));
mapTemplate.Connections.Add(new Connection("5", "2"));
mapTemplate.Connections.Add(new Connection("5", "4"));
mapTemplate.Connections.Add(new Connection("5", "6"));
mapTemplate.Connections.Add(new Connection("5", "8"));
mapTemplate.Connections.Add(new Connection("6", "4"));
mapTemplate.Connections.Add(new Connection("6", "5"));
mapTemplate.Connections.Add(new Connection("6", "9"));
mapTemplate.Connections.Add(new Connection("6", "10"));
mapTemplate.Connections.Add(new Connection("6", "7"));
mapTemplate.Connections.Add(new Connection("6", "23"));
mapTemplate.Connections.Add(new Connection("7", "6"));
mapTemplate.Connections.Add(new Connection("7", "10"));
mapTemplate.Connections.Add(new Connection("7", "11"));
mapTemplate.Connections.Add(new Connection("7", "21"));
mapTemplate.Connections.Add(new Connection("7", "29"));
mapTemplate.Connections.Add(new Connection("7", "23"));
mapTemplate.Connections.Add(new Connection("8", "2"));
mapTemplate.Connections.Add(new Connection("8", "3"));
mapTemplate.Connections.Add(new Connection("8", "5"));
mapTemplate.Connections.Add(new Connection("8", "9"));
mapTemplate.Connections.Add(new Connection("8", "14"));
mapTemplate.Connections.Add(new Connection("8", "13"));
mapTemplate.Connections.Add(new Connection("9", "6"));
mapTemplate.Connections.Add(new Connection("9", "8"));
mapTemplate.Connections.Add(new Connection("9", "14"));
mapTemplate.Connections.Add(new Connection("9", "10"));
mapTemplate.Connections.Add(new Connection("9", "12"));
mapTemplate.Connections.Add(new Connection("10", "6"));
mapTemplate.Connections.Add(new Connection("10", "7"));
mapTemplate.Connections.Add(new Connection("10", "9"));
mapTemplate.Connections.Add(new Connection("10", "12"));
mapTemplate.Connections.Add(new Connection("10", "11"));
mapTemplate.Connections.Add(new Connection("11", "7"));
mapTemplate.Connections.Add(new Connection("11", "10"));
mapTemplate.Connections.Add(new Connection("11", "18"));
mapTemplate.Connections.Add(new Connection("11", "12"));
mapTemplate.Connections.Add(new Connection("11", "21"));
mapTemplate.Connections.Add(new Connection("12", "10"));
mapTemplate.Connections.Add(new Connection("12", "11"));
mapTemplate.Connections.Add(new Connection("12", "14"));
mapTemplate.Connections.Add(new Connection("12", "9"));
mapTemplate.Connections.Add(new Connection("12", "17"));
mapTemplate.Connections.Add(new Connection("12", "18"));
mapTemplate.Connections.Add(new Connection("13", "3"));
mapTemplate.Connections.Add(new Connection("13", "8"));
mapTemplate.Connections.Add(new Connection("13", "14"));
mapTemplate.Connections.Add(new Connection("13", "15"));
mapTemplate.Connections.Add(new Connection("14", "8"));
mapTemplate.Connections.Add(new Connection("14", "9"));
mapTemplate.Connections.Add(new Connection("14", "12"));
mapTemplate.Connections.Add(new Connection("14", "13"));
mapTemplate.Connections.Add(new Connection("14", "15"));
mapTemplate.Connections.Add(new Connection("15", "13"));
mapTemplate.Connections.Add(new Connection("15", "14"));
mapTemplate.Connections.Add(new Connection("15", "16"));
mapTemplate.Connections.Add(new Connection("15", "17"));
mapTemplate.Connections.Add(new Connection("16", "15"));
mapTemplate.Connections.Add(new Connection("16", "19"));
mapTemplate.Connections.Add(new Connection("16", "17"));
mapTemplate.Connections.Add(new Connection("17", "12"));
mapTemplate.Connections.Add(new Connection("17", "15"));
mapTemplate.Connections.Add(new Connection("17", "16"));
mapTemplate.Connections.Add(new Connection("17", "18"));
mapTemplate.Connections.Add(new Connection("17", "19"));
mapTemplate.Connections.Add(new Connection("18", "11"));
mapTemplate.Connections.Add(new Connection("18", "12"));
mapTemplate.Connections.Add(new Connection("18", "17"));
mapTemplate.Connections.Add(new Connection("18", "21"));
mapTemplate.Connections.Add(new Connection("18", "22"));
mapTemplate.Connections.Add(new Connection("18", "19"));
mapTemplate.Connections.Add(new Connection("19", "16"));
mapTemplate.Connections.Add(new Connection("19", "17"));
mapTemplate.Connections.Add(new Connection("19", "18"));
mapTemplate.Connections.Add(new Connection("19", "20"));
mapTemplate.Connections.Add(new Connection("19", "22"));
mapTemplate.Connections.Add(new Connection("20", "19"));
mapTemplate.Connections.Add(new Connection("20", "22"));
mapTemplate.Connections.Add(new Connection("20", "34"));
mapTemplate.Connections.Add(new Connection("20", "36"));
mapTemplate.Connections.Add(new Connection("21", "7"));
mapTemplate.Connections.Add(new Connection("21", "11"));
mapTemplate.Connections.Add(new Connection("21", "18"));
mapTemplate.Connections.Add(new Connection("21", "22"));
mapTemplate.Connections.Add(new Connection("21", "28"));
mapTemplate.Connections.Add(new Connection("21", "29"));
mapTemplate.Connections.Add(new Connection("22", "18"));
mapTemplate.Connections.Add(new Connection("22", "19"));
mapTemplate.Connections.Add(new Connection("22", "20"));
mapTemplate.Connections.Add(new Connection("22", "21"));
mapTemplate.Connections.Add(new Connection("22", "28"));
mapTemplate.Connections.Add(new Connection("22", "34"));
mapTemplate.Connections.Add(new Connection("22", "44"));
mapTemplate.Connections.Add(new Connection("23", "6"));
mapTemplate.Connections.Add(new Connection("23", "7"));
mapTemplate.Connections.Add(new Connection("23", "29"));
mapTemplate.Connections.Add(new Connection("23", "24"));
mapTemplate.Connections.Add(new Connection("24", "23"));
mapTemplate.Connections.Add(new Connection("24", "25"));
mapTemplate.Connections.Add(new Connection("25", "24"));
mapTemplate.Connections.Add(new Connection("25", "26"));
mapTemplate.Connections.Add(new Connection("26", "25"));
mapTemplate.Connections.Add(new Connection("26", "27"));
mapTemplate.Connections.Add(new Connection("26", "32"));
mapTemplate.Connections.Add(new Connection("27", "26"));
mapTemplate.Connections.Add(new Connection("27", "32"));
mapTemplate.Connections.Add(new Connection("27", "33"));
mapTemplate.Connections.Add(new Connection("27", "41"));
mapTemplate.Connections.Add(new Connection("28", "21"));
mapTemplate.Connections.Add(new Connection("28", "29"));
mapTemplate.Connections.Add(new Connection("28", "22"));
mapTemplate.Connections.Add(new Connection("29", "7"));
mapTemplate.Connections.Add(new Connection("29", "28"));
mapTemplate.Connections.Add(new Connection("29", "21"));
mapTemplate.Connections.Add(new Connection("29", "23"));
mapTemplate.Connections.Add(new Connection("30", "44"));
mapTemplate.Connections.Add(new Connection("30", "31"));
mapTemplate.Connections.Add(new Connection("31", "30"));
mapTemplate.Connections.Add(new Connection("31", "44"));
mapTemplate.Connections.Add(new Connection("31", "32"));
mapTemplate.Connections.Add(new Connection("31", "45"));
mapTemplate.Connections.Add(new Connection("32", "26"));
mapTemplate.Connections.Add(new Connection("32", "27"));
mapTemplate.Connections.Add(new Connection("32", "31"));
mapTemplate.Connections.Add(new Connection("32", "45"));
mapTemplate.Connections.Add(new Connection("32", "33"));
mapTemplate.Connections.Add(new Connection("32", "46"));
mapTemplate.Connections.Add(new Connection("33", "27"));
mapTemplate.Connections.Add(new Connection("33", "32"));
mapTemplate.Connections.Add(new Connection("33", "41"));
mapTemplate.Connections.Add(new Connection("33", "48"));
mapTemplate.Connections.Add(new Connection("33", "46"));
mapTemplate.Connections.Add(new Connection("34", "20"));
mapTemplate.Connections.Add(new Connection("34", "22"));
mapTemplate.Connections.Add(new Connection("34", "44"));
mapTemplate.Connections.Add(new Connection("34", "35"));
mapTemplate.Connections.Add(new Connection("34", "36"));
mapTemplate.Connections.Add(new Connection("35", "34"));
mapTemplate.Connections.Add(new Connection("35", "44"));
mapTemplate.Connections.Add(new Connection("35", "45"));
mapTemplate.Connections.Add(new Connection("35", "38"));
mapTemplate.Connections.Add(new Connection("35", "36"));
mapTemplate.Connections.Add(new Connection("36", "20"));
mapTemplate.Connections.Add(new Connection("36", "34"));
mapTemplate.Connections.Add(new Connection("36", "35"));
mapTemplate.Connections.Add(new Connection("36", "37"));
mapTemplate.Connections.Add(new Connection("36", "38"));
mapTemplate.Connections.Add(new Connection("37", "36"));
mapTemplate.Connections.Add(new Connection("37", "40"));
mapTemplate.Connections.Add(new Connection("37", "48"));
mapTemplate.Connections.Add(new Connection("37", "47"));
mapTemplate.Connections.Add(new Connection("37", "39"));
mapTemplate.Connections.Add(new Connection("37", "38"));
mapTemplate.Connections.Add(new Connection("38", "35"));
mapTemplate.Connections.Add(new Connection("38", "36"));
mapTemplate.Connections.Add(new Connection("38", "37"));
mapTemplate.Connections.Add(new Connection("38", "39"));
mapTemplate.Connections.Add(new Connection("38", "45"));
mapTemplate.Connections.Add(new Connection("39", "37"));
mapTemplate.Connections.Add(new Connection("39", "38"));
mapTemplate.Connections.Add(new Connection("39", "46"));
mapTemplate.Connections.Add(new Connection("39", "47"));
mapTemplate.Connections.Add(new Connection("40", "37"));
mapTemplate.Connections.Add(new Connection("40", "54"));
mapTemplate.Connections.Add(new Connection("40", "51"));
mapTemplate.Connections.Add(new Connection("40", "50"));
mapTemplate.Connections.Add(new Connection("40", "48"));
mapTemplate.Connections.Add(new Connection("41", "27"));
mapTemplate.Connections.Add(new Connection("41", "33"));
mapTemplate.Connections.Add(new Connection("41", "42"));
mapTemplate.Connections.Add(new Connection("41", "48"));
mapTemplate.Connections.Add(new Connection("41", "49"));
mapTemplate.Connections.Add(new Connection("42", "41"));
mapTemplate.Connections.Add(new Connection("42", "43"));
mapTemplate.Connections.Add(new Connection("42", "51"));
mapTemplate.Connections.Add(new Connection("43", "42"));
mapTemplate.Connections.Add(new Connection("43", "52"));
mapTemplate.Connections.Add(new Connection("44", "22"));
mapTemplate.Connections.Add(new Connection("44", "30"));
mapTemplate.Connections.Add(new Connection("44", "31"));
mapTemplate.Connections.Add(new Connection("44", "34"));
mapTemplate.Connections.Add(new Connection("44", "35"));
mapTemplate.Connections.Add(new Connection("44", "45"));
mapTemplate.Connections.Add(new Connection("45", "31"));
mapTemplate.Connections.Add(new Connection("45", "32"));
mapTemplate.Connections.Add(new Connection("45", "35"));
mapTemplate.Connections.Add(new Connection("45", "38"));
mapTemplate.Connections.Add(new Connection("45", "44"));
mapTemplate.Connections.Add(new Connection("45", "46"));
mapTemplate.Connections.Add(new Connection("46", "32"));
mapTemplate.Connections.Add(new Connection("46", "33"));
mapTemplate.Connections.Add(new Connection("46", "39"));
mapTemplate.Connections.Add(new Connection("46", "45"));
mapTemplate.Connections.Add(new Connection("46", "48"));
mapTemplate.Connections.Add(new Connection("46", "47"));
mapTemplate.Connections.Add(new Connection("47", "37"));
mapTemplate.Connections.Add(new Connection("47", "39"));
mapTemplate.Connections.Add(new Connection("47", "46"));
mapTemplate.Connections.Add(new Connection("47", "48"));
mapTemplate.Connections.Add(new Connection("48", "33"));
mapTemplate.Connections.Add(new Connection("48", "37"));
mapTemplate.Connections.Add(new Connection("48", "40"));
mapTemplate.Connections.Add(new Connection("48", "41"));
mapTemplate.Connections.Add(new Connection("48", "46"));
mapTemplate.Connections.Add(new Connection("48", "47"));
mapTemplate.Connections.Add(new Connection("48", "49"));
mapTemplate.Connections.Add(new Connection("48", "50"));
mapTemplate.Connections.Add(new Connection("49", "41"));
mapTemplate.Connections.Add(new Connection("49", "48"));
mapTemplate.Connections.Add(new Connection("49", "50"));
mapTemplate.Connections.Add(new Connection("49", "51"));
mapTemplate.Connections.Add(new Connection("50", "40"));
mapTemplate.Connections.Add(new Connection("50", "49"));
mapTemplate.Connections.Add(new Connection("50", "51"));
mapTemplate.Connections.Add(new Connection("50", "48"));
mapTemplate.Connections.Add(new Connection("51", "40"));
mapTemplate.Connections.Add(new Connection("51", "42"));
mapTemplate.Connections.Add(new Connection("51", "49"));
mapTemplate.Connections.Add(new Connection("51", "50"));
mapTemplate.Connections.Add(new Connection("51", "52"));
mapTemplate.Connections.Add(new Connection("51", "53"));
mapTemplate.Connections.Add(new Connection("51", "54"));
mapTemplate.Connections.Add(new Connection("52", "43"));
mapTemplate.Connections.Add(new Connection("52", "51"));
mapTemplate.Connections.Add(new Connection("52", "53"));
mapTemplate.Connections.Add(new Connection("53", "51"));
mapTemplate.Connections.Add(new Connection("53", "52"));
mapTemplate.Connections.Add(new Connection("53", "55"));
mapTemplate.Connections.Add(new Connection("53", "54"));
mapTemplate.Connections.Add(new Connection("54", "40"));
mapTemplate.Connections.Add(new Connection("54", "51"));
mapTemplate.Connections.Add(new Connection("54", "53"));
mapTemplate.Connections.Add(new Connection("54", "56"));
mapTemplate.Connections.Add(new Connection("54", "55"));
mapTemplate.Connections.Add(new Connection("55", "53"));
mapTemplate.Connections.Add(new Connection("55", "54"));
mapTemplate.Connections.Add(new Connection("55", "57"));
mapTemplate.Connections.Add(new Connection("55", "56"));
mapTemplate.Connections.Add(new Connection("56", "54"));
mapTemplate.Connections.Add(new Connection("56", "55"));
mapTemplate.Connections.Add(new Connection("56", "58"));
mapTemplate.Connections.Add(new Connection("56", "57"));
mapTemplate.Connections.Add(new Connection("57", "55"));
mapTemplate.Connections.Add(new Connection("57", "56"));
mapTemplate.Connections.Add(new Connection("57", "58"));
mapTemplate.Connections.Add(new Connection("58", "56"));
mapTemplate.Connections.Add(new Connection("58", "57"));

            return mapTemplate;
		}
    }
}

