# Deploy any change to master to the dev environment
name: Build & Test & Deploy to dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    concurrency: Dev

    environment:
      name: Dev

    env:
      Website: dev.imperaonline.de

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore
        run: dotnet restore -r linux-x64 --force-evaluate
      - name: Build deployment package
        run: dotnet publish -r linux-x64 -o "/home/runner/drop"      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: dev.imperaonline.de
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: "/home/runner/drop/"
          server-dir: "dev.imperaonline.de/api/"
      - name: Restart service
        uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
        with:
          command: /bin/systemctl restart imperadev
          host: dev.imperaonline.de
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
